### PR TITLE
Ignore git *.orig files and emacs backup files

### PR DESCRIPTION
**Pull request by becker33**
Update/improvement to .gitignore file

### CODE REVIEW

**Comment by adamjstewart** [comment]
The way I handle `.gitignore` in my projects is to put language-/project-specific files in the `.gitignore` for that project, and global text editor-specific files in my global `.gitignore`. That seems to be what https://github.com/github/gitignore encourages as well. The advantage is that project `.gitignore` only contains files to ignore specific to that project, leaving personal choices like text editor files to ignore up to the individual user.

I'm not opposed to having text-editor-specific files in our `.gitignore`, just saying how I usually handle things like this.

**Comment by becker33** [comment]
@adamjstewart we can go that way. We already had the emacs backup files in our .gitignore, we just hadn't escaped the comment character properly so it wasn't working. The .orig files are what's really new here.

**Comment by adamjstewart** [comment]
I also consider things like `*.swp` (vim) and `.DS_Store` (macOS) to be global, not project-specific. But that's just me.

**Comment by becker33** [comment]
Yeah I was only speaking to the ones I was changing.

I do think Spack is in the slightly unusual situation of generating some of those files internally, like `*~` files from the `filter_file` operations. So it's not quite as clear a distinction as sometimes.

**Comment by tgamblin** [comment]
> The advantage is that project .gitignore only contains files to ignore specific to that project, leaving personal choices like text editor files to ignore up to the individual user.

The flip side of this is that we don't want those files inadvertently checked into the project, and putting them in the project `.gitignore` helps with that.

Would it help if we divided `.gitignore` into sections?

**Comment by adamjstewart** [comment]
I think it would be cool to divide `.gitignore` into sections and subsections, like "text editors: {vim, emacs}, operating systems: {macOS, Linux}, etc". But I'm also fine doing whatever. Don't consider my review to be blocking, it's merely an opinion. The problem with adding things like text editors to your .gitignore is that there are hundreds of text editors, and it never ends.

**Comment by tgamblin** [comment]
Ok, merging this and leaving this:

> I think it would be cool to divide .gitignore into sections and subsections, like "text editors: {vim, emacs}, operating systems: {macOS, Linux}, etc".

to @adamjstewart's future OCD tendencies.  I'm willing to accept core developers' and frequent committers' editor settings :)

**Pull request merged**
