### PR TITLE
tasmanian: fix unzip dependency error

### PR DESCRIPTION
**Pull request by balay**
```
==> Installing tasmanian
==> Fetching http://tasmanian.ornl.gov/documents/Tasmanian_v5.0.zip
######################################################################## 100.0%
==> Staging archive: /home/balay/spack/var/spack/stage/tasmanian-5.0-sfa7smmito7cdxkcpa6oahdabzibhvcq/Tasmanian_v5.0.zip
==> Error: spack requires 'unzip'. Make sure it is in your path.
==> Error: SystemExit: 1
```
cc: @mkstoyanov

### CODE REVIEW

**Comment by mkstoyanov** [comment]
@balay: Thanks for fixing this.

The current Tasmanian spack package was not created by our team. The current version is not XSDK compliant and does not include any of the Tasmanian options. You can use the current spak to build infrastructure for testing, but don't believe too much on the tests.

I am working on an updated spack (and learning spack in the process), but I had missed the "unzip" issue. Thanks for finding this!

**Comment by balay** [comment]
I was just attempting builds of current state - once XSDK compliant version is ready - hoping the change would be smooth.

Most packages appear to use .tar.gz or git - so presumably don't have this issue.

If Tasmanian will continue to be distributed as .zip - then I think its good to keep this fix.

Other packages that are distributed as .tar.gz don't need a `depends_on('gunzip') depends_on('tar')` etc.. so perhaps  spack should internally  handle this somehow?

cc: @davydden or @tgamblin

**Comment by davydden** [comment]
> so perhaps spack should internally handle this somehow?

ideally yes. In the same way we don't add `depends_on(git)` if you try to install a version from Git repo. 

@adamjstewart @alalazo thoughts?

**Comment by adamjstewart** [comment]
See #8527. I would recommend against merging this PR.

**Comment by davydden** [comment]
>  I would recommend against merging this PR.

fully agree. [this](https://github.com/spack/spack/pull/8527#issuecomment-398841559) is a good summary why.

**Comment by balay** [comment]
ok will close this PR

**Pull request closed without merging**
