### PR TITLE
Recover coverage from subprocesses during unit tests

### PR DESCRIPTION
**Pull request by alalazo**
Moving `pytest.ini` to Spack's root folder since apparently moving to another folder during tests
causes `coverage` to output coverage files within `lib/spack/spack/test` with no coverage data.

Currently `spack test` can be run from any directory, but coverage will be correctly measured only if run from Spack's root folder.

### CODE REVIEW

**Comment by alalazo** [comment]
Can anybody stress test the `spack test` command locally and check that it still works as it is expected to? Otherwise I think this PR is ready to go and adds back coverage on anything tested by subprocesses during unit tests.

**Comment by tgamblin** [comment]
The only downside I see here is that this means we’ll need to specify full paths (from root) to individual test files, right?

**Comment by alalazo** [comment]
> The only downside I see here is that this means we’ll need to specify full paths (from root) to individual test files, right?

Yes, that's one change. I was wondering if there are others that I missed. Also coverage is computed correctly only from Spack root, otherwise we suffer from the same problem when we move into the `root` with `working_dir`.

**Comment by alalazo** [comment]
> Is anyone else getting these messages? Should we be disabling or investigating them?

I get them too and they are the cause of the three or four changes to `llnl.util.log` tests here (the output was getting caught by stderr and didn't match the expected one). They seem benign to me (probably from the logger?) but I didn't investigate them deeply.

**Comment by alalazo** [comment]
> I get a lot of the following messages, which cause several of the tests to fail:

All the failing tests have been fixed in the PR - at least all the ones that are run on Travis. Is there any chance that you are running some of the skipped tests on another machine (here I'm specifically thinking of locking)?

**Comment by tldahlgren** [comment]
> > I get a lot of the following messages, which cause several of the tests to fail:
> 
> All the failing tests have been fixed in the PR - at least all the ones that are run on Travis. Is there any chance that you are running some of the skipped tests on another machine (here I'm specifically thinking of locking)?

Sounds like the answer is yes.  I'll check.

**Comment by tldahlgren** [comment]
Thanks!

**Pull request merged**
