### PR TITLE
apply spack env var updates after module loads

### PR DESCRIPTION
**Pull request by scheibelp**
See: https://github.com/spack/spack/issues/8232

This updates Spack to apply environment modifications after loading modules: those associated with external packages, as well as those associated with compilers. This means that:

* Spack settings for `CC` take precedence over modules setting `CC`
* Spack `prepend_path` actions take precedence over environment variable path modifications from modules

Before this PR both of these were not necessarily true.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@citibeth Can you see if this fixes #8232?

**Comment by citibeth** [comment]
`gettext` now builds with compiler wrappers, which is progress.  However, it does not fix the original problem in #2882.  See #8232 for most recent build log.

**Comment by scheibelp** [comment]
> Was wondering how do you deal with the comment: 

>> All module loads that otherwise would belong in previous functions have to occur after the spack_env object has its modifications applied. Otherwise the environment modifications could undo module changes, such as unsetting LD_LIBRARY_PATH after a module changes it.

This PR separates environment modifications into 3 steps

1. clear env variables (unless spack was invoked with `--dirty`)
1. load all external/compiler modules
1. apply spack-specific environment variable updates (all non-deletes)

The old order was:

1. clear env variables (unless spack was invoked with `--dirty`)
1. apply spack-specific environment variable updates (all non-deletes)
1. load all external/compiler modules

(where actually 1 and 2 occurred together)

So in this PR, it is possible for spack package environment settings to override module settings, although only if they set/unset variables vs. updating them. The core logic (in `build_environment`) which clears environment variables like `LD_LIBRARY_PATH` is guaranteed not to interfere because of the reordering.

> P.S. I missed this PR when submitting #8346. To be honest I also searched for open issues before submitting #8345 and couldn't find any (apparently #8232 was closed without this PR being merged).

Good point. @citibeth for future reference: it may be best to leave an issue as open until the resolving PR is merged - if the commit message contains something like "fixes #8232" it will auto-close the referenced issue; it will also close if the PR is merged and the description contains a message like that.

**Comment by alalazo** [comment]
@scheibelp Thanks for the explanation. I took a more defensive approach based on the sentence:

> All module loads that otherwise would belong in previous functions have to occur after the spack_env object has its modifications applied.

and didn't change the order of modifications.

> The core logic (in build_environment) which clears environment variables like LD_LIBRARY_PATH is guaranteed not to interfere because of the reordering.

I see. I think this is a sensible approach if you reorder things like you do here. The only drawback I can think of is that the modifications are applied in two steps, so they can't be analyzed together by:

https://github.com/spack/spack/blob/54f97d1dec8df18b3d34144f38760abd9a7cc5b4/lib/spack/spack/environment.py#L517-L529

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/8346 was merged so this should be unnecessary.

**Pull request closed without merging**
