### PR TITLE
[WIP] Add packages for packagekit and polkit

### PR DESCRIPTION
**Pull request by adamjstewart**
A few packages I was working on in conjunction with #2581. I was unable to get the mozjs build working, and therefore could not test polkit or packagekit to make sure all of the dependencies were added. I've given up on mozjs for now, so this one is up-for-grabs.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I got a little closer this time. I am still unable to build `mozjs@17.0.0` as it fails to find `zlib` during `make`. The error message looks like:
```
/usr/bin/python2.7 /tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/config/pythonpath.py -I./config /tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/config/expandlibs_exec.py --depend .deps/libmozjs-..so.pp --target libmozjs-..so --uselist --  /home/ajstewart/spack/lib/spack/env/gcc/g++  -pedantic -Wall -Wpointer-arith -Woverloaded-virtual -Werror=return-type -Wtype-limits -Wempty-body -Wno-ctor-dtor-privacy -Wno-overlength-strings -Wno-invalid-offsetof -Wno-variadic-macros -Wcast-align -Wno-long-long -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -pthread -pipe  -DNDEBUG -DTRIMMED -g -O3 -freorder-blocks  -fomit-frame-pointer -DUSE_SYSTEM_MALLOC=1 -DENABLE_ASSEMBLER=1 -DENABLE_JIT=1 -fPIC -shared -Wl,-z,defs -Wl,--gc-sections -Wl,-h,libmozjs-..so -o libmozjs-..so  bignum-dtoa.o bignum.o cached-powers.o diy-fp.o double-conversion.o fast-dtoa.o fixed-dtoa.o strtod.o jsalloc.o jsanalyze.o jsapi.o jsarray.o jsatom.o jsbool.o jsclone.o jscntxt.o jscompartment.o jsdate.o jsdbgapi.o jsdhash.o jsdtoa.o jsexn.o jsfriendapi.o jsfun.o jsgc.o jscrashreport.o jsinfer.o jsinterp.o jsiter.o jslog2.o jsmath.o jsnativestack.o jsnum.o jsobj.o json.o jsonparser.o jsopcode.o jsproxy.o jsprf.o jsprobes.o jspropertycache.o jspropertytree.o jsreflect.o jsscope.o jsscript.o jsstr.o jstypedarray.o jsutil.o jswatchpoint.o jsweakmap.o jswrapper.o jsxml.o prmjtime.o sharkctl.o ArgumentsObject.o ScopeObject.o Debugger.o GlobalObject.o ObjectImpl.o Stack.o String.o BytecodeCompiler.o BytecodeEmitter.o FoldConstants.o NameFunctions.o ParallelArray.o ParseMaps.o ParseNode.o Parser.o SPSProfiler.o TokenStream.o TestingFunctions.o LifoAlloc.o Eval.o MapObject.o MemoryMetrics.o RegExpObject.o RegExpStatics.o RegExp.o Marking.o Memory.o Statistics.o StoreBuffer.o StringBuffer.o Unicode.o Xdr.o MethodJIT.o StubCalls.o Compiler.o FrameState.o FastArithmetic.o FastBuiltins.o FastOps.o LoopState.o StubCompiler.o MonoIC.o PolyIC.o ImmutableSync.o InvokeHelpers.o Retcon.o TrampolineCompiler.o ExecutableAllocator.o PageBlock.o YarrInterpreter.o YarrPattern.o YarrSyntaxChecker.o ExecutableAllocatorPosix.o OSAllocatorPosix.o ARMAssembler.o MacroAssemblerARM.o MacroAssemblerX86Common.o YarrJIT.o jsperf.o pm_linux.o HashFunctions.o SHA1.o    -lpthread    -Wl,-rpath-link,./dist/bin -Wl,-rpath-link,/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/mozjs-17.0.0-ku457ywppzaa2fe2zj2yxtstt73mn5tk/lib    -Wl,-version-script,symverscript   -ldl -lz -lm -L/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/zlib-1.2.10-pebmsmknfn5f7flodqqei3md3lqah7r3/lib -lz -ldl  
jsutil.o: In function `js::DecompressString(unsigned char const*, unsigned long, unsigned char*, unsigned long)':
/tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/jsutil.cpp:109: undefined reference to `inflateInit_'
/tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/jsutil.cpp:114: undefined reference to `inflate'
/tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/jsutil.cpp:116: undefined reference to `inflateEnd'
/usr/bin/ld: libmozjs-..so: hidden symbol `inflate' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-seITWU/mozjs17.0.0/js/src/config/rules.mk:885: recipe for target 'libmozjs-..so' failed
make[1]: *** [libmozjs-..so] Error 1
```
I'm not sure why it can't find zlib even though it has `-L/path/to/zlib` and `-lz` in the link line. I submitted a bug report with Mozilla, but this is for Firefox 17, so I doubt they still support it. I wish I could get `polkit` to build with a newer version of `mozjs`.

**Comment by adamjstewart** [comment]
Looks like mozjs 17.0.0 is no longer supported (obviously):
https://bugzilla.mozilla.org/show_bug.cgi?id=1339245

I poked the Polkit developers and asked them when they will have support for newer versions of mozjs. It looks like they are already working on porting to mozjs 24. I'll see if I can find any patches to get this working.

**Comment by adamjstewart** [comment]
Has anyone ever seen an Autotools package that produced libraries with no version number?
```
$ l /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/mozjs-17.0.0-cl2rqqyoz4pq6jdksy6lndcfu2vsl6eh/lib
libmozjs-..a  libmozjs-..so  pkgconfig
```
I think this is messing up Polkit's ability to find mozjs.

**Comment by tgamblin** [comment]
Yeah, you can get that behavior with `autotools` by adding `libfoo_la_LDFLAGS=-avoid-version`.  Some projects do this.  

More info:
* https://stackoverflow.com/questions/11989255/gnu-autotools-rebuild-without-version-info

**Comment by adamjstewart** [comment]
Looks like this was unrelated. It's a bug in a Perl script that determines the version number. Running it with Perl 5.24.1 results in the error:
```
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /tmp/pytest-of-ajstewart/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-6291uZ/mozjs17.0.0/js/src/config/milestone.pl line 58.
```
The solution is to use an older Perl, or just remove the `defined`. I'll add a patch for the latter and see if that fixes the problem.

**Comment by adamjstewart** [comment]
Alright, mozjs should be working properly now. The latest problem is that PolKit and PackageKit both require systemd, which is much harder to install from source. I'm not sure if it even makes sense to install systemd on CentOS 6. I wonder if I should wait for CentOS 7 and see if it works there.

**Comment by adamjstewart** [comment]
Ok, I'm close to getting glibc working. The linux headers are quick and easy to install, but the glibc build now crashes with:
```
./../include/libc-symbols.h:440:26: error: ‘__EI__libc_intl_domainname’ aliased to undefined symbol ‘__GI__libc_intl_domainname’
   extern __typeof (name) __EI_##name \
                          ^
```

**Comment by adamjstewart** [comment]
Submitted a bug report as I am pretty lost on this one and out of ideas: https://sourceware.org/bugzilla/show_bug.cgi?id=21172

**Comment by adamjstewart** [comment]
@tgamblin I won't have any time to work on this PR for a while. How do you feel about merging it as is? I wasn't able to get glibc to build, but the rest of the packages should be pretty solid. If anyone wants to tackle glibc they are more than welcome.

If you don't want to merge it just yet, I can try to break it up into several smaller PRs. Then we can merge everything that doesn't depend on glibc.

**Comment by adamjstewart** [comment]
Moved all of the working packages to separate PRs and merged them individually. The remaining packages require someone to get glibc working. Still up for grabs.

**Comment by svenevs** [comment]
I was trying to see if I could hack this, but was not able to.  FYI, there is likely a direct relationship between `glibc` and `systemd`.  Specifically, on my system I have

```console
$ systemd-run --version
systemd 222
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

and

```console
$ ls -al /lib/libc-*.so
-rwxr-xr-x. 1 root root 2.1M Aug 18  2016 /lib/libc-2.22.so*
```

so if this stuff ever does get working, you will likely have successful builds but failed runtimes if you don't enforce the versions are the same.  I don't know if there's any truth to this, but it seems suspicious enough :wink:

**Comment by adamjstewart** [comment]
Closing as I was never able to get any of these packages working.

**Pull request closed without merging**
