### PR TITLE
Revert Python: optional dependencies and post-installation tests

### PR DESCRIPTION
**Pull request by citibeth**
This reverts #10335 which was found to be buggy: see #10793.  I recommend that #10335 be re-submitted once it has been more fully tested / debugged.  In the meantime, @phyxz12 and others will be helped greatly if this PR can be merged quickly.

### CODE REVIEW

**Comment by citibeth** [comment]
You're right, I was confused.

**Comment by baberlevi** [comment]
The change from the +tk variant to +tkinter has bit us as well.  As expected, the existing spec that contains +tk is not understood, so I can't install anything using that existing python as a dependency.

I understand the logic about not reverting it, since now there will be people in the same boat who've installed it with the +tkinter label.  But, it seems not renaming variants would be preferable to avoid situations like this to begin with. 

Is there an alternate solution besides rebuilding my python (like referencing the old package.py or rebuilding the database) that doesn't involve me maintaining a separate branch where +tk is still a valid variant ?

**Comment by citibeth** [comment]
We need to encourage people to use spack environments, which make
rebuilding everything easy.  We need to get out of the manual software
install mindset that building software is hard and therefore life must be
optimized to minimize the number of times something is built.

**Comment by citibeth** [comment]
Also I suggest either we rename the variant back, or we ask prior users to
rebuild.

**Comment by citibeth** [comment]
In retrospect I think we should be more cautious in renaming variants

**Comment by adamjstewart** [comment]
@alalazo @scheibelp can we fix the bug causing #10793 so we don't have to worry about variant renames?

**Comment by baberlevi** [comment]
To complicate things: besides renames we'd also have to deal with added variants in whatever the fix is.
In this example, +ssl and +sqlite3 were implied before, but now are explict variants (set to true by default).  While the resultant package behavior is the same, the spec is pretty different.

So attempts to use an existing python even after handling the tk/tkinter rename result in errors like
```
Error: bridger does not depend on sqlite or openssl
```
because they are pulled in as python dependencies, but spack can't figure out why b/c the spec for the existing python doesn't include +ssl or +sqlite3.

**Comment by baberlevi** [comment]
@citibeth - I agree, using spack environments & doing releases via CI/CD is our eventual plan, but right now I'm just trying to satisfy user requests.  Also, we have 1,377 unique packages installed. So frequent rebuilds are non-trivial.

**Comment by alalazo** [comment]
@adamjstewart This bug is a long standing one, see #3515 or https://github.com/spack/spack/pull/3350#issuecomment-284490656. In the meanwhile the repository code has been changed a lot, so maybe we should have another look at how easy is this fix right now?

**Comment by citibeth** [comment]
Unfortunately, I'm not convinced that the changes in code since then will
make this issue any easier to solve.  AFAIK, solving it would place
additional burdens on package authors, i.e. to register somewhere whenever
they change variants.  And that list of variant changes would have to be
maintained in the Spack code... indefinitely.  Plus, code that handles
variants would have to check that registry, producing numerous places for
bugs to pop up because variant changes were not handled properly in one
place or another in the code.

All this pain and bugs for what?  To save people from telling Spack to what
it does best... build software.

I think it's more practical to push people toward a scheme in which they
use environments, and assume they will need to rebuild those environments
periodically.  That's how modern OS's seem to work as well.

Please tell me if I'm wrong and it's simpler/easier than this.

-- Elizabeth

**Comment by alalazo** [comment]
@citibeth 

>AFAIK, solving it would place additional burdens on package authors, i.e. to register somewhere whenever they change variants.

Not at all. If you check, whenever you install something you also store the recipes at the time of install in some subfolder of `<prefix>/.spack`. All that is "logically" needed is to set-up a repository from that location whenever you parse a spec by hash, and give that repository preference over the default ones.

That was complicated to implement, as far as I remember, because `spack.repo` used to be a global variable that was initialized very early in the flow of the program, and it was difficult to change its state. Maybe it's not the case anymore?

> I think it's more practical to push people toward a scheme in which they use environments

Environments are awesome, but I think the two issues are kind of orthogonal.

**Comment by alalazo** [comment]
> Environments are awesome, but I think the two issues are kind of orthogonal.

Thinking about that a bit more they are *really* orthogonal. You can't reproduce an exact installation with just a `spack.lock`. You also need a `repo.lock` associated with that in case the repository changes in the meantime. @tgamblin @scheibelp

**Comment by citibeth** [comment]
Can you clarify what spack.lock and repo.lock are?

**Comment by alalazo** [comment]
@citibeth `spack.lock` is discussed [here](https://spack.readthedocs.io/en/latest/tutorial_environments.html#spack-lock) and contains all the details of your environment after you concretized it. A `repo.lock` should be a dump of all the recipes used to produce the `spack.lock` file. I think currently we don't keep track of the latter.

**Pull request closed without merging**
