### PR TITLE
py-basemap: Re-apply fix

### PR DESCRIPTION
**Pull request by citibeth**
Re-apply patch for py-basemap.  See #8716, #9350

TODO: Incorporate the fix described in #9350 into this PR as well.

### CODE REVIEW

**Comment by lee218llnl** [comment]
@citibeth are you still working on this? I recently installed basemap and to get it to import properly I just manually created a symlink of the basemap*.egg/mpl_toolkits/basemap into the python installations's site-packages/mpl_toolkits directory. It looks like this PR would properly solve the problem.

I also needed to add a build and run dependence on py-pyproj and py-pyshp, otherwise basemap would install its own. Can you please add those in this PR?

**Comment by citibeth** [comment]
I’m on vacation.  This PR works for me but needs advocacy to get merged.
Getting that advoclcacy requires effort and people’s focus.  You can go
ahead and see if you can make that happen.

**Comment by lee218llnl** [comment]
I can give this some attention. Is there some debate that requires "advocacy" or is it just a matter of someone testing and merging? Note, that travis currently isn't happy:

>       assert not all_issues
E       AssertionError: assert not {(2, 7): {'/home/travis/build/spack/spack/var/spack/repos/builtin/packages/py-basemap/package.py': [(33, 'str.format with {} format string')]}}
python_version.py:140: AssertionError
----------------------------- Captured stdout call -----------------------------
==> Spack must remain compatible with Python version 2.6
==> These files require version 2.7:
File                                                        Reason
---------------------------------------------------------   --------------------
var/spack/repos/builtin/packages/py-basemap/package.py:33   str.format with {} format string
======== 1 failed, 1285 passed, 83 skipped, 1 xfailed in 592.21 seconds ========
The command "share/spack/qa/run-$TEST_SUITE-tests" exited with 1.

**Comment by citibeth** [comment]
Well... my PR undoes a previous PR which undid a fix in a PR I got merged a
long time ago.  This kind of flip flopping screams out for added scrutiny.

**Comment by lee218llnl** [comment]
It looks like the contributors to this file are @tgamblin @adamjstewart @michaelkuhn @alalazo @xjrc @mathstuf. I think it makes sense to merge this back in. As is, installing and activating py-basemap is not sufficient, so we would be changing something that is already broken. Are folks OK with this PR?

**Comment by lee218llnl** [comment]
@citibeth I just tested this out and had a few issues. First, with python 3.7.2 it was failing to build basemap 1.0.7. I added version 1.2.0 and that built OK. I can see that the matplotlib mpl_toolkits was linked into basemap's mpl_toolkit, however even after activating py-basemap, it fails to find the basemap mpl_toolkits:

  File "basemap_test.py", line 2, in <module>
    from mpl_toolkits.basemap import Basemap
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

It looks like python finds the mpl_toolkits directly in site-packages:

[lee218@rzwiz2:basemap]$ /usr/WS2/lee218/spack.pr10590/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/python-3.7.2-apdywtyqrsgyqfatjo7zmioh3yqenngj/bin/python3.7 -c 'import mpl_toolkits ; print(mpl_toolkits.__path__)'
_NamespacePath(['/usr/WS2/lee218/spack.pr10590/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/python-3.7.2-apdywtyqrsgyqfatjo7zmioh3yqenngj/lib/python3.7/site-packages/mpl_toolkits'])

Loading the py-basemap module doesn't help either. Is there something I'm missing here? Should basemaps *.egg/mpl_toolktis directory be linked into the main site-packages mpl_toolkits directory instead?

**Comment by lee218llnl** [comment]
If I make the changes I suggest above, then it appears to work OK. Note I also added py-matplotlib version 3.0.2 (already in develop):
[lee218@rzwiz2:spack.pr10590]$ git diff var/spack/repos/builtin/packages/py-basemap/package.py
diff --git a/var/spack/repos/builtin/packages/py-basemap/package.py b/var/spack/repos/builtin/packages/py-basemap/package.py
index 63ad79c..eff26db 100644
--- a/var/spack/repos/builtin/packages/py-basemap/package.py
+++ b/var/spack/repos/builtin/packages/py-basemap/package.py
@@ -30,7 +30,7 @@ def my_find_package_dir(spack_package_root, name):
 #        if not os.path.exists(os.path.join(path, '__init__.py')):
 #            continue
 
-        print('      --> returns {}'.format(path))
+        print('      --> returns {0}'.format(path))
         return path
 
     print('     --> returns None')
@@ -71,6 +71,7 @@ class PyBasemap(PythonPackage):
     homepage = "http://matplotlib.org/basemap/"
     url      = "https://downloads.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz"
 
+    version('1.2.0', 'f8e64bd150590223701a48d60408e939', url='https://github.com/matplotlib/basemap/archive/v1.2.0rel.tar.gz')
     version('1.0.7', '48c0557ced9e2c6e440b28b3caff2de8')
 
     # Per Github issue #3813, setuptools is required at runtime in order
@@ -80,6 +81,8 @@ class PyBasemap(PythonPackage):
     depends_on('py-numpy', type=('build', 'run'))
     depends_on('py-matplotlib', type=('build', 'run'))
     depends_on('pil', type=('build', 'run'))
+    depends_on('py-pyproj', type=('build', 'run'))
+    depends_on('py-pyshp', type=('build', 'run'))
     depends_on('geos')
 
     def setup_environment(self, spack_env, run_env):
@@ -103,9 +106,10 @@ class PyBasemap(PythonPackage):
             #     https://github.com/Homebrew/homebrew-python/issues/112
             # In practice, Python will see only the basemap version of
             # mpl_toolkits
-            path_m = my_find_package_dir(
-                spec['py-matplotlib'].prefix, 'mpl_toolkits')
             path_b = my_find_package_dir(spec.prefix, 'mpl_toolkits')
+            path_m = my_find_package_dir(spec.prefix, 'site-packages')
+            path_m = os.path.join(path_m, 'mpl_toolkits')
+            mkdirp(path_m)
             print('path_m', path_m, type(path_m))
             print('path_b', path_b, type(path_b))
-            my_link_dir(path_m, path_b)
+            my_link_dir(path_b, path_m)

**Comment by citibeth** [comment]
I don’t use spack activate, I load the modules instead.  Could that explain
why it worked for me and not you?  I’m glad to see this is getting more
testing, scrutiny and fixes.  (I’m still on vacation)

**Comment by citibeth** [comment]
@lee218llnl It looks like you were the author of #3835, which broke my original fix in #1964.  Therefore, if you are OK with merging this PR, I don't think any further scrutiny is required.

I've added you as a collaborator to my repo where the PR is currently stored.  Would you be able to please apply your fixes to it an help shepherd this PR to getting merged?  That would be super!

**Comment by lee218llnl** [comment]
@citibeth, #11104 was merged. Can this PR be closed?

**Pull request closed without merging**
