### PR TITLE
Generalize STK package settings in Trilinos

### PR DESCRIPTION
**Pull request by jrood-nrel**
Changes have been made to the STK package in Trilinos and I am now able to generalize STK for more than just Nalu. I removed the comments about Nalu. I also removed the explicit disabling of Seacas when `~exodus`.

### CODE REVIEW

**Comment by citibeth** [comment]
I'll wait for a reviewer who's familiar with Trilinos to weigh in.

**Comment by jrood-nrel** [comment]
@davydden @aprokop

**Comment by jrood-nrel** [comment]
I'm looking back at my outstanding pull requests today. I'm not sure what other projects are using STK, but this is the recommended configuration from @alanw0 who manages the STK project. Who else should we be tagging here to get this merged?

**Comment by alanw0** [comment]
I concur with @jrood-nrel , the stk configuration change is a good change.

**Comment by jrood-nrel** [comment]
Trilinos actually won't build for Nalu without this change. I'm hearing reports about others not being able to build Nalu with Spack. This is an ECP application and we probably shouldn't let it stay broken here. @scheibelp @adamjstewart

**Pull request merged**
