### PR TITLE
Update to the latest version of jsonschema

### PR DESCRIPTION
**Pull request by adamjstewart**
Updates our vendored copy of `jsonschema` from 2.4.0 (2014-08-19) to 2.6.0 (2017-02-05).

### CODE REVIEW

**Comment by adamjstewart** [comment]
Much like #6788, this is another dependency that has dropped support for Python 2.6. I'll see what I can do.

**Comment by adamjstewart** [comment]
Tried replacing all occurrences of `{}` with `{0}` but a lot of other Python 2.6 bugs cropped up. I give up.

**Comment by tgamblin** [comment]
To some extent, we can just leave the vendored versions, especially as long a we need 2.6 support.  Do we need this to support a newer version of python?

**Comment by adamjstewart** [comment]
Nah, I just noticed that many of these libraries were fairly out-of-date. For libraries like `jsonschema` and `distro`, it would be nice if we knew for certain that these versions are the newest versions that still supported Python 2.6.

Speaking of which, how much longer do we plan on supporting 2.6? Perhaps you could chime in on my conversation in https://github.com/nir0s/distro/pull/206.

**Comment by tgamblin** [comment]
LLNL is going to have RHEL6 nodes until I think mid-2018, and I have a suspicion that others sites may as well.  Also, as long as Mira sticks around at ALCF (which may be a while given that Aurora isn't happening?) I think we should run on it.  So there are two data points.  I think other centers are in a similar situation, though I find it hard to believe they don't have Python 2.7 *somewhere*.

**Comment by adamjstewart** [comment]
Alright, maybe we can come back to this question a year from now. Unfortunately, RHEL 6 EOL isn't until 11/30/2020, so I expect to see it around for quite a while. RHEL 6 comes with Python 2.6.6.

I wonder if it's easier to ask users to install Python 3 than it is to ask for Python 2.7?

**Pull request closed without merging**
