### PR TITLE
package/py-pyqt: add version 5, handle version based url

### PR DESCRIPTION
**Pull request by Sinan81**
- add version 5
- handle version based url

### CODE REVIEW

**Comment by adamjstewart** [comment]
See #12157

**Comment by Sinan81** [comment]
@adamjstewart will you be pushing a PR for pyqt5 as SIP package soon, should I give it a try?

**Comment by adamjstewart** [comment]
#12157 includes both `py-pyqt4` and `py-pyqt5` as SIPPackages.

**Comment by Sinan81** [comment]
Great! will be cancelling this PR then.

**Pull request closed without merging**
