### PR TITLE
Add gtk+3 and meson package manager

### PR DESCRIPTION
**Pull request by tmerrick1**
Installed a new package named gtkplus3 (version 3 of gtk+), with its requirements.  Added the new meson/ninja package manager.  And changed qt to version 3 of gtk+ and it compiled cleanly.

### CODE REVIEW

**Comment by adamjstewart** [comment]
There are a lot of changes in this PR (most of which I like). Would it be possible to split the `MesonPackage` and `gtkplus3` stuff into 2+ separate PRs? That would make it a lot easier to review. Also, would you be willing to write documentation on `MesonPackage` in the style of #5015? You can either contribute it directly to #5015 or add it here and wait for #5015 to be merged.

**Comment by healther** [comment]
This PR is another point where we should probably think about how to handle packages that change their build system between versions. Not that this should necessary become part of this PR, but you needed to remove older versions of packages in order to get this into the current shape.

**Comment by tmerrick1** [comment]
I would have to wait for the MesonPackage to be installed for the gtkplus3 to pass its tests.  The only part that is not needed is the qt module, which was modified to show that gtkplus3 works as the build failed using gtkplus.

**Comment by adamjstewart** [comment]
Good point @healther. There are currently 7 out of 2731 packages in Spack that require split build systems, and an unknown number where older versions were dropped to keep the package simple. Personally, I'm in favor of dropping old versions where possible (as was done in this PR) unless another package explicitly requires the older version (as was the case in #8207).

**Comment by adamjstewart** [comment]
@tmerrick1 In that case, I would still split this PR into multiple PRs. The `MesonPackage` and `gtkplus3` changes will take a bit of time to get merged, but combining them into a single PR will take even longer.

**Comment by tmerrick1** [comment]
I did not like removing the old releases of atk as this prevents one from trying out a package from an earlier release to check computational results.  Which package shows how to do dual build systems?

**Comment by adamjstewart** [comment]
> Which package shows how to do dual build systems?

See https://github.com/spack/spack/pull/8207#issuecomment-391919375 for a list of example packages to check out.

**Comment by tmerrick1** [comment]
Since I create a new pull for the meson package manager, what is the best way to remove it from here?

**Comment by adamjstewart** [comment]
@tmerrick1 Now that MesonPackage has been merged, you can remove those changes from this PR. Merging with or rebasing on top of develop is probably the easiest way to do this if you know what you're doing. If you don't, it's probably easier to create a new PR and manually copy the package changes. There's also `git cherry-pick`, but I've never used it. @davydden might be able to help on that front.

**Comment by tmerrick1** [comment]
That is what I have been doing with dbus, etc.  The next major one with be the new atk needed by gtkplus3.

**Comment by adamjstewart** [comment]
What's the status of this PR?

**Comment by alalazo** [comment]
Closing this PR as there was no reply to the last message + it has a high number of conflicts. Feel free to reopen if you consider this PR still relevant.

**Pull request closed without merging**
