### PR TITLE
cmd/install: remove unused install_status option

### PR DESCRIPTION
**Pull request by becker33**
Pretty straightforward. The option isn't actually hooked up to any functionality, and I'm not sure how it got into the `install` command.

Motivated by the error report on slack that confused it with the similarly named option for the `spack spec` command.

### CODE REVIEW

**Comment by alalazo** [comment]
@becker33 Looking at `git blame` it seems to come from e63b45b29.

**Comment by becker33** [comment]
@alalazo that's just where it was refactored, it came in from d1cce990cd682ce76eebec9d311e2c10d0082d82 originally. There doesn't appear to be any reason it was included there (and no code in `cmd/install.py` has ever referenced the value it stores) so I think we're fine removing it.

**Comment by adamjstewart** [comment]
May need to update bash completion script

**Comment by becker33** [comment]
@adamjstewart done.

**Pull request merged**
