### PR TITLE
Chill Fix

### PR DESCRIPTION
**Pull request by dhuth**

### CODE REVIEW

**Comment by dhuth** [comment]
The changes to IEGenLib are identical to https://github.com/spack/spack/pull/12229

**Comment by dhuth** [comment]
Ready to merge

**Comment by dhuth** [comment]
Is there anything else I need to do before this can be merged?

**Comment by scheibelp** [comment]
> Is there anything else I need to do before this can be merged?

No: apologies for missing it. In the future if you @ me it will make it easier for me to spot.

**Comment by dhuth** [comment]
No worries, thanks, will do!

**Pull request merged**
