### PR TITLE
Update veloc preferred version to 1.1 and update dependency on master

### PR DESCRIPTION
**Pull request by fbudin69500**
* Add veloc 1.1 version
* Add pdsh as a dependency for `master`

### CODE REVIEW

**Comment by fbudin69500** [comment]
@chuckatkins

**Comment by chuckatkins** [comment]
@fbudin69500 lgtm

**Comment by chuckatkins** [comment]
@gonsie We're updating this as part of the Data & Viz SDK.  Do these changes look good to you?

**Comment by gonsie** [comment]
@bnicolae is right the person to ask about this.

**Comment by chuckatkins** [comment]
@gonsie thanks (you showed up as the previous committer, hence my asking you)

@bnicolae the changes are fairly minor but we're going through and making sure the Data & Viz products are all up to date.  Does this look good to you?

**Comment by fbudin69500** [comment]
@gonsie @bnicolae ping

**Comment by bnicolae** [comment]
@fbudin69500 yes, bumping up to 1.1 is right. Thanks for taking care of it.

**Pull request merged**
