### PR TITLE
py-horovod: fix compilation of ~cuda

### PR DESCRIPTION
**Pull request by adamjstewart**
Closes https://github.com/horovod/horovod/issues/1832

@tgaddair let me know if you see anything else wrong with our build recipe. Also, if you or any other Horovod developers would like to be listed as "maintainers" of this package, let me know.

### CODE REVIEW

**Comment by tgaddair** [comment]
Hey @adamjstewart, this recipe looks good overall.  I had a couple questions that may be due to my lack of familiarity with spack syntax. 

For dependencies it lists pytorch@0.4.0 and tensorflow@1.1.0, which are pretty old versions.  Does that imply the user must have those versions installed, or is that just specifying the min required version?

Also, I noticed that the defaults for gpu_allreduce etc. are listed as MPI.  Those should be NCCL in most cases, and generally we would not set gpu_allgather=MPI even if CUDA is available, because it requires that your MPI installation is specifically CUDA-aware (which is non-standard).

**Comment by adamjstewart** [comment]
> For dependencies it lists pytorch@0.4.0 and tensorflow@1.1.0, which are pretty old versions. Does that imply the user must have those versions installed, or is that just specifying the min required version?

Yep, the version ranges work like numpy arrays, so those are minimum constraints.

> Also, I noticed that the defaults for gpu_allreduce etc. are listed as MPI. Those should be NCCL in most cases, and generally we would not set gpu_allgather=MPI even if CUDA is available, because it requires that your MPI installation is specifically CUDA-aware (which is non-standard).

Thanks! Let me fix that.

**Comment by adamjstewart** [comment]
@tgaddair It seems like `GPU_ALLGATHER` only has one option, `mpi`, is that correct? Or is having it not set at all another option? We might need to add "none" as an additional option.

**Comment by tgaddair** [comment]
@adamjstewart not setting it at all is the norm.  My suggestion would to use the following options:

gpu_allreduce = nccl, mpi, none (default: nccl)
gpu_allgather = mpi, none (default: none)
gpu_broadcast = nccl, mpi, none (default: nccl)

Then as you do in this diff, we do not set these variables if CUDA is unavailable.

**Comment by tgaddair** [comment]
By the way, we recently added an [installation guide](https://github.com/horovod/horovod/blob/master/docs/install.rst) that has more details on these flags and how they're used.

**Comment by adamjstewart** [comment]
Thanks so much for your help @tgaddair, and even more thanks to whoever wrote that Installation Guide!

I basically rewrote our Horovod package from scratch. Now there are only 3 variants, which control everything. We lose a bit of flexibility, but hopefully it's a lot harder to shoot ourselves in the foot now.

I'm able to successfully install Horovod 0.19.1 with TensorFlow 2.1.0 and OpenMPI 3.1.5 on macOS 10.15.3 with Python 3.7.6 and Clang 11.0.3. @rvinaybharadwaj @aweits can you test this when you get a chance? And let me know if anyone wants to join the "maintainers" bandwagon.

**Comment by aweits** [comment]
Python is dumping core if I attempt to build with ```frameworks=tensorflow,pytorch```. But builds successfully with ```frameworks=tensorflow``` or ```frameworks=pytorch```. Have you done a successful build this way? (probably related to something local on my end...).

Also there's a problem fetching pytorch 1.4.0:
```
fatal: reference is not a tree: 6aaaa4754fe2a7467c5f0584648ba47482caad7d
Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'
```

I'll poke further when I get the chance.

**Comment by adamjstewart** [comment]
> Python is dumping core if I attempt to build with `frameworks=tensorflow,pytorch`

Are you able to reproduce this with `spack spec py-horovod frameworks=tensorflow,pytorch`? I wasn't able to reproduce this with Python 2 or 3, although I haven't tried a full install yet.

> Also there's a problem fetching pytorch 1.4.0

Can you reproduce this with `spack fetch py-torch`? I'm not able to reproduce it, but I wouldn't be shocked since the same thing happened with the `third_party/nervangpu` submodule in 0.4.1.

**Comment by aweits** [comment]
It only happens if torch is imported first in setup.py. If I comment out dummy_import_torch() I can get it to build.
```
        # If PyTorch is installed, it must be imported before TensorFlow, otherwise
        # we may get an error: dlopen: cannot load any more object with static TLS
        if not os.environ.get('HOROVOD_WITHOUT_PYTORCH'):
            dummy_import_torch()
        if not os.environ.get('HOROVOD_WITHOUT_TENSORFLOW'):

```
So with py-tensorflow and py-torch loaded, I can run python directly under gdb:
```
>>> import torch
Detaching after fork from child process 32093.
warning: File "/dev/shm/UPSTREAM/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-7.4.0/gcc-7.4.0-wtlnicmc4lbuxcjt5bcmehurjvs374pg/lib64/libstdc++.so.6.0.24-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /dev/shm/UPSTREAM/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-7.4.0/gcc-7.4.0-wtlnicmc4lbuxcjt5bcmehurjvs374pg/lib64/libstdc++.so.6.0.24-gdb.py
line to your configuration file "/home/aweits/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/aweits/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
Missing separate debuginfo for /lib64/librt.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/85/b4dd66ff1213dc51bf382e9d162e7c2c9b73b6.debug
Missing separate debuginfo for /lib64/libnuma.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/7b/5685624928640e897cb287f10b6b5b2e11e0db.debug
>>> import tensorflow

Program received signal SIGSEGV, Segmentation fault.
0x00007fffc5b56b73 in google::protobuf::internal::(anonymous namespace)::InitSCC_DFS(google::protobuf::internal::SCCInfoBase*)
    ()
   from /dev/shm/UPSTREAM/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-7.4.0/protobuf-3.11.2-yirqcbn3iljp4ilmecpi5w3twy4tsm7u/lib64/libprotobuf.so.3.11.2.0

```
the reverse works just fine:
```
[aweits@skl-a-00 spack]$ python
Python 3.7.6 (default, Mar 25 2020, 12:19:58) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
2020-03-28 14:12:25.062021: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
WARNING: Logging before flag parsing goes to stderr.
W0328 14:12:26.032979 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.042706 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.043915 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.047821 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.067554 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.079231 139636498904896 __init__.py:327] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0328 14:12:26.092036 139636498904896 __init__.py:354] Limited tf.summary API due to missing TensorBoard installation.
>>> import torch
>>> print(tensorflow.__version__)
2.1.0
>>> print(torch.__version__)
1.3.1

```


So this is going to take some digging on my end, as this build tree has been through testing with '-isystem' and whatnot.

as to the fetch:

```
[aweits@skl-a-00 spack]$ spack fetch py-torch cuda_arch=70,75
==> Cloning git repository: https://github.com/pytorch/pytorch.git at tag v1.4.0
Fetching tags only, you probably meant:
  git fetch --tags
fatal: reference is not a tree: 6aaaa4754fe2a7467c5f0584648ba47482caad7d
Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'
==> Fetching from [git] https://github.com/pytorch/pytorch.git at tag v1.4.0 failed.
==> Error: All fetchers failed for spack-stage-py-torch-1.4.0-2sttexl7mz37bwi2i5m7kgkgawxdcdyv
spack:/dev/shm/UPSTREAM/spack
[aweits@skl-a-00 spack]$ 

```

**Comment by adamjstewart** [comment]
I assume `py-horovod +tensorflow +pytorch` didn't work before this PR either, right? This definitely seems like a Horovod bug, not a bug with our package.

**Comment by aweits** [comment]
I'd go ahead with merging this, seems like it might even be a interaction between how torch and tensorflow use protobuf's init routines?

**Comment by adamjstewart** [comment]
I'm going to merge this now that https://github.com/horovod/horovod/issues/1832 has been resolved. @aweits maybe you can open up an issue with Horovod directly for PyTorch+TF support. If any additional changes are needed, we can always open a new PR. Luckily, this Spack package is still very new, so I don't mind much turnover.

**Pull request merged**
