### PR TITLE
Added optimization flags for Intel compilers

### LINKED ISSUE #13103: Add microarchitecture specific flags for Intel compilers
As a user I want to have microarchitecture specific flags injected for Intel compilers so that I would compile by default code that is optimized for the target of the installation.

### Rationale

We already support this feature for GCC since #3206 and need to extend the capability to other compilers as well

### Description
What needs to be done is carefully reviewing docs and man pages, and encode in [this file](https://github.com/spack/spack/blob/develop/lib/spack/llnl/util/cpu/microarchitectures.json) the information found.

### Additional information
A non exhaustive list of pages we might want to consult:

- [Intel C++ compiler Reference](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference)
- [Intel Fortran compiler Reference](https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference)
- auto-dispatch PR #11697

### PR DESCRIPTION
**Pull request by alalazo**
fixes #13103

### CODE REVIEW

**Comment by alalazo** [comment]
@glennpj

**Comment by tgamblin** [comment]
@alalazo: note that AMD has compiler flag reference guides for icc too.  See, e.g., here:

https://www.amd.com/system/files/documents/compiler-options-guide-amd-epyc-7xx1-series-processors.pdf

They list what options you should use for icc on AMD chips.

**Comment by alalazo** [comment]
> Add icc options for AMD chips, too.

Given [this post on Reddit](https://www.reddit.com/r/Amd/comments/440ze8/amd_cpus_and_intel_compilers/) and [this notice from Intel](https://software.intel.com/en-us/articles/optimization-notice#opt-en) I'll put by default a warning that basically repeats the first sentence in the notice. Let me know if you want to go without it.

**Comment by alalazo** [comment]
References found to add Intel flags for AMD cpus:

- [bdver1](http://developer.amd.com/wordpress/media/2012/10/CompilerOptQuickRef-AbuDhabi.pdf)
- [bdver3](http://developer.amd.com/wordpress/media/2012/10/BerlinQuickRef_final1.pdf)
- [bdver4](http://developer.amd.com/wordpress/media/2012/10/EmbeddedR-SeriesSOCQuickReferenceGuide.pdf)
- [znver1](https://www.amd.com/system/files/documents/compiler-options-guide-amd-epyc-7xx1-series-processors.pdf)

**Comment by tgamblin** [comment]
@alalazo: LGTM.

Question for you and @becker33: given that we now know that `zen`'s recommended flags are `core-avx2` (ivybridge), should we not make `zen` say `"from": "ivybridge"` instead of `"from": "x86_64"`?  Likewise for `excavator`.

**Comment by becker33** [comment]
@tgamblin I don't think so. I don't think we can guarantee that non-icc compilers generate compatible binaries between the two. Maybe I'm being overly conservative, but I would worry about whether clang/gcc would allow the same comparison.

In general I would prefer to keep the separate vendors separate on cpu info.

**Comment by tgamblin** [comment]
> In general I would prefer to keep the separate vendors separate on cpu info.

I think we should eventually figure this out for sure, but we don't have to right now.  I would like to have *very detailed* compatibility info for this stuff as I think it will make resolving dependency graphs easier.

**Comment by glennpj** [comment]
I am pretty sure that this will interfere with the ability to use the Intel compiler with the -ax option.

From the icc man page:

> If you specify both the -ax and -march options, the compiler will  not  generate  Intel-specific
>               instructions.

**Pull request merged**
