### PR TITLE
Paraview:  Add motionfx variant

### PR DESCRIPTION
**Pull request by psakievich**
Paraview@5.6.0 fails to build with intel compilers on certain platforms.
Error messages have been traced to the optional MotionFX lib.
(see https://discourse.paraview.org/t/error-build-5-6-0-rc1/572)
Adding the motionfx variant allows for succesful builds on these platforms.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
@DarylGrunau @chuckatkins @danlipsa Has anyone experienced this with Intel? I usually have problems with dependencies before it gets to Paraview, but I am interested in getting this to work with Intel at some point, so I'm curious about this issue.

**Comment by psakievich** [comment]
@chuckatkins thanks for the review.  I'll make these changes.  I've also found to get Paraview to build with python2/matplotlib I need to specify ^freetype@2.7.1 and ^py-matplotlib@2.0.0.  Should I include these as well? After py-matplotlib@2.0.0 the spack package requires python3 

Also when you're referring to VTK do you mean the VTK package or the cmake flags in the Paraview package?

**Comment by jrood-nrel** [comment]
https://github.com/spack/spack/pull/11485 Is dealing with Python issues.

**Comment by chuckatkins** [comment]
I meant that the same issue will show up in the stand alone vtk package and that's the option needed to deal with it there.  It's fine to not worry about that package with this though.  Either myself, @danlipsa, or @opadron can push the appropriate change to the vtk and catalyst packages (all likely to suffer from the same problem) after this is merged.

Wrt freetype, it's an issue that needs to be dealt with in freetype itself, not here.

**Comment by jrood-nrel** [comment]
I've had various freetype issues that make me use older versions. @psakievich Your error wasn't related to this issue was it? https://github.com/spack/spack/issues/9729 Depending on the error I would say it's well within Spack to deal with it since one purpose of Spack is to be a knowledgebase that works around all these build issues.

**Comment by chuckatkins** [comment]
> Depending on the error I would say it's well within Spack to deal with it since one purpose of Spack is to be a knowledgebase that works around all these build issues.

Yes, I agree completely.  I meant only that they should be dealt with in the freetype spack package, not the paraview package.  Sorry for the misunderstanding.

**Comment by psakievich** [comment]
@jrood-nrel I'm not sure.  It was a month or two ago that I ran into it, and I haven't tried using the latest version of freetype since.  I'd say it's likely the same issue.  I'll leave it out for now and just stick the the motionfx issue.  Based on the discussion within the link of my commit message this motionfx issue should be resolved in a coming release of paraview so we'll want to circle back on this issue going forward.

**Comment by chuckatkins** [comment]
Looks like travis got hung up.  This is good to go so I just restarted the traviss builds and once it passes then I'll merge this.  Thanks for the fix.

**Pull request merged**
