### PR TITLE
adios2: Patch findmpi for downstream issues.

### PR DESCRIPTION
**Pull request by chuckatkins**
This patch fixes some integration issues with downstream cmake-based projects depending on adios2 getting broken MPI configurations.

See https://github.com/ornladios/ADIOS2/pull/1632

### CODE REVIEW

**Comment by ax3l** [comment]
@chuckatkins we are seeing some compile issues downstream with this patch installing `adios2%clang@5.0.0+mpi`:
https://travis-ci.org/openPMD/openPMD-api/jobs/565944316

```
924
  >> 24    CMake Error:
925
     25      Error evaluating generator expression:
926
     26    
927
     27        $<COMPILE_LANGUAGE:CUDA>
928
     28    
929
     29      $<COMPILE_LANGUAGE:...> Unknown language.
930
     30    
931
     31    
932
  >> 32    CMake Error at /tmp/travis/spack-stage/spack-stage-lsj8kbha/spack-bu
933
           ild/CMakeFiles/CMakeTmp/CMakeLists.txt:18 (target_link_libraries):
934
     33      Error evaluating generator expression:
935
     34    
936
     35        $<COMPILE_LANGUAGE:CUDA>
937
     36    
938
     37      $<COMPILE_LANGUAGE:...> Unknown language.
939
     38    
940
     39    
941
  >> 40    CMake Error at cmake/upstream/FindMPI.cmake:1202 (try_compile):
942
     41      Failed to generate test project build system.
943
     42    Call Stack (most recent call first):
944
     43      cmake/upstream/FindMPI.cmake:1253 (_MPI_try_staged_settings)
945
     44      cmake/upstream/FindMPI.cmake:1513 (_MPI_check_lang_works)
946
     45      cmake/FindMPI.cmake:8 (include)
947
     46      cmake/DetectOptions.cmake:94 (find_package)
```

**Comment by chuckatkins** [comment]
I just noticed this with ParaView.  See https://github.com/ornladios/ADIOS2/pull/1654

**Comment by chuckatkins** [comment]
The testing I had dome didn't end up hitting the 3.11.x branch hence I missed this initially.

**Comment by chuckatkins** [comment]
https://github.com/spack/spack/pull/12241

**Comment by chuckatkins** [comment]
"vendoring" upstream cmake modules into a project is always tricky since they often need to be back-ported to the minimum CMake version the project builds.  It's even trickier if those are public dependencies that then need to be exported, as is the case of FindMPI.

**Comment by ax3l** [comment]
Yep, no prob. Thanks for the backport!

**Pull request merged**
