### PR TITLE
glib: A patch to enable Red Hat 6 users to be able to compile the current version

### PR DESCRIPTION
**Pull request by tmerrick1**
Red Hat/Centos 6 users get undefined variables when compiling at 2.56.  This patch removes the undefined variables and puts in the normal value for the buffer size.

### CODE REVIEW

**Comment by adamjstewart** [comment]
I don't think Spack currently has a way to detect the kernel version. It certainly isn't available through the spec. @tgamblin @becker33?

**Comment by scheibelp** [comment]
RHEL6 and RHEL7 are distinguished currently by the `architecture` property of a Spec; you can access this with `Spec.architecture.platform_os`:

```
$ spack-python
> from spack.spec import Spec
> x = Spec('bzip2')
> x.concretize()
> x.architecture.platform_os
'rhel7'
> x.architecture
'linux-rhel7-x86_64'
```

If you mean something as fine-grained as what `uname -a` returns then that is definitely not exposed in the Spec.

**Comment by scheibelp** [comment]
@tmerrick I wanted to check: did you create this patch yourself?

**Comment by tmerrick1** [comment]
Yes.  I have not seen anything else about it.

**Comment by tmerrick1** [comment]
How do you do this in an if statement in the patch section of a package?  I am not sure what variables are exposed there.

**Comment by adamjstewart** [comment]
If you want to restrict it to `rhel6`, you can do:
```python
patch('foo.patch', when='os=rhel6')
```
Basically, anything that is included in the spec syntax can be used in the `when=` argument. See `spack help --spec` for a summary of the full syntax.

**Comment by tmerrick1** [comment]
Is there a cleaner way to do this:

    patch('old-kernels.patch', when='@2.56: os=rhel6')
    patch('old-kernels.patch', when='@2.56: os=centos6')

I wonder how many use Scientific Linux?

**Comment by adamjstewart** [comment]
There is no "or" in Spack's spec syntax, so there is currently no simpler way of doing that.

**Pull request merged**
