### PR TITLE
xsdk: enable slepc in deal.ii (used to be a concretization error)

### PR DESCRIPTION
**Pull request by davydden**
should be merged after https://github.com/spack/spack/pull/10217

### CODE REVIEW

**Comment by balay** [comment]
Hm - wrt xsdk@0.4.0 I think the preference is to not change it as we've already done the release.

Perhaps we should do this for xsdk@develop - but that is not in a good/installable state yet.

cc: @jwillenbring

**Comment by davydden** [comment]
> wrt xsdk@0.4.0 I think the preference is to not change it as we've already done the release.

does `xsdk` recommend a certain version of Spack? If not, I am fine keeping it as-is (i.e. do not use `slepc` in `deal.II`).

**Comment by balay** [comment]
On Sat, 29 Dec 2018, Denis Davydov wrote:

> > wrt xsdk@0.4.0 I think the preference is to not change it as we've already done the release.
> 
> does `xsdk` recommend a certain version of Spack? If not, I am fine keeping it as-is (i.e. do not use `slepc` in `deal.II`).

So far we have not done that i.e recommend a snapshot of spack - or create a xsdk-0.4.0 tag/branch in spack on the current snapshot.
[current instructions just start off from spack 'develop' banch]

Perhaps its a good idea to create xsdk-0.4.0 branch/tag in spack as this would preserve the current tested state [as changes in other packages like suite-sparse or boost or other basic stuff can invalidate current testing - and can potentially result in a broken build].

So - I think its something to discuss in xsdk group..

cc: @jwillenbring

**Comment by davydden** [comment]
> Perhaps its a good idea to create xsdk-0.4.0 branch/tag in spack as this would preserve the current tested state

yes, I think it's a good idea. Otherwise eventually new versions will be added, concretizer might change, new issues appear, etc.

**Comment by tgamblin** [comment]
Why wouldn't this be xsdk@0.4.1?  You already released 0.4.0...

**Comment by tgamblin** [comment]
@balay: did you make a decision on this?

Oddly in develop right now, `xsdk` concretizes successfully but `xsdk@0.4.0` does not.  Is this related?

**Comment by balay** [comment]
I'm not sure if the xsdk project members have an opinion on this. We haven't met since the break/release - to discuss such topics [except for the upcoming ecp tutorial]

Wrt 0.4.1 - its in the general xsdk release workflow - and it was part of discussions in terms of: we could do this if we need to [wrt any issues that come up - that need fixes - likely patched versions of individual xsdk packages] - but practically - we haven't done that with previous releases.

The biggest issue here is re-testing on LCFs [its easy enough to retest on workstations..]

Wrt  feature changes as in this PR - my preference is to schedule it for next release - i.e add it to xsdk @develop [but then xsdk@develop is likely broken as it hasn't been tested in a while] and schedule it fo r the next release.

Wrt a xsdk branch/tag -  I'm currently inclined towards treating xsdk as any other package in spack - where one assumes  individual packages in spack to  continue to work even as spack progresses [and some dependencies change.

[so a branch/tag/hash of the tested spack snapshot  would be primarily useful - to debug broken builds - or if users encounter unfixable issues.]

cc: @jwillenbring

**Comment by davydden** [comment]
@tgamblin 

> Oddly in develop right now, xsdk concretizes successfully but xsdk@0.4.0 does not. Is this related?

It should not, see https://github.com/spack/spack/issues/10281

**Comment by davydden** [comment]
@balay ping.

**Comment by balay** [comment]
@davydden some of this was discussed at last weeks meeting [wrt 0.4.1 vs branch/tag vs use develop for xsdk].

Current inclination is:
- continue to recommend 'develop' for xsdk-.0.4.0
-  if any issues come up  (minor/build or with spack changes)- try fixing them - i.e the fixes will go with xsdk-.0.4.0
- work on 0.4.1 update only if there is a major need for it. [currently none]
- work on xsdk@develop for any feature enhancements [for future 0.5.0]

@jwillenbring can correct me if I'm misrepresenting anything.

I'm currently testing xsdk@develop to see if its in usable state. I have a couple of fixes in branch  `balay/xsdk-develop`

Wrt this PR - can we make this change only for xsdk@develop and not 0.4.0 [as this is more of a feature enhancement for xsdk] ?

**Comment by balay** [comment]
I just attempted xsdk@develop build with this change on a couple of boxes - and that went well for me.

**Pull request merged**
