### PR TITLE
Add artisanal, handcrafted SVG Spack logo.

### PR DESCRIPTION
**Pull request by tgamblin**
- This isn't one of those autogenerated SVGs from a drawing program!

- This is a completely re-traced, minimalist SVG file with clearly
  delineated pieces so that your favorite renderer can draw a Spack logo
  at whatever resolution you want.

- Included versions with text, as well.

### CODE REVIEW

**Comment by tgamblin** [comment]
That didn't go well.

Displays fine [here](https://github.com/spack/spack/blob/features/svg-logo/share/spack/logo/spack-logo-text.svg):

screen shot 2017-11-06 at 1 59 08 pm

But [not here](https://github.com/spack/spack/tree/features/svg-logo):

screen shot 2017-11-06 at 1 58 26 pm

Hm.

**Comment by tgamblin** [comment]
Appears to be isaacs/github#316.  Maybe [this comment](https://github.com/isaacs/github/issues/316#issuecomment-113790202) will help...

**Comment by tgamblin** [comment]
Ok, fixed it using a cdn.rawgit.com link.  Also, the first line of the README is now text and not part of the image.  I think it's nicer.

Now to use the SVGs for stickers at SC17.

**Comment by adamjstewart** [comment]
I wonder if we can get this thing on RTD? The current logo looks a bit fuzzy.

**Pull request merged**
