### PR TITLE
mesa: Revert updated meson build and restore autotools build

### PR DESCRIPTION
**Pull request by chuckatkins**
Due to the large number of issues this migration has caused, this rolls back
to the older autotools build.  However, it still keeps the updates wrt
variants and virtual packages.

### CODE REVIEW

**Comment by chuckatkins** [comment]
See comments in #11553 

Fixes #11537 
Fixes #11398

**Comment by chuckatkins** [comment]
@danlipsa does this simplify any of your life wrt python and paraview?

**Comment by danlipsa** [comment]
@chuckatkins Please note https://github.com/spack/spack/pull/11594 fix for the build dependencies issue. If that goes in I think I have everything I need for paraview / catalyst with the
```
   python:
      version: [3, 2]
```

**Comment by danlipsa** [comment]
If that does not go in, yes, I think this is going to help.

**Comment by danlipsa** [comment]
@chuckatkins This 'spack spec' find for both paraview 5.6 and 5.5.2 (python3 and python2). I'll try building next.

**Comment by danlipsa** [comment]
The packages also build fine.

**Pull request merged**
