### PR TITLE
for fakeroot support, add "shadow" dependency

### PR DESCRIPTION
**Pull request by odoublewen**
WIP.  @vsoch @hartzell 

* v3.3 now depends on the new package `shadow` (#12750) and appears to build successfully.  --fakeroot option still needs testing.
* v3.4 does not yet build.  The build error message is:

```
 checking: libseccomp+headers... no
 checking: cryptsetup... no

unable to find the cryptsetup program, is the package cryptsetup-bin installed?
```

### CODE REVIEW

**Comment by vsoch** [comment]
Yeah that's yet another dependency (for 3.4) - they [reported that it's not a build dependency](https://groups.google.com/a/lbl.gov/d/msg/singularity/omx0y0ZhYt8/X_0oDelGBgAJ) but a runtime dependency, but requiring it for build suggests otherwise! @odoublewen do you want to have this PR just for the --fakeroot update, or hold off to see if we can add the other package too? 

Either way, I'll be able to test this tomorrow, and help out with any additional stuffs needed!

**Comment by odoublewen** [comment]
> have this PR just for the --fakeroot update

Yes, I think that's a good idea.  I'm not convinced `cryptsetup` will be a cakewalk and I'm not sure how much time I'll have tomorrow.  If it's okay with @adamjstewart I will just comment out v3.4 checksum and write a TODO.

**Comment by vsoch** [comment]
okay, and this morning my wireless is not working and I'm using a mobile hotspot, so I won't be able to test :( But maybe it will come back to life sometime in the day...

**Comment by vsoch** [comment]
okay I'm using a cloud instance to work today (thank god!) testing now!

**Comment by vsoch** [comment]
Okay testing with Singularity, confirming version 3.3.0:

```bash
$ which singularity
/usr/local/bin/singularity
$ singularity --version
singularity version 3.3.0-1
```

Hey @odoublewen did you update your branch with shadow? It says not found:

```bash
$ bin/spack install singularity@3.3.0
==> Warning: CROSS has not been set, however cannot detect scheduler.
==> Error: Package shadow not found.
```

**Comment by vsoch** [comment]
To test, I just pulled from upstream develop. I cloned the branch here directly, not sure why the rest of develop didn't come with it!

**Comment by vsoch** [comment]
okay I think (with shadow added) this worked for me!

```bash
# Fix permissions
$ sudo /home/vanessa/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/singularity-3.3.0-aoqvpetqwumap67qo5uskpopdpmt2ojw/bin/spack_perms_fix.sh 
...
$ singularity build --fakeroot container.sif Singularity 
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:7c9d20b9b6cda1c58bc4f9d6c401386786f584437abbe87e58910f8a9a15386b
 742.94 KiB / 742.94 KiB [==================================================] 0s
Copying config sha256:8cf90cc9e23fce3bb22a95933b0f1008115828369857f09825dfb376b175f897
 575 B / 575 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: container.sif
```

```bash
$ singularity build shouldnt-work.sif Singularity 
FATAL:   You must be the root user, however you can use --remote or --fakeroot to build from a Singularity recipe file
```

**Comment by vsoch** [comment]
If we can change the title here to just be for adding shadow to singularity 3.3.0, I have tested that and confirmed we're good :)

**Pull request merged**
