### PR TITLE
Specs add a space before dependencies

### LINKED ISSUE #7941: String representation of a spec might be semantically different from the originating spec
For specs that have multi-valued variants specified and a dependency following them, the string representation of a Spec might be parsed differently from the originating Spec.

### Expected Result

If I declare something like:
```python
Spack version 0.11.2
Python 2.7.6, Linux x86_64
>>> import spack.spec
>>> s = spack.spec.Spec('fftw+mpi simd=avx2 ^mvapich2')
>>> str(s)
'fftw+mpi simd=avx2^mvapich2'
>>> t = spack.spec.Spec(str(s))
```
I expect `s` and `t` to be semantically the same spec

### Actual Result
The fact that `str(s)` is emitted without a space between the variant value and the dependency causes Spack to interpret `avx2^mvapich2` as a unique token.

### Steps to reproduce the issue
```python
Spack version 0.11.2
Python 2.7.6, Linux x86_64
>>> import spack.spec
>>> s = spack.spec.Spec('fftw+mpi simd=avx2 ^mvapich2')
>>> str(s)
'fftw+mpi simd=avx2^mvapich2'
>>> t = spack.spec.Spec(str(s))
>>> s.concretize()
>>> t.concretize()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1829, in concretize
    changes = (self.normalize(force),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2206, in normalize
    self.validate_or_raise()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2268, in validate_or_raise
    substitute_abstract_variants(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/variant.py", line 615, in substitute_abstract_variants
    pkg_variant.validate_or_raise(new_variant, spec.package_class)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/variant.py", line 135, in validate_or_raise
    raise InvalidVariantValueError(self, not_allowed_values, pkg)
InvalidVariantValueError: invalid values for variant "simd" in package "fftw": ['avx2^mvapich2']
```

### Information on your system

Should not be relevant, as the problem is very likely in the parsing.

### PR DESCRIPTION
**Pull request by alalazo**
Modified string representation of Specs to add a space before deps

fixes #7941

### CODE REVIEW

**Comment by healther** [comment]
Does this mean that `a^b` is now illegal syntax?

**Comment by alalazo** [comment]
@healther Nope:
```console
$ spack spec hdf5+mpi^openmpi
Input spec
--------------------------------
hdf5+mpi
    ^openmpi

Concretized
--------------------------------
hdf5@1.10.1%gcc@4.8~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu14.04-x86_64 
    ^openmpi@3.0.1%gcc@4.8~cuda fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-ubuntu14.04-x86_64 
        ^hwloc@1.11.9%gcc@4.8~cairo~cuda+libxml2+pci+shared arch=linux-ubuntu14.04-x86_64 
            ^libpciaccess@0.13.5%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                ^libtool@2.4.6%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                    ^m4@1.4.18%gcc@4.8 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-ubuntu14.04-x86_64 
                        ^libsigsegv@2.11%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                ^pkgconf@1.4.0%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                ^util-macros@1.19.1%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
            ^libxml2@2.9.4%gcc@4.8~python arch=linux-ubuntu14.04-x86_64 
                ^xz@5.2.3%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                ^zlib@1.2.11%gcc@4.8+optimize+pic+shared arch=linux-ubuntu14.04-x86_64 
            ^numactl@2.0.11%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                ^autoconf@2.69%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                    ^perl@5.24.1%gcc@4.8+cpanm+shared arch=linux-ubuntu14.04-x86_64 
                        ^gdbm@1.14.1%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                            ^readline@7.0%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
                                ^ncurses@6.0%gcc@4.8 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-ubuntu14.04-x86_64 
                ^automake@1.16.1%gcc@4.8 arch=linux-ubuntu14.04-x86_64
```

**Comment by adamjstewart** [comment]
Is the main motivation for this PR that the `^` sigil can't follow a multi-valued variant without a space? Is there any way we could allow that in the parser?

**Comment by alalazo** [comment]
@adamjstewart In some sense that's the main motivation. But I would treat the two issues separately. I think the regression test I added makes sense on its own:
```python
@pytest.mark.regression('7941')
def test_regression_issue_7941(self):
    s = Spec('a foobar=bar ^b')
    t = Spec(str(s))

    s.concretize()
    t.concretize()

    assert s.dag_hash() == t.dag_hash()
```
as it is sensible to ask `s` and `t` to be always equal (even regardless of the string used to initialize `s`). Whether or not fixing the parser depends on whether or not we want `^@%+~` to be allowed characters within variants values. As far as I can see right now they are. If we want to remove them I'd agree though.

**Comment by alalazo** [comment]
@tgamblin Should be done. Let me know if you want further changes.

**Comment by alalazo** [comment]
@scheibelp @becker33 @tgamblin ping

**Comment by alalazo** [comment]
@tgamblin Given that you approved, I am going to merge the PR. Concerning this:
> Whether or not fixing the parser depends on whether or not we want ^@%+~ to be allowed characters within variants values.

do we want to change the parser too in another PR? Or should we leave parsing like it is?

**Pull request merged**
