### PR TITLE
resource: fixing a problem with shutil.move and symlinks to dirs

### PR DESCRIPTION
**Pull request by baberlevi**
This seems to fix an issue with the rubygems ssl cert resource on the ruby package #7130 

Tested lua and git which also both have resources, and those still seem to work as expected.

### CODE REVIEW

**Comment by healther** [comment]
LGTM

**Comment by scheibelp** [comment]
Also flake is complaining about the line length here

**Comment by baberlevi** [comment]
CI issue seems unrelated to PR

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
