### PR TITLE
add package verilator

### PR DESCRIPTION
**Pull request by healther**

### CODE REVIEW

**Comment by healther** [comment]
Trying to use this like
```
spack load -r verilator
```
ends with:
```
make[1]: Entering directory '/wang/users/wv385/cluster_home/tmp/verilatortest/obj_dir'
/wang/users/wv385/cluster_home/spack_failure/spack3/lib/spack/env/gcc/g++  -I.  -MMD -/wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/linux-debian8-x86_64/gcc-.9.2/verilator-3.920-zpciqgqruabe64npk4s35xvsglo5bpbd/include -/wang/users/wv385/cluster_home/spack_failure/spack3/opt/spack/linux-debian8-x86_64/gcc-.9.2/verilator-3.920-zpciqgqruabe64npk4s35xvsglo5bpbd/include/vltstd -VL_PRINTF=printf -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow      -VL_DEBUG=1  -c -o sim_main.o ../sim_main.cpp
[...]
Spack compiler must be run from Spack! Input 'SPACK_PREFIX' is missing.
```

This seems to be the same problem as in #7326. Anyone have an idea how to fix this? @scheibelp?

**Comment by healther** [comment]
Okay, I needed to manually patch their `verilated.mk`-File. Maybe there should be a way for spack to hand out the actual compiler path into the CXX-variable or the wrapper scripts should be usable without actually having loaded spack.

**Comment by healther** [comment]
maybe there should be a retry for failing fetches...

**Comment by healther** [comment]
I'm pretty sure that I didn't cause this test failure @alalazo do you have an idea why this failed?

**Comment by healther** [comment]
okay I'm not sure why the test failed, doesn't seem to be related closed & reopened to test

**Comment by scheibelp** [comment]
> not sure why the test failed, doesn't seem to be related closed & reopened to test

This isn't an issue with this PR - it looks like one of the build tests was stalled. I have restarted it.

**Comment by healther** [comment]
thanks, is there a way to make the feedback a bit more transparent? I.e. have Travis post to github?

**Pull request merged**
