### PR TITLE
Fix missing dependencies and glibc build failures

### PR DESCRIPTION
**Pull request by michaelkuhn**
I just started building my default set of packages in a minimal Fedora 29 container and a few packages failed due to missing dependencies or glibc problems.

I have split up the changes into multiple commits to make them easy to revert if necessary.

### CODE REVIEW

**Comment by michaelkuhn** [comment]
Looks like openssl's perl dependency broke the tests again (#6830). I have added a new commit that makes the flag_handlers tests use the mock repo to fix this.

**Comment by michaelkuhn** [comment]
I have added a few more commits to fix some other missing dependencies. Additionally, findutils now build with recent versions of glibc.

**Comment by ax3l** [comment]
do you want to split the package changes from the spack library changes?

**Comment by michaelkuhn** [comment]
> do you want to split the package changes from the spack library changes?

Good point. I have extracted the flag_handlers test changes into #9132.

**Comment by michaelkuhn** [comment]
Now that #9132 has been merged, this should be good to go. I have rebased to develop (without any changes) and force-pushed to trigger the tests again.

**Comment by michaelkuhn** [comment]
@healther @ax3l Ping :-) Can we merge this?

**Comment by ax3l** [comment]
looks good to me, but I don't have merge access ;-)

**Comment by healther** [comment]
me neither :) @adamjstewart @alalazo who is our go-to-guy for merging stuff?

**Comment by scheibelp** [comment]
@healther @michaelkuhn you can also ping me to merge

**Pull request merged**
