### PR TITLE
Mark unsatisfied conditions as visited while normalizing

### LINKED ISSUE #2793: Concretization broken for version ranges
```
$ spack spec py-configparser
...
py-configparser@3.5.0%gcc@6.1.0 arch=linux-centos6-x86_64
    ^py-ordereddict@1.1%gcc@6.1.0 arch=linux-centos6-x86_64
        ^python@2.6.999%gcc@6.1.0+tk~ucs4 arch=linux-centos6-x86_64
            ^bzip2@1.0.6%gcc@6.1.0 arch=linux-centos6-x86_64
            ^ncurses@6.0%gcc@6.1.0 arch=linux-centos6-x86_64
            ^openssl@1.0.2j%gcc@6.1.0 arch=linux-centos6-x86_64
                ^zlib@1.2.10%gcc@6.1.0+pic arch=linux-centos6-x86_64
            ^readline@6.3%gcc@6.1.0 arch=linux-centos6-x86_64
            ^sqlite@3.8.5%gcc@6.1.0 arch=linux-centos6-x86_64
            ^tcl@8.6.5%gcc@6.1.0 arch=linux-centos6-x86_64
            ^tk@8.6.5%gcc@6.1.0~X arch=linux-centos6-x86_64
    ^py-setuptools@25.2.0%gcc@6.1.0 arch=linux-centos6-x86_64
```
Why is it choosing `python@2.6.999` here? I see two places where we went wrong.

First of all, `py-configparser` doesn't depend on `py-ordereddict` _unless_ we are building with Python 2.6. Spack should still default to the latest version of Python 2.7.

Second, the following doesn't fare any better:
```
$ spack spec py-ordereddict
...
py-ordereddict@1.1%gcc@6.1.0 arch=linux-centos6-x86_64
    ^python@2.6.999%gcc@6.1.0+tk~ucs4 arch=linux-centos6-x86_64
        ^bzip2@1.0.6%gcc@6.1.0 arch=linux-centos6-x86_64
        ^ncurses@6.0%gcc@6.1.0 arch=linux-centos6-x86_64
        ^openssl@1.0.2j%gcc@6.1.0 arch=linux-centos6-x86_64
            ^zlib@1.2.10%gcc@6.1.0+pic arch=linux-centos6-x86_64
        ^readline@6.3%gcc@6.1.0 arch=linux-centos6-x86_64
        ^sqlite@3.8.5%gcc@6.1.0 arch=linux-centos6-x86_64
        ^tcl@8.6.5%gcc@6.1.0 arch=linux-centos6-x86_64
        ^tk@8.6.5%gcc@6.1.0~X arch=linux-centos6-x86_64
```
This is also choosing `python@2.6.999` even though it should be choosing the latest version of Python 2.6 in Spack.

### PR DESCRIPTION
**Pull request by healther**
This should fix #2793 and #3628. I only broke a `module_parsing` test, but that seems unrelated. Nevertheless I'm not really sure of what I'm doing, please review critically

@alalazo

### CODE REVIEW

**Comment by healther** [comment]
If you agree that this is a correct way of doing this, I can either comment in the `depends_on('..', when='^...')` lines here or in a separate PR.

**Comment by healther** [comment]
@scheibelp @alalazo ping. I'd like to get feedback on this before I start building our software `^python@3.6.3`

**Comment by alalazo** [comment]
@healther I am afraid I need until early next week (say Tuesday) before having the time to take a close look at the implications of this PR.

**Comment by healther** [comment]
@alalazo okay thanks for the feedback :) I'll wait for your review

**Comment by healther** [comment]
@alalazo Did you get a chance to look at this?

**Comment by alalazo** [comment]
@healther Looking at this right now. It might take a while for me, as I don't know this part of the code much and need to figure out the implications of the changes (which from a user perspective seem indeed to fix the two issues). 

Right now I have a question that you may help answer. I rebased this PR locally on `develop` at 4dd6ee25d609f87864cef71abfcb8ebe25516131. Then I started trying to concretize a few complicated specs and noticed differences in the computed hash without other apparent differences. Take `trilinos`, for instance (I marked the different hashes to make them more visible):

**With this PR**:
```console
$ spack spec -l trilinos
Input spec
--------------------------------
trilinos

Concretized
--------------------------------
**qerrhnv**  trilinos@12.12.1%gcc@4.8~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~dtk+epetra+epetraext+exodus+fortran~fortrilinos+gtest+hdf5+hypre+ifpack+ifpack2+instantiate~instantiate_cmplx~intrepid~intrepid2+metis+ml+muelu+mumps~nox~openmp~pnetcdf~python~rol+sacado~shards+shared~stk+suite-sparse~superlu+superlu-dist+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-ubuntu14.04-x86_64 
7zka2ph      ^boost@1.65.1%gcc@4.8+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu14.04-x86_64 
wig75ws          ^bzip2@1.0.6%gcc@4.8+shared arch=linux-ubuntu14.04-x86_64 
eksallf          ^zlib@1.2.11%gcc@4.8+optimize+pic+shared arch=linux-ubuntu14.04-x86_64 
e4hkely      ^cmake@3.10.1%gcc@4.8~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu14.04-x86_64 
ddmfsab          ^ncurses@6.0%gcc@4.8 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-ubuntu14.04-x86_64 
ygcoovv              ^pkgconf@1.4.0%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
stgpdvo          ^openssl@system%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
tlvxime      ^glm@0.9.7.1%gcc@4.8 build_type=RelWithDebInfo arch=linux-ubuntu14.04-x86_64 
5vazptx      ^hdf5@1.10.1%gcc@4.8~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu14.04-x86_64 
l4xdmkz          ^openmpi@3.0.0%gcc@4.8~cuda fabrics= ~java schedulers= ~sqlite3~thread_multiple~ucx+vt arch=linux-ubuntu14.04-x86_64 
mirdssl              ^hwloc@1.11.8%gcc@4.8~cuda+libxml2+pci+shared arch=linux-ubuntu14.04-x86_64 
csy7hfl                  ^libpciaccess@0.13.5%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
qejqfff                      ^libtool@2.4.6%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
r26rlmg                          ^m4@1.4.18%gcc@4.8 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-ubuntu14.04-x86_64 
fotodb6                              ^libsigsegv@2.11%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
mhmq2ag                      ^util-macros@1.19.1%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
een6xtv                  ^libxml2@2.9.4%gcc@4.8~python arch=linux-ubuntu14.04-x86_64 
ekob74s                      ^xz@5.2.3%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
4emterp      ^hypre@2.13.0%gcc@4.8~int64~internal-superlu+mpi+shared arch=linux-ubuntu14.04-x86_64 
eiorwa3          ^openblas@0.2.20%gcc@4.8 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-ubuntu14.04-x86_64 
zzzf2hj      ^matio@1.5.9%gcc@4.8+hdf5+shared+zlib arch=linux-ubuntu14.04-x86_64 
xflmsls      ^metis@5.1.0%gcc@4.8 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 ~real64+shared arch=linux-ubuntu14.04-x86_64 
aqpmrcy      ^mumps@5.1.1%gcc@4.8+complex+double+float~int64~metis+mpi~parmetis~ptscotch~scotch+shared arch=linux-ubuntu14.04-x86_64 
ugnk4sp          ^netlib-scalapack@2.0.2%gcc@4.8 build_type=RelWithDebInfo ~pic+shared arch=linux-ubuntu14.04-x86_64 
5qpxgzq      ^netcdf@4.4.1.1%gcc@4.8~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-ubuntu14.04-x86_64 
**zzb4zyf**      ^parmetis@4.0.3%gcc@4.8 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-ubuntu14.04-x86_64 
duyygsh      ^suite-sparse@5.1.0%gcc@4.8~cuda~openmp+pic~tbb arch=linux-ubuntu14.04-x86_64 
**njpvuum**      ^superlu-dist@5.2.2%gcc@4.8~int64 arch=linux-ubuntu14.04-x86_64 
```
**On develop**
```console
$ spack spec -l trilinos
Input spec
--------------------------------
trilinos

Concretized
--------------------------------
**fwgw5nl**  trilinos@12.12.1%gcc@4.8~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~dtk+epetra+epetraext+exodus+fortran~fortrilinos+gtest+hdf5+hypre+ifpack+ifpack2+instantiate~instantiate_cmplx~intrepid~intrepid2+metis+ml+muelu+mumps~nox~openmp~pnetcdf~python~rol+sacado~shards+shared~stk+suite-sparse~superlu+superlu-dist+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-ubuntu14.04-x86_64 
7zka2ph      ^boost@1.65.1%gcc@4.8+atomic+chrono~clanglibcpp+date_time~debug+exception+filesystem~graph~icu+iostreams+locale+log+math~mpi+multithreaded patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199 +program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu14.04-x86_64 
wig75ws          ^bzip2@1.0.6%gcc@4.8+shared arch=linux-ubuntu14.04-x86_64 
eksallf          ^zlib@1.2.11%gcc@4.8+optimize+pic+shared arch=linux-ubuntu14.04-x86_64 
e4hkely      ^cmake@3.10.1%gcc@4.8~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu14.04-x86_64 
ddmfsab          ^ncurses@6.0%gcc@4.8 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-ubuntu14.04-x86_64 
ygcoovv              ^pkgconf@1.4.0%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
stgpdvo          ^openssl@system%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
tlvxime      ^glm@0.9.7.1%gcc@4.8 build_type=RelWithDebInfo arch=linux-ubuntu14.04-x86_64 
5vazptx      ^hdf5@1.10.1%gcc@4.8~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu14.04-x86_64 
l4xdmkz          ^openmpi@3.0.0%gcc@4.8~cuda fabrics= ~java schedulers= ~sqlite3~thread_multiple~ucx+vt arch=linux-ubuntu14.04-x86_64 
mirdssl              ^hwloc@1.11.8%gcc@4.8~cuda+libxml2+pci+shared arch=linux-ubuntu14.04-x86_64 
csy7hfl                  ^libpciaccess@0.13.5%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
qejqfff                      ^libtool@2.4.6%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
r26rlmg                          ^m4@1.4.18%gcc@4.8 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-ubuntu14.04-x86_64 
fotodb6                              ^libsigsegv@2.11%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
mhmq2ag                      ^util-macros@1.19.1%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
een6xtv                  ^libxml2@2.9.4%gcc@4.8~python arch=linux-ubuntu14.04-x86_64 
ekob74s                      ^xz@5.2.3%gcc@4.8 arch=linux-ubuntu14.04-x86_64 
4emterp      ^hypre@2.13.0%gcc@4.8~int64~internal-superlu+mpi+shared arch=linux-ubuntu14.04-x86_64 
eiorwa3          ^openblas@0.2.20%gcc@4.8 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-ubuntu14.04-x86_64 
zzzf2hj      ^matio@1.5.9%gcc@4.8+hdf5+shared+zlib arch=linux-ubuntu14.04-x86_64 
xflmsls      ^metis@5.1.0%gcc@4.8 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 ~real64+shared arch=linux-ubuntu14.04-x86_64 
aqpmrcy      ^mumps@5.1.1%gcc@4.8+complex+double+float~int64~metis+mpi~parmetis~ptscotch~scotch+shared arch=linux-ubuntu14.04-x86_64 
ugnk4sp          ^netlib-scalapack@2.0.2%gcc@4.8 build_type=RelWithDebInfo ~pic+shared arch=linux-ubuntu14.04-x86_64 
5qpxgzq      ^netcdf@4.4.1.1%gcc@4.8~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-ubuntu14.04-x86_64 
**xj2xqbz**      ^parmetis@4.0.3%gcc@4.8 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-ubuntu14.04-x86_64 
duyygsh      ^suite-sparse@5.1.0%gcc@4.8~cuda~openmp+pic~tbb arch=linux-ubuntu14.04-x86_64 
**wbcddji**      ^superlu-dist@5.2.2%gcc@4.8~int64 arch=linux-ubuntu14.04-x86_64 
```

Do you have any idea where these differences may come from? If not I'll start trying to get a sense of it from the dot graph.

**Comment by healther** [comment]
As far as I could see the only additional usage of `visited` is in `spec.py:l1251 traverse_edges`. There is a breaking condition `if spec in visited` which could explain the change of behaviour. Although I'm not certain it's the same `visited`.

**Comment by healther** [comment]
Okay I found some time to look at this. Here is what I found out:

First of all my solution is actually doing wrong things!

I took @alalazo's `trilinos` spec and tried to get one of the dependencies to show a discrepancy, but both `superlu-dist` and `parmetis` end up having the same hash (and spec) according to `spack spec parmetis` and `spack spec superlu-dist`. The difference only occurs only when they are both part of a larger spec.

Diffing the two yaml-representations yields:
```
$ diff tri.*
123c123
<         hash: xbdy7fma2kbh2habkpisoumq7hk5jiu5
---
>         hash: lvmbxohfbvkzfjbvg62k3pya5vrwhcxq
133c133
<         hash: 7d5t3qizvczfd64p7qlyw4d5n2qpp4hl
---
>         hash: 7iu7t3jfjep6yx7gyivz3s4h5opy4bxy
137c137
<     hash: y2wcqd7u4xefxsufwzvxkag55vbmpgdn
---
>     hash: amlagwgmpsy44upn4vvtrr6mr6exgy2u
686,697c686
<     dependencies:
<       metis:
<         hash: js6dgygw2fgg465cvx67seo5elcxiqkb
<         type:
<         - build
<         - link
<       openmpi:
<         hash: olzjwq5pl665ybgoucnu5ce6toaa7klz
<         type:
<         - build
<         - link
<     hash: xbdy7fma2kbh2habkpisoumq7hk5jiu5
---
>     hash: lvmbxohfbvkzfjbvg62k3pya5vrwhcxq
766c755
<         hash: xbdy7fma2kbh2habkpisoumq7hk5jiu5
---
>         hash: lvmbxohfbvkzfjbvg62k3pya5vrwhcxq
770c759
<     hash: 7d5t3qizvczfd64p7qlyw4d5n2qpp4hl
---
>     hash: 7iu7t3jfjep6yx7gyivz3s4h5opy4bxy
```
The missing dependencies are from `parmetis`, which when used with `trilinos` would still pick them up, but on its own they are missing.


The main action is happening in `spec.py:l2123:Spec._normalize_helper`. Previously when 
`self._evaluate_dependency_conditions(dep_name)` 
returned that we do not (or at least not yet) depend on `dep_name`, `dep_name` wasn't added to the `visited`-set. Meaning that we could in some cases end up in the situation that a _possible_ dependency (e.g. through `depends_on('^python@2.7')`, but also from the command line) was never marked as "we did look at it, but it's not relevant for us".

Marking a dependency as visited doesn't mean that it isn't changeable anymore (this happens in `_merge_dependency`), but it DOES mean that on the next call on `_normalize_helper` we will break early. I'm not yet certain why this is a problem.
From my understanding `Spec._merge_dependency` should take care of that, and it does not have a break early part. For some reason it still fails to add `metis` and `mpi` to the dependencies of `parmetis`. 

I'm not sure when I'll be able to come back to this, but I wanted to have my thoughts out here. Maybe @tgamblin or @scheibelp want to take a look? My gut feeling is that the add-to-visited-even-if-not-relevant-right-now is the correct solution and there is a different bug in `Spec._merge_dependency), but I may very well be completely wrong.

**Comment by healther** [comment]
Okay I took another turn at this. The current version (if I didn't screw up along the way) produces the same graph for `trilinos` as the current `develop` does. The solution is to use a clean `visited`-set when we insert the dependencies of a dependency. In that case we don't know what we need and may have to revisit nodes that weren't required for the original package. Hence breaking early because we visited that node at SOME prior point isn't helpful at this point.

Please take a look at it @alalazo. Since my last change didn't break any tests, the fact that this one doesn't either may not mean too much...

**Comment by healther** [comment]
@tgamblin could you add this to a somewhat soonish milestone? I'd really have a fix for the `depends_on('^python@3:')` kind of dependencies

**Comment by healther** [comment]
@alalazo @scheibelp ping

**Comment by healther** [comment]
guys I really need someone to look at this... @tgamblin @scheibelp @alalazo

**Comment by tgamblin** [comment]
I’ll look at it!

**Comment by citibeth** [comment]
Can you try this PR out with one of the problems listed in #2310 or #7156 ?  It would be great if that could be fixed and we put this little mess behind us.

**Comment by healther** [comment]
I have put all `depends_on('xxx', when='^yyy')` dependencies in our local spack and this didn't break anything so far, i.e. our software stack builds and is usable (especially also with python3 which most of the `^` dependencies we actually end up using relate to). However I can't say much regarding anything else.

**Comment by citibeth** [comment]
Sounds good to me, I'd love to see this merged.

**Comment by healther** [comment]
@tgamblin ping

**Comment by healther** [comment]
I don't think I have the time and as the new concretiser is on the horizon... For us it doesn't unreasonably blow up our installation time, so I guess we will keep it running until we run into a problem.

**Pull request closed without merging**
