### PR TITLE
ftgl: Move to frankheckenbach fork + CMakePackage

### PR DESCRIPTION
**Pull request by HadrienG2**
The original ftgl project on sourceforge [has been unmaintained since 2011](https://sourceforge.net/p/ftgl/code/HEAD/tree/), and [its last release is the 2.1.3-rc5 release candidate from 2008](https://sourceforge.net/projects/ftgl/files/FTGL%20Source/). This leaves most packages, including Spack's, in the uncomfortable situation where all they can rely on is an RC that was never finished.

Furthermore, downloading that RC is broken with the latest version of Spack, because Spack has issues translating the "2.1.3-rc5" version identifier into a download URL that ends with `FTGL Source/2.1.3~rc5/ftgl-2.1.3-rc5.tar.gz/download` (notice the `~` vs `-` inconsistency).

All hope is not lost, however, as some developers who were unsatisfied with the ftgl maintenance situation started maintaining forks of the project on GitHub. From a quick search, the most actively updated of these forks is [the one from frankheckenbach](https://github.com/frankheckenbach/ftgl), which also follows the good practice of tagging proper releases from time to time.

This PR therefore proposes enabling that fork and the releases that it has published as a supplementary download source for Spack's ftgl package.

---

Here are some other things which we could do, but which I didn't integrate in this PR as I suspected that it might cause some unnecessary controversy:

- Remove the `2.1.3-rc5` ftgl release, as its download URL generation is broken on latest Spack and probably not worth fixing.
    * A less brutal alternative would be to manually specify the proper download url as an `url=` version parameter, if `version()` allows for that.
- Remove all old ftgl releases and switch to the CMakePackage recipe. However, if we do this, I suspect we're going to hit the https://github.com/frankheckenbach/ftgl/issues/8 bug. So let's not fix what isn't broken yet?

### CODE REVIEW

**Comment by chissg** [comment]
I tentatively agree with the idea of making this a `CMakePackage`, but that would of course be pending tests with ROOT. You could add https://github.com/frankheckenbach/ftgl/commit/835f2ba7911a6c15a1a314d5e3267fa089b5a319 as a patch for 2.4.0 if you wish. Be sure to test the `+doc`  and `~doc` variants if you're going to do that, though / verify it even remains meaningful.

Finally, can I also suggest putting in a general issue that the URL generator now fails for `-rcX`?

**Comment by HadrienG2** [comment]
@chissg Here's a version that turns ftgl into a CMakePackage, which is actually a pleasantly drastic simplification. I removed the "doc" variant because...

1. I have the impression that the new docs build mechanism based on custom make/ninja command could be somewhat unpleasant to invoke from spack.
2. There doesn't seem to be any spack package using ftgl outside from ROOT, which suggests that this is a somewhat obscure library.
3. There is prior art for not including docs/tests variants in spack packages when they don't seem to be worth the trouble.

Please tell me if you think it's worthwhile to keep it alive, in which case I'll try harder.

PR is WIP while I wait for my test ROOT build to complete.

**Comment by HadrienG2** [comment]
The test ROOT build completed correctly with this PR in its current state, so I'm un-WIPping.

**Comment by chissg** [comment]
@HadrienG2 I think it would be relatively straightforward to preserve `+doc` using `@run_before` or `@run_after`, but if it doesn't shake out immediately for you I can add it as a subsequent PR when I get time.

**Comment by HadrienG2** [comment]
@chissg So, the best I could manage was this...

```diff
diff --git a/var/spack/repos/builtin/packages/ftgl/package.py b/var/spack/repos/builtin/packages/ftgl/package.py
index d68dd4c85..55e508593 100644
--- a/var/spack/repos/builtin/packages/ftgl/package.py
+++ b/var/spack/repos/builtin/packages/ftgl/package.py
@@ -16,9 +16,11 @@ class Ftgl(CMakePackage):
     version('2.4.0', commit='483639219095ad080538e07ceb5996de901d4e74')
     version('2.3.1', commit='3c0fdf367824b6381f29df3d8b4590240db62ab7')
 
+    variant('doc', default=False, description='Build the documentation')
     variant('shared', default=True, description='Build as a shared library')
 
     depends_on('cmake@2.8:', type='build')
+    depends_on('doxygen', type='build', when='+doc')
     depends_on('pkgconfig', type='build')
     depends_on('gl')
     depends_on('glu')
@@ -31,3 +33,15 @@ def cmake_args(self):
         spec = self.spec
         args = ['-DBUILD_SHARED_LIBS={0}'.format(spec.satisfies('+shared'))]
         return args
+
+    @run_after('build')
+    def build_docs(self):
+        if '+doc' in self.spec:
+            cmake = self.spec['cmake'].command
+            cmake('--build', '../spack-build', '--target', 'doc')
+
+    @run_after('install')
+    def install_docs(self):
+        if '+doc' in self.spec:
+            cmake = self.spec['cmake'].command
+            cmake('--install', '../spack-build', '--target', 'doc')
```

...at which point I ended up on a failure which I don't feel responsible for:

```
[...]

[100%] Built target ftgl
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
/opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake -E cmake_progress_start /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles 0
==> [2020-01-14-14:34:03.264054] '/opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake' '--build' '../spack-build' '--target' 'doc'
/opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake -S/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-src -B/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/gmake -f CMakeFiles/Makefile2 doc
gmake[1]: Entering directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
/opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake -S/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-src -B/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build --check-build-system CMakeFiles/Makefile.cmake 0
/opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake -E cmake_progress_start /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles 1
/usr/bin/gmake -f CMakeFiles/Makefile2 CMakeFiles/doc.dir/all
gmake[2]: Entering directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
/usr/bin/gmake -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/depend
gmake[3]: Entering directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
cd /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build && /opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/cmake-3.16.2-5hexs3i27oycbt6r77pwqtqsgm6uar52/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-src /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-src /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles/doxygen.dir/DependInfo.cmake --color=
Dependee "/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles/doxygen.dir/DependInfo.cmake" is newer than depender "/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles/doxygen.dir/depend.internal".
Dependee "/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build/CMakeFiles/doxygen.dir/depend.internal".
Scanning dependencies of target doxygen
gmake[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
/usr/bin/gmake -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
gmake[3]: Entering directory '/tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-build'
[100%] Doxygen ...
cd /tmp/root/spack-stage/spack-stage-ftgl-2.4.0-g52pnvbduybexoa5wcoqu77evxxvxspb/spack-src && /opt/spack/opt/spack/linux-opensuse_tumbleweed20200111-x86_64/gcc-9.2.1/doxygen-1.8.15-53pywi64jnlc5aaqessdwwwemnaddcqq/bin/doxygen
error: Doxyfile not found and no input file specified!
```

I've never used Doxygen so I can't be sure, but as far as I can tell this boils down to the "doc"/"doxygen" upstream build target being badly broken. Either it runs doxygen in the wrong directory or it does not pass the right input file to it.

No matter which one it is, if the above conclusion is correct, it's pretty clear to me that the "doc" target of the CMake version of ftgl's build system is just a half-hearted attempt at feature parity with the original autotools-based build system that was never actually tested.

I would personally prefer not to expend any more of my time on this.

**Comment by chissg** [comment]
@HadrienG2 Fair enough: thanks for taking a look. Could I suggest leaving the code commented-out with an explanatory TODO so the next person doesn't have to start from scratch?

**Comment by HadrienG2** [comment]
@chissg Done

**Comment by HadrienG2** [comment]
Ping @chissg, anything else you want me to do before merging?

**Pull request merged**
