### PR TITLE
wrf: new package

### PR DESCRIPTION
**Pull request by baberlevi**
refers #15246

I could use some suggestions on dealing with the configure options. I can look at the arch and compiler from spack, and combine that with the variant from the user for serial, dmpar, etc. to come up with the numeric value for the configure script, but it seems the configure script changes as wrf versions update - so that seems kludgy. Any better ideas? 

Anyway, it does seem to build and install successfully.

I plan to follow up with some of the post-processing tools, etc.

### CODE REVIEW

**Comment by bebosudo** [comment]
Hi @baberlevi!
I tried your package for wrf, but it doesn't support other compilers apart from gcc, and only with the `dmpar` build type.
At our company, we need it working with PGI and dmsm (55 in the input table: https://gist.github.com/bebosudo/f33d88872c0e7445d3ccc23c5398ac97).
I think we should change these lines:
```python
if spec.variants['build_type'].value == 'dmpar':
    build_type_value = '34'
```

to sth like:
```python
if self.spec.satisfies('%gcc'):
    if spec.variants['build_type'].value == 'serial':
        build_type_value = '32'
    elif spec.variants['build_type'].value == 'smpar':
        build_type_value = '33'
    elif spec.variants['build_type'].value == 'dmpar':
        build_type_value = '34'
    elif spec.variants['build_type'].value == 'dmsm':
        build_type_value = '35'
elif self.spec.satisfies('%intel'):
    ...
elif self.spec.satisfies('%pgi'):
    ...
    elif spec.variants['build_type'].value == 'dmsm':
        build_type_value = '55'
else:
    raise InstallError("Compiler not recognized nor supported.")
```
and a similar "switch" should be made also for the nesting variable.

I'd like to contribute to this package: should I open a pull request to your fork?

**Comment by baberlevi** [comment]
Sure, @bebosudo  - that would be great, thanks for the help

**Comment by bebosudo** [comment]
Hi! Any news about this package? We would need it included to install it on a new cluster.
@baberlevi could you fix those flake8 errors on Travis? I can also submit a patch to your fork if needed.

**Comment by bebosudo** [comment]
I'm working on some new variants, adding an old version and some fixes, I'll update your fork @baberlevi.

**Comment by tz-rrze** [comment]
Instead of patching the WRF sources, one could also make use of the existing WRF feature which accepts links to netcdf/netcdf-fortran in $src/netcdf_links. Thus, something like

```
    def configure(self, spec, prefix):
        # make links for netcdf/netcdf-fortran in the freshly extracted source tree
        os.mkdir(self.stage.source_path + "/netcdf_links")
        os.mkdir(self.stage.source_path + "/netcdf_links/include")
        os.mkdir(self.stage.source_path + "/netcdf_links/lib")
        for p in ['netcdf', 'netcdf-fortran']:
            for f in glob.glob( self.spec[p].prefix + "/include/*"):
                os.symlink(f, self.stage.source_path + '/netcdf_links/include/' + f.split('/')[-1])
            for f in glob.glob( self.spec[p].prefix + "/lib/lib*"):
                os.symlink(f, self.stage.source_path + '/netcdf_links/lib/' + f.split('/')[-1])
            ...
```
and later on
```
            ...
            Executable('env NETCDF=' + self.stage.source_path + '/netcdf_links ./configure')(input=fp)

```
would work, too. An alternative to setting NETCDF in the line above would be adding a "y" to the beginning of the answer file.

The resulting binaries have correct rpath to the real netcdf/netcdf-fortran SPACK directories.

**Comment by yellowhat** [comment]
Are there any update?

**Comment by alex--m** [comment]
@baberlevi Thanks for the patch!

Probably because this is somewhat outdated, I had a couple of issues, such as the following error (see workaround below):
````
=> Building wrf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: TypeError: a bytes-like object is required, not 'str'

/opt/ohpc/pub/spack/var/spack/repos/builtin/packages/wrf/package.py:118, in configure:
        115            fp.write(build_type + '\n' + nesting_value + '\n')
        116            fp.seek(0)
        117            import pdb; pdb.set_trace()
  >>    118            Executable('./configure')(input=fp)
````

I used the following workarounds:
````
--- a/var/spack/repos/builtin/packages/wrf/package.py
+++ b/var/spack/repos/builtin/packages/wrf/package.py
@@ -49,14 +49,14 @@ class Wrf(AutotoolsPackage):
     # http://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.0/users_guide_chap2.html#_Required_Compil
     # Section: "Required/Optional Libraries to Download"
     # parallel netcdf should not be used
-    depends_on('netcdf~parallel-netcdf')
+    depends_on('netcdf-c~parallel-netcdf')
     depends_on('netcdf-fortran')
     depends_on('jasper')
     depends_on('libpng')
     depends_on('zlib')
     depends_on('perl')
     # not sure if +fortran is required, but seems like a good idea
-    depends_on('hdf5+fortran')
+    depends_on('hdf5+fortran+hl')
     # build script use csh
     depends_on('tcsh', type=('build'))
     # time is not installed on all systems b/c bash provides it
@@ -69,7 +69,7 @@ class Wrf(AutotoolsPackage):
     depends_on('libtool', type='build')

     def setup_environment(self, spack_env, run_env):
-        spack_env.set('NETCDF', self.spec['netcdf'].prefix)
+        spack_env.set('NETCDF', self.spec['netcdf-c'].prefix)
         # This gets used via the applied patch files
         spack_env.set('NETCDFF', self.spec['netcdf-fortran'].prefix)

@@ -111,7 +111,7 @@ def configure(self, spec, prefix):

         nesting_value = nesting_opts[spec.variants['nesting'].value]

-        with tempfile.TemporaryFile() as fp:
+        with tempfile.TemporaryFile(mode='w') as fp:
             fp.write(build_type + '\n' + nesting_value + '\n')
             fp.seek(0)
             Executable('./configure')(input=fp)
````

**Comment by adamjstewart** [comment]
@baberlevi what's the status of this PR? I know a lot of people would like to build `wrf` with Spack. Maybe we can merge this in some partially working state and add follow-up PRs to iron out the bugs?

**Comment by alex--m** [comment]
Actually, our team did some work on this patch since the time of it's publication: we posted most of our work [here](https://github.com/ResearchIT/spack/pull/5), but just last week we also added Parallel-NetCDF support (so there's more on the way).

**Comment by adamjstewart** [comment]
Please submit a PR upstream 😄

**Comment by alex--m** [comment]
@adamjstewart I'd love to, but our work is based on the patches from @baberlevi - with his consent, I'll open a new PR including his patches, and our patches on top of them, to upstream.

**Comment by adamjstewart** [comment]
Alternatively, I can merge this PR as is and you can submit a follow-up PR. Whatever is easiest for folks!

**Comment by alex--m** [comment]
> 
> 
> Alternatively, I can merge this PR as is and you can submit a follow-up PR. Whatever is easiest for folks!

@adamjstewart That's easier, indeed. 👍

**Comment by adamjstewart** [comment]
Hmm, I may have gotten ahead of myself. This PR is pretty outdated and uses API calls that are deprecated and depends on packages that have been renamed. If I merge as is, our CI tests will fail. It's probably best to wait for a response from @baberlevi

**Comment by alalazo** [comment]
Would it work to submit @alex--m PR upstream and merge it with a [co-contribution](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) from @baberlevi ?

**Comment by alex--m** [comment]
I contacted @baberlevi and he agreed. I'm OOO these next few days - I'll create a new PR (including his patches) on Sunday, and make all the necessary changes to merge it upstream.

**Comment by alalazo** [comment]
@alex--m Sure, feel free to ping me on the new PR.

**Comment by alex--m** [comment]
I asked @MichaelLaufer, a member of my team, to push our latest version (#18398). It includes all the previous patches by @baberlevi and the changes we did on top of those. We've tested it on our (x86) cluster, and it works well aside from Spack's issue #8054 giving us grief (we have an ugly workaround). Similarly, we also have WPS working - I'll create a separate PR for that as well.

**Pull request closed without merging**
