### PR TITLE
Set DYLD_LIBRARY_PATH on macOS

### LINKED ISSUE #9066: On Darwin, lmod sets LD_LIBRARY_PATH, but neither DYLD_LIBRARY_PATH nor DYLD_FALLBACK_LIBRARY_PATH
### Steps to reproduce the issue

```console
$ ml load googletest
$ echo $DYLD_LIBRARY_PATH

$ echo $DYLD_FALLBACK_LIBRARY_PATH

$ echo $LD_LIBRARY_PATH
/Users/oxberry1/spack/opt/spack/darwin-sierra-x86_64/clang-9.0.0-apple/googletest-1.8.0-mnxlvco6lhjzrkedmusu7mdqghewmf2b/lib
```

### Error Message

See above; setting `LD_LIBRARY_PATH` does not affect linking via `dyld`, the macOS system linker.

### Workaround

```console
$ export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
$ # Do whatever it is you want to do
$ unset DYLD_LIBRARY_PATH
```

Note, however, that this workaround sort of defeats the purpose of using `lmod` to manage paths in environment variables -- it would be better if some sort of `dyld`-aware path functionality were build into the module files generated by spack.

### Information on your system

I'm running macOS 10.12.6. I don't think `packages.yaml` or `compilers.yaml` are particularly relevant for this issue, except perhaps that I'm building packages with an XCode-provided compiler (in my case, `clang@9.0.0-apple`).

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #9066 

Are there any other macOS-specific environment variables we should be setting? Are there any other OSes that we support aside from `darwin` and `linux`?

@goxberry

### CODE REVIEW

**Comment by adamjstewart** [comment]
@svenevs You probably know more about macOS development than I do. Can you comment on this PR?

**Comment by goxberry** [comment]
This PR works. Thanks @adamjstewart!

**Comment by ax3l** [comment]
Why don't we set the `PKG_CONFIG_PATH` on Linux/Darwin as well as in the `default/modules.yaml`? I would find that super useful :)

**Comment by adamjstewart** [comment]
We do:
https://github.com/spack/spack/blob/develop/etc/spack/defaults/modules.yaml#L35,L38

**Comment by ax3l** [comment]
Oh, I tested with the wrong package that had no `.pc` files and thought these options are overwritten. Mea culpa :)

**Pull request merged**
