### PR TITLE
Use UTF-8 encoding for logs

### PR DESCRIPTION
**Pull request by iarspider**
Fixes https://github.com/spack/spack/issues/15285
Fixes https://github.com/spack/spack/issues/18536
Fixes https://github.com/spack/spack/issues/20837

This should - hopefully - put an end to countless UnicodeDecodeErrors and UnicodeEncodeErrors when building packages (e.g. icu4c)

### CODE REVIEW

**Comment by alalazo** [comment]
> This should - hopefully - put an end to countless UnicodeDecodeErrors and UnicodeEncodeErrors when building packages (e.g. icu4c)

Is there a specific issue you are referring to? I'm building a lot of packages lately on different machines, but never got these errors. Just tried to build `icu4c` and:
```console
$ spack install  icu4c
[ ... ]
==> No patches needed for icu4c
==> 10710: icu4c: Building icu4c [AutotoolsPackage]
==> 10710: icu4c: Executing phase: 'autoreconf'
==> 10710: icu4c: Executing phase: 'configure'
==> 10710: icu4c: Executing phase: 'build'
==> 10710: icu4c: Executing phase: 'install'
==> 10710: icu4c: Successfully installed icu4c
  Fetch: 27.32s.  Build: 4m 12.12s.  Total: 4m 39.44s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.0.1/icu4c-65.1-yec4fe4muffr4piqgslwcykjbc47owcq
```

**Comment by iarspider** [comment]
It fails for me:
```
$ spack install --test=root icu4c
(...)
==> 21036: Installing icu4c
==> Fetching https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-src.tgz
########################################################################################################################################################################################################### 100.0%
==> Staging archive: /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/icu4c-65_1-src.tgz
==> Created stage in /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna
==> No patches needed for icu4c
==> 21036: icu4c: Building icu4c [AutotoolsPackage]
==> 21036: icu4c: Executing phase: 'autoreconf'
==> 21036: icu4c: Executing phase: 'configure'
==> 21036: icu4c: Executing phase: 'build'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/tty/log.py", line 447, in _writer_daemon
    line = in_pipe.readline()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 88: ordinal not in range(128)
==> Error: ProcessError: Command exited with status -13:
    'make' '-j8'
See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt

==> Error: Failed to install icu4c due to ChildError: ProcessError: Command exited with status -13:
    'make' '-j8'See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_systems/autotools.py", line 284, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j8'
```

Doing `export LC_ALL=en_US.utf8` before the build seems to be an alternative solution to the problem.

**Comment by alalazo** [comment]
@iarspider Can you please report which Python version are you using with Spack and your locale settings?

**Comment by iarspider** [comment]
```
$ python3 --version
Python 3.6.8
$ locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by alalazo** [comment]
Confirmed I was able to reproduce with:
```console
$ LC_ALL=POSIX spack install icu4c
```

**Comment by alalazo** [comment]
Looking at the Spack's code, it seems we have already this:

https://github.com/spack/spack/blob/c0032a366091c112fb68d521d137344497f7ff8b/lib/spack/spack/build_environment.py#L149-L154

and this which at first glance is redundant:

https://github.com/spack/spack/blob/c0032a366091c112fb68d521d137344497f7ff8b/var/spack/repos/builtin/packages/icu4c/package.py#L53-L57

Are you using a recent commit on the `develop` branch of Spack? If so, can you open an issue and ping me there?

**Comment by nightlark** [comment]
Is there a decision for what route to take that has been made? Setting the encoding as this PR does, or change the default in the spack config file and fallback to en_US.utf-8 if setting the locale fails as suggested by @dev-zero in #15285?

**Comment by scheibelp** [comment]
I should have read this more-carefully, it looks like an even better solution than https://github.com/spack/spack/pull/22888 (since it works for Python 2). Would you be able to update it?

**Pull request closed without merging**
