### PR TITLE
Silo: depend on Non-mpi hdf5

### PR DESCRIPTION
**Pull request by junghans**
See #7255 for discussion

### CODE REVIEW

**Comment by rspavel** [comment]
@markcmiller86 Was a solution at the silo level ever found? Currently we are running in to issues where specs cannot be concretized due to combinations that involve both silo and an hdf5+mpi dependency.

**Comment by markcmiller86** [comment]
Hmm. Is this a Silo issue or a spack issue? I mean, can't a package depend on hdf5~mpi and still be used together with other mpi-enabled packages. @tgamblin  If you are in the situation where you need to depend on *both* silo (which depends_on("hdf5~mpi")) and hdf5+mpi in the same application, can't spack handle that case?

**Comment by junghans** [comment]
Nope, see proxyapps/proxy-ci#16

**Comment by rspavel** [comment]
From limited testing it seems to cause issues with concretization. And regardless, I think that depending on multiple installations of hdf5 is one of the issues spack was meant to resolve.
So if Silo itself is not incompatible and is able to build and be used with an hdf5+mpi installation, it is probably worth going that route and putting the burden on spackage maintainers to periodically update/check the fix.

A proper solution is definitely the way to go but, in the meantime, if there is a test we can run to verify things linked together then I think using the previous workarounds coupled with a properly worded variant description wouldn't add too much technical debt and would be a good stopgap.

**Comment by markcmiller86** [comment]
>  And regardless, I think that depending on multiple installations of hdf5 is one of the issues spack was meant to resolve

yeah, I agree. So, the stop-gap of explicitly requesting NO dependence on MPI in HDF5 for silo's package.py file is obviously problematic.

I guess we need Silo's package.py file to say "...I can use whatever HDF5 you give me" and not explicitly say one or the other. So, maybe the solution is `depends_on("hdf5+mpi, when="+mpi")`(and then ensure CFLAGS and LDFLAGS for Silo's configure are set to indicate where mpi include/lib is) as well as `depends_on("hdf5~mpi",when="~mpi")`.

I guess I just don't understand why a package needs all these darn Spack gymnastics when it doesn't even depend on MPI itself. Still smells like this is an issue in Spack itself.

**Comment by rspavel** [comment]
Yeah, I have a branch (almost) ready to be turned into a PR that does almost exactly that, I was just hoping to find out a test case I can use to verify we aren't breaking functionality.

And I don't think this is a spack issue per se. The idea is that if an application is not impacted by what its dependency is built as it wouldn't have any details of that in its spackage to begin with. So in this case, it would just be `depends_on("hdf5")`

The problem is that MPI is a particularly invasive dependency coupled with other aspects of previous discussion I glossed over/that are lost due to how github stores them. So even though Silo has no dependency on MPI, the combination of it and hdf5's build system means we need to account for it anyway.

**Comment by markcmiller86** [comment]
So, the flip side of this is that I don't truly regard this as a Silo issue either. If Silo's configure is invoked to link against an mpi enabled HDF5, then is currently the responsibility of the use to ensure CFLAGS and LDFLAGS are set such that Silo's configure tests for finding hdf5 headers and linking to hdf5 libs works when those turn around and wind up including mpi.h or depending on libmpi. That is what is fundamentally happening here.

So, what I think is best/easiest is in Silo's package.py file to be able to inquire of the HDF5 library its dependent on and ask if that lib depends on mpi. If it does, that'll trigger logic to set CFLAGS/LDFLAGS with mpi paths for Silo's configure. Else, not.

**Comment by rspavel** [comment]
Cool, I'll have a PR shortly. Thanks

**Pull request merged**
