### PR TITLE
More sensible duplication of version and compiler info.

### PR DESCRIPTION
**Pull request by krafczyk**
Do not overwrite a concretized version or compiler and or version with a
non concretized version! This can happen from external packages if
their definition is not concrete!

Example: In `packages.yaml` you add an external package with a non-fully concretized spec:

```
packages:
  external-package:
    paths:
      external-package%gcc: /path/to/external-package-with-gcc
    buildable: False
```

Then you install this package with `spack install external-package`.
When checking for external and virtual packages, `external-package%gcc` matches the spec, so the install spec is replaced with `external-package%gcc`. The spec is then concretized to something more specific like `external-package%gcc@5.3.0`. During the next stage, `external-package%gcc` matches the spec again, so the spec is replaced with `external-package%gcc` thus starting an infinite loop.

This commit adds an option `soft_dup` to the `_dup` routine of a spec. When `soft_dup=True`, `_dup` prevents overwriting a spec which is concrete with one which is not.

I ment to include this set of patches with the external pacakges pull request from @alalazo but I forgot to add it.

### CODE REVIEW

**Comment by davydden** [comment]
> This can happen from external packages if
their definition is not concrete!

can you please add a regression test? see lib/spack/spack/test/concretize_preferences.py

**Comment by alalazo** [comment]
Maybe OT, but I never ran into this issue before because I always interpreted this [line of the docs](https://spack.readthedocs.io/en/latest/build_settings.html#external-packages):

>Each package version and compiler listed in an external should have entries in Spack’s packages and compiler configuration, even though the package and compiler may not ever be built

as prohibiting to have just `gcc` after a compiler statement. The rationale being that a compiler config looks like:
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14
    paths:
      cc: /usr/bin/gcc-4.8
      cxx: /usr/bin/g++-4.8
      f77: /usr/bin/gfortran-4.8
      fc: /usr/bin/gfortran-4.8
    spec: gcc@4.8 # <-- gcc won't match gcc@4.8
    target: x86_64
```
Now that I read them better, I am not really sure if I interpreted those lines correctly, as the behavior proposed above by @krafczyk seems far more intuitive.

**Comment by davydden** [comment]
on one hand hand `external-package%gcc: /path/to/external-package-with-gcc`, is indeed very intuitive. On another hand, it completely lack any info on version of `gcc`. So I am not sure this makes sense in Spack land. Essentially one is saying "here's external package built with GCC, but I don't know which or I don't care". 

Instead of this fix, I would vote a sensible error message when parsing `packages.yaml` to ask user to specify conretized spec.

**Comment by adamjstewart** [comment]
This is similar to #3164.

**Comment by krafczyk** [comment]
@davydden Let me make a case for the lazy specification:
1. Spack's specification system attempts to be as intuitive as possible. As @alalazo mentions, Whenever a version isn't specified, I take this to mean 'any compiler version'. I'd be for a warning message noting this, but I wouldn't disable it because:
2. There are indeed cases (not the norm) when this behaviour is a good idea. For example, a maintainer installs a version of some package, but either forgets or doesn't tell you what version of gcc they used. Then not specifying the version accurately reflects your knowledge about what is in that package. I think you could make an argument about how you shouldn't be using such a package, but I dont' think that's up to spack necessarily to enforce. Again it should probably give a warning, but let the user go about their business.
3. Let me give another example from my own work:

I work on a cray supercomputer which can be very annoying when building certain software dependencies such as python. I've found that not only does python take forever to compile, it is sometimes impossible with certain compilers such as cray's.
A solution I found which worked was to find the 'oldest' compiler available without loading any modules (a gcc of some type. I don't remember) and to build python manually in a directory external to spack. Now it's cheating a bit, but I can 'pretend' that this python installation is built with any compiler I like. I can now add an external package to my pacakges.yaml like `python@2.7.13: /path/to/external/python` and I'm good to go. Spack resolves the compiler version it likes, and I don't have to waste an hour for each compiler to build it's own spack-happy version of python.

**Comment by davydden** [comment]
> Whenever a version isn't specified, I take this to mean 'any compiler version'.

i see you point but in this, second, case

> I think you could make an argument about how you shouldn't be using such a package, but I dont' think that's up to spack necessarily to enforce

you can just add whichever version of `gcc` you feel like to `packages.yaml`.  Exactly as you say below

> it's cheating a bit, but I can 'pretend' that this python installation is built with any compiler I like

Personally, I am not sold on this feature. I think there could be cases when a user will get into troubles by pretending that some package is build with `gcc@6.3` but it was actually build with `gcc@4.4`. My point is that this type of hacks should be made by users **when they know what they are doing** (like what you explained above about Cray and python), instead of being automatically assumed/encouraged by Spack's parameter system. 

p.s. I certainly understand your point and see why you suggest it. Let's see what others have to say....

**Comment by alalazo** [comment]
Ok, I think this PR makes the case for pushing on #2507. If we have a command to add external packages that will impose a proper interface to ask for whatever information it needs. @mamelara What is the status of that PR?

**Comment by mamelara** [comment]
@alalazo its falling a little behind. I'm also working on looking for defaults but that can wait in favor of just having the command.

**Comment by becker33** [comment]
Closing this because the bug it was designed to fix no longer occurs.

@krafczyk feel free to reopen and ping me if you find a way to reproduce the bug that I failed to find.

**Pull request closed without merging**
