### PR TITLE
Remove `pre_run` hook

### PR DESCRIPTION
**Pull request by tgamblin**
Spack has a system of modular hooks, which are mostly used to do things before and after install.  There is also a `pre_run` hook, which has only been used so far to check the format of `compilers.yaml` (which we changed ~3.5 years ago around the time of a2f90453f).

This PR removes the `compilers.yaml` check, as it likely does nothing 99% of the time now, and is no longer needed.

As this is the last pre-run check in Spack, I'm also removing the ability to have `pre_run` hooks, as they require listing the contents of the `hooks` directory and dynamically loading modules, which consumes time at startup.  If we need to do something pre-run in the future, we should do it some way that avoids using hooks or adding startup overhead.

This PR also removes all calls to `spack.config.get()` at module scope -- so that getting things like environment module configuration is lazy.  This should also save us a few config file reads at startup.

- [x] remove pre-run hook
- [x] also remove all module-scoped calls to `spack.config.get()`, to avoid parsing unnecessary YAML on startup.
- [x] consolidate configuration `yaml` files in the `test/data/` directory to `test/data/config`
- [x] mock configuration now includes `modules.yaml` configuration (module tests were only working because we determined if they were enabled at module scope)

### CODE REVIEW

**Comment by tgamblin** [comment]
@alalazo: for some reason, removing this caused me to have to make some modifications to the `module_file_generation` hook.  I am not sure why -- but maybe you can take a look.

**Comment by alalazo** [comment]
I'll have a look at this. It seems a test related to environments (`test_env_loads`) is failing consistently across all Python versions.

**Comment by alalazo** [comment]
I have a use case where `pre_run` modifications are required: a [command extension](https://spack.readthedocs.io/en/latest/extensions.html) that is allowed to extend or modify built-in schema for its own purposes (in my case it needs to add a few attribute names to the list of allowed ones). Would that be considered a valid use case or do we want people to write separate configuration files for extensions?

**Comment by tgamblin** [comment]
@alalazo: does that really need to be a pre-run hook or could it be worked into `spack.config`?  I think the schema could be updated lazily, right?

**Comment by alalazo** [comment]
> I think the schema could be updated lazily, right?

Yeah, in the end I went that way. I'll mark this topic as outdated.

**Comment by tgamblin** [comment]
@alalazo: Ok fixed this, ready for review.  The issue was similar to some of #14309 -- because I moved where `spack.config.get()` was called, and the test config didn't include `modules.yaml`, `test_env_loads` was failing because modules were not generated.  I've consolidated the test config scope to deal with that.

**Pull request merged**
