### PR TITLE
Spack Setup (2): Developer Build Tool

### PR DESCRIPTION
**Pull request by citibeth**
Continuation of #7830

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
Finally got around to testing this branch with `spack install --setup`, and I think it could actually solve my issues raised in #7904. One think I've noticed is that packages installed via "make install" using <foo>-setup.py don't show up when I run `spack find foo`. Is that expected?

**Comment by AndrewGaspar** [comment]
Something else I was curious about is where we're expected to put our spackage manifest? Should we have a dedicated repo for all the related projects? I was following [Developing Software with Spack](https://spack.readthedocs.io/en/latest/workflows.html#developing-software-with-spack) (I know it's out of date), and it didn't seem to specify.

For now I've gone with a dedicated repo for just my related projects. I suppose you could have a super fine-grained approach where each project is its own repo.

**Comment by citibeth** [comment]
Try spack module refresh and see what happens.  I don’t use spack find

**Comment by AndrewGaspar** [comment]
I'm not sure if I was doing something wrong at first, but it's working now.

So far I'm very happy with this feature. I think it resolves the issue I opened. Let me know if you'd like me to test anything out!

**Comment by citibeth** [comment]
Sorry, this will not be merged.  Spack Setup has morphed a little bit with Spack Environments, and a new Spack Setup needs to be put together given the current context.

At this point, a change to the grammar is required so the YAML files can accommodate Spack Setup functionality.  I don't know how to change the grammar appropriately.  If someone can come up with the right YAML grammar, that would really help things.

.. Elizabeth

> During the recent Spack Environments work, I made a request to change the grammar of the YAML file to accommodate Spack Setup:

> Change YAML grammar to accommodate future inclusion of Spack Setup. See for example: https://github.com/citibeth/spack/blob/efischer/giss/var/spack/environments/twoway-dev-gibbs/env.yaml

> It was decided at the time that this change is NOT needed, and there's another way to do what Spack Setup requires.  Can you please elaborate on this, as I don't really know what to do here or how it will work?  I would like to get a (final) Spack Setup PR ready soon, now that Environments are in.

**Comment by davydden** [comment]
thanks for the clarification @citibeth .

**Pull request closed without merging**
