### PR TITLE
blast-legacy: new package at 2.2.26

### PR DESCRIPTION
**Pull request by molecuul**
provides legacy `blastall` binary required by some older packages

### CODE REVIEW

**Comment by hartzell** [comment]
This is installing a pre-built linux binary from the NCBI site.  I haven't run into too many Spack packages that grab binaries, although I guess that Java jar files aren't far off.

The source is here: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.26/ncbi.tar.gz

Looks like unpacking the tarball and running `./ncbi/make/makedis.csh` should build the things.  Details in `ncbi/make/readme.unx` from the `ncbi.tar.gz` tarball.

**Comment by molecuul** [comment]
@hartzell My mistake -- I saw the file and thought it was some SDK they were using but it does build the blastall binary. Updated to compile from source.

**Comment by hartzell** [comment]
Building failed for me.  Here's the build.out:

```consolesession
==> Executing phase: 'install'
==> [2019-02-15-07:42:34.498945] '/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/tcsh-6.20.00-5bnaboe4csivuygai627r4npznd7mter/bin/tcsh' './ncbi/make/makedis.csh'
lsb_release: Command not found.
libs version is:
ls: No match.
the gcc version is:
Reading specs from /home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-8.2.0-sxbf4jq6ghmoybsjlpqz2dm2qbbxzfyn/lib/gcc/x86_64-pc-linux-gnu/8.2.0/specs
COLLECT_GCC=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-8.2.0-sxbf4jq6ghmoybsjlpqz2dm2qbbxzfyn/bin/gcc
COLLECT_LTO_WRAPPER=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-8.2.0-sxbf4jq6ghmoybsjlpqz2dm2qbbxzfyn/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /home/ghartzell/spack/var/spack/stage/gcc-8.2.0-sxbf4jq6ghmoybsjlpqz2dm2qbbxzfyn/gcc-8.2.0/configure --prefix=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-8.2.0-sxbf4jq6ghmoybsjlpqz2dm2qbbxzfyn --disable-multilib --enable-languages=c,c++,fortran --with-mpfr=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/mpfr-3.1.6-kflyoj7nrj2mht5pf4z7mtkdp4hcbs5v --with-gmp=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gmp-6.1.2-6bsovvkqwx6zscwtbvjj6egrgizbyycm --enable-lto --with-quad --with-system-zlib --with-mpc=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/mpc-1.1.0-v5rqsbkr3zbia475v33ndowqhecvcvzn --with-isl=/home/ghartzell/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/isl-0.18-l4somr6goh77xpmdb4tey7uwovhds526
Thread model: posix
gcc version 8.2.0 (GCC)
platform is linux
Linux bifx1n03.bold.bio 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Disabling assert().
BLAST version is 2.2.26
make CFLAGS1="-DNDEBUG -O3 -c " LDFLAGS1="-O3" OTHERLIBS="-lm" SHELL="/bin/sh" LCL="lnx" RAN="ranlib" AR="ar" CC="gcc -pipe -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_GNU_SOURCE" all
chmod -R ug+rw,o+r . ../include
./ln-if-absent ../corelib/tsprintf.h ../include
make: ./ln-if-absent: Command not found
make: *** [copy] Error 127

Fatal error building NCBI core libraries.
Please be sure that you have X11 and Motif libraries installed.
The NCBI toolkit FAQ at ftp://ftp.ncbi.nih.gov/toolbox/FAQ.html may be helpful.
```

**Comment by hartzell** [comment]
Looks like those scripts are calling `/bin/csh` explicitly.  

```consolesession
[ghartzell@bifx1n03 make]$ head ln-if-absent
#!/bin/csh -f
# NOTE:  use "/bin/tcsh" above if "/bin/csh" is absent (e.g. on QNX OS)
#        use a "ln-if-absent.beos" on the BeOS platform (rename it to ln-if-absent)
#
# Make a symbolic link if the target is absent
#
# $Id: ln-if-absent,v 1.6 2002/06/17 14:27:20 ivanov Exp $
#
```

[The `ncl` package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ncl/package.py#L92-L108) dealt with a similar issue.  You'll probably need the the *sbang* fix too (for people like me who build their trees in deep paths).

**Comment by molecuul** [comment]
Hm, I'm having trouble reproducing the error there. When the build script is passed as an argument to `tcsh` I believe it should treat the shebang as a comment and ignore it.

**Comment by hartzell** [comment]
The problem is this bit of the install, where it calls that script explicitly, depending on the shebang line.

```
chmod -R ug+rw,o+r . ../include
./ln-if-absent ../corelib/tsprintf.h ../include
```

Do you have a `/bin/tcsh` on your system?  I do not.

**Pull request merged**
