### PR TITLE
patchelf : change tar.gz url to tar.bz2 url

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Comment by alalazo** [comment]
@gartung

**Comment by gartung** [comment]
Can spack unpack bzip2 archives? At the time the package was created I think only gzip archives were supported. I could be wrong.

**Comment by adamjstewart** [comment]
Spack can unpack the following archives: https://github.com/spack/spack/blob/develop/lib/spack/spack/util/compression.py#L13

gzip and bzip2 have always been there, xz might have been added later. Basically, we wrap around tar anyway, so anything tar can handle, Spack can handle.

**Comment by gartung** [comment]
I see no problem with merging this PR. The size savings is minimal but I am sure @darmac has his reasons.

**Comment by adamjstewart** [comment]
> I am sure @darmac has his reasons.

I would like to hear this reasons. Changing the URL requires everyone to redownload the tarball even if it's already in their downloads cache. If there's a good reason, that's fine. If not...

**Comment by darmac** [comment]
Well,it's a little strange, because when I download the ".gz" package:
1) it shows sha256sum not correct(tried several times and got the same different hash).
2) after I changed the sha256, it shows this package is broken.
3) I changed the package to ".bz2", then it can work.
So, I thought maybe the package on the web is broken.

But in fact, it works well in your side, I think maybe there is something wrong with my network environment. And I have tried other network environment, the ".gz" package is good.
So I will close this PR，Thanks for your kindly helps.

**Comment by darmac** [comment]
Another question, sometimes I cannot downloads some package properly, maybe it interfered by the environment on my side (e.g. firewall, overseas transmission, ...), but sourceforg and github always work well for me.
Does spack have a method to support multi-url (maybe different hash for each url) download?

**Comment by alalazo** [comment]
> Well,it's a little strange, because when I download the ".gz" package: [ ... ]

Not sure it's your case, but from what you describe could it be that you had a corrupted tarball in your cache? In that case you can clean it by:
```console
$ spack clean -d
```

**Comment by alalazo** [comment]
> So I will close this PR，Thanks for your kindly helps.

@darmac Is it fine to close this PR or are you still working on it?

**Comment by darmac** [comment]
Well, there is not any new version on `patchelf`, I will close it.

**Pull request closed without merging**
