### PR TITLE
More consistent colored messages from activate/deactivate

### PR DESCRIPTION
**Pull request by adamjstewart**
Previously, the following discrepancies existed in the messages printed by `spack activate` and `spack deactivate`:

* `spack activate` would print twice (once before "activating" and once when "activated"), while `spack deactivate` would only print once (when "deactivate")
* Specs when "activating" and when "activated" were colored differently
* Extendee spec was colored but extension spec was not

This PR removes those discrepancies.

### Before

screen shot 2018-08-21 at 11 01 17 am

### After

screen shot 2018-08-21 at 11 00 21 am

### CODE REVIEW

**Comment by healther** [comment]
I'm pretty sure we added these "double reporting" for the activating part while debugging `spack view`. I don't particularly mind right now, but it might be worth keeping it around when in debugging mode or so

**Comment by healther** [comment]
I didn't run into problems with deactivating, but from a principle point yes: Saying what you are about to do is more helpful. But if the debug output is available I'm happy either way

**Comment by adamjstewart** [comment]
Does anyone else have any opinions on whether or make `activating` or `activated` the default `tty.msg`? We have one vote for each so far.

**Comment by tgamblin** [comment]
I like `activated` here because it's obvious what you want it to do when you type the command.  For longer stuff like `spack install`, `building`, `patching`, etc. makes sense because it's a longer process and it's nice to know what's in progress (which also helps you know what failed if something goes wrong).  But for this, you know it's going to be "activating" because you told it to do it.  All you need is for it to tell you exactly what it activated.

**Comment by healther** [comment]
> But for this, you know it's going to be "activating" because you told it to do it.

This is only true if you activate specs one-by-one, if you do something like `spack activate -d py-flake8` spack will activate multiple specs, and it takes some digging to find the order

**Comment by tgamblin** [comment]
True.  I guess I don't mind `activating`, either, then 😄 .

**Pull request merged**
