### PR TITLE
patch aws-parallelcluster so that it doesn't require enum34

### PR DESCRIPTION
**Pull request by adamjstewart**
When I try to run `pcluster configure` with Python 3.7.6, I get the following error:
```
$ pcluster configure
Traceback (most recent call last):
  File "/Users/Adam/.spack/darwin/.spack-env/view/bin/pcluster", line 7, in <module>
    from pkg_resources import load_entry_point
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/Adam/.spack/darwin/.spack-env/view/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34>=1.1.6' distribution was not found and is required by aws-parallelcluster
```
It seems `enum34` is required even for Python 3.4+, where it is a builtin library.

@sean-smith @demartinofra @enrico-usai @lukeseawalker @rexcsn @ddeidda @tilne I wonder if it would be possible to use the builtin enum module in Python 3.4+ so the extra dependency wouldn't be required.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Hmm, this doesn't seem to work either. When I build `py-enum34` with `python@3.7.6`, I get the following build error:
```
==> Executing phase: 'build'
==> [2020-02-06-14:52:52.747258] '/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-2fae6in3cavuqbynqeg5jqel42wwy4on/bin/python3.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import setuptools
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/py-setuptools-41.4.0-tqlhyi4ojqflv5a737y7svaxt6zlowqf/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-2fae6in3cavuqbynqeg5jqel42wwy4on/lib/python3.7/distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-2fae6in3cavuqbynqeg5jqel42wwy4on/lib/python3.7/distutils/dist.py", line 9, in <module>
    import re
  File "/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/python-3.7.6-2fae6in3cavuqbynqeg5jqel42wwy4on/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by adamjstewart** [comment]
@sean-smith @demartinofra @enrico-usai @lukeseawalker @rexcsn @ddeidda @tilne I added some basic unit tests (can we import all the libraries, can we run `foo --help` for all the installed executables), but let me know if you want me to add anything more complex. We also run `python setup.py test`, but there don't seem to be any unit tests included in the PyPI tarball. These tests can be invoked by running `spack install --test=root aws-parallelcluster`.

**Comment by sean-smith** [comment]
@adamjstewart Thanks for the updates, we don't package the unit tests into the pypi distribution (just source) so that's something we could definitely change.

**Comment by adamjstewart** [comment]
@sean-smith personally, I think it's fine not to package tests with pypi, you want the tarballs to be as small as possible.

**Pull request merged**
