### PR TITLE
Xsdk 0.3.0

### PR DESCRIPTION
**Pull request by balay**
XSDK is a metapackage over: many packages.

Most package updates have gone through individual PRs

This PR also includes updates to:
- alquimia (xsdk release)
- pflotran  (xsdk release)
- plasma (ideally a separate PR - but then would have to wait for it to get to master before doing xsdk PR - so its included here)

### CODE REVIEW

**Comment by davydden** [comment]
> plasma (ideally a separate PR - but then would have to wait for it to get to master before doing xsdk PR - so its included here)

i think it would be much easier to review if you separate it.

**Comment by balay** [comment]
On Mon, 13 Nov 2017, Denis Davydov wrote:

> > plasma (ideally a separate PR - but then would have to wait for it to get to master before doing xsdk PR - so its included here)
> 
> i think it would be much easier to review if you separate it.

Ok https://github.com/spack/spack/pull/6280

**Comment by davydden** [comment]
blocked by https://github.com/spack/spack/pull/6280

**Comment by balay** [comment]
Could we start this review on the sources that are not part of #6280

- i.e ignoring netlib-lapack/package.py and plasma/package.py

thanks,

**Comment by balay** [comment]
#6280 is merged now. Thanks @tgamblin 

I've updated this PR with a merge from latest 'develop - that includes #6280

**Comment by balay** [comment]
@tgamblin Perhaps this is also ready for a merge?

thanks,

**Comment by tgamblin** [comment]
@balay: Done!

**Pull request merged**
