### PR TITLE
Fix external numpy package support

### PR DESCRIPTION
**Pull request by adamjstewart**
See https://github.com/spack/spack/issues/13190#issuecomment-541211722

@balay can you confirm that this fixes your problem? I confirmed that it still works as expected when building the package, but don't have an external installation to test on.

### CODE REVIEW

**Comment by balay** [comment]
Thanks! This gets rid of the error.

```
bash-4.2$ spack install py-libensemble
==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
==> py-numpy@1.12.1 : externally installed in /usr
==> py-numpy@1.12.1 : generating module file
==> py-numpy@1.12.1 : registering into DB
==> python@3.6.6 : externally installed in /usr
==> python@3.6.6 : already registered in DB
==> py-setuptools is already installed in /home/balay/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/py-setuptools-41.0.1-mzt5gwgrxtpk2fhgp7gzeiltfoa6rhu4
==> Installing py-libensemble
==> Searching for binary cache of py-libensemble
==> No binary for py-libensemble found: installing from source
==> Using cached archive: /home/balay/spack/var/spack/cache/py-libensemble/py-libensemble-0.5.2.tar.gz
==> Staging archive: /home/balay/spack-temp/stage/py-libensemble-0.5.2-2iegogywkpi7wmvuzl445lxg6jcou3fm/libensemble-0.5.2.tar.gz
==> Created stage in /home/balay/spack-temp/stage/py-libensemble-0.5.2-2iegogywkpi7wmvuzl445lxg6jcou3fm
==> No patches needed for py-libensemble
==> Building py-libensemble [PythonPackage]
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed py-libensemble
  Fetch: 0.01s.  Build: 8.06s.  Total: 8.07s.
[+] /home/balay/spack/opt/spack/linux-centos7-mic_knl/intel-18.0.2/py-libensemble-0.5.2-2iegogywkpi7wmvuzl445lxg6jcou3fm
bash-4.2$ 
```

checking xsdk now.

**Comment by balay** [comment]
my partial rebuild xsdk worked aswell.

I should do a clean rebuild [that will take a long time]. I should also avoid rebuild of `py-setuptools` by adding it to .spack/packages.yaml. [this might fix one of the osx issues for me]

**Comment by healther** [comment]
@adamjstewart this deserves a comment otherwise we will have a hard time understanding why this works

**Comment by adamjstewart** [comment]
Yeah... you're not wrong. But also, when #9149 is resolved or #11115 is merged, this hack will no longer be necessary. I'm also maintaining the numpy package in Spack, so I'm fine with making sure the bug doesn't get reintroduced.

**Pull request merged**
