### PR TITLE
libwebp: fix sha256 checksum

### PR DESCRIPTION
**Pull request by darmac**

### CODE REVIEW

**Comment by darmac** [comment]
I checked this package sha256sum in both of my different network environment.
It looks like not the same one  with the sha256 in package.py

**Comment by darmac** [comment]
@alalazo There are some PR are pending, looks like @adamjstewart  has no time to review these patches.
And we have some other patch maybe depends on these patches.
Is there any chance that these patch can be reviewed in recently?

B.R.

**Comment by scheibelp** [comment]
Closing/reopening to restart tests

Also:

> Is there any chance that these patch can be reviewed in recently?

You can ping me (scheibelp) on PRs you want looked at. I can't guarantee looking at them as fast but I should be able to get to each one within a few days.

**Comment by darmac** [comment]
> Closing/reopening to restart tests
> 
> Also:
> 
> > Is there any chance that these patch can be reviewed in recently?
> 
> You can ping me (scheibelp) on PRs you want looked at. I can't guarantee looking at them as fast but I should be able to get to each one within a few days.

Got it, thanks so much.

**Pull request merged**
