### PR TITLE
omega-h: add versions and variants

### PR DESCRIPTION
**Pull request by tristan0x**
* add 5 most recent versions and git master branch
* add trilinos, gmodel, throw, examples, optimize, symbols, and warnings variants
* disable XSDK so that Trilinos dependencies are found.

### CODE REVIEW

**Comment by tristan0x** [comment]
Jenkins failed on Python 3.5. It is a glitch, isn't it?

**Comment by tristan0x** [comment]
CC @ibaned

**Comment by ibaned** [comment]
Most of this seems okay, although I worry that turning xSDK defaults off will break compliance with the xSDK effort...

**Comment by tgamblin** [comment]
Restarted Travis.  FYI: you can open and close the PR to force a restart... it's rather annoying how often Travis flakes on us though.

**Comment by tgamblin** [comment]
@tristan0x: I see you're a first-time contributor!

Welcome to Spack!  Note that we are trying to relicense Spack, so please add your consent at #9137 if you agree to contribute this as MIT/Apache-2.0.

**Comment by tristan0x** [comment]
> Most of this seems okay, although I worry that turning xSDK defaults off will break compliance with the xSDK effort...

Trilinos is not found by CMake when xSDK is turned ON. I suggest to:
1. merge this PR as it is for now
1. discuss/fix the xSDK matter in omega_h repository
1. update spack recipe accordingly

Are you ok with that @ibaned ?

**Comment by ibaned** [comment]
@tristan0x yes, right now your usage takes priority over xSDK

**Comment by tgamblin** [comment]
Also note that things don't have to build with xSDK defaults unless they're built as part of xSDK, so the `xsdk` package can, worst case, be responsible for depending on the right variants.

**Pull request merged**
