### PR TITLE
arm-forge: add all available versions

### PR DESCRIPTION
**Pull request by nazavode**
After some failed attempts at coming up with a decent way to parametrize version checksums based on the target platform, the most straightforward solution seemed to just add an explicit platform suffix to each version and let Spack do its magic.

Please note that the previous version of this `package.py` makes Spack hang on requested user input when installing on an architecture other than `x86_64`.

Pinging @alalazo b/c of some previous discussion on this issue.

### CODE REVIEW

**Comment by nazavode** [comment]
> This looks good to me. One request, however, I believe we typically put the newer versions first.

Thanks, should be fixed now!

**Comment by lee218llnl** [comment]
perhaps we should also remove the allinea-forge package in this PR too.

**Comment by nazavode** [comment]
> perhaps we should also remove the allinea-forge package in this PR too.

Is there a way to inform users that a package has been renamed or superseded by some other package like in this case? Anyway, I can commit the removal of `allinea-forge` if it sounds ok.

**Comment by lee218llnl** [comment]
> perhaps we should also remove the allinea-forge package in this PR too.
> 
> Is there a way to inform users that a package has been renamed or superseded by some other package like in this case? Anyway, I can commit the removal of allinea-forge if it sounds ok.

I, for one, dare say we don't need to inform anyone. The URL doesn't exist anyway. I'm not sure if there are general guidelines for deleting obsolete packages. @tgamblin @becker33 @scheibelp?

**Comment by lee218llnl** [comment]
@nazavode, if you commit the removal of the allinea-forge package, then I will merge this PR.

**Comment by nazavode** [comment]
> @nazavode, if you commit the removal of the allinea-forge package, then I will merge this PR.

Just pushed, I'm sorry, I was waiting for the remaining reviewers!

**Pull request merged**
