### PR TITLE
Fix for libffs [DNM]

### PR DESCRIPTION
**Pull request by alfredo-gimenez**
Builds and tests successfully, but I'm not entirely sure if this is the right fix...

@GTKorvo ?

### CODE REVIEW

**Comment by adamjstewart** [comment]
Does pinging a repo actually notify anyone? It looks like @eisenhauer is the top contributor.

**Comment by alfredo-gimenez** [comment]
I hoped it would ping watchers, but pinging the top contributor is probably a better idea, thanks

**Comment by eisenhauer** [comment]
@adamjstewart No idea what pinging a repo is per se, but I didn't see a notification other than the mention here.  I'm the author and maintainer of libffs, but the spack package was done by @kshitij-v-mehta.   At first blush, no, I wouldn't think this would be the right fix.  Was this an attempt to maybe use lex, rather than flex?   (Or maybe the build just found lex and not flex somehow?)  Historically, lex generated to a fixed set of symbols, yylex, etc., which had the side effect that you could have only one lexer per program.  Flex let you set a symbol prefix (here "cod") to help with that problem.  I honestly don't know if libffs is compatible with traditional lex.  I think it was once, but that support might have bitrotted long ago.   Anyhow, guessing about the nature of the problem you're running into, but something like this seems likely.

Just FYI, libffs (and the entire GTkorvo software stack) have undergone significant changes in how they are build and configured since this spack package was created.  This was done so that they could be included as third-party packages directly into ADIOS2.  At some point the Spack package probably needs to be rethought.  Maybe some build arg updates would be sufficient, but maybe not...  @kshitij-v-mehta ?

**Comment by adamjstewart** [comment]
It looks like `flex` is listed as a dependency, so it will be in the `PATH` and linked via `-L` and RPATH, so it should definitely be picking up flex.

**Comment by eisenhauer** [comment]
Some more info about the problem that prompted this PR would be useful at this point.

**Comment by alfredo-gimenez** [comment]
@eisenhauer, the spack install for libffs on TOSS3 (and ubuntu) is failing with undefined references to `cod_yylex` hence the PR. We have a package (@sos_flow) that depends on evpath, and in turn, libffs. It looked like no code was being generated for `cod_yylex`, and that it was simply aliasing `yylex` in a macro, so I removed the macro. Maybe the updated spack version of Flex handles symbol prefixes differently?

**Comment by eisenhauer** [comment]
@alfredo-gimenez So, I tried to reproduce the problem on an Ubuntu VM, and actually ran into another issue with a redeclaration that has been fixed in a more recent version of libffs.  It's also the case that the more recent libffs can build without flex or bison and will just use pre-built versions of the necessary generated files if those packages aren't present.  My recommendation would be to move to a more recent version of the whole GTkorvo softwar stack and avoid all of this.  I'd be pretty sure that sosflow is going to be version agnostic, but we can double-check with @khuck (or Chad?  not sure of his github ID, or who might be packaging for Spack)  There are minor tweaks to the package files necessary (cmake_args), but I can put in a PR later today if this works for all.

**Comment by kshitij-v-mehta** [comment]
I was able to install libevpath on a Debian machine without issues, but let me update the packages anyway. I will issue a PR shortly (if @eisenhauer you aren't working on it already).

**Comment by alfredo-gimenez** [comment]
Closing in favor of #8659

**Pull request closed without merging**
