### PR TITLE
Fix Eigen include path

### PR DESCRIPTION
**Pull request by jslee02**
Eigen installs its headers in [`<install_prefix>/include/eigen3`](https://bitbucket.org/eigen/eigen/src/4f9e93b66572c3a52c23d5f463aa3aa28bca6d58/CMakeLists.txt?at=default&fileviewer=file-view-default#CMakeLists.txt-422), and the users are encouraged to include them as:
```cpp
#include <Eigen/Core>
#include <Eigen/Dense>
```

However, the current `package.py` doesn't reflect the custom path so the users have to include the headers as:
```cpp
#include <eigen3/Eigen/Core>
#include <eigen3/Eigen/Dense>
```
Otherwise, it fails to find the header.

This PR fixes it following [this guide](https://spack.readthedocs.io/en/latest/module_file_support.html#override-api-calls-in-package-py).

### CODE REVIEW

**Comment by adamjstewart** [comment]
@svenevs

**Comment by davydden** [comment]
@alalazo could you pleaseadvie how to fix it using the new interface in HeadersList?

**Comment by scheibelp** [comment]
(Apologies for closing this, that was accidental)

Regarding https://github.com/spack/spack/pull/10773#issuecomment-469355115:

> I use scons as a buildsystem for my project and run spack module loads <packages> to let scons find the package location using the environment variables (e.g., CPATH). Could you please elaborate how this PR fixes #10751 without modifying CPATH?

#10773 does not address this use case. It does fix an issue with the Spack eigen package, so I merged it and kept this open. Unfortunately, that merge created a conflict here; FYI the function you add here can just be added without consideration of the other changes in #10773.

Also note: I'm willing to merge this for now, but `CPATH` modifications have caused trouble in the past (see for example: https://github.com/spack/spack/pull/10644). You only modify `run_env` so that will avoid issues with building Spack packages; the motivation for #10644 remains because that author is also interested in external-to-Spack builds.

**Comment by jslee02** [comment]
Thank you for the clarification! I'm new to spack, but your description helped me to understand spack better. I resolved the conflict. Please let me know if further change is required.

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
