### PR TITLE
Balay/xsdk trilinos develop

### PR DESCRIPTION
**Pull request by balay**
The first commit can be reverted once the following gets resolved

https://github.com/trilinos/Trilinos/pull/320

cc: @jwillenbring @keitat

### CODE REVIEW

**Comment by jrood-nrel** [comment]
@balay I just noticed that the `superlu_dist_v5.4.0.patch` is failing for Trilinos `develop` branch now. Is the correct solution to revert the first commit here then?

**Comment by davydden** [comment]
> I just noticed that the superlu_dist_v5.4.0.patch is failing for Trilinos develop branch now. Is the correct solution to revert the first commit here then?

I think only the patching should be removed (first commit has one extra change)

**Comment by balay** [comment]
Yes - the relevant superlu_dist patches are in trilinos develop branch.
However the fixes are not yet in 'trilinos-release-12-14-branch' branch - needed for xsdk-0.4.0 release.

So for now - will remove them from spack-develop

https://github.com/spack/spack/pull/9422

**Comment by balay** [comment]
@jrood-nrel , spack develop is now updated

**Pull request merged**
