### PR TITLE
Build shared libs for tinyxml.

### PR DESCRIPTION
**Pull request by weijianwen**

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like @mdavezac wrote the original `CMakeLists.txt` in #2627. Would you mind reviewing this? Regrettably, I don't know much about CMake.

**Comment by mdavezac** [comment]
will do

**Comment by mdavezac** [comment]
@adamjstewart, this looks good to me. I'm not sure where the codecov failure is coming from.

**Comment by adamjstewart** [comment]
> I'm not sure where the codecov failure is coming from.

See the note at the bottom of http://spack.readthedocs.io/en/latest/contribution_guide.html#coverage

**Pull request merged**
