### PR TITLE
improve ssh handling in docker images

### PR DESCRIPTION
**Pull request by opadron**
Salvaged from #12636, this PR reworks how some of the shell scripts in the docker images work.  The most visible effect of these changes are that downstream image builds now have access to a few commands implemented as shell functions, mostly for cleanly starting and stopping sshd.

For example:

```Dockerfile
FROM spack/centos7

RUN spack install my-mpi-app \
 && ssh_init \
 && some-command-that-uses-mpi # needs ssh \
 && ssh_clear

...
```

### CODE REVIEW

**Comment by tgamblin** [comment]
@opadron: why do we need the container images to run `sshd`?  Is this for GitLab?  What's the motivation?

**Comment by opadron** [comment]
@tgamblin, I was going to say that `sshd` is supposed to be for MPI apps, but I realize

1. There's already an `openssh` spack package, and
1. None of the other spack packages depend on it.

So, I'm wondering if I'm just not privy to how the latest versions of MPI work.

1. If I wanted to run an MPI code with ranks spread across multiple containers, would the containers need to be running `sshd`?
1. If "yes" to the above, would installing the `openssh` spack package be sufficient in preparing the above containers?

**Comment by tgamblin** [comment]
@opadron: I’m confused about why this is necessary right now.  I’d *really* rather you work on the S3 PR.

**Comment by tgamblin** [comment]
Regarding MPI, it’s likely that containers needing MPI are going to use some other mechanism to start it up (like bindmounting the host MPI implementation, and working through PMI or some other startup mechanism). I do not believe that it is necessary to run sshd in the container at all.

**Comment by adamjstewart** [comment]
Is this PR still a WIP or can it be closed?

**Comment by opadron** [comment]
Closing.  This PR isn't relevant, anymore.

**Pull request closed without merging**
