### PR TITLE
tau: added new variants

### PR DESCRIPTION
**Pull request by carsonwoods**
This PR adds new variants to the Tau package. Unfortunately, as best I could tell, Tau has no way to explicitly disable a config option, only enable it explicitly. Because of this this PR contains no logic for explicitly disabling these new config options. 

New variants are added for enabling profiling, profile parameters, profile callpaths, tau to slog2 conversion, and the cputime option.

### CODE REVIEW

**Comment by wspear** [comment]
@carsonwoods Hi Carson. With the exception of -PROFILEPARAM, which is very rarely used, the variants you added are deprecated/redundant and only in TAU for historical purposes. They should not be in the Spack package. Could you please roll back the other variants you added here? Thanks.

**Comment by adamjstewart** [comment]
@wspear are you interested in maintaining the `tau` package in Spack?

**Comment by carsonwoods** [comment]
@wspear Sorry about that, I'll remove them now. See #16041. Thanks for letting me know!

**Comment by adamjstewart** [comment]
> If there is a way to be assigned an official maintainer position, or to get updates when the package is changed, that would be useful.

Yes! Just add the following to the `package.py`:
```python
maintainers = ['wspear', 'eugeneswalker', ...]
```
It's not currently _automatic_, but I do check for maintainers and ping them before merging things. Also, you don't need to be an expert on the package or a developer, you just need to be someone who cares and is willing to review PRs or take a look at build issues.

**Pull request merged**
