### PR TITLE
Make setup use all environment changes from build_environment

### PR DESCRIPTION
**Pull request by becker33**
Resolves an issue with compiler flags and the spack setup command reported by @bvanessen. 

Still working on testing this with @bvanessen

### CODE REVIEW

**Comment by alalazo** [comment]
@becker33 Not sure it's relevant here, but since #3183 we vendor `jinja2` (just in case it could be considered helpful to generate `spconfig`)

**Comment by pramodskumbhar** [comment]
@becker33  : just curious,  is `spack setup` working for you? `spack setup` is broken with the develop branch and I have been testing and reporting issues in PR #5043.

**Comment by adamjstewart** [comment]
Is this PR still a WIP or can we close it?

**Comment by bvanessen** [comment]
@adamjstewart Honestly I had lost track of this PR and I don't know if it is still relevant.

**Pull request closed without merging**
