### PR TITLE
libplist, libusbmuxd: Fix pkgconfig dependency

### PR DESCRIPTION
**Pull request by michaelkuhn**
pkgconfig is the correct virtual provider.

### CODE REVIEW

**Comment by michaelkuhn** [comment]
@whitfin: Was there any reason for using pkg-config explicitly?

**Comment by whitfin** [comment]
@michaelkuhn just that the libraries in their README have `pkg-config` as a dependency. Is there some significant difference as to why `pkgconfig` should be preferred (for reference when adding more packages later)?

**Comment by alalazo** [comment]
Despite this PR seems sensible we have an issue with build deps I think:
```console
$ spack spec -Il libplist ^pkgconf
Input spec
--------------------------------
 -   libplist
 -       ^pkgconf

Concretized
--------------------------------
[+]  wxa3i2x  libplist@2.0.0%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 
[+]  zaevtj5      ^pkgconf@1.5.4%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 

$ spack spec libusbmuxd ^pkgconf
Input spec
--------------------------------
libusbmuxd
    ^pkgconf

Concretized
--------------------------------
==> Error: Multiple providers found for 'pkgconfig': ['pkg-config@0.29.2%gcc@8.2.0+internal_glib arch=linux-ubuntu18.04-x86_64', 'pkgconf@1.5.4%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64']

$ spack spec -Il libusbmuxd ^/wxa3i2x
Input spec
--------------------------------
 -   libusbmuxd
[+]      ^libplist@2.0.0%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 

Concretized
--------------------------------
 -   yeebdws  libusbmuxd@1.0.10%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 
[+]  wxa3i2x      ^libplist@2.0.0%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 
 -   hkqu4ng          ^pkg-config@0.29.2%gcc@8.2.0+internal_glib arch=linux-ubuntu18.04-x86_64 

$ spack spec -Il libusbmuxd ^/wxa3i2x ^pkgconf
Input spec
--------------------------------
 -   libusbmuxd
[+]      ^libplist@2.0.0%gcc@8.2.0 arch=linux-ubuntu18.04-x86_64 
 -       ^pkgconf

Concretized
--------------------------------
==> Error: Multiple providers found for 'pkgconfig': ['pkg-config@0.29.2%gcc@8.2.0+internal_glib arch=linux-ubuntu18.04-x86_64', 'pkgconf']
```
Is anybody aware if we have an issue already open for this?

**Comment by adamjstewart** [comment]
@alalazo see #7339. There are also dozens of other issues with the "multiple providers found for" message.

**Comment by alalazo** [comment]
@adamjstewart I'd merge this, what do you think?

**Comment by michaelkuhn** [comment]
> @michaelkuhn just that the libraries in their README have `pkg-config` as a dependency. Is there some significant difference as to why `pkgconfig` should be preferred (for reference when adding more packages later)?

@whitfin pkgconfig is our virtual provider for either pkg-config (legacy) or pkgconf (the default). pkgconf has fewer dependencies and has replaced pkg-config as the default implementation in most Linux distributions.

**Comment by michaelkuhn** [comment]
> Despite this PR seems sensible we have an issue with build deps I think:

@alalazo With the PR merged, your examples work for me. It seems that whenever a package does not use the virtual provider as a dependency, this issue comes up.

**Pull request merged**
