### PR TITLE
dyninst: add patch to work with new boost

### PR DESCRIPTION
**Pull request by mwkrentel**
Add tribool.patch to add explicit casts from tribool to bool in two
places.  Boost, starting with version 1.69, turned on explicit
conversions for tribool, which breaks the build for dyninst.

----------

The purpose of this PR is to allow dyninst 9.3.x and 10.0.0 to work
with the latest boost >= 1.69.

Also, probably within a week, I expect dyninst 10.1.0 to be released.
10.1 will include the patch.

My plan is to wait for 10.1 to be tagged and released and fold that
into this PR.  It's a 1-line change to add version 10.1.0 and I could
add that line now.  (I know what the tag will be.)  We just have wait
until the tag exists before merging the PR.

I'm leaning in favor of waiting, but we could do two commits if the
release is delayed.  Either way.

ping @hainest from dyninst

### CODE REVIEW

**Comment by sknigh** [comment]
This PR let me build 10.0.0 with boost 1.69.0

**Comment by scheibelp** [comment]
Is this patch from somewhere? Could a link be added if so (not to say the patch has to be a URL patch, but the link may contain an explanation).

**Comment by mwkrentel** [comment]
The patch is from dyninst/dyninst PR #541 that I submitted, not yet
merged into dyninst, so there isn't a commit to refer to yet.

I'm ok with merging this now, not waiting for dyninst 10.1.

Btw, I expect dyninst 10.1 will include this patch.
That's why I wrote the spec:

```
patch('tribool.patch', when='@9.3.0:10.0.0 ^boost@1.69:')
```

The code that fails doesn't exist before 9.3.0, the patch is needed
for 9.3.0 to 10.0.0, and I expect the patch will be included in 10.1
and later.

**Comment by scheibelp** [comment]
> The patch is from dyninst/dyninst PR #541

I think the link may have gotten clobbered.

IMO it would be great to add a link to the PR you submitted to `dyninst` as a comment on the `patch` clause in the Spack dyninst package - could you do that?

**Comment by mwkrentel** [comment]
> I think the link may have gotten clobbered.

Github is interpreting 541 as a spack issue, mainly because I didn't
know how to specify an issue from another repo.

I think we're into bikeshed territory here.
https://www.freebsd.org/doc/en/books/faq/misc.html#idp50187640

I wrote a description for the patch in the patch itself, although I
didn't include the dyninst PR ref.  I might prefer that, but I'll
figure something out.

More importantly, I'd like to get Mario's PR #10369 merged.  That's
blocking me from building on Cray.

**Comment by scheibelp** [comment]
The explanation is useful, but the link will tell people in the future whether this patch was rejected, or whether it was delayed to a later release; therefore I think it is a worthwhile update rather than a nitpick. I almost always request that the origin of patches be recorded (for one thing, it determines whether Spack is the only place this patch exists).

> More importantly, I'd like to get Mario's PR #10369 merged. That's blocking me from building on Cray.

I'll try to comment on that today (in the PR thread), I had some concerns with it

Also, bike sheds should be painted red because red paint is cheapest.

**Comment by mwkrentel** [comment]
@scheibelp Sorry, I just meant that it's a simple, 2-line patch and I
didn't want to go overboard.  (Plus, there was already an explanation
in the patch itself.)

Sure, I can put in a reference to dyninst.  I'll add something
tomorrow.  Is the patch ok, that's where I wrote the explanation.

**Comment by mwkrentel** [comment]
Well, just this afternoon, my PR to dyninst was merged.
So, I expanded the description and added a link to the commit.

Unless there's something else, then I'm done.

**Pull request merged**
