### PR TITLE
Re-add list_url for all R packages

### LINKED ISSUE #6104: r-igraph 404
```
==> Installing r-igraph
==> Fetching https://cran.r-project.org/src/contrib/igraph_1.0.1.tar.gz

curl: (22) The requested URL returned error: 404
==> Fetching from https://cran.r-project.org/src/contrib/igraph_1.0.1.tar.gz failed.
==> Error: FetchError: All fetchers failed for r-igraph-1.0.1-3yi2pl375w4rscthxq6yywk3geqkx725
FetchError: FetchError: All fetchers failed for r-igraph-1.0.1-3yi2pl375w4rscthxq6yywk3geqkx725

/pbtech_mounts/softlib001/apps/EL6/spack/lib/spack/spack/package.py:991, in do_fetch:
     25                                     self.spec.format('$_$@'), ck_msg)
     26    
     27            self.stage.create()
  >> 28            self.stage.fetch(mirror_only)
     29            self._fetch_time = time.time() - start_time
     30    
     31            if spack.do_checksum and self.version in self.versions:
```

Now at https://cran.r-project.org/src/contrib/Archive/igraph

### PR DESCRIPTION
**Pull request by mathstuf**
Fixes #6104.

---
Cc: @JusticeForMikeBrown

### CODE REVIEW

**Comment by mathstuf** [comment]
I added commits to use the CRAN archive for all CRAN packages.

Cc: @lingnanyuan @fanne-stat @glennpj @JavierCVilla (based on R package commit statistics)

**Comment by fanne-stat** [comment]
I think for CRAN packages there is default list_url. See #4439. And sometimes the old versions still cannot be installed when you have list_url.

**Comment by mathstuf** [comment]
Hmm, I see. Then why was it failing for `r-igraph`, `r-irlba`, and `r-lazyeval` (at least) if there's a default URL? Ideas @adamjstewart?

**Comment by adamjstewart** [comment]
I removed these `list_url`s in @4439 because I didn't realize that `list_url` served a double purpose. The default `list_url` I added for CRAN helps find versions of a new package during creation, but it doesn't find existing versions of a package after they have been moved. The `package.py` `list_url` does double duty, which I didn't realize at the time.

@4516 was supposed to fix this by re-adding the `list_url`s for every package, but never got merged due to a bad rebase. So :+1: from me! Once this is merged, we can rewrite @4516 to do what it was intended to do.

**Comment by JusticeForMikeBrown** [comment]
Excellent!

**Pull request merged**
