### PR TITLE
Module parsing: improve checking of path variables based on package name

### PR DESCRIPTION
**Pull request by scheibelp**
Module parsing (to extract package paths from associated module files of Spack external packages) was potentially missing cases where a module named something like `foo-bar/1.0.0` set an environment variable like `FOO_BAR_DIR`, and in that case not finding the package.

This adds some formatting steps when checking the contents of `module show` for a variable set by the module based on the package name.

This is related to https://github.com/spack/spack/issues/9232 but technically this type of parsing would be required for either strategy (in the case of #9232 it's a matter of checking for the right environment variable).

### CODE REVIEW

**Comment by bavier** [comment]
What does spack expect to find in the 'external_path'?  Is it looking for "/lib", "/include", etc?  I ask, because this patch seems like it would end up using e.g. the "CRAY_LIBSCI_DIR" variable from cray-libsci, which doesn't have the typical "/lib" and "/include".  The more desirable path for cray-libsci, I think, would be the one found in the CRAY_LD_LIBRARY_PATH set by the cray-libsci module (which spack currently doesn't parse right because of the "CRAY_" prefix and the use of find() instead of rfind()).

**Comment by scheibelp** [comment]
> What does spack expect to find in the 'external_path'? Is it looking for "/lib", "/include", etc? 

Yes

> this patch seems like it would end up using e.g. the "CRAY_LIBSCI_DIR" variable from cray-libsci, which doesn't have the typical "/lib" and "/include"

That was my intent but I'm not actually familiar with the directory structure. Out of curiosity, are they in some nested directory? Or in some completely unrelated path?

I'm trying to decide if it's the business of this PR to pay more attention to the appropriate path to extract, or the business of Cray packages to understand the directory structure better and calculate the appropriate lib/include dirs from the prefix (e.g. https://github.com/spack/spack/pull/7634 has a specialized implementation of `.libs`)

**Comment by bavier** [comment]
> > this patch seems like it would end up using e.g. the "CRAY_LIBSCI_DIR" variable from cray-libsci, which doesn't have the typical "/lib" and "/include"
> 
> That was my intent but I'm not actually familiar with the directory structure. Out of curiosity, are they in some nested directory? Or in some completely unrelated path?

Most are in a nested subdirectory, but other packages might have several directories.

> I'm trying to decide if it's the business of this PR to pay more attention to the appropriate path to extract, or the business of Cray packages to understand the directory structure better and calculate the appropriate lib/include dirs from the prefix (e.g. #7634 has a specialized implementation of `.libs`)

There are probably some sensible defaults.  Looking at CRAY_LD_LIBRARY_PATH is a good start.  But I agree, having the Cray packages calculate the dirs is probably a better way to go.

**Comment by scheibelp** [comment]
As noted in https://github.com/spack/spack/pull/9374#issuecomment-425250705, detection of `CRAY_LD_LIBRARY_PATH` was also broken (the regex in https://github.com/spack/spack/pull/9100 was made overly-strict) and is now fixed here.

**Pull request merged**
