### PR TITLE
libxc: Download from git, new version 4.3.4

### PR DESCRIPTION
**Pull request by jabl**
The libxc homepage has been missing in action for a long time, making
installations fail. See e.g. https://gitlab.com/libxc/libxc/issues/110
.  Thus switch to downloading from the upstream git repo.  The old
version hashes are left commented out, in case the libxc website
returns to life at some point and somebody wishes to switch the spack
package back to downloading tarballs.

However, the upstream repo does not contain a configure script, thus:

- To generate the configure script, add build dependencies on
  autotools.

- The patch file patches the configure script from the tarballs, which
  doesn't exist when downloading via git. Thus remove it. This then
  effectively removes the support for the Fujitsu compiler that was
  added by the patch. I guess the proper solution would be to add
  Fujitsu compiler support to autoconf, but that is probably better
  done by somebody having access to said compiler and being able to
  test it.

### CODE REVIEW

**Comment by jabl** [comment]
Ping @t-karatsu

**Comment by t-karatsu** [comment]
Sorry for late reply... For now, we believe that if we can apply changes on #12004 pull request to Fujitsu compiler, we can do it.

**Comment by chuckatkins** [comment]
Rather than switch to the git clones for everything, you can keep the tarballs for releases by pointing to the gitlab download url: `https://gitlab.com/libxc/libxc/-/archive/4.3.4/libxc-4.3.4.tar.gz`

**Comment by simonpintarelli** [comment]
Could someone please merge this PR? Installing libxc is failing at the moment, although tddft.org is back (all but the v4.3.4 release tar.gz have been removed from the page).

Btw, here are the hashes for the gitlab version (tar.gz):
```
    version('4.3.4', sha256='2d5878dd69f0fb68c5e97f46426581eed2226d1d86e3080f9aa99af604c65647')
    version('4.3.2', sha256='3bbe01971d0a43fb63b5c17d922388a39a3f0ae3bd37ae5f6fe31bca9ab63f3c')
    version('4.2.3', sha256='869ca4967cd255097fd2dc31664f30607e81f5abcf5f9c89bd467dc0bf93e5aa')
    version('3.0.0', sha256='df2362351280edaf2233f3b2c8eb8e6dd6c68105f152897a4cc629fa346a7396')
    version('2.2.2', sha256='6ffaad40505dbe8f155049448554b54ea31d31babf74ccf6b7935bfe55eeafd8')
    version('2.2.1', sha256='c8577ba1ddd5c28fd0aa7c579ae65ab990eb7cb51ecf9f8175f9251f6deb9a06')

 ```

**Comment by chuckatkins** [comment]
This still needs to be adjusted to use tarballs, even if downloaded from gitlab, instead of the git repo for all versions.

**Comment by simonpintarelli** [comment]
I've added the tarballs already: https://gist.github.com/7bd9c89b42c639f43dd225fc46938b74


```
 homepage = "https://gitlab.com/libxc"
    url      = "https://gitlab.com/libxc/libxc/-/archive/2.2.2/libxc-2.2.2.tar.gz"

    version('4.3.4', sha256='2d5878dd69f0fb68c5e97f46426581eed2226d1d86e3080f9aa99af604c65647')
    version('4.3.2', sha256='3bbe01971d0a43fb63b5c17d922388a39a3f0ae3bd37ae5f6fe31bca9ab63f3c')
    version('4.2.3', sha256='869ca4967cd255097fd2dc31664f30607e81f5abcf5f9c89bd467dc0bf93e5aa')
    version('3.0.0', sha256='df2362351280edaf2233f3b2c8eb8e6dd6c68105f152897a4cc629fa346a7396')
    version('2.2.2', sha256='6ffaad40505dbe8f155049448554b54ea31d31babf74ccf6b7935bfe55eeafd8')
    version('2.2.1', sha256='c8577ba1ddd5c28fd0aa7c579ae65ab990eb7cb51ecf9f8175f9251f6deb9a06')
```

**Comment by chuckatkins** [comment]
@simonpintarelli That looks good to me.  It's not part of this PR though so could you make a new PR with those changes and just reference that it supersedes this one?  I'll be happy to close this and merge that in liu of.

**Comment by simonpintarelli** [comment]
@chuckatkins: Thanks, I've submitted a PR #13471 referencing this one.

**Comment by chuckatkins** [comment]
Superseded by #13471

**Pull request closed without merging**
