### PR TITLE
Added the CUDA_TOOLKIT_ROOT_DIR field to the environment

### PR DESCRIPTION
**Pull request by bvanessen**
Fixes https://github.com/spack/spack/issues/14804

### CODE REVIEW

**Comment by bvanessen** [comment]
@scheibelp

**Comment by bvanessen** [comment]
@scheibelp It is hard to know if this works because of the other bug where external packages are not properly included in the view issue #14743.  I get the following message when loading the environment. 

`Warning: [spack.git/var/spack/environments/lbann-dev-broadwell-cuda/.spack-env/view] Skipping external package: cuda@10.0.130%gcc@7.3.0 arch=linux-rhel7-broadwell/ldfmnok`

**Comment by ax3l** [comment]
Since this PR lacks a description: why do we add this environment variable?
I am only aware of `CUDA_TOOLKIT_ROOT_DIR` as a CMake variable.

**Comment by bvanessen** [comment]
When cuda is included as a package in an environment, it is not properly configured when the environment is activated.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by ax3l** [comment]
> When cuda is included as a package in an environment, it is not properly configured when the environment is activated.

I see the intention, I am looking for the source of this claim. Does Nvidia by default set this environment variable when installing the CUDA Toolkit via their `runscript` install?

**Comment by ax3l** [comment]
ping @bvanessen :)

**Comment by bvanessen** [comment]
It turns out that if I make cuda a root package in the environment then the CUDA_HOME is placed into the users environment when it is activated.  We can close this.

**Pull request closed without merging**
