### PR TITLE
camellia: fix hdf5 dependency

### PR DESCRIPTION
**Pull request by t-karatsu**
As camellia needs hdf5 version:1.8.x, we changed the way to specify version of hdf5.

comments from https://github.com/spack/spack/pull/8337
"HDF5 1.10.x is incompatible with Camellia, at least right now, so adding dependency to versions up to 1.8.x."

### CODE REVIEW

**Comment by citibeth** [comment]
Please add a comment to the package referencing the #8337 URL that explains the incompatibility.

**Comment by t-karatsu** [comment]
I added a comment to #8337.

"Hello, Nate.
Camellia specifies hdf5 version with 'hdf5@:1.8', but It is determined that "1.8.10" or "1.8.21" does not correspond to the condition. So, the following error occurs.
'==> Error: Invalid Version range: 1.8.9:1.8'

As camellia needs hdf5 version:1.8.x, I corrected the condition to specify version of hdf5 as follows.
'depends_on('hdf5@:1.8.21')'
Could you tell me if there are any problems?
#11810"

**Comment by citibeth** [comment]
This needs a comment in THIS PR, something along the lines of:
```
# Cameilla needs hdf5 but It is determined that "1.8.10" or "1.8.21" does not work.
# See https://github.com/spack/spack/pull/8337

**Comment by t-karatsu** [comment]
Sorry, I see what you mean. 
I added comment to this PR on commit "camellia: Add comment".
Could you confirm this commit contents?

**Pull request merged**
