### PR TITLE
byobu: add tmux to $PATH

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by hartzell** [comment]
On my system the lua modulefile for `byobu` includes

```lua
if not isloaded("tmux/2.7-7sgiyx2") then
    load("tmux/2.7-7sgiyx2")
end
```

and loading it adds the `tmux` bin to my PATH.

The dependency in the copy of the `byobu` package that I have is:

```python
    depends_on('tmux', type=('build', 'run'))
```

with no extra environment setup.

**Comment by matthiasdiener** [comment]
Without this patch, when I run `spack load byobu`, tmux does not get added to the $PATH, and byobu can not be run (despite the `depends_on(... type='run')`) :
```
/Users/mdiener/Work/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/byobu-5.125-qymgjvuj6y667efuayssriaqyto75qev/bin/byobu: line 238: exec: tmux: not found
```

**Comment by hartzell** [comment]
I use Lmod modules and don't go through `spack load`.  I'm not sure how it decides what modules tool to load.

Do you have any modulefiles for `byobu` (under `share/spack/`)?  What does your modules configuration look like (have you overridden any of the defaults?)

Is your shell set up to use modules (e.g. does `module avail` do anything interesting?)?

**Comment by matthiasdiener** [comment]
As far as I understand, `spack load` never loads any dependencies. 

I do have module files for bayou and tmux under share/spack. I didn't change any module configuration (As I am on Mac OS, I'm using spack bootstrap for modules).

`module avail` shows the byobu and tmux modules.

**Comment by healther** [comment]
I used to use 
```
spack load -r <mypackage>
```
or
```
spack module loads -r <mypackage>
```
to effectively do the `autoload` thing manually. But I never completely understood how the module system was supposed to be used. I, as a user, always expected `spack load` to just work :tm:, which would require autoload in all modules. For some reason, that I don't remember anymore, this didn't get picked up

**Comment by hartzell** [comment]
@adamjstewart ...

> @hartzell I just tested this on macOS and without any changes to the default modules.yaml (aside from enabling LMod and setting a core_compiler), none of the 3 modules systems autoload 'run' dependencies by default.

Hmmm.  I just checked out a clean tree, built *byobu*, added this `etc/spack/modules.yaml` file

```yaml
modules:
  enable::
    - lmod
    - tcl
  lmod:
    core_compilers:
      - 'gcc@4.8.5'
```

and generated the lmod modulefiles with 

```
spack module refresh --module-type lmod --delete-tree -y
```

I got the same result you got: neither the tcl nor the Lmod modulefiles autoloaded *tmux*.

Then I added a bit from *my* standard `modules.yaml` that *should* generate autoloads for packages that depend on *python* (following [the documentation](https://spack.readthedocs.io/en/latest/tutorial_modules.html#autoload-dependencies), the resulting `modules.yaml` file contained:

```yaml
modules:
  enable::
    - lmod
    - tcl
  lmod:
    core_compilers:
      - 'gcc@4.8.5'
    ^python:
      autoload:  'direct'
```

The resulting *byobu* Lmod modulefile contained:

```lua
if not isloaded("tmux/2.7-2b6gc3z") then
    load("tmux/2.7-2b6gc3z")
end
```

@alalazo -- I expected this line to only generate autoloads for things that depend on *python*.  *byobu* does not seem to depend on Python:

```
[hartzell@bunny spack]$ spack spec -t byobu
Input spec
--------------------------------
[    ]  byobu

Concretized
--------------------------------
[    ]  byobu@5.125%gcc@4.8.5 arch=linux-centos7-x86_64
[b r ]      ^tmux@2.7%gcc@4.8.5 arch=linux-centos7-x86_64
[bl  ]          ^libevent@2.0.21%gcc@4.8.5+openssl arch=linux-centos7-x86_64
[bl  ]              ^openssl@1.0.2o%gcc@4.8.5+systemcerts arch=linux-centos7-x86_64
[bl  ]                  ^zlib@1.2.11%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64
[bl  ]          ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-x86_64
[b   ]              ^pkgconf@1.4.2%gcc@4.8.5 arch=linux-centos7-x86_64

[hartzell@bunny spack]$
```

Is this a bug or a SNAFU on my part?

**Pull request closed without merging**
