### PR TITLE
silo: add an updated config.guess to configury

### PR DESCRIPTION
**Pull request by hppritcha**
I tried to just do a autoreconf on the contents of the 4.10.2-bsd tarball but
that caused a meltdown due to missing subdirs, etc.  So just insert manually
an updated config.guess.

Useful for detecting aarch64 and latest cray compilers.

I don't have access to older tarballs, so only patch for the two tarballs I can test.

Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

### CODE REVIEW

**Comment by floquet** [comment]
Howard:

My approach to these configury problems is to (1) patch the app, or (2) create a corrected tarball and and give it precedence in repos.yaml.

Dan

**Comment by hppritcha** [comment]
@adamjstewart could you rerun travis?  It looks like something borked up with installing packages needed for CI.

**Comment by adamjstewart** [comment]
Closing and reopening to rerun tests. But for the record, `AutotoolsPackage` already contains logic to update `config.guess`, so this PR may no longer be needed.

**Comment by alalazo** [comment]
I think this can be closed since #18347 has been merged. Can you confirm @hppritcha ?

**Comment by alalazo** [comment]
Closing since building `silo` completes fine for me on

* **Spack:** 0.15.4-1473-dd35f8e
* **Python:** 2.7.5
* **Platform:** linux-rhel7-power9le

and config.guess is patched correctly. Feel free to reopen if there's anything else that I overlooked.

**Pull request closed without merging**
