### PR TITLE
Remove version from py-mpi4py

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by cyrush** [comment]
@danlipsa We should be able to use Python 3, I would rather work out the build issues than block building with Python 3.

**Comment by danlipsa** [comment]
@cyrush Sounds good. I removed pinning to python2. This is the errors I get with python3
```console
==> Error: ProcessError: Command exited with status 2:
    'make' '-j40'

15 errors found in build log:
     351    [  8%] Linking CXX executable ../../../tests/blt_openmp_smoke
     352    cd /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build/blt/tests/smoke && /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/cmake-3.9.6-rp7
            abvw5kxeaz5vii3hctu3du4ecjzcx/bin/cmake -E cmake_link_script CMakeFiles/blt_openmp_smoke.dir/link.txt --verbose=1
     353    /usr/bin/g++-7      -O2 -g -DNDEBUG  -fopenmp  CMakeFiles/blt_openmp_smoke.dir/blt_openmp_smoke.cpp.o  -o ../../../tests/blt_openmp_smoke
     354    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     355    [  8%] Built target blt_openmp_smoke
     356    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp: In member function 'bool flow::PythonInterpreter::initialize(int, char**)':
  >> 357    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:131:40: error: cannot convert 'char*' to 'const wchar_t*' for argument '1' to 'void Py_
            SetProgramName(const wchar_t*)'
     358                 Py_SetProgramName(prog_name);
     359                                            ^
  >> 360    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:135:38: error: cannot convert 'char*' to 'const wchar_t*' for argument '1' to 'void Py_
            SetProgramName(const wchar_t*)'
     361                 Py_SetProgramName(argv[0]);
     362                                          ^
  >> 363    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:146:40: error: cannot convert 'char**' to 'wchar_t**' for argument '2' to 'void PySys_S
            etArgv(int, wchar_t**)'
     364                 PySys_SetArgv(1, &prog_name);
     365                                            ^
  >> 366    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:150:37: error: cannot convert 'char**' to 'wchar_t**' for argument '2' to 'void PySys_S
            etArgv(int, wchar_t**)'
     367                 PySys_SetArgv(argc, argv);
     368                                         ^
     369    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp: In static member function 'static bool flow::PythonInterpreter::PyObject_to_double(PyO
            bject*, double&)':
  >> 370    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:453:8: error: 'PyInt_Check' was not declared in this scope
     371         if(PyInt_Check(py_obj))
     372            ^~~~~~~~~~~
     373    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:453:8: note: suggested alternative: 'PySet_Check'
     374         if(PyInt_Check(py_obj))
     375            ^~~~~~~~~~~
     376            PySet_Check
  >> 377    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:455:24: error: 'PyInt_AS_LONG' was not declared in this scope
     378             res = (double) PyInt_AS_LONG(py_obj);
     379                            ^~~~~~~~~~~~~
     380    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:455:24: note: suggested alternative: 'PyLong_AS_LONG'
     381             res = (double) PyInt_AS_LONG(py_obj);
     382                            ^~~~~~~~~~~~~
     383                            PyLong_AS_LONG
     384    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp: In static member function 'static bool flow::PythonInterpreter::PyObject_to_int(PyObje
            ct*, int&)':
  >> 385    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:486:8: error: 'PyInt_Check' was not declared in this scope
     386         if(PyInt_Check(py_obj))
     387            ^~~~~~~~~~~
     388    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:486:8: note: suggested alternative: 'PySet_Check'
     389         if(PyInt_Check(py_obj))
     390            ^~~~~~~~~~~
     391            PySet_Check
  >> 392    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:488:20: error: 'PyInt_AS_LONG' was not declared in this scope
     393             res = (int)PyInt_AS_LONG(py_obj);
     394                        ^~~~~~~~~~~~~
     395    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:488:20: note: suggested alternative: 'PyLong_AS_LONG'
     396             res = (int)PyInt_AS_LONG(py_obj);
     397                        ^~~~~~~~~~~~~
     398                        PyLong_AS_LONG
  >> 399    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:501:24: error: 'PyNumber_Int' was not declared in this scope
     400         PyObject *py_val = PyNumber_Int(py_obj);
     401                            ^~~~~~~~~~~~
     402    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:501:24: note: suggested alternative: 'PyNumber_And'
     403         PyObject *py_val = PyNumber_Int(py_obj);
     404                            ^~~~~~~~~~~~
     405                            PyNumber_And
  >> 406    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:504:17: error: 'PyInt_AS_LONG' was not declared in this scope
     407         res = (int) PyInt_AS_LONG(py_val);
     408                     ^~~~~~~~~~~~~
     409    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:504:17: note: suggested alternative: 'PyLong_AS_LONG'
     410         res = (int) PyInt_AS_LONG(py_val);
     411                     ^~~~~~~~~~~~~
     412                     PyLong_AS_LONG
     413    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp: In static member function 'static bool flow::PythonInterpreter::PyObject_to_string(PyO
            bject*, std::__cxx11::string&)':
  >> 414    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:523:11: error: 'PyString_AS_STRING' was not declared in this scope
     415         res = PyString_AS_STRING(py_obj_str);
     416               ^~~~~~~~~~~~~~~~~~
     417    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:523:11: note: suggested alternative: 'PyBytes_AS_STRING'
     418         res = PyString_AS_STRING(py_obj_str);
     419               ^~~~~~~~~~~~~~~~~~
     420               PyBytes_AS_STRING
     421    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp: In member function 'bool flow::PythonInterpreter::PyTraceback_to_string(PyObject*, PyO
            bject*, PyObject*, std::__cxx11::string&)':
  >> 422    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:580:11: error: 'PyString_AS_STRING' was not declared in this scope
     423         res = PyString_AS_STRING(py_str);
     424               ^~~~~~~~~~~~~~~~~~
     425    /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/src/flow/flow_python_interpreter.cpp:580:11: note: suggested alternative: 'PyBytes_AS_STRING'
     426         res = PyString_AS_STRING(py_str);
     427               ^~~~~~~~~~~~~~~~~~
     428               PyBytes_AS_STRING
     429    flow/CMakeFiles/ascent_flow.dir/build.make:257: recipe for target 'flow/CMakeFiles/ascent_flow.dir/flow_python_interpreter.cpp.o' failed
  >> 430    make[2]: *** [flow/CMakeFiles/ascent_flow.dir/flow_python_interpreter.cpp.o] Error 1
     431    make[2]: *** Waiting for unfinished jobs....
     432    [  8%] Linking CXX executable ../../../tests/blt_mpi_smoke
     433    cd /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build/blt/tests/smoke && /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/cmake-3.9.6-rp7
            abvw5kxeaz5vii3hctu3du4ecjzcx/bin/cmake -E cmake_link_script CMakeFiles/blt_mpi_smoke.dir/link.txt --verbose=1
     434    /usr/bin/g++-7      -O2 -g -DNDEBUG  -fexceptions -Wl,-rpath -Wl,/home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/hwloc-1.11.11-gyfonmecs4urva4bxjq5ut
            aai6i2hw3c/lib -Wl,-rpath -Wl,/home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib  CMakeFiles/blt_mpi_
            smoke.dir/blt_mpi_smoke.cpp.o  -o ../../../tests/blt_mpi_smoke -Wl,-rpath,/home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww
            4nkt34lzoaaizleuonx/lib /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi.so /home/danlipsa/p
            rojects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi_cxx.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu
            18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmi
            sfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi_usempif08.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/
            lib/libmpi_usempi_ignore_tkr.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi_mpifh.so /h
            ome/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi.so /home/danlipsa/projects/spack/opt/spack/li
            nux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi_cxx.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/ope
            nmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libmpi_usempif08.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34
            lzoaaizleuonx/lib/libmpi_usempi_ignore_tkr.so /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/openmpi-3.1.4-pmisfzi4ma6ww4nkt34lzoaaizleuonx/lib/libm
            pi_mpifh.so
     435    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     436    [  8%] Built target blt_mpi_smoke

     ...

     461    cd /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build/blt/tests/smoke && /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/cmake-3.9.6-rp7
            abvw5kxeaz5vii3hctu3du4ecjzcx/bin/cmake -E cmake_link_script CMakeFiles/blt_fruit_smoke.dir/link.txt --verbose=1
     462    /usr/bin/gfortran-7   -O2 -g -DNDEBUG CMakeFiles/blt_fruit_smoke.dir/blt_fruit_smoke.f90.o  -o ../../../tests/blt_fruit_smoke -Wl,-rpath,/tmp/danlipsa/spack-stage/spack-stage-q
            DUEv5/ascent/spack-build/lib ../../../lib/libfruit.so
     463    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     464    [  9%] Built target blt_fruit_smoke
     465    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     466    CMakeFiles/Makefile2:1578: recipe for target 'flow/CMakeFiles/ascent_flow.dir/all' failed
  >> 467    make[1]: *** [flow/CMakeFiles/ascent_flow.dir/all] Error 2
     468    make[1]: *** Waiting for unfinished jobs....
     469    [  9%] Linking CXX shared library ../../lib/libascent_lodepng.so
     470    cd /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build/thirdparty_builtin/lodepng && /home/danlipsa/projects/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/cmak
            e-3.9.6-rp7abvw5kxeaz5vii3hctu3du4ecjzcx/bin/cmake -E cmake_link_script CMakeFiles/ascent_lodepng.dir/link.txt --verbose=1
     471    /usr/bin/g++-7 -fPIC     -O2 -g -DNDEBUG  -shared -Wl,-soname,libascent_lodepng.so -o ../../lib/libascent_lodepng.so CMakeFiles/ascent_lodepng.dir/lodepng.cpp.o -Wl,-rpath,::::
            ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
     472    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     473    [  9%] Built target ascent_lodepng

     ...

     475    cd /tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build/blt/thirdparty_builtin/googletest-master-2018-02-01/googletest && /home/danlipsa/projects/spack/opt/spack/lin
            ux-ubuntu18.04-x86_64/gcc-7.3.0/cmake-3.9.6-rp7abvw5kxeaz5vii3hctu3du4ecjzcx/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
     476    /usr/bin/g++-7 -fPIC     -O2 -g -DNDEBUG  -shared -Wl,-soname,libgtest.so -o ../../../../lib/libgtest.so CMakeFiles/gtest.dir/src/gtest-all.cc.o -pthread
     477    make[2]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     478    [  9%] Built target gtest
     479    make[1]: Leaving directory '/tmp/danlipsa/spack-stage/spack-stage-qDUEv5/ascent/spack-build'
     480    Makefile:143: recipe for target 'all' failed
  >> 481    make: *** [all] Error 2

See build log for details:
```

**Comment by cyrush** [comment]
@danlipsa thanks, we will work to resolve and then turn on Python 3 testing in our CI setup

**Comment by danlipsa** [comment]
@cyrush Great. ping me when you have a PR. I would like to try paraview+ascent from the spack develop branch. Thanks!

**Comment by citibeth** [comment]
I agree...  everything must work with Python3 (or not work at all) starting 2020.  We need to be moving toward Python3, not away.

**Comment by cyrush** [comment]
@danlipsa Ascent develop should now build with Python 3. 

Note: Other non-python 3 caveats apply: You need to use the blessed version of VTK-m, etc.
Those are handled in uberenv -- talking to Ken Moreland I think we can move some of that logic the vtk-m spack package.

**Comment by danlipsa** [comment]
Great! Thanks @cyrush

**Comment by danlipsa** [comment]
@cyrush I think you need this change, otherwise you'll get an error for mpi4py at least for python 3.7.3. Without pinning mpy4py everything installs fine with python 3.7.3. This is how I did it.
```spack install ascent+python~vtkh^python@3.7.3```

**Comment by cyrush** [comment]
sorry about that, yes this change looks good to me

**Comment by danlipsa** [comment]
@cyrush @cyrush Sorry, I am not allowed to merge yet, so you'll have to also merge this for me.

**Pull request merged**
