### PR TITLE
Buildcache Error:  when an external is declared with the version installed on the system 

### PR DESCRIPTION
**Pull request by gartung**
package source ID cannot be determined when the url can't be extrapolated for older version.
Put a try except around the call and catch the ExtrapolationError making source ID None.

### CODE REVIEW

**Comment by gartung** [comment]
Closes #14233

**Comment by gartung** [comment]
@chissg you may want to cherry-pick this onto fnal-devel since I have encountered this bug before.

**Comment by eugeneswalker** [comment]
Is it possible that ExtrapolationError could occur in cases other than the one discussed in https://github.com/spack/spack/issues/14233 ? If so, then perhaps this fix, in addition to actually being a fix for our case, could also mask a legitimate error case where it may actually be desirable to fail out?

**Comment by eugeneswalker** [comment]
I've been using this PR by @gartung to successfully avoid the bug in my pipelines, FYI.

**Comment by gartung** [comment]
@tgamblin I think this would be safe to merge since this is the only exception caught and the very next line checks if source_id  is None.

**Pull request merged**
