### PR TITLE
Bypass build_cache/index.html read when trying to download spec.yaml for concretized spec.

### PR DESCRIPTION
**Pull request by gartung**
Add binary_distribution::get_spec which takes concretized spec.
Add binary_distribution::try_download_specs for downloading of spec.yaml files to cache.
get_spec is used by package::try_install_from_binary_cache to download only the spec.yaml
for the concretized spec if it exists.

This arose from a discussion with @eugeneswalke. Muliple pipelines write to the same build_cache and the index.html is not updating correctly when two processes content for writing index.html.  Buildcaches that are available are skipped by spack install because they don't have a link in index.html.

### CODE REVIEW

**Comment by gartung** [comment]
@scottwittenburg @eugeneswalker This is supposed to allow spack install to concretize a generic spec (not a hash) and try to get exactly that spec.yaml file. 

I can always revert this change until further testing can be done.

**Comment by scottwittenburg** [comment]
That could make sense, I'm just not sure which of the couple topics may have broken things.

**Comment by gartung** [comment]
I will start by reverting this one or you can try the commit just before this one.

**Comment by gartung** [comment]
If you want to test before I can merge the revert to develop try commit 
12a99f4a2df3f4bbb3dc85414cd3b7aaa2849a6c

**Comment by scottwittenburg** [comment]
Ok, I'm retrying one of the jobs that failed with the current `develop`.  I'll let you know what happens, thanks.

**Comment by scottwittenburg** [comment]
I'm still getting:

```
==> [2020-01-31-21:10:42.634572] Error: No binary for util-macros found and cache-only specified
```

But that spec with a matching hash is clearly in my binary mirror.  

Would you rather I start trying previous commits and try to find the one that broke it?  Just to avoid churn in the repository?

**Comment by gartung** [comment]
Yes please. Just look back through the commits and pick the one just before my latest commits.

**Comment by gartung** [comment]
a26e5caa572a2c1cb39225bc52f20dc49589fb02

**Comment by gartung** [comment]
In the mean time I will make a branch that backs out the recent buildache changes.

**Comment by scottwittenburg** [comment]
I had a hard time testing pipelines with older spack (`a26e5ca`), as recently they must have changed the `compilers.yaml` schema and the build container I'm pulling for testing pipelines now has the new `compilers.yaml` baked in, so spack just dies unable to read it.  So I tried to test with `b072caa` but still had the problem of not being able to install deps from binary cache.

But it seems like what you have in #14714 is working for me again, thank you 😄

**Pull request merged**
