### PR TITLE
llvm patch for installing numba

### PR DESCRIPTION
**Pull request by s-sajid-ali**
As suggested here : [1](https://github.com/numba/llvmlite/issues/258#issuecomment-388882748)

### CODE REVIEW

**Comment by s-sajid-ali** [comment]
How does one add the last patch which is only for intel CPU's ?

**Comment by adamjstewart** [comment]
There is currently no way to add a patch only for Intel CPUs. Is it not a generic patch that can be applied for anyone but only used when on Intel?

**Comment by s-sajid-ali** [comment]
I don't know enough about llvm to comment. Can I tag someone who knows more about llvm here to get more info on this ?

**Comment by adamjstewart** [comment]
Pinging some people who have contributed to the `llvm` package in the past:
@trws @KineticTheory @eschnett @aprokop @goxberry @mmpozulp

**Comment by trws** [comment]
Since that include is merged in upstream llvm, what's the upper bound on the version this should be applied to?  CC: @cwearl

**Comment by alalazo** [comment]
> There is currently no way to add a patch only for Intel CPUs. Is it not a generic patch that can be applied for anyone but only used when on Intel?

Since #3206 was merged we should be able to do this. @s-sajid-ali Feel free to update this PR if you consider it still relevant or close it otherwise.

**Comment by s-sajid-ali** [comment]
@alalazo @adamjstewart 
Since the link to the original `Intel-SVML` patch is dead, I think this particular issue can be closed.

 But the bigger issue of patching `LLVM` for `py-llvmlite` still remains. As per `py-llvmlite`'s `conda-recipe` [here](https://github.com/numba/llvmlite/blob/master/conda-recipes/llvmdev/build.sh) and installation instructions [here](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#building-manually), the required `llvm` version changes with each `py-llvmlite` release. In addition to this, they seem to only maintain the [llvm patches](https://github.com/numba/llvmlite/tree/master/conda-recipes) for the current `master` version in the github repo. If we are interested in doing the same in `spack`, we'd have to pull the git repo for `py-llvmlite` for each release to patch `llvm` or have ~5 patches per each version of `py-llvmlite` in spack.

**Pull request closed without merging**
