### PR TITLE
CD: Package Index

### PR DESCRIPTION
**Pull request by ax3l**
Build the docker image for the new package index REST API on each merge/push to develop and master.

Follow-up to: #11652

### CODE REVIEW

**Comment by ax3l** [comment]
removed it already, accidentally pushed

**Comment by tgamblin** [comment]
ok can we remove initial spaces from shebangs?

**Comment by ax3l** [comment]
huh! clumsy f1ngers

**Comment by ax3l** [comment]
Wonderful! Yes, this provides a nginx image with static files for all packages as shown in #11652

**Comment by ax3l** [comment]
If you spin up packages.spack.io with it we can provide version badges to our users! :)
https://github.com/badges/shields/pull/3536

**Comment by ax3l** [comment]
@opadron I already pushed a first image manually to `spack/packages.spack.io`. If you spin up packages.spack.io with it we can provide version badges to our users! :)
https://github.com/badges/shields/pull/3536

**Comment by opadron** [comment]
@ax3l Done! 

But, it looks like something isn't working quite right.  Here's some log output that I see after hitting [packages.spack.io](https://packages.spack.io) a few times:

```
2019/06/08 00:30:44 [error] 7#7: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.118.41, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "packages.spack.io"
192.168.118.41 - - [08/Jun/2019:00:30:44 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" "75.183.5.177"
192.168.118.41 - - [08/Jun/2019:00:31:16 +0000] "GET /.git/config HTTP/1.1" 404 153 "http://packages.spack.io/.git/config" "Go-http-client/1.1" "195.176.3.20"
2019/06/08 00:31:16 [error] 7#7: *2 open() "/usr/share/nginx/html/.git/config" failed (2: No such file or directory), client: 192.168.118.41, server: localhost, request: "GET /.git/config HTTP/1.1", host: "packages.spack.io", referrer: "http://packages.spack.io/.git/config"
192.168.118.41 - - [08/Jun/2019:00:31:40 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" "75.183.5.177"
2019/06/08 00:31:40 [error] 7#7: *3 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.118.41, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "packages.spack.io"
2019/06/08 00:32:44 [error] 7#7: *4 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.118.41, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "packages.spack.io"
192.168.118.41 - - [08/Jun/2019:00:32:44 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" "75.183.5.177"
```

**Comment by opadron** [comment]
Taking a closer look, it seems like there isn't supposed to be a landing page, and the default page was just left unmodified?  I'm not familiar with the API this server is supposed to serve, but e.g.: [packages.spack.io/z/zlib.json](https://packages.spack.io/z/zlib.json) seems to work just fine.

**Comment by ax3l** [comment]
Yes, we didn't add one yet and consider adding a little search frontend later on, such as https://github.com/Homebrew/formulae.brew.sh

For the API itself a landing page is not needed.

**Comment by ax3l** [comment]
@tgamblin ready for merge :)

**Comment by ax3l** [comment]
@opadron I pushed the endpoint change to include `api/` now but the service does not seam to automatically re-deploy with the updated image on dockerhub.

**Comment by ax3l** [comment]
@opadron @tgamblin shall we merge this already?

**Comment by tgamblin** [comment]
@ax3l: it’s approved and I think you have merge rights :)

**Comment by ax3l** [comment]
Okay, I just wasn't sure if self-merge is fine :)

**Pull request merged**
