### PR TITLE
checksums updated, new compiler version

### PR DESCRIPTION
**Pull request by ThemosTsikas**

### CODE REVIEW

**Comment by alalazo** [comment]
I see that `nag@6.0` changed checksum. I was trying to verify that but I'm not able to fetch that version:
```console
$ spack fetch nag@6.0
[ ... ]
==> Failed to fetch file from URL: https://www.nag.com/downloads/impl/npl6a60na_amd64.tgz
    URL https://www.nag.com/downloads/impl/npl6a60na_amd64.tgz was not found!
==> Fetching from https://www.nag.com/downloads/impl/npl6a60na_amd64.tgz failed.
==> Error: All fetchers failed for spack-stage-nag-6.0-bbjiqpkvmcgr5dlakdq4qvspux5tew2b
```

**Comment by adamjstewart** [comment]
Also, when I download `nag@6.2`, the current checksum seems correct, so that checksum may not need to be changed.

**Comment by ThemosTsikas** [comment]
We should remove 6.0 as it's no longer served in the old URL. 

I made a mistake on the hash of 6.2, I gave a hash for a later Build that has not yet appeared at that URL

6.1, 6.2 and 7.0 should be fetchable.

Cancel this pull request.

**Comment by adamjstewart** [comment]
You can still add 7.0 and add yourself as a maintainer if you want, no need to cancel the PR, just add another commit.

**Comment by ThemosTsikas** [comment]
Hello Adam, I don't use github's web gui often enough to know what this "maintainer" malarkey is, I've already searched and looked at help links. If you can arrange it yourself, I will click on  any "accept" emails I get.

**Comment by adamjstewart** [comment]
@ThemosTsikas I don't use GitHub's notification email malarkey, but if you add the following code to the package:
```python
maintainers = ['ThemosTsikas']
```
then I can manually ping you (via @ThemosTsikas) on any issues/PRs related to NAG, and presumably you'll get an email from GitHub letting you know that you've been summoned. This is completely optional, it's only if you want to be summoned. I'm also going to try to get better at adding the `nag` label to issues/PRs, so you can use the `label:nag` filter on GitHub to find any NAG-related issues/PRs.

**Comment by ThemosTsikas** [comment]
The penny dropped!

**Pull request closed without merging**
