### PR TITLE
Changes necessary to build lbann@develop

### PR DESCRIPTION
**Pull request by rblake-llnl**
A new dependency on clara was added, and the Conduit CMake flags were changed.

Tagging @bvanessen for review.

### CODE REVIEW

**Comment by bvanessen** [comment]
@rblake-llnl There is a change in the LBANN CMake that we want to tweak that will impact this PR.

**Comment by bvanessen** [comment]
@adamjstewart No not yet.  It turns out that Clara is already a dependency, so let me work with @rblake-llnl to clean up and test this.

**Comment by rblake-llnl** [comment]
I think the clara dependency happened due to a rebase with develop.  Removed the redundant clara dependency.

@bvanessen : using the package above worked for me.  I used this instead of following the install guide instructions.

**Comment by adamjstewart** [comment]
@bvanessen good now?

**Comment by bvanessen** [comment]
> @bvanessen good now?

yes.

**Pull request merged**
