### PR TITLE
xsdk: disable assimp in deal.II

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/spack/spack/issues/9189

### CODE REVIEW

**Comment by davydden** [comment]
@balay ping.

**Comment by balay** [comment]
should I worry about codecov? [don't really understand it]

My build goes through fine now - so I can merge this.

```bash-4.2$ spack find
==> 43 installed packages.
-- linux-centos7-x86_64 / intel@18.0.2 --------------------------
adol-c@develop    intel-mpi@18.0.2  parmetis@4.0.3
alquimia@develop  intel-tbb@2018.5  petsc@develop
amrex@develop     libtool@2.4.6     pflotran@develop
arpack-ng@3.6.2   m4@1.4.18         pkg-config@1.3.9
autoconf@2.69     matio@1.5.9       python@2.7.13
automake@1.15.1   metis@5.1.0       slepc@develop
boost@1.68.0      mfem@develop      sowing@1.1.25-p1
bzip2@1.0.6       muparser@2.2.5    suite-sparse@5.3.0
cmake@3.12.1      nanoflann@1.2.3   sundials@3.1.0
dealii@develop    ncurses@6.1       superlu-dist@develop
glm@0.9.7.1       netcdf@4.6.1      trilinos@develop
gsl@2.5           numactl@2.0.11    xsdk@develop
hdf5@1.10.3       oce@0.18.3        zlib@1.2.11
hypre@develop     openssl@1.0.2o
intel-mkl@18.0.2  p4est@2.0
bash-4.2$ 
```

**Comment by davydden** [comment]
@balay we can merge this as well, if you wish, so that the whole xsdk does not depends on unstable assimp

**Comment by balay** [comment]
yes - even though  #9191 fixes the assimp issue - I'm inclined to merge this aswell - to reduce the dependency tree [and hence build itme] for xsdk packages..

**Pull request merged**
