### PR TITLE
More variants for cairo

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by aweits** [comment]
This commit broke a lot of builds (visit, opencv, trinity, r, etc) in our CI, due to the effective switch of the default for freetype and fontconfig.

**Comment by adamjstewart** [comment]
@aweits it sounds like those packages need to declare an explicit dependency on `cairo+xxx`

**Comment by aweits** [comment]
@adamjstewart after looking around in other package systems and reading the README file in cairo, this seems to be an "odd" selection of defaults. Can you shed some light on the motivation behind the default settings for me?

**Comment by adamjstewart** [comment]
@aweits I can't speak to @iarspider's selection of defaults, and until someone volunteers to be the maintainer of the `cairo` package in Spack, the defaults will likely continue to change. Personally, when I'm adding variants to a package, I usually disable variants that add additional dependencies to the package like @iarspider did here. This minimizes the time it takes the package to build. If another package requires those variants to be activated, they need to say that in their `depends_on` statement. For example, if `r` requires `cairo` built with fontconfig support, it needs to say `depends_on('cairo+fc')`. It should be a simple one line change to fix any packages that depend on cairo.

**Comment by cessenat** [comment]
Can someone tell me why png conflicts with darwin ?
I could build cairo+png on Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021.

**Comment by mpbelhorn** [comment]
FYI: There is a dependency loop with `cairo+svg` and `librsvg`. `librsvg` [necessarily depends on `cairo`](https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/COMPILING.md#installing-dependencies-for-building). And, though the librsvg docs state it needs cairo built with PNG support (not currently declared in the spack package), I find that it also needs cairo configured with the flag `--enable-svg=yes` in order to have svg-related parts of the cairo interface used by librsvg. That is, `librsvg ^cairo+svg` (also not in the current spack package for `librsvg`).

However, since the spack package for `cairo+svg` depends on `librsvg`, having `librsvg` depend on `cairo+png+svg` introduces a dependency loop.
 
This affects builds of gtkplus, and any gtkplus dependents. In the past, I've side-stepped this by using external OS-provided GTK but I'm interested in not relying on external GTK for future builds. I'm not sure of the best way to break this dependency loop. I've successfully built `cairo+svg` having removed cairo's dependency on `librsvg` from the `cairo` spack package. For what it's worth, this is similar to the way Archlinux packages cairo, librsvg, and gtkplus. And dependents using these builds run successfully. But I have yet to carefully study the build log to be sure cairo isn't picking up svg-related libs from the OS and that this is truly the correct way to break the circular dependency. The cairo and librsvg documentation isn't very clear about the dependency chain and investigating it requires more free time than I usually have available.

**Pull request merged**
