### PR TITLE
update mothur

### PR DESCRIPTION
**Pull request by xfzhao**
update to 1.43.0

### CODE REVIEW

**Comment by xfzhao** [comment]
resolve conflicts in hash style , and add vsearch option.

**Comment by xfzhao** [comment]
update to 1.43.0

**Comment by xfzhao** [comment]
please merge.

**Comment by adamjstewart** [comment]
Can you rebase?

**Comment by xfzhao** [comment]
need help, please.
I did: 
$ git rebase origin/master 
OK
$git commit -m 'did rebase'
$git push origin mothur
the message:
! [rejected]        mothur -> mothur (non-fast-forward)                                                                                                                          
error: failed to push some refs to 'https://github.com/researchit/spack.git'                                                                                                      
hint: Updates were rejected because the tip of your current branch is behind                                                                                                      
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')                                                                                                          
hint: before pushing again.                                                                                                                                                       
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by adamjstewart** [comment]
Here are the steps I usually take to rebase: https://spack.readthedocs.io/en/latest/contribution_guide.html#rebasing

**Comment by xfzhao** [comment]
I followed your ref:
$ git checkout develop
$ git pull upstream develop

$ git checkout mothur
$ git rebase develop
got the msg:
lib/spack/spack/cmd/find.py: needs merge
You must edit all merge conflicts and then
mark them as resolved using git add

**Comment by adamjstewart** [comment]
Hmm, honestly, if you're not super familiar with git, it might be easier to just create a new PR.

**Comment by xfzhao** [comment]
good idea, i am thinking to do so. i close this request

**Pull request closed without merging**
