### PR TITLE
gasnet: add 1.30.0

### PR DESCRIPTION
**Pull request by junghans**
/cc @PHHargrove @bonachea

### CODE REVIEW

**Comment by junghans** [comment]
Honestly, I haven't looked if the configure options make sense at all, but this build works with legion.

**Comment by bonachea** [comment]
This spack file is not useful/representative as a good way to build GASNet in general.
Most notably it only supports one of the native networks (ibv), includes some options that are just plain ridiculous (--with-segment-mmap-max=64MB) and potentially performance-killing for general clients ("--disable-pshm").  It also omits the majority of GASNet's rich user-tunable configure space. This file might be sufficient for the purposes of Legion on a few platforms, but should not be construed or advertised as a "good" Spack config for general use.

We have plans to develop a better Spack file for GASNet, but haven't gotten to it yet.

All that being said the addition of the new version in this PR doesn't make it any better or worse, but the config file remains probably a poor (and potentially misleading) choice for most clients.

**Comment by junghans** [comment]
Most of the options (incl. `--disable-pshm`) are copied from http://legion.stanford.edu/gasnet/, I guess. `--with-segment-mmap-max=64MB` was added in 240f1fd223 by @tgamblin , but iirc that was part of the legion build guide as some point.

@streichler, @lightsighter & @elliottslaughter could you comment, which options are actually needed for legion?

@bonachea can you give a recommendation for a more optimal option set?

**Comment by streichler** [comment]
Strictly speaking, I think the only things that Legion _requires_ is `--enable-par` and the `-fPIC` (or equivalent) compiler flag.  Our usage of GASNet is such that we strongly prefer `--enable-segment-fast` and a large `--with-segment-mmap-max` (we'd definitely not be too happy with only 64MB - I'm not sure where that setting came from).
The Legion-friendly configs we maintain at https://github.com/StanfordLegion/gasnet/tree/master/configs generally also turn off things we don't need (e.g. pshm, aligned-segments, other threading modes), but unless they add undesirable overhead, I don't believe their presence is a problem for Legion.

**Comment by PHHargrove** [comment]
Based on the direction this seems to be going, would it be appropriate to rename this package to "gasnet-legion" or "legion-gasnet" (or some other variant that best fits spack conventions) until/unless a more general-purpose range of variants is available?

Legion's configs (linked by @streichler) configure with `--disable-seq
--disable-parsync`.  This saves build time and space on disk, by omitting libs that Legion does not need.  Please do not adopt those into the spack configuration because other GASNet clients do use those libs.


Some potential improvements to increase generality:

Make PSHM support a variant.  Then Legion doesn't need to worry about whether the overhead is small or not, but clients that do want to use shared-memory comms between procs on the same node will still have access to PSHM.

I suspect that in addition to ibv and mpi, a udp-conduit variant would be useful to users w/o a high-speed network (and faster than mpi-conduit in most such cases).

Support for Cray Gemini or Aries networks would require the configure logic to use the appropriate cross-configure script, depending on which network *and* which job-launcher (alps vs slurm) is used.  I assume use of the cross-configure script in place of configure is scriptable and that the selection of the right on for network+launcher is expressible as variants.


I am afraid I don't know enough about spack (or python) to give concrete suggestions regarding implementation of any of my suggestions above.

**Comment by tgamblin** [comment]
> Based on the direction this seems to be going, would it be appropriate to rename this package to "gasnet-legion" or "legion-gasnet" (or some other variant that best fits spack conventions) until/unless a more general-purpose range of variants is available?

Generally the convention in Spack is that packages are templates, and we add variants for this stuff. So packages that need a feature should depend on it explicitly, e.g.:

```
    depends_on('legion+seq+parsync')
```

I think we can update this incrementally from the current form of the GASNet package -- there shouldn't be a need to rename.

> Legion's configs (linked by @streichler) configure with --disable-seq --disable-parsync. This saves build time and space on disk, by omitting libs that Legion does not need. Please do not adopt those into the spack configuration because other GASNet clients do use those libs.

Are they commonly used?  Unless there's some reason not to, I think we should add variants for them and choose a sensible default -- sounds like maybe they should default to `True`.  That doesn't mean other packages shouldn't be explicit about what they need, though.  It just means a default build from `spack install gasnet` with no options is likely to satisfy future installs of clients.

> Make PSHM support a variant. Then Legion doesn't need to worry about whether the overhead is small or not, but clients that do want to use shared-memory comms between procs on the same node will still have access to PSHM.
>
> I suspect that in addition to ibv and mpi, a udp-conduit variant would be useful to users w/o a high-speed network (and faster than mpi-conduit in most such cases).

I agree with Paul here -- I think more variants are good.

> Support for Cray Gemini or Aries networks would require the configure logic to use the appropriate cross-configure script, depending on which network and which job-launcher (alps vs slurm) is used. I assume use of the cross-configure script in place of configure is scriptable and that the selection of the right on for network+launcher is expressible as variants.

Correct.  Someone would need to ensure that `configure()` is either overridden or [specialized](https://spack.readthedocs.io/en/latest/packaging_guide.html#multimethods-and-when) for those machines, though currently we don't know how to submit cross-compile tests to a job launcher.  The GASNet script *could* do a simple check to see whether `srun` or `aprun` is available and call the right thing.  Ideally we'll have better handling for that in Spack itself one day.

**Comment by junghans** [comment]
@streichler @tgamblin @PHHargrove @bonachea how about this as a compromise? `pshm`, `aligned-segments` are on by default, but legion depends on a `gasnet` without them. For `segment-mmap-max` I made 16GB the default.

Due to the fact that gasnet's configure has 206 with/enable/disable options, I won't add all of them in this PR ;-)

**Comment by streichler** [comment]
Looks reasonable to me.

**Comment by PHHargrove** [comment]
@tgamblin wrote:  
> The GASNet script could do a simple check to see whether srun or aprun is available and call the right thing.

Unfortunately, if it was that easy we'd have pushed that automation into the cross-configure scripts distributed with GASNet instead of making the end-user pick from different cross-configure scripts.  The issue is that the front-end of a Cray XE, XK or XC system (where configure will run) may validly have one, both, or neither of `srun` and `aprun` in $PATH.

**Comment by tgamblin** [comment]
> Unfortunately, if it was that easy we'd have pushed that automation into the cross-configure scripts distributed with GASNet instead of making the end-user pick from different cross-configure scripts. The issue is that the front-end of a Cray XE, XK or XC system (where configure will run) may validly have one, both, or neither of srun and aprun in $PATH.

We'll have to wait for some support for this from Spack then, I'm afraid.  Possibly with some user configuration to set up the way jobs are submitted.  It's something I'd like to support more generally but for which there seems to be no generality across HPC sites.

**Comment by bonachea** [comment]
@junghans `enable-aligned-segments` and `enable-pshm` are fundamentally incompatible, so that's a bad choice of default. 

IMO the default should be the same as GASNet's configure default, which as of the current release is `--enable-pshm --disable-aligned-segments`

Also, I believe the inclusion of `segment-mmap-max` in this discussion is a red herring springing from an old version of the GASNet for Legion document that incorrectly encouraged the use of that option to control an ibv-conduit registration behavior (which has since been improved in the code, and was never affected by that option anyhow). All this option actually does is set the default value for envvar GASNET_MAX_SEGSIZE (which can be overridden at runtime) and whose default should ideally be set based on site-specific information (compute node physical memory size). I don't see the point of Spack providing a different default for this than GASNet's, given they are both arbitrary wild guesses based on no information (although I could be convinced to raise GASNet's wild guess default to a more modern size). Certainly there are more important options in the GASNet configure space that actually affect correct building.

**Comment by junghans** [comment]
@bonachea Fixed, but I left `segment-mmap-max` for now!

**Comment by junghans** [comment]
Ok, if `--disable-aligned-segments` is the default and `segment-mmap-max` is actually needed, I will drop these variants for an easier `package.py`. That should give gasnet's configure a chance to do things more right.

@streichler, reading the legion's documentation again, it seems we want `--enable-pshm` to support MPI interoperability in Legion, correct?

**Comment by streichler** [comment]
@junghans No, I'd keep pshm disabled for Legion.  The mode that would benefit from it (running a Legion-enabled process per core on a system) is so awful from a performance perspective that enabling pshm will not be noticeable, and we want to avoid any extra overhead in the actual common Legion case (a Legion process per node, whether you're interop'ing with MPI or not).

@bonachea A question regarding the segment-mmap-max part:  Are you saying that setting really doesn't matter at all, or that it doesn't matter if you've gone to the trouble of setting the corresponding environment variable to reasonable setting for a given app/system combination?  If it's the latter, I'd continue to recommend the configure setting for legion's use of gasnet since we don't set that environment variable.

**Comment by bonachea** [comment]
@junghans I would revert your commit that removed the aligned-segments support, if you are interested in supporting anything but the current GASNet 1.30.0 release. Older GASNet releases defaulted to enable-aligned-segments (the default changed in 1.30), so building Legion against older GASNet with --disable-pshm will require an explicit --disable-aligned-segments on many systems.

@streichler configure --with-segment-mmap-max sets the default value for environment variable GASNET_MAX_SEGSIZE. So it's the latter: "it doesn't matter if you've gone to the trouble of setting the corresponding environment variable to reasonable setting for a given app/system combination".  

Some client job spawners (notably upcrun and upcxx-run) have logic to set their own default for GASNET_MAX_SEGSIZE (eg based on the additional info of the UPC shared heap size) when the user/site didn't provide GASNET_MAX_SEGSIZE in the environment, so those spawners will sometimes ignore GASNet's configure-time default. However clients who don't do this will get the configure-time default when users don't set GASNET_MAX_SEGSIZE.

As an aside, this conversation has prompted a [related discussion on the GASNet Bugzilla](https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3680) that may lead to improvements to this default in future releases.

**Comment by streichler** [comment]
> However clients who don't do this will get the configure-time default when users don't set GASNET_MAX_SEGSIZE.

In that case, I'd prefer to keep an explicit segment-mmap-max setting for the Legion-friendly variant of the gasnet build.  @junghans can we revert the other half of 8efd030 too?  :)

**Comment by junghans** [comment]
@streichler, thanks to `git` I can ;-)

**Comment by bonachea** [comment]
@junghans 8b9b91d  only reverted half of 8efd030 - please explain.

**Comment by junghans** [comment]
@bonachea wasn’t that @streichler asked for?

**Comment by bonachea** [comment]
@junghans See [this comment](https://github.com/spack/spack/pull/6167#issuecomment-342893525) where I asked you to revert the removal of aligned-segments support, if we want to support GASNet releases older than the current 1.30.0

**Comment by tgamblin** [comment]
Seems like we can just make that option apply only at version 1.30.0 or higher.

**Comment by junghans** [comment]
I see, let's us 3791012c139f11b6b910a0a516b64b525bdaf987 then!

**Comment by junghans** [comment]
Done, further patches welcome.

**Pull request merged**
