### PR TITLE
Update to py 1.4.34

### PR DESCRIPTION
**Pull request by adamjstewart**
Update our vendored copy of `py` from 1.4.32 (2016-12-16) to 1.5.2 (2017-11-15).

### CODE REVIEW

**Comment by asottile** [comment]
While the tests appear to pass, `py` dropped support for py26 / py33 in 1.5.0: https://github.com/pytest-dev/py/commit/96649d5058380c9509895b1cfaf0c95893175677

The latest py26 compatible version is 1.4.34

**Comment by asottile** [comment]
Another note, the `py` project (by the pytest team) is being moved away from as much as possible in their projects so you may want to avoid using it if possible (unless it's a transitive dependency, then just ignore this advice!).

**Comment by adamjstewart** [comment]
> The latest py26 compatible version is 1.4.34

Good find! @tgamblin do we want to stop with 1.4.34 or take the chance that the latest version works on 2.6?

> unless it's a transitive dependency, then just ignore this advice!

I think it's only needed as a `pytest` dependency. If newer versions of `pytest` don't need it, then neither do we. But I think I tried upgrading `pytest` and it didn't work at all in 2.6.

**Comment by adamjstewart** [comment]
I think it's safest to stick with the last version that explicitly supported 2.6 unless we happen to need a feature only available in newer versions of `py`/`pytest`. Revert the latest commit if you disagree.

**Pull request merged**
