### PR TITLE
fix petsc int64 metis dependencies

### PR DESCRIPTION
**Pull request by gardner48**
Fixes metis dependencies for installing petsc +int64

### CODE REVIEW

**Comment by balay** [comment]
In petsc 3.8 - the metis/parmetis dependency was changed so that (default) single precision [or any precision] metis/parmetis can be used from any precision petsc. 
https://github.com/petsc/petsc/commit/2d4f01c230

So perhaps the following change is needed?

```
-    depends_on('metis@5:~int64+real64', when='+metis~int64+double')
-    depends_on('metis@5:+int64', when='+metis+int64~double')
-    depends_on('metis@5:~int64+real64', when='+metis~int64+double')
-    depends_on('metis@5:+int64', when='+metis+int64~double')
+    depends_on('metis@5:~int64', when='+metis~int64')
+    depends_on('metis@5:+int64', when='+metis+int64')
```

Was there a build case where you had issues? [prompting this change?]

cc: @BarrySmith

**Comment by gardner48** [comment]
When I run "spack install petsc +int64" the install fails and the spack-build.out file has the following:
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Metis specified is incompatible!
--with-64-bit-indices option requires a metis build with IDXTYPEWIDTH=64.
Suggest using --download-metis for a compatible metis
*******************************************************************************

**Comment by balay** [comment]
Hm - [after my change] 'spack install petsc+int64' works fine for me.

What do you have for the following [with the equivalent path on your box]?

$ grep '#define IDXTYPEWIDTH' /home/balay/git-repo/github/spack/opt/spack/linux-fedora27-x86_64/gcc-7.2.1/metis-5.1.0-6edm6tizt7kphpj2owu5hk3ld7smd77b/include/metis.h 
#define IDXTYPEWIDTH 64

Perhaps you need to uninstall/reinstall metis/parmetis - this way
'metis+int64' version gets built?

**Comment by gardner48** [comment]
Sorry my last comment wasn't very clear, I meant that the current spack develop branch gives the error above. In that case the metis.h file has #define IDXTYPEWIDTH 32. With your change or mine the metis.h file has #define IDXTYPEWIDTH 64 and the install is successful. 

So either set of changes will work for petsc 3.8 or newer but will your change work older versions of petsc?

**Comment by balay** [comment]
On Wed, 7 Feb 2018, Denis Davydov wrote:

> davydden approved this pull request.
> 
> > In petsc 3.8 - the metis/parmetis dependency was changed so that (default) single precision [or any precision] metis/parmetis can be used from any precision petsc.
> petsc/petsc@2d4f01c
> 
> To make this work one might add version constraints to the current state for older petsc and add two more lines for newer petsc. You will end up with 8 lines to define Metis dependency for all versions of petsc. 
> 

Here is what I have:

-    depends_on('metis@5:~int64+real64', when='+metis~int64+double')
-    depends_on('metis@5:+int64', when='+metis+int64~double')
-    depends_on('metis@5:~int64+real64', when='+metis~int64+double')
-    depends_on('metis@5:+int64', when='+metis+int64~double')
+    depends_on('metis@5:~int64+real64', when='@:3.7.99+metis~int64+double')
+    depends_on('metis@5:+int64', when='@:3.7.99+metis+int64~double')
+    depends_on('metis@5:~int64+real64', when='@:3.7.99+metis~int64+double')
+    depends_on('metis@5:+int64', when='@:3.7.99+metis+int64~double')
+    # petsc-3.8+ uses default (float) metis with any (petsc) precision
+    depends_on('metis@5:~int64', when='@3.8:+metis~int64')
+    depends_on('metis@5:+int64', when='@3.8:+metis+int64')

**Comment by davydden** [comment]
> Here is what I have

LGTM

**Comment by gardner48** [comment]
@balay I think you meant the follwing. In your comment the ~int64+real64 and +int64 cases are repeated so the ~int64 and +int64+real64 cases are missing.
```
- depends_on('metis@5:~int64+real64', when='+metis~int64+double') 
- depends_on('metis@5:+int64', when='+metis+int64~double') 
- depends_on('metis@5:~int64+real64', when='+metis~int64+double') 
- depends_on('metis@5:+int64', when='+metis+int64~double') 
+ depends_on('metis@5:~int64+real64', when='@:3.7.99+metis~int64+double') 
+ depends_on('metis@5:~int64', when='@:3.7.99+metis~int64~double')
+ depends_on('metis@5:+int64+real64', when='@:3.7.99+metis+int64+double') 
+ depends_on('metis@5:+int64', when='@:3.7.99+metis+int64+double') 
+ # petsc-3.8+ uses default (float) metis with any (petsc) precision 
+ depends_on('metis@5:~int64', when='@3.8:+metis~int64') 
+ depends_on('metis@5:+int64', when='@3.8:+metis+int64')
```

**Comment by balay** [comment]
On Wed, 7 Feb 2018, David Gardner wrote:

> @balay I think you meant the follwing. In your comment the ~int64+real64 and +int64 cases are repeated so the ~int64 and +int64+real64 cases are missing.

Ah yes - I see the repetition now.

> ```
> - depends_on('metis@5:~int64+real64', when='+metis~int64+double') 
> - depends_on('metis@5:+int64', when='+metis+int64~double') 
> - depends_on('metis@5:~int64+real64', when='+metis~int64+double') 
> - depends_on('metis@5:+int64', when='+metis+int64~double') 
> + depends_on('metis@5:~int64+real64', when='@:3.7.99+metis~int64+double') 
> + depends_on('metis@5:~int64', when='@:3.7.99+metis~int64~double')
> + depends_on('metis@5:+int64+real64', when='@:3.7.99+metis+int64+double') 
> + depends_on('metis@5:+int64', when='@:3.7.99+metis+int64+double') 

Hm - should't this be:
depends_on('metis@5:+int64', when='@:3.7.99+metis+int64~double')

Perhaps you could update PR with these changes.

> + # petsc-3.8+ uses default (float) metis with any (petsc) precision 
> + depends_on('metis@5:~int64', when='@3.8:+metis~int64') 
> + depends_on('metis@5:+int64', when='@3.8:+metis+int64')
> ```
> 
>

**Comment by davydden** [comment]
@alalazo @junghans @becker33 could you please merge?

**Pull request merged**
