### PR TITLE
Add x86_64 as target to cray platform

### PR DESCRIPTION
**Pull request by mamelara**
x86_64 as the frontend target does not get set in the cray platform.
This makes sure to add the target as named target x86_64 as well as the
aliased target front_end.  This fixes the issue where specifying
arch=cray-fe-x86_64 gives the error:

==> Error: ValueError: Can't recreate arch for spec cray-sles12-x86_64
on current arch cray-cnl6-mic_knl; spec architecture is too different

@scheibelp can you check whether this is a viable solution for @mwkrentel problem?

### CODE REVIEW

**Comment by mwkrentel** [comment]
I tried this for my use case (the above error) and yes, now it works.

The odd thing (odd to me at least) was that 'spack spec' was ok with
arch=cray-fe-x86_64 but 'spack install' was not.

I don't know much about spack internals for cray, but I'll ask two
questions anyway.

1. Are all cray front ends x86_64?  All the cray machines I've every
used are, but I'm guessing this is not guaranteed to always be true.

2. When @becker33 finishes his work on target hierarchies, you may
want to revisit this.

But it works for me.

**Comment by mwkrentel** [comment]
@mamelara Was your second commit supposed to address the problem of
not picking up gcc@7.3.0 for the front end automatically?  It doesn't,
I still have to tell spack that /opt/gcc/7.3.0/bin/gcc is a compiler.

Anyway, it does now recognize the front-end x86_64 as a valid
archicture type.  So, that's useful to me.  If someone wanted to
review and merge ....

**Comment by mwkrentel** [comment]
@scheibelp would you like to review?
I need something like this for 'spack install' to work on Cray.

**Comment by scheibelp** [comment]
@mwkrentel to make sure, are your issues resolved when you apply this PR, or do you get additional errors

@mamelara this has a flake error. I'm inclined to say that while this can add an `x86_64` target, it should not explicitly set it as the frontend (in which case, the user will have to say `cray-sles12-x86_64`, but at least for now with just that change Spack will accept it).

Generally, while this may be useful in the short term, I think it would be good to investigate the compiler/target construction for Cray in Spack. Currently there is a different pathway for determining targets for compilers vs. determining the targets on the OS:

* OS targets are parsed from `module avail`, looking for modules prefixed with `craype-` (and doing some filtering). `x86_64` is not among the available modules so it is not considered a target in terms of keeping track of OS features.
* `CrayFrontend` uses `platform.machine()` (the system python module) to set the target for compilers that it discovers. On Cori this reports `x86_64`, which is why Spack can report a compiler for `cray-sles12-x86_64` but not allow me to install anything with that set as the architecture

**Comment by mwkrentel** [comment]
@scheibelp Yes, with this, then 'spack install' works for Cray FE,
which is what I need to build hpctoolkit for Cray.

Btw, is there a way to ask spack, what are all the FE and BE arch
types that you know about for this system?  'spack compiler list'
indirectly gives me that answer (as long every arch has at least one
compiler), but is there a more direct way?

I was hoping arch=cray-fe-x86_64 (or even cray-fe-fe) would continue
to work, where 'fe' would map to the correct os for this machine.

**Comment by mwkrentel** [comment]
@mamelara   @scheibelp 
Is there anything else to add here?

This is still a blocker for me to build hpctoolkit on Cray.
So, I'd like to get something merged into develop, even if
a more complete fix comes later.

**Pull request merged**
