### PR TITLE
Adding new releases to LIKWID package

### PR DESCRIPTION
**Pull request by TomTheBear**

### CODE REVIEW

**Comment by scheibelp** [comment]
Hi @TomTheBear this is conflict with the recently merged https://github.com/spack/spack/commit/a11b252a1b8f2292715ee9eedadafdc59398594b#diff-b97172943d9d9645127569c7f31e1bfe (which removed a line - you'll have to rebase this or merge with develop (but that should be straightforward).

**Comment by TomTheBear** [comment]
I merged it with develop. I don't know why codecov/patch fails now but it's probably not caused by my two lines.

**Comment by scheibelp** [comment]
Hi @TomTheBear do you recall how you merged/rebased this? I'm trying to figure out why Github is including a whole bunch of unrelated commits.

**Comment by TomTheBear** [comment]
@scheibelp: Not really. But I could close this PR and re-open it again with just the added two lines. It seems like the more convenient way to get it merged...

**Comment by scheibelp** [comment]
That would be great. Apologies for the bother.

**Pull request closed without merging**
