### PR TITLE
Update to distro 1.0.4

### PR DESCRIPTION
**Pull request by adamjstewart**
Updates our vendored copy of `distro` to the latest release: 1.2.0 (2017-12-24).

### CODE REVIEW

**Comment by adamjstewart** [comment]
Looks like `distro` dropped Python 2.6 support: https://github.com/nir0s/distro/pull/195

I think they'll be open to a pull request fixing 2.6 incompatibilities. Let me see how much work that would be.

**Comment by adamjstewart** [comment]
Opened up a pull request with `distro` to regain Python 2.6 support: https://github.com/nir0s/distro/pull/206

**Comment by adamjstewart** [comment]
Okay, I reverted back to `distro` 1.0.4. This is the last release that had official Python 2.6 support.

**Comment by healther** [comment]
Out of curiosity, does anyone use spack with python2.6?

**Comment by adamjstewart** [comment]
@healther See https://github.com/nir0s/distro/pull/206 and https://twitter.com/tgamblin/status/947254477160988672 and the Slack channel. Python 2.6 is the default OS Python on RHEL/CentOS 6, which is still very popular.

**Pull request merged**
