### PR TITLE
added mesa v18.3.6

### PR DESCRIPTION
**Pull request by flxmr**

### CODE REVIEW

**Comment by ax3l** [comment]
cc @chuckatkins

**Comment by chuckatkins** [comment]
@flxmr See #10482, it's a massive re-work of the whole mesa stuff.  Among many other things though, it also bumps to Mesa 19.

**Comment by chuckatkins** [comment]
@flex Given that #10482 is merged now, which bumps the version to 19.0.0, is that sufficient for you and are you okay with me closing this?

**Comment by chuckatkins** [comment]
@flxmr since more recent versions are already present in the new mesa package then I'm going to go ahead and close this for now.  If you do need those older versions explicitly, then we can figure out how to possibly keep both versions of the package (the older autotools and newer meson).  Hopefully though the newer meson based package can work for you now.

**Pull request closed without merging**
