### PR TITLE
pkgconf migration

### PR DESCRIPTION
**Pull request by michaelkuhn**
This PR is a proposal to migrate from `pkg-config` to `pkgconf`.

pkgconf is a new pkg-config implementation with additional features and no external dependencies. For a detailed comparison, see: http://pkgconf.org/features.html.

I have rebuilt a number of packages with the proposed changes and have not noticed any problems.

Edit: Several distributions have already switched from pkg-config to pkgconf: https://github.com/pkgconf/pkgconf/wiki/Roadmap

### CODE REVIEW

**Comment by davydden** [comment]
does `pkgconf` build on macOS?

**Comment by michaelkuhn** [comment]
I do not have access to a macOS machine, so I could not test it. From what I could find in their issues/changelog, it should.

**Comment by davydden** [comment]
i can confirm that `pkgconf` build on Sierra with clang. 

@michaelkuhn don't know if someone will be against this change, but you can also cherry-pick the first commit in a separate PR (leaving this PR as-is) which shall be merged rather quickly.

**Comment by tgamblin** [comment]
I'm ok with this conversion, especially since it reduces the number of dependencies required for many builds, and since it seems like `pkgconf` is being adopted by many distros.

Would it make sense to make a vdep for these packages and make `pkgconf` the preferred implementation?  That would allow folks to use `pkg-config` with a `packages.yaml` tweak, if they want/need to.  See the recent #5190 for an example of that.

**Comment by michaelkuhn** [comment]
I also thought about solving it that way but took the easy way first. :-) Before I update the PR, how would you prefer the naming to be?

1. Keep the `pkg-config` and `pkgconf` packages and introduce a virtual package `pkgconfig` (or something similar) or
2. keep `pkgconf`, rename `pkg-config` to `fdo-pkg-config` (or something similar) and introduce a virtual package `pkg-config`?

I guess the second would be a bit cleaner because it has less potential for confusing the package names.

**Comment by tgamblin** [comment]
@michaelkuhn: I actually like the first better just because the name `pkg-config` is so well known.  I think people are more inclined to type `^pkg-config` if they need to rather than `^fdo-pkg-config` -- I didn't even know it was from freedesktop.

I dunno a good name for the virtual but I think `pkgconfig` or maybe `vpkg-config` would be ok.  This case makes me wonder whether we need to reserve virtual names.  e.g., should we make it so that it's ok for `pkgconf` to provide `pkg-config`, and either `pkgconf` or `pkg-config` would be a suitable resolution for a dependency on `pkg-config`.  This isn't the only case where the first version of a thing has become the de-facto interface name.  I'll think about that for later.

**Comment by michaelkuhn** [comment]
I have updated the PR. There is now a virtual dependency `pkgconfig` with two providers (`pkgconf` and `pkg-config`).

**Comment by michaelkuhn** [comment]
@tgamblin: Ping? :-) I have just rebased the PR to resolve a conflict and catch a new pkg-config dependency.

**Comment by michaelkuhn** [comment]
@tgamblin: I have rebased the PR to fix some recent conflicts and to update pkgconf to 1.3.10.

It would be great if someone else could test this but from my side this should be good to go.

**Comment by michaelkuhn** [comment]
Rebased again. @alalazo @junghans Could you take a look?

**Comment by tgamblin** [comment]
@junghans: I was holding off on merging this because it has the potential to affect a lot of packages. See #6514.  We may need to revert this.

**Pull request merged**
