### PR TITLE
Use get_spec in relocated _try_install_from_binary_cache

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
I added the force option because I suspected the spec.yaml files were not being updated in the build_cache stage if they existed. The force option is only passed to get_specs which calls try_download_specs. The force option is not passed to get_spec.

**Comment by tldahlgren** [comment]
> I added the force option because I suspected the spec.yaml files were not being updated in the build_cache stage if they existed. The force option is only passed to get_specs which calls try_download_specs. The force option is not passed to get_spec.

Okay.  (I initially confused `get_specs` and `get_spec`.)  Thanks for the clarification.

**Comment by gartung** [comment]
Thanks, I explicitly added the force option instead of relying on the function definition.

**Comment by tldahlgren** [comment]
Thanks for restoring the change.

**Pull request merged**
