### PR TITLE
lmod: module files are written in a root folder named by target family

### LINKED ISSUE #13005: Problems with Lmod modulefile names post-PR#3206
We're using Spack on CentOS 7 systems.  We build our things nightly
to stay on top of changes.

The recent changes in #3206 changed the names of the directories in
which our modules end up.  We splice a spack tree into our users
environments with a shell script that used to refer to the Core
directory with something like this:

```
_APPS_LMOD_CORE_DIR=${APPS_DIR}/share/spack/lmod/linux-centos7-x86_64/Core
```

which worked well enough since all of our systems are x86_64.

Now I have two problems (and I'm not even using [regular expressions][1]):

1. the Core modules end up in `linux-centos7-haswell` but there's no
   good way for us to guess the `haswell` bit, it seems to be the arch
   of the system on which the system compiler was built.

   I poked around at the `gcc` command line a bit, but don't see any
   info about how it was built

   ```
   $ /usr/bin/gcc -dumpmachine
   x86_64-redhat-linux
   $ /usr/bin/gcc -print-multiarch

   $
   ```

2. We use the system gcc (4.8.5) to build gcc@8.2.0 and use that to
   build the rest of the things

   Unfortunately, the Core module prepends this bit onto the
   MODULEPATH:

   ```
   $ grep MODULEPATH share/spack/lmod/linux-centos7-haswell/Core/gcc/8.2.0-q5tss7s.lua
   prepend_path("MODULEPATH", "/home/ELIDED/temp/spack/share/spack/lmod/linux-centos7-haswell/gcc/8.2.0")
   ```

   but that directory doesn't exist, all the things that we've built
   with the compiler we built with the system compiler end up in
   `linux-centos7-skylake_avx512`.

[1]: https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/

### PR DESCRIPTION
**Pull request by alalazo**
fixes #13005

This commit fixes an issue with the name of the root directory for module file hierarchies. 

Since #3206 the root folder was named after the microarchitecture used for the spec, which is too specific and not backward compatible for lmod hierarchies. Here we compute the root folder name using the target family instead of the target name itself and we add target information in the "whatis" portion of the module file.

### CODE REVIEW

**Comment by alalazo** [comment]
@hartzell @odoublewen After thinking a bit about the issue, this seems to me the best fix at hand. It should be backward compatible for the naming of the folders and will cover most of the cases. Let me know if this solves your problem and what do you think of the PR.

**Comment by odoublewen** [comment]
I tried this out and it works for me.  The lmod Core directory winds up in `spack/share/spack/lmod/linux-centos7-x86_64/Core`, even when I don't specify `target: x86_64` in packages.yaml.

Thank you @alalazo

**Comment by hartzell** [comment]
@odoublewen -- when you load that Core module, does it "unlock" all of the %gcc@8.2.0 applications that you've built (in other words, do it add The Right Thing(tm) to MODULEPATH?)?

**Comment by odoublewen** [comment]
Yes, everything works correctly.  Tested both with simple standalone modules and modules that have complex runtime dependencies (looking at you python).   I also tested it manually, outside of our CI job, and yes, after I (1) `source` the lmod bash script, (2) `module use spack/share/spack/lmod/linux-centos7-x86_64/Core`, and (3) `module load gcc@8.2.0`, I have access to all of the modules built with gcc 8.2.0.  The lmod modules *Do The Right Thing*.

**Comment by hartzell** [comment]
> The lmod modules _Do The Right Thing_.

Woo hoo!  Thanks @alalazo !

**Comment by tgamblin** [comment]
@CamStan: does this fix your issue?

**Comment by CamStan** [comment]
@tgamblin, might have tagged the wrong Cameron.

**Pull request merged**
