### PR TITLE
Package/perl-bio-perl updated

### PR DESCRIPTION
**Pull request by trecakov**
New version.

### CODE REVIEW

**Comment by hartzell** [comment]
Hi @trecakov 

It looks like you included a lot of stuff in this branch that isn't related to BioPerl.

**AND**

It looks like you changed the URL from the one for BioPerl-1.007002.tar.gz (11-Sep-2017) to the one for BioPerl-1.7.0._2.tar.gz (06-Jul-2016).

[Metacpan's BioPerl page](https://metacpan.org/pod/distribution/BioPerl/BioPerl.pm) has 1.007002 as the latest/current.

What are you trying to do?

**Comment by scheibelp** [comment]
@hartzell 

> It looks like you included a lot of stuff in this branch that isn't related to BioPerl.

There's something weird going on where users merging the develop branch of Spack into their feature branch results in github displaying a bunch of commits that have already made it into Spack; oddly, the commits, though duplicates, have different hashes (see https://github.com/spack/spack/pull/9326#issuecomment-424554143) 

Currently the only way I know how to determine what the changes are is to pull the branch (`git fetch origin pull/ID/head:BRANCHNAME` e.g. `git fetch origin pull/9385/head:bio-perl`) and then diff it with the `develop` branch. You can also get a sense that these have already been merged to Spack by selecting some of the commits (or there associated PR numbers) individually.

@trecakov if you did something other than:

```
git checkout package/perl-bio-perl
git merge develop
``` 

Could you mention that here?

**Comment by trecakov** [comment]
@hartzell
You are completely right. I do not know how I missed to check the date of the release. One user on our cluster needed version Bio-perl 1.5.x or later and when I check the version on spack it was 1.007002 so I assumed that it is old. Sorry for this.

@scheibelp 
I had some problems updating the fork, but I think I know what made this weird issue.

Thank you both for checking it and pointing these things out.
I am sorry, my mistake.

**Comment by hartzell** [comment]
No worries, Perl version numbers have a long and magical history....

**Comment by hartzell** [comment]
@scheibelp -- I don't merge develop into my feature branches, I'm of the rebase persuasion.  I'll 

```
git checkout develop
git fetch origin
git status
# this should be a simple FF merge
git merge origin/develop
git checkout my-fancy-feature
git rebase develop
git push -f origin
```

I've never had any trouble picking stuff up from the base branch.

**Comment by trecakov** [comment]
@hartzell @scheibelp 

Do you have any suggestions how I can fix my update problem. It seems that I am up to date with every single branch that is on develop.
However, it says This branch is 29 commits ahead of spack:develop.

Any suggestions are appreciated?

**Comment by hartzell** [comment]
@trecakov -- I'm not sure what the particular problem is you'd like to solve (I thought you closed the PR and abandoned this change).  I'm also not sure how you ended up where you did.

For what it's worth, here's my workflow.  I use fetch/merge instead of pull and I rebase my feature branches after updating develop rather than merging develop into my feature branch.  The workflow serves me well and results in neat/tidy Pull Requests.

If you adopt it, it's worth practicing it on toy branches and making sure that you understand each step.

I have several aliases I've collected for looking at the log.  By far, my favorite is `git hist`, but I use the others often enough to hang onto them.  Here's the relevant section of my `~/.gitconfig`.

```
[alias]
  # From Ricardo Signes
  hist = log --all --graph --color=always --pretty='[%C(cyan)%h%Creset]%C(bold cyan)%d%Creset %s'
  shist = log --graph --color=always --pretty='[%C(cyan)%h%Creset]%C(bold cyan)%d%Creset %s'

  # https://www.jacobtomlinson.co.uk/quick%20tip/2016/01/18/pretty-git-logs-with-git-lg/
  lg = !"git lg1"
  lg1 = !"git lg1-specific --all"
  lg2 = !"git lg2-specific --all"
  lg3 = !"git lg3-specific --all"

  lg1-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'
  lg2-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'
  lg3-specific = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold cyan)(committed: %cD)%C(reset) %C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset)%n''          %C(dim white)- %an <%ae> %C(reset) %C(dim white)(committer: %cn <%ce>)%C(reset)'
```

Here's a demo of my workflow:

1. clone my fork

    ```
    git clone git@github.com:hartzell/spack spack-demo
    cd spack-demo
    ```

2. add the spack repo as "upstream"

    ```
    git remote add upstream git@github.com:spack/spack
    ```

3. fetch upstream and merge into develop

   ```
   git fetch upstream
   git checkout develop
   git merge upstream/develop
   ```

4. push updated develop branch to origin (my "fork")

    ```
    git push origin
    ```

5. get to work

    ```
    git checkout -b my-new-feature
    ```

6. look at the structure, I like `git hist`

    ```
    git hist
    ```

7. Get to work (these are fake work...)

    ```
    echo foo > moose.txt
    echo bar > ape.txt
    ```

8. commit them with a GREAT commit message

   ```
   git add moose.txt ape.txt
   git commit -m 'Animals, running loose!'
   ```

9. push the feature branch to my fork for safe keeping

   ```
   git push --set-upstream origin my-new-feature
   ```

1.  look at the structure, here `git hist` output:

    ```
    * [49e14fbaf] (HEAD -> my-new-feature, origin/my-new-feature) Animals, running loose!
    * [a6ab5edea] (upstream/develop, origin/develop, origin/HEAD, develop) Laghos: add version 1.1 (#9389)
    * [bf757bd23] lighttpd: install to bin vs sbin (#9337)
    ```

1. time passes, need to pull in new commits on Spack's develop branch

    ```
    git fetch upstream
    ```

    `git hist` output:

    ```
    * [57236fa2c] (upstream/develop) kokkos: add serial backend explicitly. add kokkos options and kokkos cuda options. (#9276)
    * [691a19226] redundans: add py-numpy dep, snap-berkeley version constraint (#9354)
    | * [49e14fbaf] (origin/my-new-feature, my-new-feature) Animals, running loose!
    | /
    * [a6ab5edea] (HEAD -> develop, origin/develop, origin/HEAD) Laghos: add version 1.1 (#9389)
    * [bf757bd23] lighttpd: install to bin vs sbin (#9337)
    ```

    ```
    git checkout develop
    git merge upstream/develop
    git push origin
    git checkout my-new-feature
    ```

    `git hist` output:

    ```
    * [57236fa2c] (upstream/develop, origin/develop, origin/HEAD, develop) kokkos: add serial backend explicitly. add kokkos options and kokkos cuda options. (#9276)
    * [691a19226] redundans: add py-numpy dep, snap-berkeley version constraint (#9354)
    | * [49e14fbaf] (HEAD -> my-new-feature, origin/my-new-feature) Animals, running loose!
    |/
    * [a6ab5edea] Laghos: add version 1.1 (#9389)
    * [bf757bd23] lighttpd: install to bin vs sbin (#9337)
    ```

2.  and finally rebase my work onto the updated develop

    ```
    git rebase develop
    ```

    Here's the `git hist` output:

    ```
    * [57c58eda7] (HEAD -> my-new-feature) Animals, running loose!
    * [57236fa2c] (upstream/develop, origin/develop, origin/HEAD, develop) kokkos: add serial backend explicitly. add kokkos options and kokkos cuda options. (#9276)
    * [691a19226] redundans: add py-numpy dep, snap-berkeley version constraint (#9354)
    | * [49e14fbaf] (origin/my-new-feature) Animals, running loose!
    |/
    * [a6ab5edea] Laghos: add version 1.1 (#9389)
    * [bf757bd23] lighttpd: install to bin vs sbin (#9337)
    ```

3. and push the feature branch it back to my fork for safe keeping
    (must use force push, lease is safer-ish).

    ```
    git push --force-with-lease origin
    ```

**Pull request closed without merging**
