### PR TITLE
Add PETSc 3.10.1 to PETSc's spackage file

### PR DESCRIPTION
**Pull request by serbanmaerean**
Adding version 3.10.1 to PETSc's spackage file.

PETSc version 3.9.3 does not build the native test framework correctly, so users will need to build version 3.10.1.

### CODE REVIEW

**Comment by tgamblin** [comment]
@balay: I think you're right @serbanmaerean -- what do you think?

**Comment by serbanmaerean** [comment]
The patch file is not used during building of PETSc.  The patch file is used during building of the native tests.  I dropped it Spack for a place holder, so users that need to build the native tests can do so successfully.  These flags are not required for the building of PETSc.
Of course, I could have patch the original gmakefile.test w/those flags for the XL compiler and when the PETSc build generates the test framework (i.e. copying files to <install directory>/share/petsc/examples/src). I decided not to do it because most people will not build the native tests and I wanted to keep the spackage file simple.  I could have use the FFLAGS, but I don't believe it matters how these flags are specified in the makefile for the native tests.

**Comment by balay** [comment]
> The patch file is not used during building of PETSc. The patch file is used during building of the native tests. I dropped it in Spack for a place holder, so users that need to build the native tests can do so successfully. These flags are not required for the building of PETSc.

But spack does not build examples. So its carrying a hack for non-spack usage.

How are you building examples after spack installs PETSc?

> Of course, I could have patch the original gmakefile.test w/those flags for the XL compiler and when the PETSc build generates the test framework (i.e. copying files to /share/petsc/examples/src). I decided not to do it because most people will not build the native tests and I wanted to keep the spackage file simple. I could have use the FFLAGS, but I don't believe it matters how these flags are specified in the makefile for the native tests.

I don't completely understand what you are saying here.

For one - your patch file IS modifying gmakefile.test - but above statement is implying that 'you decided not to do it '

And patching makefiles with compiler specific flags is a hack. `FFLAGS` to `configure` or `make` would be the correct way to specify extra flags.

Currently FFLAGS to petsc configure via spack is broken. But FFLAGS to makefile should work [assuming you are somehow invoking 'make' separately out of spack - to compile the tests]

**Comment by balay** [comment]
> Currently FFLAGS to petsc configure via spack is broken. 

Potential fix in #9383

**Comment by serbanmaerean** [comment]
Under the Spack build, the tests are copied to <install directory>/share/petsc/examples.  The gmakefile.test from the top directory is copied to that directory and test cases are copied under an src sub-directory. The tests themselves are not build under Spack, they are only copied.  However, in order to verify the build, we go to that directory and explicitly build and run the testcases.
I was not interested in adding those Fortran flags to the PETSc build.  So modifying the FFLAGS in the spackage file was not something that I believe needs to be done.  Those flags are required only for building some test cases and whoever wants to build those testcases for the XL compiler can patch gmakefile.test in <install directory>/share/petsc/examples and build from there.
Again, these are not flags used for building PETSc.  They are required for building the PETSc native test cases.  It doesn't matter how one provides these flags, whether they use FFLAGS or some other gmake variable.

**Comment by balay** [comment]
> Under the Spack build, the tests are copied to <install directory>/share/petsc/examples. The gmakefile.test from the top directory is copied to that directory and test cases are copied under an src sub-directory. The tests themselves are not build under Spack, they are only copied.

Sure

>  However, in order to verify the build, we go to that directory and explicitly build and run the testcases.
> I was not interested in adding those Fortran flags to the PETSc build. So modifying the FFLAGS in the spackage file was not something that I believe needs to be done.

configure flags are used for both building PETSc library and PETSc test suite.

> Those flags are required only for building some test cases and whoever wants to build those testcases for the XL compiler can patch gmakefile.test in <install directory>/share/petsc/examples and build from there.

Presumably you are using `make alltests` to build and run these examples. If you do not want to specify these flags to spack  at build time (i.e to petsc configure) - why not specify FFLAGS to make - instead of this hack in spack for gmakefile.test?

> Again, these are not flags used for building PETSc. They are required for building the PETSc native test cases. It doesn't matter how one provides these flags, whether they use FFLAGS or some other gmake variable.

And it doesn't make sense to have this patch in spack [esp when its not need in the spack part of the build]

Or perhaps the recommended usage doesn't work due to bugs?

**Comment by serbanmaerean** [comment]
I am using gmake -f gmakefile.test test, or search='...' for individual tests.  Of course, one can specify those flags to gmake.  But they have to remember what those flags are.  I will not remember what those flags are or where I saved them in a week from now, for sure.  That's why I added that patch file that is not used in the spackage file.  It's just for safekeeping.

Honestly, I don't care how these flags are passed to the compiler.  If one wants to modify a makefile or pass them to make, who cares?  If you don't like that patch file, you can remove it and the spackage file will not be impacted.  It's just a placeholder for users to quickly get the those flags when they need them, i.e. when they build the test cases.  I could have added a README file, true.  It was just simpler to add a diff file.

There is another patch for version 3.9.0, also not used in the spackage file, just for safekeeping. You can remove both of them if you don't like them being there as safekeeping the changes required to build the test cases.

**Comment by balay** [comment]
ok. I don't think spack petsc/package.py is the correct place to store these flags - so its best to remove them. [will do]

On the PETSc side - we tend to have such things in config/examples/arch*.py files [along with other configure options] - this is used by folks that install PETSc directly [and not via spack]

**Comment by serbanmaerean** [comment]
OKay, thanks for doing that.

Those flags are needed regardless of how PETSc is installed, i.e. under Spack or directly.  I have not looked at PETSc in detail, I only wanted to make sure the tests can be built and run successfully, as they are required for CORAL acceptance at LLNL.

**Comment by balay** [comment]
could you clarify what these flags are for - and why only examples need them?

And why you don't think its appropriate to specify them at configure time?

PETSc model is - all flags are specified at configure time - and they are used by the library and examples.

Or have this discussion at petsc-maint [as this is unrelated to spack]

**Pull request merged**
