### PR TITLE
Add documentation on Codecov

### PR DESCRIPTION
**Pull request by adamjstewart**
I decided to add documentation on some of the questions I get asked multiple times per day:

- How do I restart my failed Travis tests?
- Are Codecov tests required to pass if I only modified package files?

### CODE REVIEW

**Comment by adamjstewart** [comment]
@alalazo Seeing the same weird Codecov bug you experienced here. Could it be related to the fact that we reran some of the tests a second (or third) time to get them to pass?

**Comment by tgamblin** [comment]
It looks like codecov dropped off on January 3 and didn't come back.  Am I missing a thread on that?

**Comment by alalazo** [comment]
Not really, as far as I know we had a few days in which the coverage status disappeared and #6173 was reopened, when it went back we started noticing weird behaviors (i.e. this -20%) on coverage. See also #6837

**Comment by alalazo** [comment]
Ok, looking at the [tests log](https://travis-ci.org/spack/spack/jobs/325840420) in Travis I see this:
```
Coverage.py warning: Couldn't read data from '/home/travis/build/spack/spack/.coverage.travis-job-spack-spack-325840420.travisci.net.9674.931552': CoverageException: Doesn't seem to be a coverage.py data file
```

**Comment by alalazo** [comment]
[This](https://travis-ci.org/spack/spack/jobs/324632601) is the first succeeding Travis build that should this warning. Cross-checking with codecov it's also the same commit where we see the drop in coverage.

**Pull request merged**
