### PR TITLE
nlopt: changing build procedure for v2.4.2

### PR DESCRIPTION
**Pull request by peetsv**

### CODE REVIEW

**Comment by citibeth** [comment]
@peetsv 
> I should have referenced the Issue #8127

Yes I saw that on #8127.  But that was downloading from a wonky non-official website.  The 2.4.2 release showing on the official GitHub site DOES have the CMake build.  Can we use that?

**Comment by peetsv** [comment]
I will have to get some time to try out the updated URL and the CMake build.

**Comment by peetsv** [comment]
I have recently tried build of each of the nlopt sources:
```
==> Fetching https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2.tar.gz
```
and
```
==> Fetching http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
```
Both CMake builds failed as reported in #8127

**Comment by alalazo** [comment]
Closing since in the meanwhile v2.4.2 has been removed from the versions supported in the package.

**Pull request closed without merging**
