### PR TITLE
python: dbm module + version 3.6.4

### PR DESCRIPTION
**Pull request by alalazo**
I extracted the non-controversial parts of #7496 here. Let me no if this is fine with you to merge.

### CODE REVIEW

**Comment by adamjstewart** [comment]
What is `dbm`? Is it necessary to be a default variant? I'm just worried about adding an additional dependency.

Also, does Python not need any config flags to locate it? Is it picking it up already if it happens to be installed on the system, even if `~dbm` is specified?

**Comment by alalazo** [comment]
@adamjstewart [dbm](https://docs.python.org/3/library/dbm.html) is part of the python standard library, as is [tkinter](https://docs.python.org/3/library/tk.html).

> Also, does Python not need any config flags to locate it? Is it picking it up already if it happens to be installed on the system, even if ~dbm is specified?

I need to check that, but I think it's picking it up already if `gdbm` is installed on the system. The same probably holds true for `tk`.

**Comment by alalazo** [comment]
To add on the above: I put `dbm` as `default=True` as it doesn't take a lot of time to build. If people prefer `default=False` (and miss that part of the standard library) that's definitely not an issue.

**Comment by alalazo** [comment]
Thanks for the quick feedback!

**Pull request merged**
