### PR TITLE
hpctoolkit: variants to build for cray and blue gene

### PR DESCRIPTION
**Pull request by mwkrentel**
Add variants 'cray' and 'bgq' to build for Cray and Blue Gene compute
nodes.  These systems need separate options to find the MPI compiler
for hpcprof-mpi.

### CODE REVIEW

**Comment by adamjstewart** [comment]
This doesn't require a variant, you can make it automatic like so:
```python
if self.spec.satisfies('platform=bgq'):
    ...
elif self.spec.satisfies('platform=cray'):
    ...
```
We should probably also remove the variant from `libmonitor` and any other package that has a `bgq` or `cray` variant.

**Comment by mwkrentel** [comment]
It's complicated.  We build part of hpctoolkit for the front-end and
part (mostly mpic++) for the back-end.  So, to be truly clean, we
would need access to both FE and BE compilers in the same build, and
spack doesn't support that.

For Cray, this doesn't work because we can't build hpctoolkit at all
with platform=cray.  For example, boost (a prereq) won't build due to
mixing up FE and BE compilers.  See issue #9613.

Currently, the only way I can build for Cray is to unset CRAYPE_VERSION,
treat the machine as a front-end x86_64, and search for the non-spack
CC wrapper inside hpctoolkit.  On Cray, CC is the MPI C++ wrapper, but
spack puts a CC wrapper in front of PATH, thus turning an MPI compiler
into a non-MPI compiler.

On Blue Gene, this might work, but I'm still inclined to keep the
variant.  For one thing, having platform=bgq imply the BE config would
prevent me from building for the front end.

It's a good idea and I'll keep this in mind as things evolve going
forward.  But it requires spack to better understand FE vs BE before
it really matters.

Now, if you'd like to think about some advanced issues in spack
architecture, here's what we need to be truly clean about the build.
Understand two sets of compilers (C, C++, Fortran) one for FE and one
for BE, plus MPI of course, mainly for BE.

These will need to come from two different arch's.  On Cray, this
means having prereqs from arch=cray-cnl6-mic_knl and linux-sles12-x86_64
in the same build.  Once you have that in place, then I can clean out
hpctoolkit config to build accordingly.

Adam, are you going to the ECP meeting in Houston in two weeks?
I hope to talk to Todd &co about some of the long-term issues there.

**Comment by adamjstewart** [comment]
Ah, that's more complicated than I imagined. The only thing I know about Spack's cross-compiling support is:
```console
$ spack help --spec
...
    cross-compiling:
      os=backend or os=be           build for compute node (backend)
      os=frontend or os=fe          build for login node (frontend)
```
Aside from that, it sounds like there's a lot to be desired. I'll let someone else review this PR in that case.

Unfortunately, I won't be at ECP. I have my quals coming up this semester 😄

**Comment by mwkrentel** [comment]
The way we build hpctoolkit on Cray and Blue Gene (directly in
autotools, outside of spack) is to treat the system as mostly FE with
MPICXX for the BE.

This is technically unclean, running some FE code on the BE.  We get
away with this because Cray and Blue Gene are more of a cross-link
than a true cross-compile.  (We build most libraries and it's only the
MPICXX wrapper that links a full program that won't run on the FE.)
It's cheating, but we've been cheating this way for 10+ years.

What I've done in this PR is to translate our build system into the
spack infrastructure to step around a few things that would otherwise
break the build (eg, boost).

**Comment by mwkrentel** [comment]
@tgamblin  Did you want to review this?

**Comment by scheibelp** [comment]
I can look at this by 1pm tomorrow (1/10)

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
