### PR TITLE
Add XSSP recipe

### PR DESCRIPTION
**Pull request by asmaahassan90**

### CODE REVIEW

**Comment by bhatiaharsh** [comment]
Hello @asmaahassan90. I am trying to use your package. Its header says _"The source code for building the mkdssp, mkhssp, hsspconv, and hsspsoap programs is bundled in the xssp project."_ but installing this does not provide `mkdssp` (only `mkhssp`). Further, the git repository `xssp` redirects to `hssp` (perhaps the authors split `xssp` again into two?. 

Regardless, although I can easily create a new spack package for `dssp`, I was wondering how you envision using this. Should the spack package focus only on `hssp` (in this case, we should probably call it `hssp` and update the git link), or install both `dssp` and `hssp`.

What do you think?

**Comment by asmaahassan90** [comment]
Hello @bhatiaharsh . Thank you for reaching out. I was not aware of the change made to xssp github repository. When I created this recipe and installed the package, I had them all included. But yes, I see now that xssp github repository redirects to hssp. 
I can keep this one for hssp and make the changes accordingly. I think it makes more sense since the author did split/change the repository. But if you have a suggestion to include dssp in this one, I'd like to hear it.

**Comment by bhatiaharsh** [comment]
I did create one for dssp (currently it's local, but I can push it upstream). May be rename the xssp package to hssp?

**Comment by bhatiaharsh** [comment]
Done. See https://github.com/spack/spack/pull/17188

**Pull request merged**
