### PR TITLE
Make the concretizer respect compiler preferences

### PR DESCRIPTION
**Pull request by michaelkuhn**
While it is possible to specify compiler preferences for all packages, those for single packages are currently ignored.

For instance, a `packages.yaml` such as this:
```yaml
packages:
    all:
        compiler: [clang]
    ncurses:
        compiler: [gcc]
```
results in the following output for `spack spec readline`:
```
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%clang@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%clang@9.1.1 arch=linux-fedora30-x86_64
```

Simply querying the package's compiler preferences is not enough due to the concretizer's current behavior. If a compiler preference is specified explicitly anywhere in the DAG, it is applied everywhere, as can be seen for `spack spec readline ^pkgconf%gcc`:
```
readline@7.0%gcc@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%gcc@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%gcc@9.1.1 arch=linux-fedora30-x86_64
```

This is in contrast to the concretizer's behavior in other cases such as when dealing with compiler flags, which are only applied to children. For instance, `spack spec readline ^pkgconf cflags='-g'` produces:
```
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%clang@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%clang@9.1.1 cflags="-g"  arch=linux-fedora30-x86_64
```

Therefore, this PR contains two changes to the concretizer:
1. Make compiler preferences only apply to children. On the one hand, this makes the concretizer's behavior more consistent. On the other hand, it makes sure that compiler preferences specified in `packages.yaml` are only applied to the specified package. Otherwise, it would get propagated up to its parents due to the concretizer's bottom-up approach.
2. Apply compiler preferences specified in `packages.yaml` to individual packages.

As can be seen with `spack spec readline`, the compiler preference from `packages.yaml` is applied correctly:
```
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%gcc@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%clang@9.1.1 arch=linux-fedora30-x86_64
```

Moreover, `spack spec readline ^pkgconf%gcc` shows that compiler preferences only apply to children:
```
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%gcc@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%gcc@9.1.1 arch=linux-fedora30-x86_64
```

It is also still possible to override compiler preferences in `packages.yaml` explicitly. For instance, `spack spec readline%clang`:
```
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%clang@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%clang@9.1.1 arch=linux-fedora30-x86_64
```

Fixes: #1371

### CODE REVIEW

**Comment by michaelkuhn** [comment]
@adamjstewart @tgamblin @alalazo

**Comment by tgamblin** [comment]
I like this a lot and think that it is *better* than the current behavior.  I'd like to make this change.

The one sticking point that I am nearly positive will come up is this:

```console
$ spack spec readline ^pkgconf%gcc
readline@7.0%clang@9.1.1 arch=linux-fedora30-x86_64
    ^ncurses@6.1%gcc@9.1.1~symlinks~termlib arch=linux-fedora30-x86_64
        ^pkgconf@1.6.1%gcc@9.1.1 arch=linux-fedora30-x86_64
```

I *think* users are used to the old behavior (where the whole spec would end up using `gcc`), and we'll likely need to comb the documentation for places where we use the syntax above the "wrong" way.  We even do this [in the tutorial](https://spack.readthedocs.io/en/latest/tutorial_basics.html#installing-packages).

I think the new behavior is better because it lets you much more easily construct mixed-compiler DAGs, and the preferences in `package.yaml` can be reasoned about much more clearly.  To me, outweighs the convenient shorthand we've gotten people used to, but people *are* used to it.

So, my request would be that you add another commit for documentation changes, in addition to what's here.  We should also remember to put this in the next release notes in the fall.

**Comment by adamjstewart** [comment]
I would actually expect the following behavior:

---
```console
$ spack spec readline
readline@7.0%clang
    ^ncurses@6.1%gcc
        ^pkgconf@1.6.1%gcc
```
Changed: switched `pkgconf%clang` to `pkgconf%gcc`
```console
$ spack spec readline ^pkgconf%gcc
readline@7.0%clang
    ^ncurses@6.1%gcc
        ^pkgconf@1.6.1%gcc
```
Not changed
```console
$ spack spec readline%clang
readline@7.0%clang
    ^ncurses@6.1%gcc
        ^pkgconf@1.6.1%gcc
```
Changed: switched `ncurses%clang` and `pkgconf%clang` to `ncurses%gcc` and `pkgconf%gcc`.

---

When I first wrote #1371, I was looking at things from the perspective of "how do I tell Spack that certain packages cannot be built with certain compilers". This was long before `conflicts` existed, and we still don't take `conflicts` into account during concretization. If things were implemented the way I have suggested above, then I would be able to do what I want. 

But that doesn't mean that's the best way to do things. I agree that `packages.yaml` settings are to some extent "preferences", not "hard requirements", so it's possible that the behavior you have proposed is more desirable. But we still need a way to say "hey, this package can only be built with gcc". If that is the case, it also doesn't make sense to rebuild that package's dependencies for new compilers if you're still going to build that package with gcc.

I hope what I've said above makes sense, but if not let me know.

**Comment by tgamblin** [comment]
> I hope what I've said above makes sense, but if not let me know.

I'm confused about your second case -- why is `readline` built with clang there?

**Comment by adamjstewart** [comment]
> I'm confused about your second case -- why is `readline` built with clang there?

Because the default compiler is clang. To me, when someone says `readline ^pkgconf%gcc`, they mean "I don't care what compiler `readline` is built with, but `pkgconf` must be built with gcc".

**Comment by becker33** [comment]
I think this requires more thought about how conflicts are handled.

For example: What should the behavior be for a diamond dependency for which the sides have compiler preferences.

```
               foo
          /            \
      bar                 baz
(pref: clang)       (pref: intel)
         \              /
                qux
             (no pref)
```
Should the concretization for `foo%gcc` be:

`foo%gcc ^bar%clang ^baz%intel ^qux%gcc`
`foo%gcc ^bar%clang ^baz%intel ^qux%clang`
`foo%gcc ^bar%clang ^baz%intel ^qux%intel`

I think if we adopt this feature as-is, we're going to end up in a situation where it's really not clear what the semantics of a spec are, and concretization choices will be determined by some combination or arbitrary pythonic orderings and the order of dependency declarations in packages -- neither of which seem like a good idea to me.

**Comment by michaelkuhn** [comment]
> I hope what I've said above makes sense, but if not let me know.

Sorry, I don't get it. But it's getting late here. :-)

> Should the concretization for `foo%gcc` be:
> 
> `foo%gcc ^bar%clang ^baz%intel ^qux%gcc`
> `foo%gcc ^bar%clang ^baz%intel ^qux%clang`
> `foo%gcc ^bar%clang ^baz%intel ^qux%intel`
> 
> I think if we adopt this feature as-is, we're going to end up in a situation where it's really not clear what the semantics of a spec are, and concretization choices will be determined by some combination or arbitrary pythonic orderings and the order of dependency declarations in packages -- neither of which seem like a good idea to me.

When the preferences are taken from `packages.yaml`, only the specific package is influenced, not any of its parents or children. `qux` should always end up with `%gcc` then.

For `foo ^bar%clang ^baz%intel`, you are right and there might be conflicts. I will take a look tomorrow.

> Code looks good -- see my request above for doc changes.

I will take a look at this tomorrow, too.

**Comment by michaelkuhn** [comment]
> > I think if we adopt this feature as-is, we're going to end up in a situation where it's really not clear what the semantics of a spec are, and concretization choices will be determined by some combination or arbitrary pythonic orderings and the order of dependency declarations in packages -- neither of which seem like a good idea to me.
> 
> When the preferences are taken from `packages.yaml`, only the specific package is influenced, not any of its parents or children. `qux` should always end up with `%gcc` then.
> 
> For `foo ^bar%clang ^baz%intel`, you are right and there might be conflicts. I will take a look tomorrow.

One addition: If I'm not mistaken, the new behavior should not differ from the old one in this case. Since everything is concretized bottom-up, `qux` will look at its parents to figure out which compiler to use. This was also the case before this change.

**Comment by michaelkuhn** [comment]
> So, my request would be that you add another commit for documentation changes, in addition to what's here. We should also remember to put this in the next release notes in the fall.

I have grepped around a bit (`spack.*\^.*%` and `spack.*%.*\^`) and only found the one instance that you mentioned where the behavior would be different. I have also added one more sentence to the compiler spec explanation.

**Comment by michaelkuhn** [comment]
ping?

**Comment by michaelkuhn** [comment]
@tgamblin @alalazo @becker33 Anything else I can do here?

**Pull request closed without merging**
