### PR TITLE
[GLVis] Add new version: 3.4

### PR DESCRIPTION
**Pull request by v-dobrev**
Also, update all checksums to be SHA-256.

Building the new version (3.4) requires PR #8453.

### CODE REVIEW

**Comment by imnasnainaec** [comment]
When I run `spack install glvis` on -- linux-ubuntu18.04-x86_64 / gcc@7.3.0 --, it successfully installs all the dependencies, but then ends with a cryptic `==> Error: Version('3.4')`.

**Comment by adamjstewart** [comment]
@imnasnainaec Can you run:
```console
$ spack --debug install glvis
```
This should give much more useful error messages.

**Comment by imnasnainaec** [comment]
==> WRITE LOCK: /home/dror/spack/opt/spack/.spack-db/prefix_lock[4926663922316013287:1] [Acquiring]
==> WRITE LOCK: /home/dror/spack/opt/spack/.spack-db/prefix_lock[4926663922316013287:1] [Acquired]
==> READ LOCK: /home/dror/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /home/dror/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /home/dror/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /home/dror/spack/opt/spack/.spack-db/prefix_lock[4926663922316013287:1] [Released]
Traceback (most recent call last):
  File "/home/dror/spack/bin/spack", line 61, in <module>
    sys.exit(spack.main.main())
  File "/home/dror/spack/lib/spack/spack/main.py", line 653, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/dror/spack/lib/spack/spack/main.py", line 432, in _invoke_command
    return_val = command(parser, args)
  File "/home/dror/spack/lib/spack/spack/cmd/install.py", line 273, in install
    install_spec(args, kwargs, spec)
  File "/home/dror/spack/lib/spack/spack/cmd/install.py", line 154, in install_spec
    spec.package.do_install(**kwargs)
  File "/home/dror/spack/lib/spack/spack/package.py", line 1381, in do_install
    **kwargs)
  File "/home/dror/spack/lib/spack/spack/package.py", line 1344, in do_install
    partial = self.check_for_unfinished_installation(keep_prefix, restage)
  File "/home/dror/spack/lib/spack/spack/package.py", line 1577, in check_for_unfinished_installation
    stage_is_managed_in_spack = self.stage.path.startswith(
  File "/home/dror/spack/lib/spack/spack/package.py", line 704, in stage
    self._stage = self._make_stage()
  File "/home/dror/spack/lib/spack/spack/package.py", line 682, in _make_stage
    stage = self._make_root_stage(fetcher)
  File "/home/dror/spack/lib/spack/spack/package.py", line 661, in _make_root_stage
    mp = spack.mirror.mirror_archive_path(self.spec, fetcher)
  File "/home/dror/spack/lib/spack/spack/mirror.py", line 101, in mirror_archive_path
    spec.name, mirror_archive_filename(spec, fetcher, resource_id))
  File "/home/dror/spack/lib/spack/spack/mirror.py", line 60, in mirror_archive_filename
    ext = spec.package.versions[spec.package.version].get(
KeyError: Version('3.4')

**Comment by adamjstewart** [comment]
What happens if you change:
```python
depends_on('mfem@3.4', when='@3.4')
```
to:
```python
depends_on('mfem@3.4.0', when='@3.4')
```
?

**Comment by adamjstewart** [comment]
You would change it in the `glvis` package.

**Comment by imnasnainaec** [comment]
That solved that issue, but now...
`$ spack install glvis`
> [... other lines removed ...]
> ==> mesa-glu is already installed in /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mesa-glu-9.0.0-y5hhmszdxykcwznb3xe5u42t43xupmze
> [... other lines removed ...]
> ==> mfem is already installed in /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mfem-3.4.0-625aw3xex5lwwfyz2u4qlqlif7ezblow
> ==> Installing glvis
> ==> Using cached archive: /home/dror/spack/var/spack/cache/glvis/glvis-3.4.tar.gz
> ==> Staging archive: /home/dror/spack/var/spack/stage/glvis-3.4-4mnjl7sqdybr2bvd346zc7fzv43lorja/glvis-3-4
> ==> Created stage in /home/dror/spack/var/spack/stage/glvis-3.4-4mnjl7sqdybr2bvd346zc7fzv43lorja
> ==> No patches needed for glvis
> ==> Building glvis [MakefilePackage]
> ==> Executing phase: 'edit'
> ==> Error: RuntimeError: Unable to recursively locate mesa-glu libraries in /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mesa-glu-9.0.0-y5hhmszdxykcwznb3xe5u42t43xupmze
> 
> /home/dror/spack/var/spack/repos/builtin/packages/glvis/package.py:107, in edit:
>         104        mfem = spec['mfem']
>         105        config_mk = mfem.package.config_mk
>         106
>   \>\>    107        gl_libs = spec['glu'].libs + spec['gl'].libs + spec['libx11'].libs
>         108        args = ['CC={0}'.format(env['CC']),
>         109                'PREFIX={0}'.format(prefix.bin),
>         110                'MFEM_DIR={0}'.format(mfem.prefix),
> 
> See build log for details:
>   /home/dror/spack/var/spack/stage/glvis-3.4-4mnjl7sqdybr2bvd346zc7fzv43lorja/glvis-3.4/spack-build.out

**Comment by adamjstewart** [comment]
Can you run:
```console
$ find /home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mesa-glu-9.0.0-y5hhmszdxykcwznb3xe5u42t43xupmze -name '*.so'
```
I'm just wondering what the library is called and which directory it is in. Probably something like `lib/libGLU.so`.

**Comment by v-dobrev** [comment]
I believe this used to work fine with `depends_on('mfem@3.4', when='@3.4')`. Is this issue going to be fixed in the Spack core (allowing dependency on `3.4` to be resolved by `3.4.0`), or should I submit a PR to update the `glvis` package?

**Comment by imnasnainaec** [comment]
@adamjstewart 
I ran it and the result was `/home/dror/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/mesa-glu-9.0.0-y5hhmszdxykcwznb3xe5u42t43xupmze/lib/libGLU.so`

**Comment by adamjstewart** [comment]
`3.4` should not resolve to `3.4.0`, that bug has been in place for years, see #1035. There are a few places where this currently is the case, for example, patches (#8432).

**Comment by adamjstewart** [comment]
@imnasnainaec Can you check `mesa` as well?

**Comment by imnasnainaec** [comment]
@adamjstewart See edited comment above.

**Comment by adamjstewart** [comment]
Thanks @imnasnainaec, in that case #8904 should solve all of your problems.

**Pull request merged**
