### PR TITLE
f90cache: change the download url

### PR DESCRIPTION
**Pull request by Hironori-Yamaji**
The download url of the f90cache package was invalid because the following error occurred.
"The requested url returned error: 404 Not Found"

So, I changed the download url.
The version of the f90cache package provided by the vendor has changed from "0.99" to "0.99c".
"https://perso.univ-rennes1.fr/edouard.canot/f90cache/"

### CODE REVIEW

**Comment by Hironori-Yamaji** [comment]
There is no package of f90cache ver 0.99 at the following official URL.
"https://perso.univ-rennes1.fr/edouard.canot/f90cache/"
Also, there seems to be no official Github for f90cache.

Then, there is a package of f90cache ver 0.99 at the following URL:
"http://distfiles.exherbo.org/distfiles/", but it is not the official homepage. Is it appropriate to use the above URL?

**Comment by citibeth** [comment]
On Wed, Jun 26, 2019 at 1:36 AM Hironori-Yamaji <notifications@github.com>
wrote:

> There is no package of f90cache ver 0.99 at the following official URL.
> "https://perso.univ-rennes1.fr/edouard.canot/f90cache/"
> Also, there seems to be no official Github for f90cache.
>
> That's too bad.

> Then, there is a package of f90cache ver 0.99 at the following URL:
> "http://distfiles.exherbo.org/distfiles/", but it is not the official
> homepage. Is it appropriate to use the above URL?
>

If the tarball at that location has the same checksum, then it's no
problem.  If the checksum is different, we DEFINITELY want to avoid it.
That's why Spack checksums are great!

**Comment by Hironori-Yamaji** [comment]
> If the tarball at that location has the same checksum, then it's no problem. If the checksum is different, we DEFINITELY want to avoid it. That's why Spack checksums are great!

Thank you for your reply.
I checked the tarball's checksum at the following url:
"http://distfiles.exherbo.org/distfiles/f90cache-0.99.tar.bz2"

Please see below for the checksum of the above tarball:
```
$ curl -O http://distfiles.exherbo.org/distfiles/f90cache-0.99.tar.bz2

$ md5sum f90cache-0.99.tar.bz2
e4767ae876203ed4f3e118e22204cdec  f90cache-0.99.tar.bz2
```
This MD5 checksum is the same as the original checksum:
`version('0.99', 'e4767ae876203ed4f3e118e22204cdec')`

So, I added the unofficial url for ver 0.99.

Let me ask 2 more questions.
```
1. Which is the appropriate url for the original url in line 17, ver 0.99 or 0.99c?
   (for the users who already installed f90cashe)

2. Which is the appropriate checksum for ver 0.99, MD5 or SHA256?
   (for security purposes)
```

**Comment by citibeth** [comment]
> 1. Which is the appropriate url for the original url in line 17, ver 0.99 or 0.99c?
>    (for the users who already installed f90cashe)

It doesn't matter.  The version number in that "sample" URL gets parsed out and replaced by the actual version you will be using.

> 2. Which is the appropriate checksum for ver 0.99, MD5 or SHA256?
>    (for security purposes)

Changing to SHA256 requires that someone verify the change.  I'm happy enough to not do that work, so I merged with the old checksum in place.

**Pull request merged**
