### PR TITLE
[WIP] Debugging spurious deactivate for environment view

### PR DESCRIPTION
**Pull request by scheibelp**
~(EDIT 8/12: fixing some problems with this, I'll remove this message when this PR is useful for debugging)~ (UPDATE: this is now useful for debugging errors)

This is for debugging https://github.com/spack/spack/issues/12323

It doesn't contain any fix (since I don't know what the problem is yet) - it is for printing out additional information. I will update it as I get ideas about other things to try.

@adamjstewart @citibeth would you be able to use this branch to rerun failing Spack commands related to https://github.com/spack/spack/issues/12323 and report the output here?

### CODE REVIEW

**Comment by adamjstewart** [comment]
@scheibelp I got this error again:
```
==> Error: Cannot deactivate py-google-api-core@1.14.2%clang@10.0.1-apple arch=darwin-mojave-x86_64/d56cg4f because py-gee-asset-manager@0.1%clang@10.0.1-apple arch=darwin-mojave-x86_64/cpe7kqe is activated and depends on it
```
I tried your branch and ran:
```console
$ spack -d env view regenerate
```
but I wasn't able to reproduce the error. Maybe I'll just re-run `spack install` next time.

Can you rebase off of develop? My `spack.yaml` contains a lot of packages in develop but not in your branch.

**Comment by scheibelp** [comment]
Thanks for checking, yes I'll rebase on develop, and I realized there's a couple things I need to fix with this before folks try it (again).

I'm also looking into a couple test failures (so I may actually have reproduced this myself)

**Comment by adamjstewart** [comment]
Okay, on `develop`, I get:
```console
$ spack -d install
==> [2019-08-13-15:44:36.169803] ActivationError: Cannot deactivate py-psutil@5.5.1%gcc@6.3.0 arch=cray-cnl5-interlagos/gfvo7l5 because py-geeup@0.2.4%gcc@6.3.0 arch=cray-cnl5-interlagos/ars3mil is activated and depends on it
==> [2019-08-13-15:44:36.170018] Error: Cannot deactivate py-psutil@5.5.1%gcc@6.3.0 arch=cray-cnl5-interlagos/gfvo7l5 because py-geeup@0.2.4%gcc@6.3.0 arch=cray-cnl5-interlagos/ars3mil is activated and depends on it
Traceback (most recent call last):
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 697, in main
    return _invoke_command(command, parser, args, unknown)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 447, in _invoke_command
    return_val = command(parser, args)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/cmd/install.py", line 228, in install
    env.write()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 1290, in write
    self.regenerate_views()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 942, in regenerate_views
    view.regenerate(specs, self.roots())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 495, in regenerate
    view.remove_specs(*rm_specs, with_dependents=False)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/filesystem_view.py", line 419, in remove_specs
    set(map(remove_extension, extensions))
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/filesystem_view.py", line 437, in remove_extension
    remove_dependents=with_dependents)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/package.py", line 2197, in do_deactivate
    self.spec.cshort_spec, aspec.cshort_spec))
spack.package.ActivationError: Cannot deactivate py-psutil@5.5.1%gcc@6.3.0 arch=cray-cnl5-interlagos/gfvo7l5 because py-geeup@0.2.4%gcc@6.3.0 arch=cray-cnl5-interlagos/ars3mil is activated and depends on it
```
On your branch, I get:
```console
$ spack -d install
==> Error: Unexpected: specs are in view but not env
==> Error: The view contains names that aren't in the environment: py-httplib2 py-google-cloud-core py-requests-toolbelt py-poster py-uritemplate py-rsa py-geeadd py-gee-asset-manager py-beautifulsoup4 py-oauth2client libxslt py-lxml py-googleapis-common-protos py-google-resumable-media py-cachetools py-chardet py-clipboard py-pathlib libgpg-error py-google-api-core py-requests py-pyasn1-modules py-urllib3 py-protobuf py-google-auth py-google-cloud-storage py-pyasn1 py-google-auth-httplib2 libgcrypt py-earthengine-api py-pyperclip py-idna py-selenium py-pysmartdl py-future py-google-api-python-client py-psutil py-certifi py-retrying py-geeup
Traceback (most recent call last):
  File "/u/sciteam/stewart1/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 633, in main
    env = ev.find_environment(args)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 263, in find_environment
    return Environment(env)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 565, in __init__
    self._check_views_debug(specs_in_env, view_descriptor.view())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 582, in _check_views_debug
    raise ValueError()
```
Basically, what happened was that I created a `spack.yaml`, installed it, then installed other packages that were added to `spack.yaml`, forgot about them, reset `spack.yaml`, then tried to reinstall.

**Comment by scheibelp** [comment]
Thanks for checking that! Out of curiosity is your `spack.lock` also version-controlled? I get some anomalies but not this error when I mess with `spack.yaml`; reverting `spack.lock` *does* cause this error for me though.

`spack env view regenerate` would address this issue. There's a couple ways to proceed:

* Try to fix it automatically
* Print a warning message that suggests `spack env view regenerate`

I'm still thinking on which makes more sense here.

**Comment by adamjstewart** [comment]
`spack.lock` is not version controlled. I figure that can and should change as Spack changes, but `spack.yaml` should be stable enough to version control.

**Comment by alalazo** [comment]
@scheibelp I'm going through old PRs. Closing this but feel free to reopen if I missed anything.

**Pull request closed without merging**
