### PR TITLE
r-sf may not support PROJ.6

### PR DESCRIPTION
**Pull request by adamjstewart**
Might be supported in the latest release according to https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status, but I can't access the CRAN site to confirm.

### CODE REVIEW

**Comment by citibeth** [comment]
They claim:
> SystemRequirements: | C++11, GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ (>= 4.8.0)

https://cran.r-project.org/web/packages/sf/index.html

Not sure if that means it works with `proj@6`; or if they just haven't updated that line.

**Comment by adamjstewart** [comment]
Ping @citibeth

**Comment by citibeth** [comment]
Have you been able to access the CRAN site to confirm the original question?

**Comment by adamjstewart** [comment]
Yes, as you discovered, it says that `PROJ (>= 4.8.0)` works. Since I don't think it's possible to support both the PROJ.4 and PROJ.6 APIs at the same time, I'm going to assume that PROJ.6 doesn't work.

**Comment by citibeth** [comment]
> Yes, as you discovered, it says that PROJ (>= 4.8.0) works. Since I don't think it's possible to support both the PROJ.4 and PROJ.6 APIs at the same time, I'm going to assume that PROJ.6 doesn't work.

Can you put this in a comment?

**Pull request merged**
