### PR TITLE
update conduit package with conduit 0.3.1 release

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
Any hints on how to resolve the CI failure?

`TEST_SUITE=unit COVERAGE=true` is failing with what seems like a timeout:

```
lib/spack/spack/test/cmd/env.py ....
lib/spack/spack/test/cmd/find.py ....
lib/spack/spack/test/cmd/flake8.py ..
lib/spack/spack/test/cmd/gpg.py .
lib/spack/spack/test/cmd/graph.py .......
lib/spack/spack/test/cmd/help.py x....
lib/spack/spack/test/cmd/info.py ........
lib/spack/spack/test/cmd/install.py .............................
lib/spack/spack/test/cmd/list.py .....
lib/spack/spack/test/cmd/module.py ........
lib/spack/spack/test/cmd/python.py .
lib/spack/spack/test/cmd/test_compiler_cmd.py .share/spack/qa/run-unit-tests: line 31:  8836 Killed     
```

Should I try updating develop on my fork and merging into my branch?

**Comment by healther** [comment]
It's the first time I see this error, closing and reopening in order to see if the error persists

**Comment by alalazo** [comment]
@scheibelp Apparently we are playing Whac-a-Mole with the failure above.

**Comment by alalazo** [comment]
@healther See #7331

**Comment by cyrush** [comment]
@alalazo  thanks!

**Pull request merged**
