### PR TITLE
Update templight pseudo-release to remove need for patching

### PR DESCRIPTION
**Pull request by HadrienG2**
Templight, while very useful, has hopelessly optimistic build requirements. One is supposed to link the master of a mostly stagnant project with unstable APIs of the LLVM trunk and expect that to work. In principle, there are also branches building against old clang versions, but in practice these are quite ancient and did not work last time I checked.

For this reason, when I packaged Templight, I introduced an artificial stable release which pinned the version of every package involved to something which I know to work with a bit of patching. This is an update of this artificial stable release which takes advantages of some updates on the Templight side that make my patching unnecessary.

### CODE REVIEW

**Comment by healther** [comment]
Is there a reason why you removed the old version in the first place?

**Comment by HadrienG2** [comment]
One problem with templight is that there are no upstream releases (you are supposed to pick bleeding-edge commits and cross fingers). So a while ago, I invented one from a non-ideal combination of Templight and LLVM that required patching, in order to at least stabilize something that works.

Today, a better combination that does not require such patching is available. This PR proposes to stabilize that combination. Removing the old "release" is part of the point, as it removes an annoying bit of custom code from spack's maintenance burden. I think it is reasonable to do so in this specific case, since it is not as if I removed spack support for a software release that ever existed in upstream.

**Comment by healther** [comment]
I guess I don't see the point in removing a working version, it's not really a burden, because it _will_ work in the future too. But I don't care too much either way

**Comment by HadrienG2** [comment]
I don't care that much either, honestly. Let's toss a coin or wait a couple of days for another opinion?

**Comment by HadrienG2** [comment]
Ok, no other opinion. Then let's just bring back the old version to get this sorted out ;)

**Pull request merged**
