### PR TITLE
miniamr: added v1.4.1

### PR DESCRIPTION
**Pull request by junghans**
/cc @ctvaugh

### CODE REVIEW

**Comment by bhatele** [comment]
@junghans Should we move from url='' to git='' for this package? And then we just need to provide version numbers and tags like the AMG package?

**Comment by healther** [comment]
> Should we move from url='' to git='' for this package? And then we just need to provide version numbers and tags like the AMG package?

you can do either. But tags are iirc not trusted downloads, i.e. not cachable

**Comment by junghans** [comment]
I just prefer checksummed over tagged versions!

Christoph

**Comment by bhatele** [comment]
Sounds good.

**Pull request merged**
