### PR TITLE
Added go 1.13.1 and 1.12.10

### PR DESCRIPTION
**Pull request by paulbry**
Added latest version of Go that address security issues (https://groups.google.com/forum/#!topic/golang-announce/cszieYyuL9Q)

### CODE REVIEW

**Comment by jcftang** [comment]
Removing the older patch versions should be fine, the golang team are pretty good at keeping backwards compat. So +1 on cleaning it up

**Comment by paulbry** [comment]
Okay, it won't be in the next couple days but I don't mind taking a look and removing the previous releases with security vulnerabilities and associated files.

**Comment by tgamblin** [comment]
@adamjstewart: do we need to remove the old versions?  I’d like lockfiles to continue to work after things are installed.  The new version will still be preferred for new installs.

**Comment by adamjstewart** [comment]
@tgamblin Up to you. Personally I would rather have lockfiles fail, or tell the user they are asking for an unchecksummed version, than to have Spack silently install software with known security vulnerabilities.

**Comment by tgamblin** [comment]
@adamjstewart: the security issues here are for Go servers, which I am guessing are not a common case for spack users. That said, I think it would be good to have a lock file policy that either auto-updates to the latest patch version or warns you. We can’t auto-update to more than a patch version, at least not assuming semver.

One of the priorities with spack is reproducibility so I think we should generally avoid removing old stuff and try to warn.  We should eventually make it so we can mark versions with CVEs, but I don’t think we’re quite there yet.

**Comment by hartzell** [comment]
As a go-user and a guy who supports systems that need to be reproducible; I'd prefer to leave the old versions in place.  We might use caveats (#11244) or tty wanings (#10412) to give the user a heads up.

Go has a pretty aggressive "dropping support for old versions" that they can get away with because of their backward compatibility pledge.

Here's the [Release Policy](https://golang.org/doc/devel/release.html#policy):

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

**Pull request merged**
