### PR TITLE
mfem: add version 4.0 (without cuda)

### PR DESCRIPTION
**Pull request by goxberry**
Adds mfem 4.0.

### CODE REVIEW

**Comment by goxberry** [comment]
Don't merge this until I sort out some issues with the mfem team.

**Comment by v-dobrev** [comment]
We should also address this issue before merging: https://github.com/mfem/mfem/issues/1024.

**Comment by goxberry** [comment]
Renamed version 4.0 to version 4.0.0. Added `occa` and `raja` variants. Adding the `occa` variant required a minor makefile patch (upstream issue documenting bug: https://github.com/mfem/mfem/issues/1042, upstream PR fixing bug: https://github.com/mfem/mfem/pull/1043).

**Comment by goxberry** [comment]
Fixed `flake8` errors.

**Comment by goxberry** [comment]
Reworded last commit so that capitalization is consistent in all commits of this pull request.

**Comment by goxberry** [comment]
cc: @tzanio @v-dobrev @acfisher Would one (or more) of you be willing to review this PR before it is merged?

--------------------

I've tested manually the `occa` and `raja` variants by running MFEM's example 1 with the following options:

```console
$ ./ex1 -pa -d raja-cpu
$ ./ex1 -pa -d occa-cpu
```

In both cases, I see what looks like the expected output, so I think new variants install and link correctly. The latter command throws a memory leak, but running the executable through a debugger leads me to believe that the memory leak is in OCCA, not MFEM, and in any case, I don't think this memory leak is due to the Spack installation.

I haven't tried building many other configurations; I usually build with `mfem~conduit~debug~examples~gnutls+gzstream+hypre~lapack+libunwind+metis~miniapps~mpfr+mpi+netcdf~occa~openmp~petsc~raja+shared~static~suite-sparse~sundials~superlu-dist~threadsafe timer=auto ^hypre+shared ^metis@5.1.0 %clang@10.0.1-apple`, and this configuration seems to work. I've also tried perturbations of this spec:

- toggling `+examples` works
- toggling `+miniapps` works
- toggling `+debug` works
- toggling `+shared`/`+static` works
- toggling `+libunwind` works
- toggling `+netcdf` works

Due to the compiler/OS combination, I can't test CUDA at all, and I can't test OpenMP easily. I think this PR is probably mergeable in its current state, but it would be good to have someone from the MFEM team give this a quick look first before merging.

I'm not sure when I'll get around to adding CUDA. I think the configuration is probably straightforward enough, but I'd need to test on a machine with an NVIDIA GPU -- probably an LC machine. I'd prefer to merge this PR sooner, and defer adding a `cuda` option for a week or two. I also need to get some clarification from the MFEM team on the semantics of an `hpc` variant, because that would seem to overlap with other options.

**Comment by balay** [comment]
I see CI failures
```
___________________________ test_prs_update_old_api ____________________________
<snip>
           failed = (hasattr(pkg, 'setup_environment') or
                      hasattr(pkg, 'setup_dependent_environment'))
<snip>
E       AssertionError: there are 1 packages still using old APIs in this PR [mfem]
E       assert not [<spack.pkg.builtin.mfem.Mfem object at 0x1b066c10>]
package_sanity.py:184: AssertionError
======== 1 failed, 2068 passed, 97 skipped, 2 xfailed in 946.62 seconds ========
The command "share/spack/qa/run-$TEST_SUITE-tests" exited with 1.
```
So `setup_environment` usage in `mfem/package.py` needs to be reworked?

**Comment by balay** [comment]
> So setup_environment usage in mfem/package.py needs to be reworked?
Ah - I see the fix is:

```
index e03a49942..f79c9b236 100644
--- a/var/spack/repos/builtin/packages/mfem/package.py
+++ b/var/spack/repos/builtin/packages/mfem/package.py
@@ -194,7 +194,7 @@ class Mfem(Package):
 
     phases = ['configure', 'build', 'install']
 
-    def setup_environment(self, spack_env, run_env):
+    def setup_build_environment(self, env):
         spack_env.unset('MFEM_DIR')
         spack_env.unset('MFEM_BUILD_DIR')
 

```

**Comment by acfisher** [comment]
@balay Yes I just saw that and pushed a quick change that hopefully will fix it.  I didn't hear about the API change.  Is there a reference on the various API changes that I can keep an eye on?

**Comment by acfisher** [comment]
Yeah the failure looks like a fluke, I'll trigger it again.

**Comment by acfisher** [comment]
That's odd, the coverage has gone down in files we didn't touch for tests we didn't touch.  @balay do you know who we escalate this sort of thing to these days?

**Comment by balay** [comment]
I don't understand the codecov tests. But this doesn't prevent a merge - so this is not a show stopper.

Perhaps this PR is ready for merge.

**Comment by acfisher** [comment]
Yes, I believe it is ready for merge.  Are you empowered to hit the button?

**Comment by balay** [comment]
I can - but hoping one of the spack developers can approve before that.. cc: @adamjstewart

**Comment by acfisher** [comment]
Should I save some time and put the rest of the changes from my other branch in here?

**Comment by balay** [comment]
might aswell add b771af15a7ffb5a4942b97f932695e079ccf940f

**Comment by balay** [comment]
@acfisher looks like you have to trigger the CI again - as it failed again.

**Comment by acfisher** [comment]
Bah, this CI is pretty flaky.  I added b771af1 and triggered it again.  Thanks for spotting that one.

**Comment by acfisher** [comment]
Alright we pass the tests again so this is ready to pull in.

**Pull request merged**
