### PR TITLE
Resolve 'Call' object has no attribute 'id'

### LINKED ISSUE #15079: spack install paraview+python3 prints: Error: 'Call' object has no attribute 'id'
spack spec works fine.

@chuckatkins FYI

<pre>
~/projects/spack (develop $%=)]$ spack install paraview+python3
==> Warning: Missing a source id for opengl@4.5.0
==> Error: 'Call' object has no attribute 'id'
[~/projects/spack (develop $%=)]$ spack spec paraview+python3
Input spec
--------------------------------
paraview+python3

Concretized
--------------------------------
paraview@5.7.0%gcc@7.4.0 build_type=RelWithDebInfo ~cuda cuda_arch=none ~examples~hdf5+mpi+opengl2~osmesa+plugins~python+python3~qt+shared arch=linux-ubuntu18.04-broadwell
    ^bzip2@1.0.8%gcc@7.4.0+shared arch=linux-ubuntu18.04-broadwell
        ^diffutils@3.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libiconv@1.16%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^cmake@3.16.2%gcc@7.4.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
        ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-broadwell
            ^pkgconf@1.6.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^openssl@1.1.1d%gcc@7.4.0+systemcerts arch=linux-ubuntu18.04-broadwell
            ^perl@5.30.1%gcc@7.4.0+cpanm+shared+threads arch=linux-ubuntu18.04-broadwell
                ^gdbm@1.18.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^readline@8.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^zlib@1.2.11%gcc@7.4.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell
    ^expat@2.2.9%gcc@7.4.0+libbsd arch=linux-ubuntu18.04-broadwell
        ^libbsd@0.10.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^freetype@2.10.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libpng@1.6.37%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libjpeg-turbo@2.0.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^nasm@2.14.02%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libtiff@4.0.10%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^xz@5.2.4%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^libxml2@2.9.9%gcc@7.4.0~python arch=linux-ubuntu18.04-broadwell
    ^libxt@1.1.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^kbproto@1.0.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^util-macros@1.19.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libice@1.0.9%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xproto@7.0.31%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xtrans@1.3.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libsm@1.2.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^libx11@1.6.7%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^inputproto@2.3.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libxcb@1.13%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libpthread-stubs@0.4%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libxau@1.0.8%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^libxdmcp@1.1.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^xcb-proto@1.13%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^xextproto@7.3.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^mpich@3.3.2%gcc@7.4.0 device=ch3 +hydra netmod=tcp +pci pmi=pmi +romio~slurm~verbs+wrapperrpath arch=linux-ubuntu18.04-broadwell
        ^findutils@4.6.0%gcc@7.4.0 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=linux-ubuntu18.04-broadwell
            ^autoconf@2.69%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^m4@1.4.18%gcc@7.4.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-broadwell
                    ^libsigsegv@2.12%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^automake@1.16.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^libtool@2.4.6%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^texinfo@6.5%gcc@7.4.0 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-ubuntu18.04-broadwell
        ^libpciaccess@0.13.5%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^netcdf-c@4.7.3%gcc@7.4.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-ubuntu18.04-broadwell
        ^hdf5@1.10.6%gcc@7.4.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu18.04-broadwell
    ^opengl@4.5.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^py-matplotlib@3.1.3%gcc@7.4.0~animation backend=agg +image~latex~movies arch=linux-ubuntu18.04-broadwell
        ^py-cycler@0.10.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^py-setuptools@41.4.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                ^python@3.7.6%gcc@7.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-broadwell
                    ^gettext@0.20.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-broadwell
                        ^tar@1.32%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^libffi@3.2.1%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
                    ^sqlite@3.30.1%gcc@7.4.0~column_metadata+fts~functions~rtree arch=linux-ubuntu18.04-broadwell
            ^py-six@1.12.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-kiwisolver@1.1.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-numpy@1.18.1%gcc@7.4.0+blas+lapack arch=linux-ubuntu18.04-broadwell
            ^openblas@0.3.8%gcc@7.4.0~consistentFPCSR~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-broadwell
            ^py-cython@0.29.14%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-pillow@7.0.0%gcc@7.4.0~freetype~jpeg2000~lcms~tiff~webp~webpmux arch=linux-ubuntu18.04-broadwell
        ^py-pyparsing@2.4.2%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
        ^py-python-dateutil@2.8.0%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
            ^py-setuptools-scm@3.3.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
    ^py-mpi4py@3.0.3%gcc@7.4.0 arch=linux-ubuntu18.04-broadwell
</pre>

### PR DESCRIPTION
**Pull request by tldahlgren**
Fixes #15079 
Duplicates #14763 

Added an extra check to handle a nested `Call` expression in the AST when processing package directives for some packages (e.g., opengl).

### CODE REVIEW

**Comment by scheibelp** [comment]
See also: https://github.com/spack/spack/pull/14763 and https://github.com/spack/spack/issues/14735

(#14763 resolves the issue/s in the same way, but also adds a test)

**Comment by tldahlgren** [comment]
> See also: #14763 and #14735
> 
> (#14763 resolves the issue/s in the same way, but also adds a test)

Oh.  I was in a rush to fix the error and didn't see these issues.  Should we add the comments from this PR (or the equivalent) to #14763 and close this one as a duplicate?

**Comment by scheibelp** [comment]
> Should we add the comments from this PR (or the equivalent) to #14763

I personally found it difficult to explain clearly in the function docstring. IMO the comment is useful but might be clearest if it is added as a comment to the test (since it highlights the scenario where the directive detection logic needs to be careful).

**Comment by tldahlgren** [comment]
> > Should we add the comments from this PR (or the equivalent) to #14763
> 
> I personally found it difficult to explain clearly in the function docstring. IMO the comment is useful but might be clearest if it is added as a comment to the test (since it highlights the scenario where the directive detection logic needs to be careful).

I've worked with ASTs before so I'm fine either way though it is nice to provide a docstring. 

Since it was important to you, what do you think @becker33 ?

**Comment by scheibelp** [comment]
I merged https://github.com/spack/spack/pull/14763 so I am now closing this.

**Pull request closed without merging**
