### PR TITLE
adding GlobalArrays package

### PR DESCRIPTION
**Pull request by tjstavenger-pnnl**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Spack already has a `globalarrays` package.

**Comment by tjstavenger-pnnl** [comment]
Sorry -- I should have paid closer attention. The ga package I made has the options / variants we'd like to include. I'm guessing the preferred approach would be for a new PR with modifications to the existing globalarrays pacakge?

**Comment by adamjstewart** [comment]
Correct.

**Comment by tjstavenger-pnnl** [comment]
The two package use different build tools -- cmake from the globalarrays package and autotools for my PR. The existing globalarrays package also focuses on the IBM XL compilers. I would think I could work through the compiler difference with variants, but I'm not sure on the build tool difference. What is Spack's policy on when separate packages are required?

**Pull request closed without merging**
