### PR TITLE
Updating py-pillow with change in checksum for version 5.1.0.

### PR DESCRIPTION
**Pull request by jrood-nrel**
Rather than create a new version, they changed the 5.1.0 source file?

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you just confirm with the devs that this change was intentional and they haven't been hacked?

**Comment by jrood-nrel** [comment]
Sure, we'll see if they respond to this https://github.com/python-pillow/Pillow/issues/3199

**Comment by jrood-nrel** [comment]
They responded with an explanation stating that it shouldn't have changed. Well, maybe I've been testing a hacked archive then. I'll try to find out what's going on.

**Comment by jrood-nrel** [comment]
@s-sajid-ali Can you comment on this? I'm not so sure the checksum for this was initially correct for 5.1.0 if the file wasn't able to change on the pypi.io site.

**Comment by jrood-nrel** [comment]
I'm getting `cee9bc75bff455d317b6947081df0824a8f118de2786dc3d74a3503fd631f4ef` for the downloaded archive for 5.1.0 from spack with this PR, which is the same as what is listed on the pypi pillow site and confirmed in the linked issue I posted on their github. I'm confident the correct checksum is in this PR, but just confused about where the original one came from.

**Comment by s-sajid-ali** [comment]
I might have made a mistake then. Apologies for the incorrect checksum .

**Comment by adamjstewart** [comment]
I find it hard to believe that no one else noticed that the `py-pillow` checksum was wrong for a whole month, but who knows. I did know that PyPI doesn't let you reupload, so there's no way for a checksum to change. @s-sajid-ali can you check your Spack downloads cache to see if the tarball is still lying around? If I had to guess, maybe you manually downloaded and added the checksum for the `.zip` instead of the `.tar.gz`.

I can also do a diff of the last two versions just to make sure there are no viruses in there 😛

**Comment by s-sajid-ali** [comment]
Could be. I've removed the file during a ```spack clean (maybe -a)```sometime I guess.

**Comment by adamjstewart** [comment]
Mystery solved. The checksum that was in the package is the checksum from the GitHub tarball, not the PyPI tarball.

**Comment by s-sajid-ali** [comment]
Will keep this in mind next time.

**Comment by adamjstewart** [comment]
Yeah, so when you upload tarballs to PyPI, it only uploads the bare minimum of files necessary to install the package, not unit tests or travis/flake8/git config files. That's why the checksums never match.

**Pull request merged**
