### PR TITLE
Add PLASMA version 18.11.0 and Lua variant

### PR DESCRIPTION
**Pull request by luszczek**
Add PLASMA version 18.11.0 and Lua variant

### CODE REVIEW

**Comment by balay** [comment]
@luszczek, I was expecting code of type:

```
if '+lua' in self.spec:
  enable lua and specify include/libs via cmake
else:
  disable lua via cmake
```
Right now  'spack install plasma~lua` is doing:

```
-- Found Lua: /usr/lib64/liblua-5.3.so;/usr/lib64/libm.so (found version "5.3.5")
```

**Comment by luszczek** [comment]
It seems you have Lua integrated in your system. PLASMA picks it as intended. If Lua was missing, PLASMA would gracefully fall back to no-Lua configuration, by design.
There is no functionality in PLASMA to actively avoid Lua even it is an integral part of the system. Spack variant that enables Lua is meant to inform Spack that should provide Lua to PLASMA. You could imagine switching versions of Lua that Spack makes available to PLASMA when this variant is enabled.

**Comment by balay** [comment]
I hope you reconsider the design and provide a cmake option to disable Lua check.

 Either Lua is optional or mandatory.

If optional - it should be truly optional. i.e when user asks plasma~lua - it should not pick it up from user enviornment - just because it could find it..

**Comment by scheibelp** [comment]
@luszczek is there a reason to add a variant if PLASMA always needs LUA? Do you prefer to use the system-provided LUA if it's available? For that you can use an external packages (
https://spack.readthedocs.io/en/latest/build_settings.html#external-packages) although if you find that onerous, we can be flexible. I think it's worth knowing why you prefer it that way though.

**Comment by luszczek** [comment]
Lua has been optional since version 17 so I made detection of Lua optional and fully controlled by Spack. Choosing a Lua variant in Spack will make the build fail if Lua is missing. External Lua installations from system directories will not be detected unless building with Lua variant.

**Comment by balay** [comment]
works for me (checked on one of the builds with system lua installed - and plasma is not picking it anymore with ~lua) - so merging this in.

**Comment by luszczek** [comment]
Thank you!

**Pull request merged**
