### PR TITLE
Packages/trilinos

### PR DESCRIPTION
**Pull request by DarylGrunau**
This PR enables variant +fortrilinos for all of its released versions.  @aprokop, @keitat would mind taking a look as well as maintainers?

### CODE REVIEW

**Comment by DarylGrunau** [comment]
I personally don't need to provide ForTrilinos for all of these Trilinos versions; I only really care about the 12.12.1 version - and happy to remove the rest at your bidding.  I've been successful building and using the variant in my environment.  I got the checksums for all of these ForTrilinos releases at https://github.com/trilinos/ForTrilinos/releases ...

**Comment by aprokop** [comment]
Hmm, OK, let me take another look.

**Comment by DarylGrunau** [comment]
@aprokop, @keitat any status on this?  Please also see issue #12045 as I may need to enable `+fortrilinos` for a downrev version of Trilinos (12.10.1).

**Comment by DarylGrunau** [comment]
Stalled, closing ...

**Pull request closed without merging**
