### PR TITLE
Paraview: fix PYTHONPATH for static build.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@chuckatkins Please review

**Comment by chuckatkins** [comment]
Is this dependent on a minimum version of paraview?  The zip packaging is a relatively new feature I believe.

**Comment by danlipsa** [comment]
@chuckatkins Good point. Indeed, this only works on master and later. So I added that check.

**Comment by danlipsa** [comment]
@chuckatkins can we merge this?

**Pull request merged**
