### PR TITLE
py-pybedtools: adding new package

### PR DESCRIPTION
**Pull request by peetsv**
pybedtools is a Python package that wraps BEDTools

### CODE REVIEW

**Comment by peetsv** [comment]
Prerequisite for MetaSV.

**Comment by peetsv** [comment]
I have to acknowledge that this pull request is nearly identical to #6487  There is an "operational difference" (if I can coin a phrase) is that I need this as a prerequisite for another package, specifically MetaSV.  @healther listed a number of optional dependencies that should likely be added to the recipe as available variants, but are they all necessary right now or can they wait for further consideration?

**Comment by peetsv** [comment]
Slightly off topic --- I am interested in the codecov/project check results but having trouble deciphering the detail information.  Could someone take pity on a novice and point me to more comprehensible documentation/explanation, please?

**Comment by adamjstewart** [comment]
> I am interested in the codecov/project check results but having trouble deciphering the detail information.

Ignore Codecov. We don't check coverage for package.py files. If you only modified package.py files, we won't care about codecov. What happened was that you created this PR, then develop was updated with greater coverage (yay!) and now your branch has worse coverage because it is older. If you really want to get it to pass (not necessary) you can rebase off of the latest develop.

**Comment by adamjstewart** [comment]
Closing this in favor of #6487 as it came first and is much closer to having a complete list of dependencies.

**Pull request closed without merging**
