### PR TITLE
Feature/zsh completion

### PR DESCRIPTION
**Pull request by Falkor**
I was tired during the SC'16 tutorial to type all spack commands manually. So I decided to make a zsh completion file. As this is something new to me, it took me more time than planned and there are many rooms for improvement (in particular to handle automagically the specs) but I hope it would still be useful for the community.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Hi @Falkor, this looks very useful! I actually created a bash completion file back in the day (see #459), but it wasn't accepted into Spack for various reasons. The main reason being that Spack is still under active development, and every time a new command is added or option flags are changed or renamed, it would need to be updated. Of course, I still use it every day and it works great for me. @tgamblin and I discussed this, and we think the best option moving forward would be to use [argcomplete](https://argcomplete.readthedocs.io/en/latest/), a Python module that works together with argparse to determine what possible completions to use. This would have the benefit of working in all shells, and would allow complex spec analysis when doing a completion. See #459 for further discussion.

**Comment by Falkor** [comment]
OK, but unless I'm wrong, [argcomplete](https://argcomplete.readthedocs.io/en/latest/), [genzshcomp](https://pypi.python.org/pypi/genzshcomp/) (I used to generate this completion file) and just like equivalent gems in the ruby world (I'm more familiar with) such as [thor-zsh_completion](https://github.com/labocho/thor-zsh_completion) does not render a full proof scheme after executions -- you always had to manually reparse the generated output as it is hard for it to catch subtilities on the commands generation. 
Anyway, as I said, I just found it useful for the community, if you or Todd found it useless until the CLI layout is fixed, just drop it ;) But as far as I can tell you as a new user, even an imperfect bash/zsh completion is better than nothing, especially if the CLI is so vast and diverse as for spack.

**Comment by tgamblin** [comment]
Hi @Falkor: Sorry for the long delay on responding to this!  I think this could be very useful; thanks for submitting it!

Is this ready to merge as-is or do you want to update things per @adamjstewart's #3026?

**Comment by tgamblin** [comment]
Sourcing this should probably be added somewhere in `share/spack/setup-env.sh`.

**Comment by adamjstewart** [comment]
And it should probably be in the same directory. At least that's where I put mine.

**Comment by Falkor** [comment]
I guess it can be merged as is. Compared to #3026, it add support for most `--*` options so it should be still useful. 
As for usage instruction, it does not need to be sourced, if I'm not wrong it is better to complete the `fpath` variable of zsh with the directory holding `_spack`, as follows: 

```bash
fpath=(path/to/spack/contrib/completion $fpath) # OR fpath=(path/to/spack/share/spack/zsh $fpath)
```

Thus I would suggest to complete `setup-env.sh` with something like: 

```bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# [...]
if [[ -n ${ZSH_VERSION-}  ]]; then
    fpath=("${SCRIPTDIR}" $fpath)
    spack_zsh_completion_reload() {
       unfunction _spack && autoload -U _spack
    }
fi

```

**Comment by tgamblin** [comment]
And thanks again to @Falkor for submitting this!

**Comment by adamjstewart** [comment]
I would try to tweak this, but I don't really know `zsh` at all. A few commands probably need to be updated though.

**Comment by adamjstewart** [comment]
@Falkor I'm going to close this PR as most of the commands and their flags are quite out of date. In the meantime, we've merged #14393 which provides a way to automatically generate most of the tab completion script. If you or anyone else want to submit a new PR to add zsh support, use #14393 as a reference and let me know if you have any questions. It _should_ be as simple as adding a `share/spack/zsh/spack-completion.in` script and a `ZshCompletionWriter` in `lib/spack/spack/cmd/commands.py`.

**Comment by Falkor** [comment]
@adamjstewart sure, no problem and thx for the last guidelines.

**Pull request closed without merging**
