### PR TITLE
First fix for SPACK_DEPENDENCIES problem when doing setup

### PR DESCRIPTION
**Pull request by cedricchevalier19**
Tentative Fix for #10714.

### CODE REVIEW

**Comment by becker33** [comment]
If you change `SPACK_TRANSITIVE_INCLUDE_DIRS` to `SPACK_INCLUDE_DIRS` everywhere you should be able to have the same effect without losing functionality, and you can still delete the function causing the problem. Spack computes in other places the same thing that function was designed to compute.

**Comment by germasch** [comment]
So I'm not sure what the right fix is, either, but i'm hitting the same problem, ie., `spack setup <pkg>` not working because it'll complain about `SPACK_DEPENDENCIES` (and not with a very helpful error message).

```sh
==> Generating spconfig.py [camtimers@local%gcc@7.5.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-haswell/prvk35b]
==> Error: 'SPACK_DEPENDENCIES'
```

FWIW, a workaround is to `export SPACK_DEPENDENCIES=""` first. But it looks like `SPACK_DEPENDENCIES` has been removed a long time ago except in this one place. I don't know what the correct fix is -- this one here looks like it'll fix the problem for me. I could also instead make a PR that just handles `SPACK_DEPENDENCIES` not being set in the environment gracefully, though that seems more like a workaround rather than a fix.

**Comment by becker33** [comment]
@cedricchevalier19 @germasch I suggest replacing `SPACK_INCLUDE_DIRS` with `SPACK_TRANSITIVE_INCLUDE_DIRS` everywhere it appears in `$spack/lib/spack/spack/cmd/setup.py`, in addition to the changes already in this branch. If you can push that to this branch, I can review it and get it merged.

**Comment by cedricchevalier19** [comment]
Now `spack setup` properly exports `SPACK_INCLUDE_DIRS` into `spconfig.py`.

**Pull request merged**
