### PR TITLE
charmpp: fix build failing from broken hardlink

### PR DESCRIPTION
**Pull request by codeandkey**
This package currently fails to build due to a broken hard link `/doc` causing errors after the package install. This patches the recipe to check for a broken link and replace it with an empty directory if needed.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Need to replace `setup_dependent_environment` with `setup_dependent_build_environment`

**Comment by adamjstewart** [comment]
Now that #13924 has been merged, all you need to do is rebase your branch on the current develop branch.

**Comment by adamjstewart** [comment]
Ping @codeandkey, just needs a rebase.

**Comment by codeandkey** [comment]
My git says that the branch is already up-to-date with develop, so I manually added the change.

**Comment by adamjstewart** [comment]
> My git says that the branch is already up-to-date with develop

Git always says that unless you run `git fetch` or `git pull` to update its knowledge of upstream develop.

**Comment by adamjstewart** [comment]
Restarted the build tests, hopefully the caches aren't corrupted again...

**Pull request merged**
