### PR TITLE
cube: Fix configure invocation.

### PR DESCRIPTION
**Pull request by diaena**
The config was picking up the wrong compiler

### CODE REVIEW

**Comment by alalazo** [comment]
@adamjstewart is correct in his review. @diaena : what was the problem you encountered when using the wrappers?

**Comment by diaena** [comment]
Right, so the build output says it's building my source using gcc even though I have explicitly told it to use a version of clang (using the command spack --verbose install cube%clang@1.3):

> // build output
=== configuring in build-backend (/tmp/diaena/spack-stage/spack-stage-JJXkij/cube-4.3.4/build-backend)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/home/diaena/spack-github/opt/spack/linux-opensuse20161010-aarch64/clang-1.3/cube-4.3.4-dzqqqhocuwl2ngd5gxyhywwr4ddxiroy'  'FC=gfortran' 'F77=gfortran' 'CC=gcc' 'CXX=g++' '--without-gui' '--without-paraver' 'ac_scorep_platform=arm' 'ac_scorep_cross_compiling=no' --cache-file=/dev/null --srcdir=.
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
// more build output'

**Comment by tgamblin** [comment]
@daboehme: can you take a look at this one?

**Comment by daboehme** [comment]
The Score-P derived autoconfig scripts use a customized and rather complex compiler setup that doesn't really play well with spack's compiler wrappers. I'll look into it.

**Comment by tgamblin** [comment]
@daboehme: thanks

**Comment by adamjstewart** [comment]
Ping @daboehme. Any updates?

**Comment by daboehme** [comment]
Not yet - will look back into it. For now I recommend to build with gcc. 

To fix it we'll have to set the `--with-nocross-compiler-suite` option to the right suite depending on the spack selection, and then it expects to find the compilers in `PATH` under their original name (e.g., `icc`/`icpc` for intel or `clang`/`clang++` for clang). If that doesn't work we'll have to try the `--with-custom-compilers` option, and that might be more tricky.

**Comment by alalazo** [comment]
Closing as stale since a long time. Feel free to reopen if this is still an issue and you want to proceed further with the PR.

**Pull request closed without merging**
