### PR TITLE
mesa: re-written to new meson build system 

### PR DESCRIPTION
**Pull request by chuckatkins**
- Re-write mesa package to use the new meson build system
- Drop backward compatibility with old mesa versions since meson wasn't reliably usable for the spack use cases of mesa until this release.
- Express the swr driver as a variant
- Additionally add the glx and glu virtual packages since they can be provided by a vendor's binary driver.
- Drop the hardware drivers for now (they can be added later, but I don't believe there's much of a use case at the moment)
- Rework downstream dependees to accommodate the changes.

Also supersedes #11301

### CODE REVIEW

**Comment by chuckatkins** [comment]
I believe we've got all the pieces to this but since it's somewhat disruptive then I'll be sure that myself and @opadron are responsive to any downstream issues that crop up because of this over the next few weeks.

**Comment by opadron** [comment]
@chuckatkins Looks like all virtual packages are checked for a default provider, and `egl` does not have one?  Should it?

**Comment by chuckatkins** [comment]
Let's just go ahead and drop the egl virtual package entirely for now since it's really more involved and out of scope.  We'll need a separate pr to start dealing with the associated infrastructure and how that plays with glvnd.

**Comment by opadron** [comment]
@alalazo @adamjstewart how strict are we about the failing codecov check?  I'm not sure what to do about it since the codecov page with the details does not load for me.

This is ready for merge, otherwise.

**Comment by ax3l** [comment]
cc @briedel in case you want to double-check the geant4 changes

**Comment by opadron** [comment]
I went ahead and tried installing `geant4 %gcc@7 +opengl cxxstd=11`.  I'm not sure how I'd go about testing the build, but I can say that everything built and installed without any issues.

**Comment by opadron** [comment]
Since the changes are approved, and I was able to build geant4 without any issues.  I'm going ahead with the merge.  We'll keep an eye out for any issues with downstream packages.

**Comment by odoublewen** [comment]
Hello.  I have a nightly build of spack packages that my company uses, and last night it broke on the mesa package.  I don't have a lot of time to dig into this right now, but I thought I'd at least report it.

```
==> Installing mesa
==> Searching for binary cache of mesa
==> Finding buildcaches in /bifx/apps/spack/mirror/build_cache
==> No binary for mesa found: installing from source
==> Cloning git repository: https://gitlab.freedesktop.org/mesa/mesa.git at tag mesa-19.0.0
==> No checksum needed when fetching with git
==> Already staged mesa-19.0.0-xdal4fbjqmrinv36x56uu4k7d6rmejwj in /tmp/bioinfo-cimr-worker-dir/workspace/bfx_spacktree_develop/spack/var/spack/stage/mesa-19.0.0-xdal4fbjqmrinv36x56uu4k7d6rmejwj
==> No patches needed for mesa
==> Building mesa [MesonPackage]
==> Executing phase: 'meson'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j36' '-v'
```

The build log is 1000+ lines long, and I don't immediately see a smoking gun.  This is using gcc-8.2.0 & ninja-1.9.0

Please let me know how I can help.

**Comment by chuckatkins** [comment]
@odoublewen Thanks for the report.  What platform is this on (centos7, sles12, etc.)?  Are you building the default spec or are you using any particular variants or constraints?

**Comment by opadron** [comment]
Just to offer another data point, I tried installing

```
mesa @19.0.0 %gcc@8 ^ninja@1.9.0
```

on a `centos7` system, and didn't run into any build problems.

**Comment by odoublewen** [comment]
It is centos7, as I should have mentioned.

And yes, we do specify both variants and constraints.  The intersection of our `packages.yaml` file and the output of `spack spec mesa` are these three items (as far as I can tell by eyeballing it):

```
  pcre:
    variants: +jit
  perl:
    version: [5.26.2]
  python:
    version: [3.6.5]
```

Here's the full output of `spack spec mesa`:

```
Input spec
--------------------------------
mesa

Concretized
--------------------------------
mesa@19.0.0%gcc@8.2.0 buildtype=release +glx+llvm+opengl~opengles+osmesa swr=none arch=linux-centos7-x86_64
    ^binutils@2.31.1%gcc@8.2.0+gold~headers~libiberty+nls~plugins arch=linux-centos7-x86_64
        ^gettext@0.19.8.1%gcc@8.2.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-centos7-x86_64
            ^bzip2@1.0.6%gcc@8.2.0+shared arch=linux-centos7-x86_64
                ^diffutils@3.7%gcc@8.2.0 arch=linux-centos7-x86_64
            ^libxml2@2.9.8%gcc@8.2.0~python arch=linux-centos7-x86_64
                ^libiconv@1.15%gcc@8.2.0 arch=linux-centos7-x86_64
                ^pkgconf@1.6.0%gcc@8.2.0 arch=linux-centos7-x86_64
                ^xz@5.2.4%gcc@8.2.0 arch=linux-centos7-x86_64
                ^zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-centos7-x86_64
            ^ncurses@6.1%gcc@8.2.0~symlinks~termlib arch=linux-centos7-x86_64
            ^tar@1.31%gcc@8.2.0 arch=linux-centos7-x86_64
    ^expat@2.2.5%gcc@8.2.0+libbsd arch=linux-centos7-x86_64
        ^libbsd@0.9.1%gcc@8.2.0 arch=linux-centos7-x86_64
    ^libx11@1.6.7%gcc@8.2.0 arch=linux-centos7-x86_64
        ^inputproto@2.3.2%gcc@8.2.0 arch=linux-centos7-x86_64
            ^util-macros@1.19.1%gcc@8.2.0 arch=linux-centos7-x86_64
        ^kbproto@1.0.7%gcc@8.2.0 arch=linux-centos7-x86_64
        ^libxcb@1.13%gcc@8.2.0 arch=linux-centos7-x86_64
            ^libpthread-stubs@0.4%gcc@8.2.0 arch=linux-centos7-x86_64
            ^libxau@1.0.8%gcc@8.2.0 arch=linux-centos7-x86_64
                ^xproto@7.0.31%gcc@8.2.0 arch=linux-centos7-x86_64
            ^libxdmcp@1.1.2%gcc@8.2.0 arch=linux-centos7-x86_64
            ^xcb-proto@1.13%gcc@8.2.0 arch=linux-centos7-x86_64
        ^perl@5.26.2%gcc@8.2.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-x86_64
            ^gdbm@1.18.1%gcc@8.2.0 arch=linux-centos7-x86_64
                ^readline@7.0%gcc@8.2.0 arch=linux-centos7-x86_64
        ^xextproto@7.3.0%gcc@8.2.0 arch=linux-centos7-x86_64
        ^xtrans@1.3.5%gcc@8.2.0 arch=linux-centos7-x86_64
    ^libxext@1.3.3%gcc@8.2.0 arch=linux-centos7-x86_64
    ^llvm@8.0.0%gcc@8.2.0+all_targets build_type=Release +clang+compiler-rt+gold+internal_unwind+libcxx~link_dylib+lld+lldb+polly~python~shared_libs arch=linux-centos7-x86_64
        ^cmake@3.14.2%gcc@8.2.0~doc+ncurses+openssl~ownlibs~qt arch=linux-centos7-x86_64
            ^curl@7.63.0%gcc@8.2.0~darwinssl~libssh~libssh2~nghttp2 arch=linux-centos7-x86_64
                ^openssl@1.1.1b%gcc@8.2.0+systemcerts arch=linux-centos7-x86_64
            ^libarchive@3.3.2%gcc@8.2.0 arch=linux-centos7-x86_64
                ^lz4@1.9.0%gcc@8.2.0 arch=linux-centos7-x86_64
                ^lzo@2.10%gcc@8.2.0 arch=linux-centos7-x86_64
                ^nettle@3.4%gcc@8.2.0 arch=linux-centos7-x86_64
                    ^gmp@6.1.2%gcc@8.2.0 arch=linux-centos7-x86_64
                        ^autoconf@2.69%gcc@8.2.0 arch=linux-centos7-x86_64
                            ^m4@1.4.18%gcc@8.2.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-x86_64
                                ^libsigsegv@2.11%gcc@8.2.0 arch=linux-centos7-x86_64
                        ^automake@1.16.1%gcc@8.2.0 arch=linux-centos7-x86_64
                        ^libtool@2.4.6%gcc@8.2.0 arch=linux-centos7-x86_64
            ^libuv@1.25.0%gcc@8.2.0 arch=linux-centos7-x86_64
            ^rhash@1.3.5%gcc@8.2.0 arch=linux-centos7-x86_64
        ^libedit@3.1-20170329%gcc@8.2.0 arch=linux-centos7-x86_64
        ^perl-data-dumper@2.173%gcc@8.2.0 arch=linux-centos7-x86_64
        ^py-lit@0.7.1%gcc@8.2.0 arch=linux-centos7-x86_64
            ^py-setuptools@40.8.0%gcc@8.2.0 arch=linux-centos7-x86_64
                ^python@3.6.5%gcc@8.2.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter~ucs4~uuid+zlib arch=linux-centos7-x86_64
                    ^libffi@3.2.1%gcc@8.2.0 arch=linux-centos7-x86_64
                    ^sqlite@3.26.0%gcc@8.2.0~functions arch=linux-centos7-x86_64
        ^swig@3.0.12%gcc@8.2.0 arch=linux-centos7-x86_64
            ^pcre@8.42%gcc@8.2.0+jit+multibyte+utf arch=linux-centos7-x86_64
    ^meson@0.49.1%gcc@8.2.0+ninjabuild patches=d5b992925e9a927cc57d33b9ed7e61c80df9a9131d45888fbea19adcd4134e12 arch=linux-centos7-x86_64
        ^ninja@1.9.0%gcc@8.2.0 arch=linux-centos7-x86_64
    ^py-mako@1.0.4%gcc@8.2.0 arch=linux-centos7-x86_64
        ^py-markupsafe@1.0%gcc@8.2.0 arch=linux-centos7-x86_64
```

**Comment by odoublewen** [comment]
I'm checking now to see if I can recreate the error with a minimal spec file....  Will update later today.

**Comment by odoublewen** [comment]
I confirm that I get the same build error after starting from a new spack clone with vanilla configuration, running these commands:

```
spack install gcc@8.2.0
spack compiler add --scope site $(spack location -i gcc@8.2.0)
spack install mesa @19.0.0 %gcc@8.2.0 ^ninja@1.9.0 ^pcre+jit ^perl@5.26.2 ^python@3.6.5
```

**Comment by odoublewen** [comment]
OK, I think found the (at least proximal) cause:

```
  >> 1043    ../src/gallium/state_trackers/glx/xlib/glx_api.c:39:10: fatal error: GL/glxproto.h: No such file or directory                                                                                           
     1044     #include <GL/glxproto.h>                                                                                                                                                                               
     1045              ^~~~~~~~~~~~~~~                                                                                                                                                                               
     1046    compilation terminated.   
```

**Comment by ax3l** [comment]
@opadron @chuckatkins feel free to see @hartzell 's proposed fix in #11360 :)

**Pull request merged**
