### PR TITLE
omega-h: update gcc conflict - as the issue is fixed in gcc-8.3.1

### PR DESCRIPTION
**Pull request by balay**
cc: @ibaned

### CODE REVIEW

**Comment by ibaned** [comment]
@balay I think the master/develop branch will compile with all GCC 8 versions, I worked around the bug in earlier GCC versions. I don't know if conflicts can depend on the Omega_h version too?

**Comment by balay** [comment]
Sure - I think we can do that. What versions range should we use? For ex: the following will add the conflict to version 9.19.1 and lower [assuming the fix will be in the next release - 9.19.2 or 9.20]

```
    conflicts('%gcc@8:8.2.99', when='@:9.19.1)                                                                                                        
```
Or if its only all 9.19 versions - we can do:
```
    conflicts('%gcc@8:8.2.99', when='@9.19:9.19.99)                                                                                                        
```

**Comment by ibaned** [comment]
It looks like `9.22.2` is the Omega_h version where I fixed the GCC 8 build, but there isn't CI to check this yet so we should be cautious.

**Comment by balay** [comment]
Thanks! 9.22.2 works  and 9.15.0 [oldest version listed in spack] fails - so updated the conflict accordingly.

Also added new version entry for 9.22.2

**Pull request merged**
