### PR TITLE
Add flecsi-deps

### PR DESCRIPTION
**Pull request by ktsai7**

### CODE REVIEW

**Comment by chuckatkins** [comment]
What's the reason for having a distinctly separate package for the `flecsi` dependencies instead of just using the dependencies encoded in the `flecsi` package?

**Comment by junghans** [comment]
We are trying to do something like `spack install flecsi-deps && spack load -r flecsi-deps` to setup an environment for developers. I know we could replace the former command by `spack install —only=dependencies flecsi`, but what about the latter?

**Comment by chuckatkins** [comment]
> We are trying to do something like `spack install flecsi-deps && spack load -r flecsi-deps` to setup an environment for developers. I know we could replace the former command by `spack install —only=dependencies flecsi`, but what about the latter?

Would `spack build-env flecsi bash` do the trick?

**Comment by ktsai7** [comment]
I’ll test this out when I get around to it.

**Comment by chuckatkins** [comment]
Marked "don't merge" pending verification that existing spack capabilities already address the use case for this package.

**Pull request closed without merging**
