### PR TITLE
initial version of Dockerfile and README

### PR DESCRIPTION
**Pull request by ChristianKniep**
Attending the tutorial at the SC17, I had to create a dockerfile for it.

With this one can play around with spack on a (non-Linux) Laptop. Thus nice for tutorial.
But also nice to create the same output. The resulting install-directory could be extracted and put everywhere.

Furthermore, by using multi-step builds it could be introduced to other Docker images.
And that's just scratching the surface.

### CODE REVIEW

**Comment by ax3l** [comment]
Hi, have you seen the doc section [Workflows: Using Spack to Create Docker Images](https://spack.readthedocs.io/en/latest/workflows.html#using-spack-to-create-docker-images) already? :)

**Comment by ChristianKniep** [comment]
I would like to use spack in a layered fashion, so that I can build a DAG in which each node is a Docker image. That's how I install osu-micro-benchmark e.g..
https://github.com/qspack/u1604-osu-micro-benchmarks

But let me settle this thought a bit more.

**Comment by ax3l** [comment]
In case it helps you, here is a list of dockerfiles partitioning images with spack: https://github.com/ax3l/dockerfiles/tree/master/spack

We will soon also provide official spack base images in https://hub.docker.com/u/spack/

**Comment by ax3l** [comment]
> Attending the tutorial at the SC17, I had to create a dockerfile for it.

@ChristianKniep for the SC17 tutorial, @alalazo already provided a docker image. See the one here: https://spack.readthedocs.io/en/latest/tutorial_modules.html#setup-for-the-tutorial

**Comment by alalazo** [comment]
Closing this since Spack provides ready-to-go images since a while: https://hub.docker.com/orgs/spack/repositories

**Pull request closed without merging**
