### PR TITLE
Add -d option to diy to specify source path move -j to common args

### PR DESCRIPTION
**Pull request by krafczyk**
It seems that #5043 is currently stalled which was the primary location changes from #2771 were supposed to go.

Rather than continue this, I've made a new PR with these changes adopted to the current `develop` branch.

Once this is merged, I'll close #2771.

### CODE REVIEW

**Comment by krafczyk** [comment]
@luigi-calori this is PR #2771 adopted to the current `develop` branch. If you're still interested in using these changes.

**Comment by luigi-calori** [comment]
Thank you very much, I' m currently using it and would like it to be merged

**Comment by krafczyk** [comment]
@tgamblin This change has been sitting around for a while, it sounds like it's useful, can we get it merged?

**Comment by luigi-calori** [comment]
I' m currently using and confirm it works. Would like it to be merged, It seems that codecov test are failing: any idea how to fix?

**Comment by luigi-calori** [comment]
Sorry to bother but this is conflicting again. Any hope to have it merged?

I'm specifically using the ability to specify a source folder
(I want to do development work inside a git working copy:  the code is composed of python scripts, the "install" in dev mode is just a symlink to sources)

Is there a workaround like specifying install --source with git deployment? 
my current workflow is:

git clone <my_git_url> <my_package_working_copy>
spack diy -d <my_package_working_copy> my_package 

Thanks for any hints

**Comment by krafczyk** [comment]
@luigi-calori I'm not aware of other methods to use an external directory as a source code location from which spack builds a package.

I've been waiting for folks to merge this, but they haven't gotten around to it..

I'll bother them again.

**Comment by krafczyk** [comment]
@tgamblin @alalazo Can we get this merged yet? Its been quite some time and people such as myself and @luigi-calori use it in our workflows.

**Comment by adamjstewart** [comment]
Sorry it's taken so long to get this merged! Feel free to ping me on any other old PRs lying around. I don't normally like to merge non-package-related PRs myself, but it sounds like a lot of people are using this one, so I'm not too worried.

**Pull request merged**
