### PR TITLE
cmake: change optimization flags for fj@4.0.0

### PR DESCRIPTION
**Pull request by t-karatsu**
https://github.com/spack/spack/pull/14414
With this pull request, binaries are optimized for release builds, and the following optimization flags are now referenced when using Fujitsu compiler. 
```
spack-src/Modules/Compiler/GNU.cmake
  string(APPEND CMAKE_${lang}_FLAGS_RELEASE_INIT " -O3 -DNDEBUG")
```
However Fujitsu compiler@4.0.0 can' t build `cmake` with `-O3` optimization flags, because it got following error.
```
[ 22%] Building C object Tests/RunCMake/CMakeFiles/pseudo_cppcheck.dir/pseudo_cppcheck.c.o
/～/libLLVMSupport.so.6(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x28)[0xffffaa9a0888]
Stack dump:
0.      Program arguments: ～
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'CallGraph Pass Manager' on module '/tmp/pytest-of-ogura/pytest-77/mock-stage0/spack-stage-cmake-3.16.2-nbu3bjflndl6vew3miollwl6cvybjsar/spack-src/Utilities/cmzstd/lib/compress/zstd_opt.c'.
4.      Running pass 'Loop Pass Manager' on function '@ZSTD_compressBlock_opt_generic'
5.      Running pass 'Tree Height Reduction' on basic block '%7102'
Scanning dependencies of target pseudo_tidy
```
So, I changed optimization flags to `O2` from `O3` only when using Fujitsu compiler@4.0.0.

### CODE REVIEW

**Review by adamjstewart — DISMISSED** [review]
@chuckatkins

**Comment by chuckatkins** [comment]
Is the fujitsu compiler identifying as gnu?

**Comment by t-karatsu** [comment]
@chuckatkins
Fujitsu compiler is identified as a Clang compiler.
```
loading initial cache file /tmp/n0013/spack-stage/spack-stage-cmake-3.16.2-esxlmgdvtabduws3gsvdlzyd7cgjdrpi/spack-src/Bootstrap.cmk/InitialCacheFlags.cmake
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /work/n0013/debug/spack/lib/spack/env/fj/fcc
-- Check for working C compiler: /work/n0013/debug/spack/lib/spack/env/fj/fcc -- works
```

**Comment by t-karatsu** [comment]
Thanks for considering fixes for upstream. 
But, Changes of optimization is needed only when using Fujitsu compiler@4.0.0, and `-O3` is valid when using Fujitsu compiler@4.1.0.
Is there any good solution?

**Comment by t-karatsu** [comment]
@chuckatkins
Sorry, I commented without your tag last time.
Could you please tell me about the following to help me understand this problem?

>Given the nature of how CMake works, it's entirely valid and even quite likely that you'll be using a cmake built with the system gcc compiler to drive a build with the fujitsu compiler.

Does this mean that executing the following command is valid?:
`$ spack install [OSS_NAME]%fj ^cmake%gcc`

>That would still be broken here.

What does this mean?

**Comment by t-karatsu** [comment]
Hello @chuckatkins 
it's reminder.

And, I incorporated your modifications to this pull request. I didn't have any idea how to specify the compiler version in the source code, so I decided it in Spack.

**Comment by t-karatsu** [comment]
@chuckatkins
it's reminder. Please let me know if you have any problems with this fix.

**Comment by alalazo** [comment]
@chuckatkins Can you give a second view at this PR?

**Comment by alalazo** [comment]
@t-karatsu Is this still an issue?

**Comment by alalazo** [comment]
Closing since the PR got no answer. Feel free to reopen if still relevant.

**Pull request closed without merging**
