### PR TITLE
Added test function for tasmanian. 

### PR DESCRIPTION
**Pull request by wspear**
Included test directory with scripts/code/makefile.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@mkstoyanov can you test this out?

**Comment by mkstoyanov** [comment]
@adamjstewart Thanks for pointing it out, I will test is. But can I get a bit of context first?

Why include the tests directly into spack, as opposed to using ctest. All those tests are build by Tasmanian and the files are copied from the main Tasmanian repo. I honestly don't want to maintain the same files in two different places.

Why use GNU Make, why not CMake. I don't see how this can handle the transitive dependencies (if those are enabled).

Which version of Tasmanian does this cover? The tests are copied from 7.0 (and will fail if using 6.0 due to differences in the API) and tests are missing the Addon module tests that were added in 7.0. Which brings up again the problem of maintaining two sets of files in two separate repos.

**Comment by adamjstewart** [comment]
> Why include the tests directly into spack, as opposed to using ctest.

One of the things we're trying to add to Spack in the next year is post-installation unit tests. So users can run `spack test tasmanian` and test their existing installations. This is especially useful for software installed from a buildcache, or software that was installed but the user forgot to run the tests during installation. At this stage, the original source code (including tests) will no longer be present. We _could_ copy the test files directly from the source code during installation if we want to reuse them.

**Comment by wspear** [comment]
If there is a consistent way to provision test code without including it in spack that would be my preference, but projects are all over the map with test case availability. The lowest common denominator is source code and a makefile. Beyond that I'm hoping we can do smarter implementations on a case by case basis.

**Comment by mkstoyanov** [comment]
@adamjstewart @wspear with respect to your efforts, I have to say NO!

Makes no sense to put the entire test suite into two repos. Makefiles are also a bad way to manage potentially complicated transitive dependencies.

Either put a simpler "Hello World" style of a test (with CMake) or have packages install the test executables with a master script to run those. Tasmanian already installs examples that can be build to test the build system exports, can also install the executables gridtest, dreamtest, addontester, etc.

**Comment by wspear** [comment]
I think we want to be able to test building/running based on the deployed Spack environment, not necessarily the application's build environment. Pre-built test executables won't cover that case, so we'll probably need to extract something for after-build testing.

**Comment by mkstoyanov** [comment]
So you want an entire full test suite that builds and runs after the installation?

**Comment by wspear** [comment]
Something like that. If not a full test then at least a reasonable sanity-check. If we can assume that the build-time tests ran successfully then the after-build tests are more to make sure that the environment provided by Spack is correct and the binaries (if they were provided by a binary repo) are compatible with the current system.

**Comment by mkstoyanov** [comment]
@wspear if you want to check the spack environment, then you don't want the entire test suite. Tasmanian already provides a post install test script that is triggered by the `make test_install` command which build and runs a set of example problems and is using the already installed libraries.

Right now, the script is configured by CMake from the template in Testing/test_post_install.in.sh but it is executed from the build folder. I can modify that script and have an installed version of it to execute after the build folder has been cleared. I can make that change to Tasmanian and then spack will only need to run the installed script (provided cmake and the other dependencies have been loaded).

I think that is a much more reasonable solution than maintaining the test suite across two repositories. I have not tested it, but I am willing to bet that this PR and the simple Makefiles will fail if we make a full Tasmanian install, e.g.,
```
spack install tasmanian+openmp+blas+cuda+magma+python+fortran
```

**Comment by adamjstewart** [comment]
> Either put a simpler "Hello World" style of a test (with CMake)...

I personally think a "Hello World" style test is sufficient in this case.

**Comment by mkstoyanov** [comment]
> I personally think a "Hello World" style test is sufficient in this case.

I agree. The post-install test in Tasmanian is sufficient to check the validity of the installation from a build system perspective, and the examples ensure that the libraries and dependencies can be loaded at runtime.

**Comment by adamjstewart** [comment]
> The post-install test in Tasmanian is sufficient to check the validity of the installation from a build system perspective

This is the part I disagree with. Currently, Spack will run `make check` after the build phase but that's it. We would like to add a `test` method of some kind that can be run without access to any source code (after the package is installed and the stage is removed). This can be as simple as `<prefix>/bin/foo --help` or `--version` and making sure the executable doesn't crash, or it can run a small program and verify that the output is correct. I don't think we need to copy the entire test suite like @wspear is doing.

**Comment by mkstoyanov** [comment]
@adamjstewart I agree with you, I don't mean to leave thing to the current situation. My proposal is to have Tasmanian install a version of the post-install tests so that the version can be executed after the build folder vanishes.

When I was saying `sufficient` I was referring to the meat of the test, I agree that the test has to be added to the install folder and be available later.

**Comment by adamjstewart** [comment]
@mkstoyanov do you want @wspear to take a swing at implementing your above suggestion in this PR, or would you like to create your own PR?

**Comment by mkstoyanov** [comment]
I will have to add an install clause to the script on Tasmanian main and double check that it works outside of the build folder, I should get this Sunday or Monday. Then I will point @wspear to the script and we can take it from there.

**Comment by mkstoyanov** [comment]
Sorry it took so long, but I just merged with master. Tests can run with:
```
bash <tasmanian-path>/share/Tasmanian/test_post_install.sh
```

On the 7.0 release and older versions, the test can be done manually:
```
cmake <tasmanian-path>/share/Tasmanian/examples/
make
./example_sparse_grids --fast
```
Which will build the examples and run the example and tasgrid executable.

**Comment by wspear** [comment]
Thanks! On my local system the test fails when Tasmanian has been installed with Spack. It looks like Tasmanian is using the Spack compiler wrapper scripts, which don't work outside of Spack, instead of the 'real' compilers. I recently fixed a similar issue in the TAU package by post-processing some files. I'm not sure if the same approach is optimal here but you can see what I did in my PR: https://github.com/spack/spack/pull/15342


` Test 2: compile and run the C++ examples
--------------------------------------------------------------------------------
Building  "cmake /home/wspear/bin/spack/opt/spack/linux-ubuntu19.10-westmere/gcc-9.2.1/tasmanian-develop-dp7c64lseypdmdr3rslocqysgfzguj6v/share/Tasmanian/examples"
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /home/wspear/bin/spack/lib/spack/env/gcc/g++
-- Check for working CXX compiler: /home/wspear/bin/spack/lib/spack/env/gcc/g++ -- broken
CMake Error at /home/wspear/bin/spack/opt/spack/linux-ubuntu19.10-westmere/gcc-9.2.1/cmake-3.16.2-asdymcsl5yksq3henfllumq5pz4y6d22/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/home/wspear/bin/spack/lib/spack/env/gcc/g++"

  is not able to compile a simple test program.
`

**Comment by mkstoyanov** [comment]
I'm not sure I understand, you want to install Tasmanian with spack and use it outside of the spack environemnt. The test script is designed to use the same compilers as what was used during build, and I am pretty sure there is no workaround in the MPI case. What about Python? If using python outside of spack it may be missing numpy or some other package, if using the spack one it may not be able to load outside of spack. So many things in spack depend on the environment that I am not sure things can work outside of spack in genera.

Disregarding MPI and python, you can try to run the examples without the test script, i.e.,
```
cmake /home/wspear/bin/spack/opt/spack/linux-ubuntu19.10-westmere/gcc-9.2.1/tasmanian-develop-dp7c64lseypdmdr3rslocqysgfzguj6v/share/Tasmanian/examples
```
The should build and run, but I guess there are no guarantees.

If the above is working, I can add an option to the test script to disregard the build time compilers and run with the default cmake ones. That may be OK, but not sure about python and MPI. Cuda?

**Comment by mkstoyanov** [comment]
I updated the test script, now you can pass cmake options to it:
```
bash test_post_install.sh "-DCMAKE_CXX_COMPILERS=/usr/bin/g++-8 -DCMAKE_Fortran_COMPILER=/usr/bin/gfortran-8" 
```
Note the quotes "" so that all options can be passed in as a single argument.

**Comment by wspear** [comment]
To clarify, the spack compiler wrapper located in <spack>/lib/spack/env/gcc/g++ is only supposed to be used by internal spack build operations. It will always fail if invoked directly on the command line, regardless of if spack is in the environment. Any time it shows up in in a place where it can be run outside of a 'spack' command it will need to be overridden or replaced.

This creates a complication for packages that auto-detect their compilers and then use those compilers again after installation. They will have been built with the spack wrapper script but if they try to use that script instead of a 'real' compiler later they break. This can require some manual adjustments in the package to make sure the wrapper script gets replaced by the real compiler that spack was using.

**Comment by mkstoyanov** [comment]
@wspear this is very bad behavior on the spack side. If a user has multiple compilers and selects one for the build, the most natural thing to do is to use that compiler in follow on scripts. One simple example that fortran .mod files are not compatible across different version of gfortran.

The compromise that I can give is the one above, namely have a way to manually specify the CMake options (compilers or otherwise) for the post-install test build. Do you think you can add the appropriate compiler to the script command? Spack must be providing some sort of an API to extract the real compiler without manually parsing the scripts.

**Comment by wspear** [comment]
You can sub in the real compiler using a built in filter method provided by spack. Or, in less-standard cases, an approach more like what I did in the PR I linked. But passing the compiler directly to the test with the arguments support you added should work for me in this case.

**Comment by mkstoyanov** [comment]
@wspear let me know if you need help.

**Comment by adamjstewart** [comment]
It looks like there was a bad rebase at some point. Can you open a new PR with just the changes you want merged?

**Pull request closed without merging**
