### PR TITLE
aspa: Fix common errors.

### PR DESCRIPTION
**Pull request by t-karatsu**
* defined new member 'Vec_value_type' in 'self' namespace.
```
     460    In file included from ../src/mtl_headers/mtl/matrix_implementation.h:27:
  >> 461    ../src/mtl_headers/mtl/linalg_vec.h:135:21: error: no member named 'Vec_value_type
            ' in 'linalg_vec<RepType, RepPtr, NN>'
     462            while (*i == self::Vec_value_type(0)) ++i;
     463                         ~~~~~~^
```
I defined `Vec_value_type` as a member of `linalg_vec` namespace with reference to other header file `src/mtl_headers/mtl/dense1D.h`.

* fix narrowing error.
```
  >> 915    ../src/utils/toolbox/database/HDFDatabase.cc:689:24: error: non-con
            stant-expression cannot be narrowed from type 'int' to 'hsize_t' (a
            ka 'unsigned long long') in initializer list [-Wc++11-narrowing]
     916          hsize_t dim[] = {nelements};
     917                           ^~~~~~~~~
```
I did a typecast for `nelements` to 'unsigned long long' from 'int'.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Has this patch been submitted upstream?

**Comment by t-karatsu** [comment]
Not yet. However, github of `aspa` don't seem to be updated since 2014.
Should I submit a pull request to `aspa` and contact him?

**Comment by adamjstewart** [comment]
Might as well, it never hurts to open a PR.

**Comment by t-karatsu** [comment]
OK, I submitted this pull request.
https://github.com/exmatex/ASPA/pull/1

**Pull request merged**
