### PR TITLE
root: Configure ROOT correctly for python3

### PR DESCRIPTION
**Pull request by HadrienG2**
To quote Guilherme Amadio in [ROOT-9033](https://sft.its.cern.ch/jira/browse/ROOT-9033), back in February 2018:

> The `python3` option should be avoided. It has been removed in the master branch, and on the other branches, the recommended way to configure ROOT with Python 3.x is to pass `-Dpython=ON -DPYTHON_EXECUTABLE=<full path to python3 interpreter>` to CMake when configuring ROOT.

(Further, other comments on that issue suggest that the `python3` CMake option was already gone at least as far as in 2017 / the ROOT 6.10 era.)

We're already doing the `-DPYTHON_EXECUTABLE` part, but we don't set `-Dpython` when building for Python 3, which means in practice that we're not building PyROOT...

### CODE REVIEW

**Comment by HadrienG2** [comment]
I don't mind, but note that I'm mostly doing minor contributions that are focused on fixing what's broken in my personal builds ;) You may also want to ping people who contributed more major changes to the ROOT package, such as @chissg or @JavierCVilla .

**Comment by chissg** [comment]
@HadrienG2 Are you able to verify this behavior for `6.06/02`, the oldest build currently supported?

**Comment by HadrienG2** [comment]
@chissg ROOT 6.06/02 does not build at all because it's not compatible with the "honor-unuran-switch" patch which is unconditionally applied. Now investigating what is the minimal release that is compatible with that patch...

**Comment by HadrienG2** [comment]
...and that is 6.08/06. Which passes CMake, but fails to build because it doesn't manage to find zlib headers. The trick from #14224 likely needs to be extended to cover zlib in this version...

**Comment by HadrienG2** [comment]
...if I disable the patch for older ROOT releases, then the build breaks somewhere in LLVM:

```
     321    In file included from /tmp/root/spack-stage/spack-stage-root-6.06.02-7rgtkru4kyti2mg5xqrykusodrcyfqsf/spack-src/interpreter/llvm/src/include/llvm/Transforms/Utils/ValueMapper.h:18,
     322                     from /tmp/root/spack-stage/spack-stage-root-6.06.02-7rgtkru4kyti2mg5xqrykusodrcyfqsf/spack-src/interpreter/llvm/src/include/llvm/ExecutionEngine/Orc/CloneSubModule.h:18,
     323                     from /tmp/root/spack-stage/spack-stage-root-6.06.02-7rgtkru4kyti2mg5xqrykusodrcyfqsf/spack-src/interpreter/llvm/src/lib/ExecutionEngine/Orc/CloneSubModule.cpp:1:
     324    /tmp/root/spack-stage/spack-stage-root-6.06.02-7rgtkru4kyti2mg5xqrykusodrcyfqsf/spack-src/interpreter/llvm/src/include/llvm/IR/ValueMap.h: In member function 'bool llvm::ValueMap<KeyT, ValueT, Config>::hasMD() const':
  >> 325    /tmp/root/spack-stage/spack-stage-root-6.06.02-7rgtkru4kyti2mg5xqrykusodrcyfqsf/spack-src/interpreter/llvm/src/include/llvm/IR/ValueMap.h:104:31: error: cannot convert 'const std::unique_ptr<llvm::DenseMap<const llvm::Metadata*, llvm::TrackingMDRef> >' to 'bool' in return
     326      104 |   bool hasMD() const { return MDMap; }
     327          |                               ^~~~~
     328          |                               |
     329          |                               const std::unique_ptr<llvm::DenseMap<const llvm::Metadata*, llvm::TrackingMDRef> >
```

At this point, I feel like I'm starting to enter the dangerous territory of trying to build old C++ programs with recent C++ compilers. That's a very time-consuming effort which is rarely worthwhile.

Which course of action do you suggest?

**Comment by chissg** [comment]
@HadrienG2 I can tell you that we have built ROOT 6.06/02 with GCC 4.9.3 and C++2014, but have not tried anything newer. I would suggest "no extreme measures" in this case: if you find a compiler, _etc._ combination for an old release that does not work, mark it as a conflict. In this case I'd drop the `honor-unuran-switch` patch for 6.06/02 (it wasn't clear if the build was successful for you after that). For 6.08/02, I'd do the `SPACK_INCLUDE_DIRS` thing for `zlib` (subject to the checks above) for this version only and mark it a conflict with whatever compiler/version you were using.
You're perfectly correct though: maintaining a recipe for a large, complex toolkit such as this over many versions, variants, compilers, platforms—and years as those factors evolve over time—is no walk in the park. Welcome to the team! If you have an interest in a ROOT recipe that continues to work for you I would highly recommend adding yourself as a maintainer as part of this PR, because I can pretty much guarantee that this won't be the last time I unintentionally do something which breaks a build you're interested in.

**Comment by HadrienG2** [comment]
@chissg Sorry, I was not clear enough here. The latest build failure was from 6.06/02, after removing the unuran patch (via #14245 ). As it turns out, later 6.06 versions emit a clearer error message about not supporting the GCC 5+ ABI ( #14250 ). This brings back painful memories of something I had struggled with before... But anyway, it also means that I cannot check easily check the python 3 behavior for that release. Please feel free to check on your side if you have a GCC 4.x-based spack environment handy.

On my side, I'm now trying to bring back ROOT 6.08.06 from the dead...

I totally sympathize with ROOT being a "sensitive" fellow. As someone using a rolling Linux distribution, broken ROOT builds have been eating a significant fraction of my time ever since I've been working in HEP. The nice thing about spack, though, is that it allows all of our build hacks to be centralized in a single place, in the hope that the thing will gradually become just a bit more robust over time.

**Comment by chissg** [comment]
@HadrienG2 I'm not even sure ROOT is functional with Python3 that far back anyway. I'd suggest leaving it in and if someone reports errors we can worry about it then.

**Comment by chissg** [comment]
@HadrienG2 As a request for future PRs: could you follow the convention of prefixing the PR description with (in this case): `root: `? It also helps to add appropriate labels such as `new-version`, `versions`, `build-error` and/or `update-package`. That way it at least makes it a little more likely that I'll see them and be able to comment, review or otherwise contribute in a timely fashion.

**Comment by HadrienG2** [comment]
@chissg I do not have the required GitHub permissions to set labels, but I can obviously put a `root:` prefix on my PR titles.

From my quick tests, ROOT 6.12.06 (which, per the Jira issue above, already dropped the `python3` cmake option) fails to build with Python 3.7, but I do not have time to dig into the incompatibility further at present. I may look back into that after the holiday.

**Comment by HadrienG2** [comment]
Alright, I'm done testing compatibility of this change on my GCC 9.2.1 based system:

- ROOT 6.06.x does not build on that system because it's incompatible with the GCC5+ ABI.
- ROOT 6.08.x and 6.10.x do not build on that system due to some unclear incompatibility between the bundled version of Clang and GCC 9 (possibly older GCC versions as well) -> opened https://github.com/spack/spack/pull/14371 .
- ROOT 6.12.x does not build with Python 3.7, but builds with Python 3.6 -> added a conflict for this incompatibility on this PR.
- ROOT 6.14.x builds with Python 3.7, and I assume it also builds for subsequent releases of ROOT as well.

**Comment by HadrienG2** [comment]
...so as far as I'm concerned, this is now ready for merging.

**Comment by adamjstewart** [comment]
I'll merge this when @chissg approves

**Comment by HadrienG2** [comment]
@adamjstewart Note that since #14371 and this PR are editing the same file in the same place as they are adding two different conflicts, either of them will require a (rather easy) merge conflict resolution.

**Comment by HadrienG2** [comment]
@chissg Should be good now.

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/root/package.py:239: [W293] blank line contains whitespace
```

**Comment by HadrienG2** [comment]
Is it better now ?

**Pull request merged**
