### PR TITLE
the gmp build is dependent on bzip2

### PR DESCRIPTION
**Pull request by PDoakORNL**
gmp is dependent on bzip2

### CODE REVIEW

**Comment by adamjstewart** [comment]
I just tried building `gmp` and didn't see any mention of `bzip2` in the build log. Can you provide some evidence?

**Comment by PDoakORNL** [comment]
A sort of dependence you only notice on a minimal install of a distro.
```
url = "https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.bz2"
```

**Comment by adamjstewart** [comment]
Hmm... There are hundreds of packages in Spack that use `.bz2` or `.xz` tarballs. I wouldn't consider `bzip2` to be a dependency of `gmp`, I would consider it to be a dependency of Spack, much like `curl` must be installed to download most packages.

**Comment by PDoakORNL** [comment]
That's a good point.  So maybe this is really an issue and shouldn't be fixed this way.

**Comment by healther** [comment]
Just out of curiosity, do we build `bzip` as part of `spack bootstrap`?

**Comment by adamjstewart** [comment]
@tgamblin has suggested future work that would automatically build "system dependencies" like `bzip2`, `curl`, or `mercurial` when they are needed. The logic in Spack that calls these executables would automatically direct Spack to build them if they are not found when needed. I think that's probably the best way to solve this problem long-term, although `spack bootstrap` provides a short-term solution.

Either way, I wouldn't consider `bzip2` to be a dependency of `gmp` any more than I would consider `curl` to be a dependency to download it. It is needed by Spack, not by `gmp`.

**Pull request closed without merging**
