### PR TITLE
elfutils: update version and add variants

### PR DESCRIPTION
**Pull request by mwkrentel**
Add latest version 0.173.

Add variants bzip2, xz and zlib to support reading compressed DWARF
sections, default True.

Move maintainer-mode to a variant with default False.  This is only
useful for developers who want to modify the source for generated
files.

### CODE REVIEW

**Comment by mwkrentel** [comment]
Right.  The choices for bzip2 and xz are really 3-valued: (1) use
spack dependency, (2) use system version (if available), or (3) don't
use at all.  zlib is mandatory, so that has to be one of the first
two, it can't be option (3).

It seemed to me that the thematic spack thing to do was to build and
link as a spack dependency, so I made that the default.  (That's also
my use case, but my choices don't have to drive the default.)

As for the False case (~bzip2, ~xz), that could mean to use the system
version or it could mean explicitly disable.  I was unclear on which
made the more sense, so I just left it the way it previously was.
If you want all three options available, then the value of the variant
has to be 3-valued, it can't be boolean.

Did you want to change something in the variant settings?
Change the default or allow for option (3) or something?

**Comment by scheibelp** [comment]
Based on https://github.com/spack/spack/pull/5135 and https://github.com/spack/spack/issues/4190, the `+maintainer-mode` variant makes sense.

> Did you want to change something in the variant settings? Change the default or allow for option (3) or something?

As I think on this more, the safest/easiest option may be to turn them off by default: on systems which provide these, other packages may pick these dependencies up automatically, which may conflict with the Spack-built versions of `xz` etc.

**Comment by adamjstewart** [comment]
Never use system dependencies. If `zlib` is always required, always link to the Spack installation. If the others are optional, explicitly disable them.

Aside from conflicting versions ending up in the DAG, the other main problem with system dependencies is reproducibility. If I build `elfutils~xz` and you also build `elfutils~xz`, the goal is that we both have the same installation. The installation should not depend on the OS and what packages you happen to have installed.

**Comment by mwkrentel** [comment]
I got to the bottom of maintainer mode in elfutils.

This was added in the original elfutils rev from @tgamblin  in Aug 2015
when elfutils was still Package (not AutotoolsPackage),  spack had
only 224 packages and has been carried forward ever since, including
my switch to a variant.

   configure('--prefix=%s' % prefix, '--enable-maintainer-mode')

AFAICT, only @alalazo  in issue #4190 ever questioned why is this here
in the first place.

IMO, the fix in PR #5135 was the wrong fix.  Instead of adding flex
and bison as dependencies (necessary for maintainer mode for
elfutils), the better fix would have been to drop maintainer mode.

Btw, both in 2015 and now, elfutils is the only package that uses
maintainer mode.  (This only applies to automake packages.)

Maintainer mode has no use in a 1-time build.  The only use is if you
edit the source file of a generated file (Makefile.am, configure.ac,
or here the flex/bison source), then automake will automatically
detect this and rebuild the generated files.  Otherwise, it's up to
the developer to regenerate them manually.

My plan is to drop maintainer mode entirely.
Anyone have a problem with that?

Besides, if maintainer mode was the right thing here, then why don't
all automake packages use it?

As for the other dependencies, I'll make zlib mandatory (no variant).
For bzip2 and xz, they will either use a spack dependency, or else
disabled.  IMO, default on would be the more thematic spack thing to
do, but I could live with it either way.

History is good.

**Comment by tgamblin** [comment]
> My plan is to drop maintainer mode entirely.
> Anyone have a problem with that?

Nope!  Sounds like a good idea to me.

**Comment by mwkrentel** [comment]
Ok, I've updated the patch as above.  zlib is a required dependence,
bzip2 and xz are optional, default False.  I removed maintainer mode.

Thanks for all the comments.  They really helped clarify some things
for me.

Unless there's something else, I'm done.

**Pull request merged**
