### PR TITLE
WIP: adding cling to llvm package, horribly hacky workaround for git …

### PR DESCRIPTION
**Pull request by trws**
…archive issue

This is not ready, but it will let you build a merged cling/clang/llvm/lldb/everything version that should have working OpenMP.

### CODE REVIEW

**Comment by alalazo** [comment]
@trws Do you want to pursue this further?

**Comment by trws** [comment]
I would like to, but I'm out of commission for a bit after tearing the heck out of my knee a few days ago. (pain meds do not lead to good code quality...)

**Comment by alalazo** [comment]
>I would like to, but I'm out of commission for a bit after tearing the heck out of my knee a few days ago. (pain meds do not lead to good code quality...)

:fearful: No worries! Get well soon @trws!

**Comment by ax3l** [comment]
@trws have you had time to try building your cling package? :)

**Pull request closed without merging**
