### PR TITLE
superlu_dist: fix build with xl compilers

### PR DESCRIPTION
**Pull request by balay**
cc:  @xiaoyeli

### CODE REVIEW

**Comment by acfisher** [comment]
This got rid of all the errors except when building with xl except:
../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `ztrtri_'

This LLNL page mentions finding this to be an issue with a missing include?
https://hpc.llnl.gov/training/tutorials/using-lcs-sierra-system

Have you heard about this one?  Or maybe Sherry has?

**Comment by balay** [comment]
> This got rid of all the errors except when building with xl except:
> ../SRC/libsuperlu_dist.so.6.1.1: undefined reference to `ztrtri_'
> 
> This LLNL page mentions finding this to be an issue with a missing include?
> https://hpc.llnl.gov/training/tutorials/using-lcs-sierra-system
> 
> Have you heard about this one? Or maybe Sherry has?

cc: @xiaoyeli

Likely superlu-dist 6.1.1 needs additional patches.. I see code differences in 6.1.1 vs master. Perhaps the following change to  6.1.1

```
diff --git a/SRC/Cnames.h b/SRC/Cnames.h
index 792f514..ebef619 100644
--- a/SRC/Cnames.h
+++ b/SRC/Cnames.h
@@ -179,6 +179,7 @@ at the top-level directory.
 #define zher2_    ZHER2
 #define zgeru_    ZGERU
 
+#define ztrtri_   ZTRTRI
 /*
 #define mc64id_dist     MC64ID_DIST
 #define mc64ad_dist     MC64AD_DIST
@@ -307,6 +308,7 @@ at the top-level directory.
 #define zher2_    zher2
 #define zgeru_    zgeru
 
+#define ztrtri_   ztrtri
 /*
 #define mc64id_dist         mc64id_dist
 #define mc64ad_dist         mc64ad_dist
```

**Comment by balay** [comment]
@acfisher I pushed this patch to this spack branch. Can you retry?

**Comment by acfisher** [comment]
Good spot on the changes in master.  I put in a small fix to the patch spec so that it will apply it.  Now superlu_dist builds nicely on lassen.

**Comment by balay** [comment]
@acfisher is this PR good to go? I've removed the WIP tag

**Comment by acfisher** [comment]
Yes it is ready to go.

**Pull request merged**
