### PR TITLE
openmpi: add additional variants

### PR DESCRIPTION
**Pull request by carsonwoods**
This PR adds variants to the openmpi package. Specifically variants for enabling:
- static libraries
- built-in atomics
- enabling wrapper rpath

Every variant has explicit toggles for enable/disable.

### CODE REVIEW

**Comment by hppritcha** [comment]
@carsonwoods what's the motivation for the choice of enable/disable for builtin atomics?

**Comment by carsonwoods** [comment]
@hppritcha We are trying to implement an existing software environment in Spack. In that environment OpenMPI has builtin atomics enabled. I was not involved in the intial creation of that environment, only converting it to Spack, so I'm not sure the motivation for its inclusion. I'm requesting its addition to Spack so that we can keep the environments as similar as possible.

**Comment by hppritcha** [comment]
Hmm...actually the way the Open MPI configury works it checks to see if the compiler being used is modern enough to support built-in atomics.  That's the reason the configure --help says auto-detect.  I'd suggest double checking that this PR won't cause problems by trying to build the "atomic" variant against the C compiler that comes with RHEL7.  If that works, then this PR should be okay.

**Comment by carsonwoods** [comment]
I will look into if it breaks or not and post an update once I know for sure.

**Comment by adamjstewart** [comment]
@carsonwoods any updates?

**Comment by carsonwoods** [comment]
@adamjstewart @hppritcha Sorry for the delay, this week completely got away from me. I just gave it a run and it seems to install ok with atomics enabled. Was running on REHL7 using the builtin C compiler.

**Pull request merged**
