### PR TITLE
bugfix: mirror path works for nonexisting versions

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes a second error mentioned by @zzotta in https://github.com/spack/spack/issues/13474#issuecomment-550281560.

`mirror_archive_path` was failing to acccount for the case where the fetched versions isn't known to Spack.

- [x] don't require the fetched version to be in `Package.versions`
- [x] add a regression test

### CODE REVIEW

**Comment by tgamblin** [comment]
@zzotta: does this fix your fetch command?  It does for me:

```console
$ spack fetch --no-checksum libbson@1.9.5
==> Warning: clang@10.0.0-apple cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> Fetching file:///Users/gamblin2/foop/libbson/libbson-1.9.5.tar.gz
curl: (37) Couldn't open file /Users/gamblin2/foop/libbson/libbson-1.9.5.tar.gz
==> Fetching from file:///Users/gamblin2/foop/libbson/libbson-1.9.5.tar.gz failed.
==> Fetching https://github.com/mongodb/libbson/releases/download/1.9.5/libbson-1.9.5.tar.gz
######################################################################## 100.0%
```

**Comment by zzotta** [comment]
> @zzotta: does this fix your fetch command?

@tgamblin: Yes, it does

**Comment by scheibelp** [comment]
@tgamblin I agree with the changes you made, so if you agree with the test I added then this is good to go

**Comment by tgamblin** [comment]
@scheibelp: this looks good to me!

@junghans: FYI, I think this fixes the issue we saw in the tutorial.

**Pull request merged**
