### PR TITLE
Some fixes for Intel build system packages.

### LINKED ISSUE #9713: can't install two versions of intel-mkl 2019.0.117
### Description

seems that intel installer is too clever and picks up the previous installation of `intel-mkl` using `spack`. Which is unfortunate as one can't have `intel-mkl threads=none` and `intel-mkl threads=openmp` installed at the same time ;-(

### Steps to reproduce

```
spack install intel-mkl
spack install intel-mkl threads=openmp
```

gives error during installation and prints the message:

```
The install directory path was changed to <previous-spack-installed-mkl> 
because at least one software product component was detected as having already been installed on the system

Please select at least one component before you continue
```

Not sure if there is anything Spack can do... ;-(

### LINKED ISSUE #11289: Installation issue: py-numpy with intel
### Steps to reproduce the issue

```console
$ spack install py-numpy@1.16.2%intel@18.0.4 ^intel-mkl@2018.4.274%intel@18.0.4
... 
==> Error: InstallError: Cannot find a BLACS library for the given MPI.

....../spack/lib/spack/spack/build_systems/intel.py:798, in scalapack_libs:
        795            blacs_lib = 'libmkl_blacs_intelmpi'
        796        elif '^mpt' in spec_root:
        797            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    798        else:
        799            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        800
        801        int_suff = '_' + self.intel64_int_suffix

```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux login5.occigen 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
``` 

### Additional information
We are on "develop" branch, the build was working correctly in "0.12.0".

This seems to fail because in libs() function from spack/lib/spack/spack/build_systems/intel.py there are the following lines:

```
if '+mkl' in self.spec or self.provides('scalapack'):
            result = self.scalapack_libs + result

```

Which will add scalapack_libs if one depend on mkl.

Or py-numpy does depend on mkl, but not on MPI, which explains why this line fails once it calls the scalapack_libs function.

### LINKED ISSUE #11314: Installation issue: intel-mkl-dnn due to "Cannot find a BLACS library for the given MPI"
### Steps to reproduce the issue

```console
$ spack install intel-mkl-dnn %intel@19.0.3 ^intel-mkl
...
==> Error: InstallError: Cannot find a BLACS library for the given MPI.

/lustre/kcaps/lib/spack/spack/build_systems/intel.py:810, in scalapack_libs:
        807            blacs_lib = 'libmkl_blacs_intelmpi'
        808        elif '^mpt' in spec_root:
        809            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    810        else:
        811            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        812
        813        int_suff = '_' + self.intel64_int_suffix
```

### Platform and user environment

```commandline
$ uname -a 
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.3.1611 (Core)
``` 

### Other

```commandline
$ 
Input spec
--------------------------------
intel-mkl-dnn%intel@19.0.3
    ^intel-mkl

Concretized
--------------------------------
intel-mkl-dnn@0.11%intel@19.0.3 build_type=RelWithDebInfo arch=linux-centos7-x86_64
    ^cmake@3.14.2%intel@19.0.3~doc+ncurses+openssl~ownlibs~qt arch=linux-centos7-x86_64
        ^bzip2@1.0.6%intel@19.0.3+shared arch=linux-centos7-x86_64
            ^diffutils@3.7%intel@19.0.3 arch=linux-centos7-x86_64
        ^curl@7.63.0%intel@19.0.3~darwinssl~libssh~libssh2~nghttp2 arch=linux-centos7-x86_64
            ^openssl@1.1.1b%intel@19.0.3+systemcerts arch=linux-centos7-x86_64
                ^perl@5.26.2%intel@19.0.3+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-x86_64
                    ^gdbm@1.18.1%intel@19.0.3 arch=linux-centos7-x86_64
                        ^readline@7.0%intel@19.0.3 arch=linux-centos7-x86_64
                            ^ncurses@6.1%intel@19.0.3~symlinks~termlib arch=linux-centos7-x86_64
                                ^pkgconf@1.6.0%intel@19.0.3 arch=linux-centos7-x86_64
                ^zlib@1.2.11%intel@19.0.3+optimize+pic+shared arch=linux-centos7-x86_64
        ^expat@2.2.5%intel@19.0.3+libbsd arch=linux-centos7-x86_64
            ^libbsd@0.9.1%intel@19.0.3 arch=linux-centos7-x86_64
        ^libarchive@3.3.2%intel@19.0.3 arch=linux-centos7-x86_64
            ^libxml2@2.9.8%intel@19.0.3~python arch=linux-centos7-x86_64
                ^libiconv@1.15%intel@19.0.3 arch=linux-centos7-x86_64
                ^xz@5.2.4%intel@19.0.3 arch=linux-centos7-x86_64
            ^lz4@1.9.0%intel@19.0.3 arch=linux-centos7-x86_64
            ^lzo@2.10%intel@19.0.3 arch=linux-centos7-x86_64
            ^nettle@3.4%intel@19.0.3 arch=linux-centos7-x86_64
                ^gmp@6.1.2%intel@19.0.3 arch=linux-centos7-x86_64
                    ^autoconf@2.69%intel@19.0.3 arch=linux-centos7-x86_64
                        ^m4@1.4.18%intel@19.0.3 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-x86_64
                            ^libsigsegv@2.11%intel@19.0.3 arch=linux-centos7-x86_64
                    ^automake@1.16.1%intel@19.0.3 arch=linux-centos7-x86_64
                    ^libtool@2.4.6%intel@19.0.3 arch=linux-centos7-x86_64
        ^libuv@1.25.0%intel@19.0.3 arch=linux-centos7-x86_64
        ^rhash@1.3.5%intel@19.0.3 arch=linux-centos7-x86_64
    ^intel-mkl@2019.3.199%intel@19.0.3~ilp64+shared threads=openmp arch=linux-centos7-x86_64
``` 

intel-mkl-dnn doesn't depend on MPI nor Scalapack. I'm not sure why it complains about MPI.

### PR DESCRIPTION
**Pull request by glennpj**
- Only return scalapack libraries if `+mpi` is in the spec.
  Fixes #11314
  Fixes #11289

- set HOME when the intel silent installer is run. This prevents the
  installer from using the ~/intel directory
  Fixes #9713

### CODE REVIEW

**Comment by glennpj** [comment]
What do I need to do to get the codecov/patch check to succeed?

**Comment by scheibelp** [comment]
That's not necessary for package PR's but I'd like to understand a bit more about the patches

The `HOME` edit makes sense. Regarding the `mpi` check: it seemed to be the original author's understanding that `mkl` would always depend on `scalapack` (and transitively on `mpi`). It could be that this is true but that the `mpi` dependency is not encoded in the Spack DAG (which would also lead to an error). I'll have a chance to think about it more tomorrow.

**Comment by glennpj** [comment]
@scheibelp I guess I was letting the linked issues describe it but I probably should have put more comments in. What is happening is that using MKL fails when used for packages that do not use MPI, or scalapack, at all, such as py-numpy. Because there is no `+mpi` in the spec, the tests can not determine which MPI blacs flavor to use, and fails. However, no MPI blacs flavor is needed at all in those cases. MKL in general does not depend on MPI, unless it is providing the scalapack (blacs) libraries, and just needs to know which is the mpi provider.

Thanks.

**Comment by scheibelp** [comment]
Thanks @glennpj, I read the attached issues, and your own description was also helpful. I think the following may resolve the issue without overly-constraining the condition where scalapack libraries are retrieved:

```
@property
def libs(self):
	...

	spec_root = self.spec.root
	if '^scalapack' in spec_root:
		result = self.scalapack_libs + result

	# before:
	# if '+mkl' in self.spec or self.provides('scalapack'):
	# 	  result = self.scalapack_libs + result
```

The `+mpi` check you added I think will cause the library retrieval to be skipped in cases where packages need to retrieve the scalapack libs from `intel-mkl`, because as of now `intel-mkl` does not have a `+mpi` variant.

Does that work for you?

**Comment by glennpj** [comment]
@scheibelp No, that does not work, see error report below. The mkl packages are providers for scalapack so they will always look for the scalapack libraries. If there is no mpi in the spec then it will not know which mpi blacs flavor to use, which is where it is failing in the output below. That is the same behavior without the PR. Scalapack libraries are never needed without an MPI.

I do see your point about over constraining though. If a package needs scalapack then that may implicitly set mpi such that mpi would be a dependency without a variant `+mpi` setting. That would miss the scalapack libraries. However, replacing `+mpi` with `^mpi` should address that because an mpi build would have to be in the spec to use scalapack. 
```
==> Installing py-numpy
==> Searching for binary cache of py-numpy
==> Finding buildcaches in /opt/packages/gpjohnsn/spack-mirror-2019-05-04/build_cache
==> No binary for py-numpy found: installing from source
==> Error: InstallError: Cannot find a BLACS library for the given MPI.

/opt/packages/gpjohnsn/spack/lib/spack/spack/build_systems/intel.py:810, in scalapack_libs:
        807            blacs_lib = 'libmkl_blacs_intelmpi'
        808        elif '^mpt' in spec_root:
        809            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    810        else:
        811            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        812
        813        int_suff = '_' + self.intel64_int_suffix
```

**Comment by scheibelp** [comment]
> However, replacing +mpi with ^mpi should address that because an mpi build would have to be in the spec to use scalapack.

That sounds good, but I think it should be checking relative to the spec root vs. the `IntelPackage` (because e.g. `intel-mkl` doesn't declare an explicit dependency on `mpi`):

```
@property
def libs(self):
	...

	spec_root = self.spec.root
	if '^mpi' in spec_root:
		result = self.scalapack_libs + result
```

Ideally it would be possible to instead ask if any of the packages in the DAG are actually requesting the `scalapack` functionality provided by the `IntelPackage`, but I don't think that's easily doable now.

**Comment by glennpj** [comment]
@scheibelp Yes, of course, I actually meant to keep the `spec.root` check in my last commit but it got lost in the edit. I am pretty sure that the original test for `+mkl` and `scalapack` needs to still be in there. I will push a new commit shortly.

Thanks.

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
