### PR TITLE
Package hashing: fix detection of directives

### PR DESCRIPTION
**Pull request by scheibelp**
Fixes: https://github.com/spack/spack/issues/14735
Fixes: #15079 

When checking if a function call is a directive, add a preliminary check to ensure that the name of the function is available in the AST (this is always true for directives, so we can return `False` if the function call doesn't have a name).

The check for directives was tripping over logic added to `py-pillow`:

```
run_after('install')(PythonPackage.sanity_check_prefix)
```

the hashing logic was checking the names of function calls. But this particular function call (i.e. `...(PythonPackage.sanity_check_prefix)`) doesn't have a name (or at least it doesn't have a name that can be determined by examining the AST); that will always be true for directives.

TODOs:

- [x] add a regression test

### CODE REVIEW

**Comment by scheibelp** [comment]
@tldahlgren thanks for the review. The docstring is now added (copied over from #15093)

**Comment by tldahlgren** [comment]
> ```
> run_after('install')(PythonPackage.sanity_check_prefix)
> ```
> 
> the hashing logic was checking the names of function calls. But this particular function call (i.e. `...(PythonPackage.sanity_check_prefix)`) doesn't have a name (or at least it doesn't have a name that can be determined by examining the AST); that will always be true for directives.

Technically, the name could be inferred from the AST but it wouldn't be relevant for a directive since this statement represents a phase callback. If you did want to check a name, which would you want to use in this case?  The AST node dump for this entry, with formatting to help with readability, is:

```
node=Expr(
    value=Call(
        func=Call(
            func=Name(id='run_after', ctx=Load(), lineno=115, col_offset=4),
            args=[Str(s='install', lineno=115, col_offset=14)],
            keywords=[],
            lineno=115,
            col_offset=4
        ), 
        args=[
            Attribute(
                value=Name(id='PythonPackage', ctx=Load(), lineno=115, col_offset=25),
                attr='sanity_check_prefix',
                ctx=Load(),
                lineno=115,
                col_offset=25
            )
        ],
        keywords=[],
        lineno=115,
        col_offset=4
    ),
    lineno=115,
    col_offset=4
)
```

**Comment by scheibelp** [comment]
> Technically, the name could be inferred from the AST

I may not be using the correct language. What I mean is that `run_after('install')` in `run_after('install')(PythonPackage.sanity_check_prefix)` returns a function, that function is determined by `PackageMeta.register_callback`; the function returned by that function happens to be called `_decorator`, and that name doesn't appear in the AST shown in https://github.com/spack/spack/pull/14763#issuecomment-588569878.

I think I could explain it better:

> The hashing logic looks for function calls that are Spack directives. It expects that when a Spack directive is used that it is referenced directly by name, and that the directive function is not itself retrieved by calling another function. When the hashing logic encountered a function call where the function was determined dynamically, it would fail (attempting to access a `name` attribute which does not happen to exist in this case). This updates the hashing logic to filter out function calls where the function is determined dynamically when looking for uses of Spack directives.

Is that clearer?

As I read through the docstring carefully I'm curious about

> Directives are assumed to be represented in the AST as a named function call expression

Does the term "named function call expression" have a well-defined (i.e. universally understood) meaning?

**Comment by tldahlgren** [comment]
> Is that clearer?

Yes and very detailed.

> 
> As I read through the docstring carefully I'm curious about
> 
> > Directives are assumed to be represented in the AST as a named function call expression
> 
> Does the term "named function call expression" have a well-defined (i.e. universally understood) meaning?

I was probably taking liberties.  The node type being reported was an expression representing a function call that was named.

**Pull request merged**
