### PR TITLE
Update libfabric to 1.9.1

### PR DESCRIPTION
**Pull request by sethrj**
See https://github.com/spack/spack/pull/15337 and https://github.com/spack/spack/issues/15244

@ax3l @carns

### CODE REVIEW

**Comment by ax3l** [comment]
I am on vacation this week. Mac users, does this work/build for you? @sethrj and @LDAmorim

**Comment by LDAmorim** [comment]
Thanks for pointing this out @ax3l, I will try to check it out in my machine asap!

**Comment by sethrj** [comment]
I verified that it builds on my mac before submitting this PR.  This should be go for merge.

**Comment by carns** [comment]
I know this PR is closed already, but just for informational purposes for anyone interested: I have basic performance regression tests complete on InfiniBand, OmniPath, and Aries networks now with 1.9.1, and all looks well on those fronts too.

**Comment by ax3l** [comment]
@sethrj I am using libfabric 1.9.1 on OSX for Travis CI tests and still see the same error of #15244:
https://travis-ci.org/github/openPMD/openPMD-api/jobs/663670933
```
5 errors found in build log:
     610    ==> [2020-03-17-21:56:51.772800, 97889] 'make' '-j2'
     611    /Applications/Xcode-11.2.1.app/Contents/Developer/usr/bin/make  all-am
     612      CC       multinode/src/multinode_fi_multinode_coll-harness.o
     613      CC       multinode/src/multinode_fi_multinode_coll-core_coll.o
     614    In file included from multinode/src/harness.c:35:
     615    In file included from ./include/shared.h:55:
  >> 616    ./include/ft_osd.h:37:10: fatal error: 'osx/osd.h' file not found
     617    #include <osx/osd.h>
     618             ^~~~~~~~~~~
     619    In file included from multinode/src/core_coll.c:51:
     620    In file included from ./include/shared.h:55:
  >> 621    ./include/ft_osd.h:37:10: fatal error: 'osx/osd.h' file not found
     622    #include <osx/osd.h>
     623             ^~~~~~~~~~~
```

Are you sure this issue was fixed in 1.9.1?

**Comment by sethrj** [comment]
@ax3l Not sure sure, but I've installed it on my machine:
```
$ spack find -lv libfabric
==> 3 installed packages
-- darwin-mojave-x86_64 / clang@11.0.0-apple --------------------
zmsass3 libfabric@1.8.1 fabrics=sockets,tcp,udp ~kdreg
znzplsj libfabric@1.9.1 fabrics=sockets,tcp,udp ~kdreg
```

**Comment by sethrj** [comment]
wtf, `spack install --overwrite /znzplsj` fails now. 
```
  >> 626    ./include/ft_osd.h:37:10: fatal error: 'osx/osd.h' file not found
```

but if I do `git reflog` and return to `90063f6d2c8e513083a5a3c5a41488db7ed83419`
```diff
diff --git a/var/spack/repos/builtin/packages/libfabric/package.py b/var/spack/repos/builti
index bb1730993..927dd24d5 100644
--- a/var/spack/repos/builtin/packages/libfabric/package.py
+++ b/var/spack/repos/builtin/packages/libfabric/package.py
@@ -16,9 +16,9 @@ class Libfabric(AutotoolsPackage):
     git      = "https://github.com/ofiwg/libfabric.git"

     version('master', branch='master')
-    version('1.9.1rc1', sha256='fdf89a0797f0d923aaef2c41cc70be45716e4d07dc5d318365b9c17795
+    version('1.9.1', sha256='c305c6035c992523e08c7591a6a3707225ba3e72de40443eaed837a10df67
     version('1.9.0', sha256='559bfb7376c38253c936d0b104591c3394880376d676894895706c4f5f885
-    version('1.8.1', sha256='3c560b997f9eafd89f961dd8e8a29a81aad3e39aee888e3f3822da419047d
+    version('1.8.1', sha256='3c560b997f9eafd89f961dd8e8a29a81aad3e39aee888e3f3822da419047d
     version('1.8.0', sha256='c4763383a96af4af52cd81b3b094227f5cf8e91662f861670965994539b7e
     version('1.7.1', sha256='f4e9cc48319763cff4943de96bf527b737c9f1d6ac3088b8b5c75d07bd719
     version('1.7.0', sha256='b3dd9cc0fa36fe8c3b9997ba279ec831a905704816c25fe3c4c09fc7eecea
```

I can install again.

**Comment by ax3l** [comment]
@ChristianTackeGSI do we even have to install/build `fabtests` (#15440) unconditionally?
Otherwise we could skip this in call cases unless `type='test'` / `self.run_tests` is specified.

**Comment by ChristianTackeGSI** [comment]
@ax3l 
fabtests has two parts:

1. Unit tests for libfabric: Obviously, we don't need those if not running tests from spack.
2. tools to analyze a running system. For example to inspect endpoints on infiniband or run simple performance tests. Those are useful after `spack install`, really. We need them on our systems from time to time.

I see a few options:
* Try to fix fabtests for OSX. I don't know enough about libfabric, fabtests, or OSX to come up with a quick solution for this.
* Do not build fabtests on OSX. That would be okay for me.
* Package fabtests seperately. There IS a fabtests package in spack already, but it's deprecated. And as fabtests and libfabric are released together and have the same version number, it feels logical to have them in one package in spack. I could be convinced to go this route. But I don't like it.

Any other options?

**Comment by sethrj** [comment]
@ax3l @ChristianTackeGSI What about making `fabtests` a variant? That would make a `conflicts` statement trivial.

**Comment by ChristianTackeGSI** [comment]
I don't know, if a variant is absolutely needed?
But yes, I'm okay with that.

**Comment by sethrj** [comment]
@ChristianTackeGSI If the tools are optional (for debugging rather than being a critical component of downstream codes like ADIOS), and if they're consistently causing build failures on a significant number of platforms, I'd say it's a good idea to make the tools optional using a variant. @ax3l Could you set that up?  I think it would also make sense to roll all the `resource`s into a `for` loop a la `amber`, `git`, `pythia6`, etc.

**Comment by ax3l** [comment]
> tools to analyze a running system.

I am looking at [this](https://github.com/ofiwg/libfabric/blob/33ea19fd66119b8218dc50678f240d44084c2690/.travis.yml#L110-L118) right now.

Is it possible that `fabtests` should better be a libfabric-dependent package in Spack?

**Pull request merged**
