### PR TITLE
make dependency satisfaction check more strict

### PR DESCRIPTION
**Pull request by scheibelp**
Fixes https://github.com/spack/spack/issues/6231

This updates `Spec.satisfies_dependencies` to strictly check satisfaction on dependencies when it is called with `strict=True`. Without this, condition specs in `package.py` files that set variants on dependencies are not checked.

### CODE REVIEW

**Comment by scheibelp** [comment]
This looks good but I intend to add a test for this by tomorrow morning.

**Comment by scheibelp** [comment]
It turns out I overlooked an aspect of the concretization algorithm which makes constraints based on dependencies problematic (which is leading to the test failure): the `Spec.normalize` function strips all dependencies with the intent of adding them back later. Depending on the order that dependencies are visited in, the check will fail for one dependency if it is conditioned on dependency which hasn't been added back yet.

Short story is that this quick fix isn't sufficient to fix constraints that are conditioned on properties of dependencies.

**Comment by adamjstewart** [comment]
Is this still a WIP or will it become obsolete with the new concretizer?

**Comment by alalazo** [comment]
Closing since the implementation seems outdated.

**Pull request closed without merging**
