### PR TITLE
Add kraken2

### PR DESCRIPTION
**Pull request by rberg2**

### CODE REVIEW

**Comment by tgamblin** [comment]
Is this different enough from `kraken` to merit a new package?

**Comment by rberg2** [comment]
> Is this different enough from `kraken` to merit a new package?

I initially thought about adding it as a version to to kraken package, but I was not sure how to add a second github repo url.
kraken uses `url      = "https://github.com/DerrickWood/kraken/archive/v1.0.tar.gz"`
kraken2 uses `url      = "https://github.com/DerrickWood/kraken2/archive/v2.0.8-beta.tar.gz"`
so I went with a new package.

**Comment by rberg2** [comment]
After reading the documentation more in depth, I think I understand how to make the kraken package support both version 1 and 2 with `@when` syntax and adding the URL to the version line. I can close this PR and create one for that change if that is the way you would like it done.

**Comment by adamjstewart** [comment]
I personally have no opinions on whether this warrants a new package or a new version of the existing `kraken` package. It would be interesting to hear why @DerrickWood decided to create a new repository for `kraken2` and whether he thinks it should be 2 separate packages.

**Comment by adamjstewart** [comment]
No comment from @DerrickWood, I'm just going to merge this.

**Pull request merged**
