### PR TITLE
enable using spack-installed packages as externals

### PR DESCRIPTION
**Pull request by scheibelp**
Makes the following changes:

* Don't generate modules for external packages
* Remove assertion from `Spec.path_for_spec` which checks that the path doesn't contain the spack install root: it isn't required
* Check for non-existent prefixes in build_environment when collecting prefixes (e.g. if the package has a module rather than a prefix - this isn't and issue with spack-installed packages though)

### CODE REVIEW

**Comment by adamjstewart** [comment]
> Don't generate modules for external packages

I thought this was solved by #5460, but maybe I'm wrong. This was a problem first reported in #5201. I guess #5460 ignored directories in `/usr` when generating module files whereas this PR doesn't even bother writing a module file to begin with. Either way, 👍 from me.

**Comment by scheibelp** [comment]
>> Don't generate modules for external packages

> I thought this was solved by #5460, but maybe I'm wrong. This was a problem first reported in #5201.

Thanks for the heads up! I didn't recall that PR. From looking through it I'm not sure whether it addresses the case that there is no prefix associated with a spec (e.g. if a module is defined but not a path) - @alalazo do you have a notion of whether that is handled? IMO it would make sense to skip module generation for externals which don't have a prefix.

**Comment by adamjstewart** [comment]
My vote would be to skip module generation for:

1. external packages that don't have a `paths` entry (because presumably they already have a module file)
2. external packages installed in a system directory

I don't see a problem with generating module files for packages with prefixes not in system directories.

**Comment by alalazo** [comment]
@scheibelp 
> From looking through it I'm not sure whether it addresses the case that there is no prefix associated with a spec (e.g. if a module is defined but not a path) - @alalazo do you have a notion of whether that is handled?

When I did the PR I thought every external package had a path:

https://github.com/spack/spack/blob/c8f78676ebbcfa83ce9989b397fbd4a49e9cd541/lib/spack/spack/spec.py#L1890-L1898

but looking better at `get_path_from_module` I see it's not the case, as it may return `None` (probably it's worth expanding the docstring a bit). From my understanding the snippet above is mostly hit on Cray, so I must admit I have don't have much experience with external packages that are tied to module files not generated by Spack.

> IMO it would make sense to skip module generation for externals which don't have a prefix.

I agree. Currently, if they don't have a path and they are external, it means they already have an external module (and there's no need to duplicate it).

@adamjstewart 
> 2. external packages installed in a system directory

For this I would be cautious. The library / application might be configurable at run-time, and the different module files might enable different configurations for the same external application. #5460 should already ensure that variables affecting other packages (like `PATH` or `LD_LIBRARY_PATH`) are not modified.

**Comment by scheibelp** [comment]
> Why do we want to allow this? Are there compelling use cases that I am missing?

My intended use case is to use Spack to install build dependencies like CMake and then mark them as external so that Spack builds can use CMake when cross-compiling. It's the sort of thing an improved concretizer would handle.

As for using this to prevent Spack from reinstalling packages, I think that for the reasons you outline it would be best to encourage users to specify the package by hash instead. @adamjstewart, other than the tedium of invoking installation commands with `/(the hash of intel-parallel-studio)` in the spec, do you see an issue with that for the use case initially reported in https://github.com/spack/spack/issues/3787#issue-220799381? This is also a feature that could be added to Spack environments (https://github.com/spack/spack/pull/4585).

> That package was first installed by Spack and is present in the DB as something that is not external. It may have a DAG associated with it, and its dependencies might involve calls to `setup_*_environment` at build-time or to generate working module files.

If the concern is that there will be conflicting calls to `setup_dependent_environment`, Spack currently always truncates dependencies of externals during concretization (see `Spec._expand_virtual_packages`)

> Subsequent installations will be marked external, and the DAG associated with it suddenly has no leaves, doesn't call setup_*_environment on dependencies and will follow a work-flow meant for packages installed manually by the user.

This seems like more of a problem. Although IMO it wouldn't be a serious issue for build dependencies.

**Comment by scheibelp** [comment]
It turns out all the changes here are also useful for handling external packages in Spack which have associated modules but to not have associated prefixes (i.e. Spack cannot extract a path from the module).

**Comment by alalazo** [comment]
Closing as outdated

**Pull request closed without merging**
