### PR TITLE
Remove libtool version dependency

### PR DESCRIPTION
**Pull request by khuck**
Minor change to remove libtool version from adios package specification.

### CODE REVIEW

**Comment by scheibelp** [comment]
Hi @khuck this is fine (assuming the constraint is not actually required - perhaps it relaxed for more-recent versions of `adios`?).

However, I'm curious, based on our outside conversations of using `adios` in an environment, whether https://github.com/spack/spack/pull/10792 resolved the errors you were getting.

**Comment by khuck** [comment]
@scheibelp I contacted the ADIOS team, and they don't think this version requirement was necessary, just a holdover from an older configuration.  I haven't had a chance to test the spack environment patch yet, no - I'll try to give that a shot soon.  Thanks!

**Comment by adamjstewart** [comment]
It looks like this constraint was added in https://github.com/spack/spack/pull/4857/commits/24da48307d8e2d9919b30a5d5f01a9a019eedb5c

Can you test older versions of the package and make sure all of them build with the latest version of libtool? If not, we can restrict the version only for older versions of adios.

**Comment by ax3l** [comment]
@khuck can you please verify the build of `adios@develop` still works with this modification?
Maybe we are also lucky here and newer ADIOS versions work with it... At the time the libtool change was release ADIOS was still at 1.12.0 and 1.13.0/1 contain many fixes.

**Comment by khuck** [comment]
I'm cancelling this pull request.

**Comment by ax3l** [comment]
@khuck anything new on this?

**Comment by khuck** [comment]
@ax3l No - there is no justifiable need for it.  We were trying to build the ECP xSDK and E4S docker images and this issue came up.  From what I understand, there are other work-arounds.

**Pull request closed without merging**
