### PR TITLE
Docker image rework

### PR DESCRIPTION
**Pull request by opadron**
This PR experiments with the idea of slimming down the base docker images and avoiding OS-specific packages as much as possible.  Instead, almost everything in this experimental version is provisioned using Spack, itself.

Currently, only the `ubuntu-1804` dockerfile is modified with the others to follow if others agree this is a good idea.

The build process starts with only what is absolutely necessary from the OS (basically, gcc and libc), and uses a new multi-phase bootstrapping approach in which a recent version of gcc is built and subsequently used to build all the software necessary to host a fully-featured installation of Spack.  Multiple docker build stages are used to ensure that the final image contains only the end products of this build process, minimizing the final image size.

The bootstrapped packages are maintained in a Spack chain separated from the primary Spack installation and are symlinked into a Spack view under `/usr/local`.  The bootstrapped packages are built using the lowest-common-denominator `target` for maximum portability.  This portability is limited to the bootstrapped packages and is configurable when building the docker image.

The main drawback to this approach is the build time.  On my 2018 Mac Pro (with 16/32 GB Ram dedicated to docker), it takes about 2 hours to build.  This issue should go away once we have a public build cache up and running, and we can effectively rely on our own infrastructure in place of Debian and Red Hat repositories.

This PR also adds a few other minor improvements:

A new, unprivileged user, `spack` (`uid=1000, gid=1000`), is now created and runs of this new image now run under this user by default.  The user can install new packages and access the bootstrap chain, but cannot alter it or any other root-owned portions of the image's file system.

A new entrypoint script simplifies the process of running Spack.  Whether running a `RUN` command in a new dockerfile build based on this one, running this image on the CLI, or using it in a CI environment, the entrypoint logic ensures that `spack install ...` always works without any additional initialization necessary.

The above entrypoint includes a workaround for #12636.  The workaround involves precreating modulefile directories for all the targets identified as compatible with the current architecture (`_sp_compatible_sys_types`) to ensure that an entry for each is added to the `MODULEPATH` up-front.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@opadron While I'm a little agnostic about some parts of this (e.g. spack bootstrapping everything), I think some of the changes look pretty good.  Specifically, if the entrypoint changes 
 make the container more useful for testing in gitlab CI runners, I'd be happy about that.  The fact that we don't really have the ability to use the containers in CI without first sourcing the installed spack (something the pipeline code doesn't support at the moment) makes trying out the spack CI features kind of confusing and challenging.

**Comment by scottwittenburg** [comment]
@frankwillmore This is container rework I mentioned a minute ago.

**Comment by hartzell** [comment]
[edit: just noticed the merge referenced above and struck-through the second bullet below.  Sorry for the noise]

I've been playing with this with an eye towards understanding Spack and Docker tricks.  The branch still builds, although a checksum needs to be updated in the cmake package, the mpfr package needs to be updated (I grabbed the version from dev, which required me to also include the new-ish autoconf-archive package).

@opadron -- is this still something you're pursuing?  

- I'm curious why you're linking all of the various things into `/usr/local` rather than letting packages find them in the Spack tree.  Any packages that have magic dependencies that aren't specified in their package.py should be fixed, I'd argue.  Or, are you putting them there for the convenience of shell users?

- ~I'm also curious whether your entry point improvements are still relevant and if so whether they should/could go in under a less major PR?~

**Comment by hartzell** [comment]
This is probably intentional and/or a good thing, but since a shell in a container based on this image is running as the *spack* user, it's not able e.g. edit package definitions:

```
spack@621fc1e5d295:/opt/spack$ spack edit bison
==> Error: Insufficient permissions on '/opt/spack/var/spack/repos/builtin/packages/bison/package.py'!
spack@621fc1e5d295:/opt/spack$
```

**Comment by opadron** [comment]
@hartzell Thanks for having a look at this!  

> @opadron -- is this still something you're pursuing?

Yes, although I figured this was a sufficiently ambitious change set, and so I wanted to take a wait-and-see approach and get a feel for what other people think about this idea.  I'd be happy to put my attention back into fleshing this out more if there is interest.

> I'm curious why you're linking all of the various things into /usr/local rather than letting packages find them in the Spack tree. Any packages that have magic dependencies that aren't specified in their package.py should be fixed, I'd argue. Or, are you putting them there for the convenience of shell users?

The symlinking *does* make things convenient, which is nice, but the real reason I do this is because Spack has several dependencies on many of the commands from coreutils and other core packages that are not well documented.  For example, without `tar`, `gzip`, or `bzip2`, Spack is severely limited in what it can unpack, and that's just one example.  Spack doesn't currently check to see if it has an installed package that provides these utilities, and so it creates a bootstrapping problem that needs a solution before (in some cases) Spack can even load a package.

As for `/usr/local`, I had considered other prefixes but reasoned that it was the best choice since it's supposed to be for "local" packages (i.e.: separate from OS-managed software), it shouldn't require adding any extra `PATH`s or the like, and building everything from Spack is supposed to be the point of the image, anyway.

>This is probably intentional and/or a good thing, but since a shell in a container based on this image is running as the spack user, it's not able e.g. edit package definitions:

I hadn't thought of that, but I think it's for the best.  Keep in mind that you can always override the uid & gid that you run under if you need root access, and you can do the same while building another docker image using ours as a base. (Although if I come back to this PR, I'll probably want to make sure that the entrypoint still works regardless of the user you run as!)

**Pull request closed without merging**
