### PR TITLE
Work around substitution problem

### PR DESCRIPTION
**Pull request by OndrejMarsalek**
This works around a problem with substitution. With the original order, the build fails because '@MPICXX' is substituted first, which substitutes also part of '@MPICXX_LIB', thus preventing the substitution of this variable. A better solution would be a more robust substitution, but this should do it for now.

### CODE REVIEW

**Comment by OndrejMarsalek** [comment]
Good point, I was a bit too hasty and submitted it when I figured out what was breaking the build. It seems that the substitution mechanism wants a dictionary, so I am not sure what the best approach would be here - I would leave that to the authors.

As a workaround, it should be enough to just change the names of the variables so that they don't have this kind of conflict. Would that be OK?

**Comment by adamjstewart** [comment]
It honestly wouldn't be difficult to convert it from a dictionary to a nested-list. That is probably the safest solution.

**Comment by OndrejMarsalek** [comment]
It is still fragile in the sense that if someone unaware of the issue writes such a substitution nested list in the future, the issue will come up again.

One could check for shared beginnings of the strings and raise a warning, or even an error.

**Comment by OndrejMarsalek** [comment]
OrderedDict would be another option if you prefer that.

**Comment by tgamblin** [comment]
If you want to keep the dict *and* future-proof this, you could change all the substituted variables to have initial *and* final `@`'s.  Order doesn't matter if one name can't be a substring of another, and adding a final sentinel character fixes that.  So, you'd just change it to `@MPICXX@` instead of `@MPICXX`, and same for the others.

**Comment by tgamblin** [comment]
@OndrejMarsalek: can you change this to just use initial and final `@`'s?

**Comment by OndrejMarsalek** [comment]
I can put this in (though developers can change to PR, too), but it does not really future-proof it. Future authors of packages would still have to aware of the issue and use this convention. In this sense, it is the same using OrderedDict. It would be best, IMO, to improve the substitution mechanism. As a patch for now, this will do, though.

**Comment by junghans** [comment]
Couldn't one add `MPICXX=self.spec['mpi'].mpicxx` to the build targets to overwrite the variables?

**Comment by alalazo** [comment]
Closing as now the package uses a list of tuples, which preserves ordering.

**Pull request closed without merging**
