### PR TITLE
cmake: add -D_GNU_SOURCE for compilation (#8557).

### PR DESCRIPTION
**Pull request by twang15**

### CODE REVIEW

**Comment by adamjstewart** [comment]
@mathstuf

**Comment by alalazo** [comment]
@twang15 A couple of notes:
1. Briefly reading [here](https://lwn.net/Articles/590381) it seems that `_GNU_SOURCE` is a bit opinonated (and specific to Linux?). This is also reported in [the man page](http://man7.org/linux/man-pages/man7/feature_test_macros.7.html). Just to say that if we want to add such a macro, probably it would be good to apply it only in the few cases where it's really needed.
2. I recently installed the latest `cmake` with Intel 2018.02 without troubles using Spack. To be fair I have to say that I had to configure manually the Intel compiler using `ICCCFG`, etc. files.

**Comment by chuckatkins** [comment]
This shouldn't be needed.  None of the CMake dashboards that build with the Intel compiler need to do this, nor have I needed to on any of the other TOSS3 machines.  If this is actively a problem still then we should address it in upstream CMake also, although I haven't seen it.

**Comment by alalazo** [comment]
Closing as stale since a while and not reproducible by many other people. Feel free to reopen if still considered relevant.

**Pull request closed without merging**
