### PR TITLE
Remove Cray CC compilers causing problems on case-insensitive filesystems

### LINKED ISSUE #10318: Mac clone problem
```
$ git clone --depth 1 https://github.com/spack/spack.git

Cloning into 'spack'...
remote: Enumerating objects: 7553, done.
remote: Counting objects: 100% (7553/7553), done.
remote: Compressing objects: 100% (3961/3961), done.
remote: Total 7553 (delta 730), reused 4489 (delta 623), pack-reused 0
Receiving objects: 100% (7553/7553), 4.13 MiB | 7.28 MiB/s, done.
Resolving deltas: 100% (730/730), done.
Checking out files: 100% (4351/4351), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'lib/spack/env/cray/CC'
  'lib/spack/env/cray/cc'
  'lib/spack/env/craype/CC'
  'lib/spack/env/craype/cc'
```

It doesn't matter whether I do --depth 1 or not, it barfs like that. I'm on 10.13.6.  My HD is `APFS (encrypted)`

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #10318 

I wasn't actually able to reproduce #10318 on my macOS 10.14.2 using APFS, and these files have existed for over 3 years (#1288 and #1335), so I'm shocked that @paul-hammant had a problem. But I don't think these symlinks are actually necessary, since we add `lib/spack/env/case-insensitive` to the `PATH` as well.

### CODE REVIEW

**Comment by tgamblin** [comment]
I think it’s for the cray directory to have a case-insensitive subdirectory so that it’s clear cray has a CC compiler.  Also the compiler symlink paths in compilers/cray.py and compilers/ccs.py should be updated

**Comment by tgamblin** [comment]
We may need to look at this in a little more detail.  It looks like cray was moved to cce a long time ago, so we may be able to just delete the cray subdirectory.

I think the cce links here should point to cc, CC, and ftn  instead of cc, c++, f77, etc., just to get the name right for build systems that expect those names on cray:

https://github.com/spack/spack/blob/develop/lib/spack/spack/compilers/cce.py#L29

The counterpoint is that there might be more build systems that understand c++ than CC. I am not sure the right answer.  For other compilers like Intel, we have a lot more luck with libtool when the compilers are called icc, icpc, etc.  For cray I’m not positive it matters, but it would be more consistent.

**Comment by paul-hammant** [comment]
We always knew that HFS+ was a particularly *ropey* file system, and the new one from Apple was supposed to be truly modern. I'm on High Sierra though (10.13.6; paranoid that I may make my Mac slower with an upgrade) and the version of AFS for 10.13 might not be as *all singing all dancing* as 10.14. Branch juggling is hard, of course, so who'd blame them for not backporting every enhancement from 10.14's AFS to 10.13.

**Comment by adamjstewart** [comment]
> The `CC` link should go in a subdirectory called `case-insensitive`. 

There is already a `lib/spack/env/case-insensitive/CC`, why do we also need `lib/spack/env/cce/case-insensitive/CC`?

**Comment by adamjstewart** [comment]
It looks like Spack has been trying to add `lib/spack/env/cce` to the `PATH` but since it never existed, it was only adding `lib/spack/env` and `lib/spack/env/case-insensitive`. Everything should be good now. Let me try to build some stuff.

**Comment by adamjstewart** [comment]
Okay, I'm able to build `zlib%cce@8.4.6`, however, it looks like our `PATH` is backwards? From the `spack-build.env`:
```bash
export PATH="/mnt/a/u/sciteam/stewart1/spack/lib/spack/env:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/case-insensitive:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/cce:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/cce/case-insensitive:..."
```
I think these 4 directories should be in reverse order. I thought https://github.com/spack/spack/blob/develop/lib/spack/spack/build_environment.py#L345 was supposed to do that. Let me investigate.

**Comment by adamjstewart** [comment]
Okay, the most recent commit fixes things:
```bash
export PATH="/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/cce/case-insensitive:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/cce:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/case-insensitive:/mnt/a/u/sciteam/stewart1/spack/lib/spack/env:..."
```
I _believe_ this is the intended behavior, but correct me if I'm wrong.

**Comment by adamjstewart** [comment]
Still seeing some strange behavior. Although `lib/spack/env/cce` is in the `PATH` before `lib/spack/env`, the builds of `zlib` and `cfitsio` still pick up `lib/spack/env/cc` and `lib/spack/env/ftn` as the C and Fortran compilers. The latter path doesn't even exist! Let me see where we are setting `CC` and friends...

**Comment by adamjstewart** [comment]
Okay, I think everything is copacetic now. I was able to successfully install `zlib` and `cfitsio` on Cray CNL5 (Blue Waters) using CCE 8.4.6. Ready for a final review @tgamblin @becker33!

**Pull request merged**
