### PR TITLE
checksums: use sha256 checksums everywhere

### PR DESCRIPTION
**Pull request by tgamblin**
I'm still working on some straggler packages, but this covers nearly all of the MD5 hashes in Spack.  [NIST recommends](https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions) that projects move away from MD5, and we've been meaning to do this for a while.

Now that #12940 is available, we can fetch everything and hash it.  I've done that and re-written packages with SHA256's instead of with MD5 (or other algorithms).

I will also add tests to enforce this, and the use of kwarg labels on hashes (i.e., `sha256="abc123abc123"` instead of just `"abc123abc123"`).

Also, this makes the use of SHA256 consistent across Spack.  In addition to using a better hashing algorithm, we'd like to use a *consistent* checksum scheme everywhere so that we can eventually:

  1. incorporate archive checksums into our specs and have a consistent hashing algorithm across all specs (and distinguish between multiple releases of the same version with different tarballs).
  2. index mirrors with a consistent type of checksum, and not one that is dependent on how spack packages are written.

(2) is a reason this should go in *before* #12940 -- if we don't put this in first, mirrors using the new layout will need to be re-fetched (or at least reorganized) when hashes change.

- [x] convert existing md5, sha224, sha512, sha1 checksums to sha256
- [x] test to enforce use of `sha256=` in new packages

@citibeth FYI.

### CODE REVIEW

**Comment by healther** [comment]
> (2) is a reason this should go in before #12940 -- if we don't put this in first, mirrors using the new layout will need to be re-fetched (or at least reorganized) when hashes change.

why is that true? we could just reperform the hashing. 

Anyways I like this, especially the test and I think the main point here is that it should be merged quickly as most PRs would need to be fixed up. Can we provide a spack command for people to run that performs this rewrite locally?

**Comment by adamjstewart** [comment]
How was this conversion performed? When you downloaded tarballs, did you make sure the existing md5 matched before calculating the sha256? How did you handle hash changes?

I noticed a lot of packages still relying on md5. I assume this is because they are no longer available for download?

Can spack emit a warning any time someone downloads a package via md5? That will help depreciate it in addition to the unit tests.

**Comment by tgamblin** [comment]
@healther:

> > (2) is a reason this should go in before #12940 -- if we don't put this in first, mirrors using the new layout will need to be re-fetched (or at least reorganized) when hashes change.
> 
> why is that true? we could just reperform the hashing. 

#12940 has a new mirror/cache format where the files are named by checksum, and the old `package/package-version.tar.gz` names are symlinks to checksum files.  Among other things this means that if we want to have two packages with the same tarball, the tarball will only be downloaded once, because we can look it up in the index.  Since the checksum *is* the filename, it means users will need to rename files if the checksum in the package from, say, `md5` to `sha256`.  We could make a command to do that for all file in a mirror, but I'd rather not even tell users they need to.

**Comment by tgamblin** [comment]
@adamjstewart:
> How was this conversion performed? When you downloaded tarballs, did you make sure the existing md5 matched before calculating the sha256? How did you handle hash changes?

I mirrored (mostly) everything and ran this:
```bash
#!/bin/bash

echo "["
for file in $(find . -type f); do
    echo "  {"
    echo "    \"md5\":    \"$(md5sum $file | awk '{print $1}')\","
    echo "    \"sha1\":   \"$(sha1sum $file | awk '{print $1}')\","
    echo "    \"sha224\": \"$(sha224sum $file | awk '{print $1}')\","
    echo "    \"sha256\": \"$(sha256sum $file | awk '{print $1}')\","
    echo "    \"sha512\": \"$(sha512sum $file | awk '{print $1}')\""
    echo "  },"
done
echo "]"
```

I took that `json`, loaded it, and built a dict mapping every type of hash to `sha256`.  The translation looks up `md5` (or other) hashes in Spack packages in this `dict`, and it's smart about handling `md5="hashhashhash"` cases vs. `"md5": "hashhashhash"`, and cases with no label. It translates all those to forms with a `sha256` kwarg/key.  It's not 100% automatic -- there are packages (ones where people have written code at the package level, like `fenics` and `llvm`), that require manual tweaking, but the script gets us most of the way there.

> I noticed a lot of packages still relying on md5. I assume this is because they are no longer available for download?

Either that or they failed to fetch for some reason.  #12940 doesn't yet have a lot of reliability/retry logic built into it.  Also I think some sites throttle after the first few downloads of tarballs, so we have to fetch them over some longer time period.  Those are the "stragglers" I mean above.  I'm going to be updating the PR with those.

> Can spack emit a warning any time someone downloads a package via md5? That will help deprecate it in addition to the unit tests.

We can do that.  I want to get the hashes translated first.

@healther:
> Can we provide a spack command for people to run that performs this rewrite locally?

Yeah, I can turn my package-updating script into a Spack command, but as I said above it's not perfect and won't ever be.  I've been finding the rough edges by running it then running `spack test package_sanity` to make sure the packages still load properly.

**Comment by adamjstewart** [comment]
Looks like the only packages that conflict are PRs I've recently merged. I'll try to hold off on merging anything until this PR is merged.

**Comment by tgamblin** [comment]
@adamjstewart: it's easy to rebase this so don't worry about holding off.

**Comment by healther** [comment]
> We can probably take my bash script and make it into a command option as well (and get it to remove the final comma that makes the json invalid -- so annoying).

Yeah that's what I'm looking for. The problem isn't that _this_ PR acquires conflicts, it's that open PRs will acquire conflicts once this is merged, I'd rather be able to provide contributors with an easy way to convert my own PR. Not all PRs come from people as ~~experienced~~ resilient to rebase conflicts. :) 

> We could make a command to do that for all file in a mirror,

or we could ship the md5->sha256 map and perform the renaming when accessing the file and maybe folding it into `spack refresh` or something.

> #12940 has a new mirror/cache format where the files are named by checksum, and the old package/package-version.tar.gz names are symlinks to checksum files.

Actually I'm not sure if this won't break a workflow of ours. We have a mirror that is under the CI user, which does not update it automatically (historical reasons), so updating the mirror is currently done by copying the download cache of a manual instance that fetched all things, and then chowning the files. I don't think that will end up being a problem (we should just sort out our CI), but the symmetry between download cache and mirror was nice and changing might break other things that rely on this

**Comment by tgamblin** [comment]
@healther: 

> or we could ship the md5->sha256 map

If you have the file you don't really need a map.  You can just hash it.

> I don't think that will end up being a problem (we should just sort out our CI), but the symmetry between download cache and mirror was nice and changing might break other things that rely on this

They're still the same thing.

**Comment by tgamblin** [comment]
This should be ready to rebase once the tests pass.

I manually went through the various straggler packages and fixed broken URLs, verified checksums by fetching over https, etc.  I ended up removing 8 packages that were no longer fetchable.  I also removed old versions where the md5 didn't match, the old version wasn't needed, and there were obvious newer sha256-checked versions.

I've added a test that will enforce the use of sha256 for all new packages.  I had to add exceptions for the various manually-downloaded packages because I cannot get their archives.  To do that, I ended up adding a new attribute, `manual_download`, which the test checks for.  We can remove that once we get the manually downloaded packages converted; at least they are easy to find now.

**Pull request merged**
