### PR TITLE
Updating Paraview with latest versions

### PR DESCRIPTION
**Pull request by jrood-nrel**
This adds the latest versions of Paraview and a variant that will build the VisIt bridge.

I also needed to include a patch for an issue which I reported that hasn't gotten a response here: https://gitlab.kitware.com/vtk/vtk/issues/17322

I also tried to organize a little bit.

### CODE REVIEW

**Comment by olesenm** [comment]
It looks like you were a bit faster with tackling the new version. Just discussed this yesterday with @sbna about also including the catalyst patches. The vtk-m patch seems to have been missed, but without it you can get some really nasty config problems on older system (essentially Cmake bails out since it's parsing the wrong output).

```
# The VTK-m changes are slated for paraview-5.5.2
#
# The catalyst changes (the working directory for output) are slated for
# paraview-5.6. They are API-compatible with paraview-5.5 but not ABI compatible.
```

[paraview-552.patch.txt](https://github.com/spack/spack/files/2125305/paraview-552.patch.txt)

**Comment by jrood-nrel** [comment]
@olesenm Thanks for the reply, but I'm not sure I understand. Does any of this look like it shouldn't get merged? Or I am just missing the patches you have mentioned? Have you had the same VTK issue that my patch takes care of? I'm no expert in Paraview, so I'm open to any help. I just wanted to get 5.5 working so I could try getting Boxlib support and Visit bridge to work, which I think I have mostly working.

It seems really unfortunate that Paraview 5.5 is needing so many patches.

**Comment by olesenm** [comment]
The patches were just additional ones covering the vtkm issue that negatively affects some systems, and the Catalyst modifications. The patch for file-series is good to have, but no showstopper. However the Catalyst modifications aren't a bug at all, but essentially a backport for needed feature (handling the working directory of a simulation code). They are something we noticed while actively developing using the Catalyst interface. The changes are good but don't qualify for a dot patch.

It may hurt you to hear, but apart from the vtkm part I haven't experienced any real issues compiling paraview 5.5 (outside of spack). 

/mark

**Comment by sbna** [comment]
We solved the arc4random_buf undefined reference error by adding the dependency to the spack installation of expat (not using the vtk internal version of expat). You can have a look here https://github.com/RemoteConnectionManager/spack/commit/472f670469b3660b5d2740fca1b740392afcecb8. 
We will submit a PR as soon as we complete further tests.

**Comment by jrood-nrel** [comment]
I think I will close this PR then since it doesn't seem as complete, and it appears my vtkexpat patch does not seem necessary. It's no problem. I would prefer not to have to use a patch.

**Pull request closed without merging**
