### PR TITLE
py-backports-functools-lru-cache: add version 1.5

### PR DESCRIPTION
**Pull request by erimar77**
Includes version-specific URL per #2737 and #4365.

### CODE REVIEW

**Comment by alalazo** [comment]
This PR has conflicts. Can you please either fix them?

**Comment by mathstuf** [comment]
There are still conflicts.

**Comment by healther** [comment]
resolved merge conflict, why do we need the three URLs in the first place?

**Comment by mathstuf** [comment]
Here, I'm not 100% sure. Seems like spack should be able to figure it out on its own to me.

**Comment by adamjstewart** [comment]
> why do we need the three URLs in the first place?

This is due to an old bug in Spack. See #2737. If you remove the URLs:
```python
    url = "https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.4.tar.gz"
                                                                                
    version('1.5', '20f53f54cd3f04b3346ce75a54959754')                          
    version('1.4', 'b954e7d5e2ca0f0f66ad2ed12ba800e5')                          
    version('1.0.1', 'c789ef439d189330b99872746a6d9e85',                        
            url="https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.0.1.zip")
```
all of the `.tar.gz` get replaced with `.zip`:
```
$ spack info py-backports-functools-lru-cache
...
    1.5      https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.5.zip
    1.4      https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.4.zip
    1.0.1    https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.0.1.zip
```

**Pull request merged**
