### PR TITLE
Add 3.5.2; Add optional cpp implementation enable for py-protobuf

### PR DESCRIPTION
**Pull request by mcneish1**
Work in progress: see below

~To actually enable the c++ implementation, these flags need to be set:
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
[Reason, I think](https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/python/google/protobuf/internal/api_implementation.py#L69)~
EDIT: nope. The c++ stuff gets picked up or not [here](https://github.com/google/protobuf/blob/ed4321d1cb33199984118d801956822842771e7e/python/google/protobuf/internal/api_implementation.py#L40)

~However, I can't figure out how to do that. I'm not seeing any way to set additional runtime environment variables in the docs (I might have missed them). Even if I found those, if I `spack activate py-protobuf` and then `module load python-[...]` but don't `module load py-protobuf-[...]`, that doesn't seem like it will pick up the flags?~

### CODE REVIEW

**Comment by adamjstewart** [comment]
> I'm not seeing any way to set additional runtime environment variables in the docs (I might have missed them).

http://spack.readthedocs.io/en/latest/spack.html#spack.package.PackageBase.setup_environment

> Even if I found those, if I `spack activate py-protobuf` and then `module load python-[...]` but don't `module load py-protobuf-[...]`, that doesn't seem like it will pick up the flags?

http://spack.readthedocs.io/en/latest/module_file_support.html#autoload-dependencies

**Comment by mcneish1** [comment]
Perfect, I'll look through those.

**Comment by mcneish1** [comment]
Some issues:
 * google/protobuf#4605
3.5.2 doesn't even package the cc files needed. This results in it building an empty .so, which fails to import, silently.
Their pip packaging in general is not great. Of everything back to 2.6.1, only 45% have the cc files packaged.
 * py-protobuf does not install/uninstall cleanly when the --cpp_implementation flag is passed.
It installs straight to python's site-packages directory.
 * The c++ version doesn't actually need those environment variables after all, at least as far back as 2.6.1.

---

I'm starting to think the +cpp should be a +python (or something like that) on protobuf, rather than its own package. The pip packaging and versioning issues with the protobuf spack package would both be nicer that way.

That would be:
 * py-protobuf: depends_on('protobuf +python') and nothing else
 * protobuf: add python variant, only ever compile that with --cpp_implementation
 * add a patch (or upstream something) to put py-protobuf where it's supposed to be on installing

Is that something you spack would be okay with?

**Comment by adamjstewart** [comment]
> py-protobuf does not install/uninstall cleanly when the --cpp_implementation flag is passed.
It installs straight to python's site-packages directory.

This has nothing to do with the flag. The default `install_args` in `PythonPackage` is responsible for adding the installation prefix flags. If you override it, you will need to add these arguments yourself. Does it really need that flag at install time or only at build time?

**Comment by mcneish1** [comment]
Oh, that makes sense. Newest commit should fix that.
Yes, unfortunately it needs the flag in both places, I checked again just now.

**Comment by mcneish1** [comment]
Seeing as it's working as is, it's probably a good idea to just merge it. I'll look at fixing protobuf in a separate commit in a couple days.

**Pull request merged**
