### PR TITLE
Simplified directory layout trees with symlinks

### PR DESCRIPTION
**Pull request by scheibelp**
Directed at: @mamelara @mplegendre (views)
Possibly also of interest to: @alalazo (create simplified module names)

I'm curious if folks have "can it do x?" questions (I don't expect folks to read the whole thing, although the high-level description is likely useful).

High level:

Create simplified directory structure which allows a user to navigate a set of installed packages. This does not alter the existing installation paths but rather provides a view. More generally: define projections of packages to simplified names for other purposes, for example simplified module file names.

A user first creates a collection of packages, called a "tree"; the must also define a projection of packages to simplified names. Given a projection, a set of symlinks can be created for a tree. This includes logic to detect collisions between simplified names. The projection configuration includes features which help avoid collisions.

```
spack tree create tree1
spack tree add tree1 mpi
(edit projections.yaml)
spack tree --root=/usr/spackview/ --projection=p1 set tree1
spack tree project tree1
(creates symlinks under /usr/spackview/)
```

The result could look something like:

```
/usr/spackview/
    bzip2-1.0.6 (symlink to full spack prefix)
    python-2.7.12
    ...
```

Functionality also allows for creating hierarchies (based on compiler, dependency, etc.)

More details below:
1. spec.format syntax is now case-insensitive
2. This also provides functionality to create symlinks to specific files in a package.
### spec.format updates

This includes updates to spec.format so you can specify format strings that are more usable across different packages. For example:

```
"${PACKAGE}-${VERSION}${DEP:mpi:-${PACKAGE}-${VERSION}${?:+psm:-psm}}${?:%gcc@4.4.7::-gnu-${COMPILERVER}}"
```

Breaking it down:

```
${PACKAGE}-${VERSION}
```

Means the same thing as before

```
${DEP:mpi:-${PACKAGE}-${VERSION}${?:+psm:-psm}}
```

This includes the MPI implementation and version where applicable (and also differentiates builds with and without +psm). For packages which do not depend on MPI this will evaluate to an empty string.

```
${?:%gcc@4.4.7::-gnu-${COMPILERVER}}
```

This is a 4-tuple, separated by ':'. This prints nothing if the compiler is gcc version 4.4.7 and otherwise prints something like e.g. gnu-4.8.5
### Alternative projection syntax

This includes a yaml format for projecting specs to strings and is specifically oriented towards generating paths. This is an alternative to the updated spec.format syntax and is intended to be easier to use in more complex cases. For example:

```
all:
  components:
  - this:"${PACKAGE}-${VERSION}"
  - dep: mpi
```

A package "foo" that doesn't depend on mpi would project to (for example) "foo-3.5". The "dep" component is recursive, so if "foo" did depend on mpi it would project to "foo-3.5-openmpi-1.10.1".

To get something like the spec.format example above the components section would appear as follows:

```
all:
  components:
  - this:"${PACKAGE}-${VERSION}"
  - dep: mpi
  - "once:compiler:this?:%gcc@4.4.7::gnu-${compilerver}"
mpi
  extra_components:
  - this?:+psm:psm
```

One of the intended benefits of component-based specifications is that one can consider package-specific variants on a per-package basis.

One can also create a hierarchy like:

```
all:
  components:
  -dep: mpi
  - /
  -this:"${PACKAGE}-${VERSION}"
```

This will create a projection like:

```
/usr/spackview/
    openmpi-1.10.2/foo-3.5
```

As it is, this projection will actually fail if it includes mpi and a package which depends on it, since the package prefix contains the mpi prefix. To avoid that conflict, component syntax provides the "top-level-basedir" property.

```
all:
  components:
  - dep: mpi
  - /
  - this:"${PACKAGE}-${VERSION}"
mpi:
  top-level-basedir: mpi
```

Which will create a hierarchy like:

```
/usr/spackview/
    mpi/openmpi-1.10.2
    openmpi-1.10.2/foo-3.5
```

### CODE REVIEW

**Comment by alalazo** [comment]
@scheibelp Ok, now I get what you meant by projection! The PR looks really interesting : will it be part of v0.10 ? Or later ?

**Comment by tgamblin** [comment]
@alalazo: probably the release after that, but I want to get @scheibelp's RPM generation support, this tree support, and something like it for module naming into the next release.  All of these involve mapping the (large) spack build space onto a smaller set of names and doing something sensible with dependencies

**Comment by TomasPuverle** [comment]
Cool!  Well, since you asked, here are my questions:  

a) Can it infer the common tree (really a DAG) for N "top-level" packages (especially libraries)?
b) Can it infer it given a partial spec of one or more "lower-layer" dependencies?  (e.g. I want library A & B; get me a version in which they both rely on C@...)

**Comment by scheibelp** [comment]
@TomasPuverle 

> Can it infer the common tree (really a DAG) for N "top-level" packages

It cannot; I could add that although I'm not sure what the intent is. Are you saying it would be of interest to project just the members of the intersection? As of now if you project a set of top-level packages you can choose to project just those packages or you can choose to also project their dependencies (transitive).

Also potentially relevant: the logic currently does not prioritize packages based on their dependents when a conflict arises: if there are two versions of package Z installed (Z1 and Z2), and two dependents require Z2, and Z1/Z2 project to the same name, the logic currently does not have a notion of preferring Z2 because there are two packages which depend on it.

This means that if packages X and Y depend on Z2, and you project X (or Y) transitively, then the projection may choose Z1. I can imagine it would be useful to allow the user to prioritize Z2 in this case; IMO if some package W depended on Z1 it would be more complicated. I'll note that regardless of whether Z1 or Z2 is projected, X and Y RPATHs would still refer to the correct version of Z, namely Z2.

> Can it infer it given a partial spec of one or more "lower-layer" dependencies? (e.g. I want library A & B; get me a version in which they both rely on C...

Not currently: the general theme of this and the previous answer is that currently there aren't options to configure views based on dependencies, for example to project the precise version a package depends on when the package itself is projected. So far I've avoided this because these sorts of constraints could quickly become unsatisfiable, but this could be supported with the recommendation that it is only used for a few top-level packages.

Let me know if that raises more questions.

Thanks!

**Comment by becker33** [comment]
Closing this; superseded by #9679

**Pull request closed without merging**
