### PR TITLE
Advice to users are hidden when rendering issue templates

### PR DESCRIPTION
**Pull request by alalazo**
This PR makes a few minor improvements to issue templates:

- [x] Adds fancy unicode emoticon next to the title :slightly_smiling_face: 
- [x] Turn advice to users into comments, so that they'll not be displayed if not removed
- [x] Adds a field to report which Spack version the user is running
- [x] Automatically marks bug reports  as "triage"
- [x] Adds a final checklist for convenience of users reporting an issue

### CODE REVIEW

**Comment by alalazo** [comment]
Apparently I'm hitting https://github.com/actions/checkout/issues/23

**Comment by scheibelp** [comment]
> Automatically marks bug reports and feature requests as "triage"

My only request is that this only apply the `triage` tag to bug reports. Other than that this looks excellent.

**Comment by adamjstewart** [comment]
I'll look at this in more detail at some point. For comparison with other repos, I'm really fond of both [matplotlib](https://github.com/matplotlib/matplotlib/issues/new)'s and [pytorch](https://github.com/pytorch/pytorch/issues/new/choose)'s issue templates.

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
