### PR TITLE
Updating zfp version

### PR DESCRIPTION
**Pull request by markcmiller86**
Update to newest ZFP version, 0.5.2.

Cut down on and minor corrections to info text too

### CODE REVIEW

**Comment by markcmiller86** [comment]
Thanks for quick response! So, what action do I take, if any, to *clean up* after a branch is "complete" and is that after a PR is approved or merged? I donnu if I have push access to repo to do the delete myself. And, if so **must** I do that on ``develop`` or does it matter?

**Comment by healther** [comment]
Someone with write access (afaik @alalazo @adamjstewart @scheibelp @tgamblin, not sure if this list is complete) needs to merge

**Comment by alalazo** [comment]
Restartint `r-cpp` for the third time. Probably failing due to slow network connection. As soon as that one passes, I'll merge this.

**Comment by alalazo** [comment]
@markcmiller86 I cleaned the branch, so no worries about that. In any case, there's a button on the web interface to delete (or restore) it. 

If you need to do it from command line it's basically removing a remote branch. Not 100% sure on the syntax, but it should be something like:
```console
$ git push <remote> --delete <branch>
```

**Pull request merged**
