### PR TITLE
External modules now search for python directories

### PR DESCRIPTION
**Pull request by krafczyk**
This is for modules which specify python modules.

### CODE REVIEW

**Comment by krafczyk** [comment]
This is for #2550

**Comment by tgamblin** [comment]
@krafczyk: this looks pretty good, BUT it will fail in the case where an external prefix contains multiple versions of Python, which is generally something we want to support (people add `/usr` to externals all the time).  It seems like the right thing to do here would be to add a syntax for referring to the external's version... so instead of:

```yaml
    lib/python*.*/site-packages
```

We'd need:

```yaml
    lib/python{version[:2].dotted}/site-packages
```

Where the part in `{}` is an expression that can work on the external spec (e.g. it would give you `spec.version[:2].dotted`).  I think this would be worth adding later... we can merge this as-is for now.

**Comment by alalazo** [comment]
Not sure what happened here, but CI never really started.

**Comment by alalazo** [comment]
Closing this old PR as stale. Feel free to reopen if you think otherwise.

**Pull request closed without merging**
