### PR TITLE
Add extra logic for C std flags on PGI, XL, and Cray

### PR DESCRIPTION
**Pull request by chuckatkins**
Follow up to #11618

### CODE REVIEW

**Comment by chuckatkins** [comment]
@codeandkey

**Comment by chuckatkins** [comment]
@ax3l Is there a policy in spack on how to handle flags for strict language conformance vs relaxed, i.e. with extensions?  With XL, for instance, it would be the difference in `-std=c99` vs `-std=gnu99` while with Cray it could be `-h c99,conform` vs `-h c99,gnu`.

**Comment by ax3l** [comment]
That's a good question, I just know that CMake defaults to the native ones if available... maybe @alalazo or @tgamblin know that?

**Comment by chuckatkins** [comment]
> I just know that CMake defaults to the native ones if available...

CMake has separate variables for each, i.e. `CMAKE_C99_STANDARD_COMPILE_OPTION:STRING` and `CMAKE_C99_EXTENSION_COMPILE_OPTION:STRING` and which get's used is determined by `CMAKE_CXX_EXTENSIONS:BOOL`, which defaults to `ON` since that's generally the default mode of compilers.  i.e. gcc >= 5.0 with no std flags defaults to using `-std=gnu11`.

**Comment by chuckatkins** [comment]
So, are we good with using the "strict standard" flags or should we be using the "extended standard" flags?  I'd lean more towards extended since that's the default mode of most compilers.  I can do it either way though.

**Comment by tgamblin** [comment]
I lean towards extended as well because many packages assume them as they are default.

**Comment by chuckatkins** [comment]
I'l adjust this to use the extended flags then

**Comment by chuckatkins** [comment]
@tgamblin I don't really understand the code coverage CI failures happening here

**Comment by chuckatkins** [comment]
So I think this is good to merge, I just don't know about the CI coverage failures.

**Comment by ax3l** [comment]
Should not be a problem, tbh.

**Pull request merged**
