### PR TITLE
add libs property to IntelMkl and IntelParallelStudio

### PR DESCRIPTION
**Pull request by davydden**
part of https://github.com/spack/spack/pull/9032

### CODE REVIEW

**Comment by lee218llnl** [comment]
@davydden, have you tried building a package that uses this? I may be doing something wrong, but the build  of a package that tries to use scalapack from intel-parallel-studio@cluster.2019.3 failed with this:
` ==> Error: InstallError: Cannot find a BLACS library for the given MPI.

/usr/WS2/lee218/spack.pr10993/lib/spack/spack/build_systems/intel.py:797, in scalapack_libs:
        794            blacs_lib = 'libmkl_blacs_intelmpi'
        795        elif '^mpt' in spec_root:
        796            blacs_lib = 'libmkl_blacs_sgimpt'
  >>    797        else:
        798            raise_lib_error('Cannot find a BLACS library for the given MPI.')
        799
        800        int_suff = '_' + self.intel64_int_suffix
 `

**Comment by davydden** [comment]
> have you tried building a package that uses this?

yes, I did and it worked for me from my own branch https://github.com/davydden/spack/tree/develop_stable_mod , perhaps since I forked (several days ago) something changed upstream and broke this PR? Let me make this branch start from the same origin as my custom `develop` and then would you please try again?

**Comment by davydden** [comment]
there are just two other commits I use in my custom branch, which are in https://github.com/spack/spack/pull/10992 and https://github.com/spack/spack/pull/10628 . 

It is possible that https://github.com/spack/spack/pull/10992/#discussion_r268050227 is a relevant change...

**Comment by davydden** [comment]
p.s. @lee218llnl  did you try merging this branch or you checked it out? If you merged to `develop`, could you try checking it out instead?

**Comment by lee218llnl** [comment]
I think this can be fixed by adding intel-parallel-studio to the spec_root search in lib/spack/spack/build_systems/intel.py, scalapack_libs function.

**Comment by lee218llnl** [comment]
> p.s. @lee218llnl did you try merging this branch or you checked it out? If you merged to `develop`, could you try checking it out instead?

I did a checkout of your branch.

**Comment by davydden** [comment]
> I think this can be fixed by adding intel-parallel-studio to the spec_root 

Not sure, if you build something which needs `scalapack`, there should be `mpi` around in the spec anyway.

The issue could be with my understanding of `self.provides()`. I thought that it's `true` only if a given package is being used to provide a virtual dependency. But it looks like it returns `true` if the package **can** in principle provide certain library. @alalazo @scheibelp could you please correct me if I am wrong?

**Comment by davydden** [comment]
@lee218llnl 

> I think this can be fixed by adding intel-parallel-studio to the spec_root

could you please run in debug mode `spack --debug install <spec>`?

**Comment by lee218llnl** [comment]
@davydden I do have intel-parallel-studio cluster edition installed via spack and working providing MPI. The problem is that the scalapack libraries provided by Intel have different flavours, depending on which MPI you use. Currently the intel build system supports openmpi, mpich, intel-pmi, and mpt as MPI providers. I am suggesting adding a switch for intel-parallel-studio in https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/intel.py#L777. When I add this, I am able to get past this error and build qbox OK.

**Comment by davydden** [comment]
@lee218llnl ah, I see. What's the right lib in this case, 
```
blacs_lib = 'libmkl_blacs_intelmpi'
```
?

**Comment by lee218llnl** [comment]
@davydden yes, blacs_lib = 'libmkl_black_intelmpi' should do the trick

**Comment by davydden** [comment]
> yes, blacs_lib = 'libmkl_black_intelmpi' should do the trick

great, please give another try.

**Pull request merged**
