### PR TITLE
Module files won't use CPATH by default, but language specific vars

### LINKED ISSUE #11555: CPATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH and CMake
So I had a recent issue with CMake 3.14.x where the `include_directories(SYSTEM <paths>)` was not suppressing warnings from "system" headers. It turns out this is a change in behavior in CMake and it has to do with Spack setting `CPATH` in the modules I was loading. It looks like `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` are the equivalent of `-isystem` where `CPATH` is the equivalent of `-I`. So with this issue I am just curious if `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` should be used instead of `CPATH` in the future? I think @scheibelp was dealing with `CPATH` issues in the past. Also the CMake issue regarding this is here: https://gitlab.kitware.com/cmake/cmake/issues/19291

### PR DESCRIPTION
**Pull request by alalazo**
fixes #11555

Every path in `CPATH` is equivalent to a `-I` path to the compiler, while every path in `*_INCLUDE_PATH` is equivalent to `-isystem`. The latter avoids the noise due to warnings coming from 3rd party libraries that a project depends on.

### CODE REVIEW

**Comment by alalazo** [comment]
@jrood-nrel @bvanessen Can you check if this solves your issue in #11555 ? 

Also, as far as I can tell removing `CPATH` will result in a change of behavior for Fortran codes since `.mod` files are searched in paths specified by `-I` and there's no language specific environment variable for Fortran similar to `C_INCLUDE_PATH`. Is it a common practice to put `.mod` files into `include` directories? If not I think we can safely go ahead and merge this PR.

**Comment by adamjstewart** [comment]
@tgamblin this reminds me of our Bazel/TF discussion on `-I` vs `-isystem`

**Comment by glennpj** [comment]
Fortran .mod files are found by `-I` directives. It is common practice to put them in `/include` directories that will wind up in `CPATH`. My understanding of gfortran is that it will use gcc variables so `C_INCLUDE_PATH` should still work. For Intel ifort the .mod file search path uses `CPATH` and `INCLUDE`. To cover that, you can add the `INCLUDE` variable to the changes. I am not sure what other Fortran compilers like PGI and NAG use.

**Comment by alalazo** [comment]
@glennpj 

> My understanding of gfortran is that it will use gcc variables so C_INCLUDE_PATH should still work.

`C_INCLUDE_PATH` is equivalent to `-isystem` not to `-I` and is claimed in the docs to be language specific. That's why I think there could be issues with Fortran. I have to say though that I didn't try out an example yet to verify if this is a real issue or not.

**Comment by jrood-nrel** [comment]
Sorry I probably won't be able to test this in the near future.

**Comment by glennpj** [comment]
@alalazo Good point. Adding `INCLUDE` would cover ifort but there is the possibility that some packages that use gfortran, and use .mod files from dependencies, would break.

**Comment by glennpj** [comment]
There is some question as to whether gfortran actually uses `CPATH`. 
https://stackoverflow.com/questions/23991664/gfortran-include-path-is-there-an-alternative-to-passing-multiple-i-options

Here is a link to the documentation for the Intel compiler:
https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-using-module-mod-files

**Comment by alalazo** [comment]
@glennpj Thanks for the links. I can confirm empirically (tested that with an helloworld example + gfortran-9) that `CPATH` doesn't have the same effect as `-I` for `gfortran`. The difference seems that `CPATH` only affects paths used to include C headers via preprocessor, while `-I` also activates search for `.mod` files in that directory.

If that's the case I think we can safely add `INCLUDE` to the list of variables and have a somewhat backward compatible behavior.

**Comment by alalazo** [comment]
@tgamblin @becker33 @scheibelp Going to merge this since it has been posted for one week in the `modules` channel on slack and encountered no objections. Being a few lines change it's also easy to be reverted.

**Pull request merged**
