### PR TITLE
Add quiet option to buildcache list

### PR DESCRIPTION
**Pull request by daveh86**
Add a quiet option to buildcache list. Currently, the output strings contain extra words, lines of text and quotation marks, which can make string parsing inconvenient. The quiet option will silence these extras and print hash and package name pairs.

### CODE REVIEW

**Comment by daveh86** [comment]
I've added as much testing as I can in the short term.

All of the paths that are currently tested have testing with the quiet option. The drop in coverage appears (as far as I can tell) to come from those paths in fetch which are untested and from the lack of testing of buildcaches in general. 

Likely that is a worthwhile thing to take on, but would not be part of this change.

**Comment by tgamblin** [comment]
I think I fixed all the conflicts that #5776 caused here.

**Comment by daveh86** [comment]
Thanks @tgamblin . I've resolved the one outstanding issue and this is now passing most of the PR tests again.

**Comment by tgamblin** [comment]
@daveh86: Changes like this probably make sense in more places throughout Spack. Do you think there is a name we could use for such options that would be consistent throughout Spack?

Git's `--porcelain` options are the closest I can think of, since porcelain stuff is designed to be machine-parsable in `git`.  Do you have any better ideas?

Also does this output like this:
```
pkg1 abc123
pkg2 abc123
pkg3 abc123
pkg4 abc123
```

or like this:
```
pkg1 /abc123
pkg2 /abc123
pkg3 /abc123
pkg4 /abc123
```

The latter is re-parsable and could be used with, e.g., `spack uninstall`.

**Comment by daveh86** [comment]
@tgamblin agree, this kind of option makes sense all over the codebase. I had deliberately left this option to only the one code-path I could carve out easily.

I don't have any suggestions for naming, so would be happy to follow the convention of `--porcelain` for this.

This outputs like your second example, with the leading `/` left in place so that the output can be machine parsed with things like `spack buildcache install` or `spack uninstall`.

**Comment by gartung** [comment]
@daveh86 After I added better matching for partial specs passed on the command line, passing /hash to buildcache install no longer works. 
I have a pull request to improve the documentation and fixes a bug where symbolic links were turned into copies of files.
https://github.com/LLNL/spack/pull/5894

@scheibelp is working on a pull request to have 'spack install' use build caches 
https://github.com/LLNL/spack/pull/5242

**Comment by gartung** [comment]
I would close this in favor of #10052

**Pull request closed without merging**
