### PR TITLE
add debugging output when Spack detects that an unsupported arch

### PR DESCRIPTION
**Pull request by scheibelp**

### CODE REVIEW

**Comment by mwkrentel** [comment]
@scheibelp  Are you sure you added debug info in the correct place?

The 'spack install' failure that I reported fails in
spack/lib/spack/spack/package.py, not in architecture.py.
This doesn't produce any extra output for my failure.

This is from your features/debug-os-output branch (6bc5f011).

```
$ spack install zlib arch=cray-fe-x86_64
==> Installing zlib
==> Searching for binary cache of zlib
==> Warning: No Spack mirrors are currently configured
==> No binary for zlib found: installing from source
==> Error: ValueError: Can't recreate arch for spec cray-sles12-x86_64
on current arch cray-cnl6-mic_knl; spec architecture is too different

/gpfs/mira-home/krentel/arch/spack-peter/lib/spack/spack/package.py:904, in architecture:
        901        """Get the spack.architecture.Arch object that represents the
        902        environment in which this package will be built."""
        903        if not self.spec.concrete:
  >>    904            raise ValueError("Can only get the arch for concrete package.")
        905        return spack.architecture.arch_for_spec(self.spec.architecture)
```

**Comment by scheibelp** [comment]
> Are you sure you added debug info in the correct place?

My intent (which I failed to mention) was that you rerun the command with `-d` (`spack -d install`) and it then prints out the extra output. I suppose it could go into the exception itself, but generally I think it's worth printing out useful-to-devs-but-not-to-users stuff in the debug output and not in the exceptions (or whatever reaches the user).

**Comment by mwkrentel** [comment]
Ok, as long as that's what you intended, then fine.

**Comment by alalazo** [comment]
@scheibelp Do you still want to put this debug message in? If so, ping me for review once this is updated.

**Comment by alalazo** [comment]
@scheibelp Closing this PR, but feel free to reopen if you think it should still be considered.

**Pull request closed without merging**
