### PR TITLE
libbamtools.a path fix

### PR DESCRIPTION
**Pull request by Antenagora**
the path to for bamtools@2.5 libbamtools.a was not correct

### CODE REVIEW

**Comment by scheibelp** [comment]
I suspect the `lib`/`lib64` naming may be OS-specific. However, when I tried to install `bamtools` myself to confirm this, it wasn't able to download. I could not find an archive: it appears that they have switched to git tags. Were you able to install `bamtools` without modifying the Spack package? Or are you using an external version of `bamtools`?

**Comment by adamjstewart** [comment]
You could also ask `bamtools` where its libraries are by using `spec['bamtools'].libs`. There are various attributes of the `libs` object you can use depending on whether you want the library directories, filenames, or ld flags. This will support bamtools regardless of whether the libraries are in `lib` or `lib64`.

**Comment by adamjstewart** [comment]
Ping @Antenagora, I would refactor this to use `spec['bamtools'].libs`. Let me know if you need help with anything.

**Comment by alalazo** [comment]
Closing as stale (no answer to https://github.com/spack/spack/pull/15202#issuecomment-678692863)

**Pull request closed without merging**
