### PR TITLE
openfoam: correspond to build with Fujitsu compiler.

### PR DESCRIPTION
**Pull request by t-karatsu**
I want `openfoam` to recognize Fujitsu compiler.
So, I created directory included setting information of Fujitsu compiler based on Clang.

### CODE REVIEW

**Comment by olesenm** [comment]
From your changes I guess that the Fujitsu compiler is derived from clang?
If so, please follow-up on the [OpenFOAM issue 1671](https://develop.openfoam.com/Development/openfoam/issues/1671).
I think this type of approach might make some sense.

**Comment by t-karatsu** [comment]
Thanks for your comment @alalazo @olesenm !

To be precise, the Fujitsu compiler has a function that works equivalently to Clang. Basically, it is assumed that this function is enabled.

Since we first aim to be able to install `openfoam` with Spack, so this time, I just took the method of diverting the configuration file of Clang. It is very simple.
Apart from that, another team is tuning for `openfoam`, so we believe they will make suggestions for changes to the upstream as needed.
So we hope that any countermeasures for `openfoam` in Spack will be merged as soon as possible.

I confirmed the issue, thanks.
However, in Spack processing, the directory name including the name of the compiler  is searched in `openfoam`, so an error will occur when `fj` is searched.
Is the problem solved by replacing the name of the compiler with `Clang10Fujitsu` and adding processing to analyze `COMPILER_FAMILY`?

- Reference information about Fujitsu compiler
```
Compiler generic name in Spack : fj
C compiler name : fcc
C++ compiler name : FCC
Fortran compiler name : frt
```

**Comment by olesenm** [comment]
Are you working with openfoam 1912 or older? If 1912, we work together on the upstream side to properly integrate the Fujitsu compiler into OpenFOAM - this would also be my preference. 

Your current patch is okay for local use, but I would prefer not to have it integrated into spack in its current form. 
After we determine which changes we need upstream, we can see about using them as a patch for supporting older OpenFOAM in spack.

**Comment by t-karatsu** [comment]
>Are you working with openfoam 1912 or older?

I confirmed the installation of openfoam version `1912`.

>we can work together on the upstream side to properly integrate the Fujitsu compiler into OpenFOAM - this would also be my preference.
Your current patch is okay for local use, but I would prefer not to have it integrated into spack in its current form.
After we determine which changes we need upstream, we can see about using them as a patch for supporting older OpenFOAM in spack.

We will fully cooperate in improving the upstream! In addition, I would like the current patch to be incorporated as a temporary fix for the limited members who are already using the Fujitsu compiler.
If the current patch seems to be a problem, please let me know the problem.
Of course, I would like to cooperate with re-correction for Spack after the upstream correction method has been clarified.

**Comment by olesenm** [comment]
Hi @t-karatsu 

I've made some modifications to your changes, that should integrate better with what we have in mind for upstream changes.
I've discussed internally, and we will be going with `Fujitsu` as the compiler designation in OpenFOAM (easier for us to know what it means than `fcc` or `fj`). It is also probably safer/cleaner for us to have a `linuxARM64Fujitsu` directory instead of the compiler family workaround previously mentioned.

I have reworked your commit as the following:
https://github.com/olesenm/spack/tree/openfoam-fujitsu

Could you please check that it works for you or needs modification. If it does work, then please do a forced push onto this merge request.

Cheers,
/mark

**Comment by t-karatsu** [comment]
Hello @olesenm 

I cherry-picked your modification, and it works very good on my environment!
So I merged your modification into this pull request.

Thanks for your cooperation.

**Comment by olesenm** [comment]
Hi @alalazo - not sure why there are two commits, should be squashed together.

Otherwise it's how I'd like it to look, shouldn't collide with upstream changes, and @t-karatsu confirmed that it is fit-for-purpose.

**Pull request merged**
