### PR TITLE
Darshan 3.1.7 and develop versions

### PR DESCRIPTION
**Pull request by fbudin69500**
* Add version 3.1.7
* Add develop branch (git master)

### CODE REVIEW

**Comment by fbudin69500** [comment]
@chuckatkins

**Comment by chuckatkins** [comment]
Please also update the darshan-util package together with the darshan-runtime

**Comment by chuckatkins** [comment]
@carns We're updating this as part of the Data & Viz SDK. Do these changes look good to you, aside from also updating the darshan-util package?

**Comment by carns** [comment]
Yes, this looks great to me modulo the darshan-util updates.  Thanks!

**Comment by fbudin69500** [comment]
I updated `darshan-util` too now.

**Comment by fbudin69500** [comment]
@carns : Does it look good to you now that `darshan-utils` has been updated too?

**Comment by carns** [comment]
> @carns : Does it look good to you now that `darshan-utils` has been updated too?

Yep! LGTM

**Pull request merged**
