### PR TITLE
Packages/kokkos

### PR DESCRIPTION
**Pull request by womeld**
Update Kokkos spackage to include support for latest release, 2.7.00.

### CODE REVIEW

**Comment by adamjstewart** [comment]
It looks like your branch has a few hundred additional files changed. You may need to rebase this branch on the latest develop.

**Comment by womeld** [comment]
Thanks @adamjstewart! I got some help from @junghans and this PR should be pointed at the right branch (develop) and rebased. It is a tiny change vice the last one.

**Comment by adamjstewart** [comment]
Travis appears to be hung, closing and reopening to give it a kick.

**Comment by womeld** [comment]
Thanks Adam! I wondered why the CI was sad.

**Pull request merged**
