### PR TITLE
Add OpenFOAM 1912

### PR DESCRIPTION
**Pull request by olesenm**

### CODE REVIEW

**Comment by olesenm** [comment]
Added a single line to openfoam/package.py, so the code coverage failure would seem to be quite unrelated.

**Comment by adamjstewart** [comment]
@olesenm see the note at the bottom of https://spack.readthedocs.io/en/latest/contribution_guide.html#coverage

**Comment by olesenm** [comment]
@adamjstewart OK - must have been the osx bits I guess. Was just worried about not being able to fix/resubmit before heading off on hols. Cheers

**Comment by adamjstewart** [comment]
Yep, #14333 should fix that.

**Pull request merged**
