### PR TITLE
Minor upgrades to `spack diy`:

### PR DESCRIPTION
**Pull request by citibeth**
Small changes to DIY, hopefully they can be merged quickly.

1. Add source_path option to specify where the downloaded source is found.  (Defaults to '.', previously hardcoded to '.')

2. Add missing `-j` option to match `spack install`

### CODE REVIEW

**Comment by citibeth** [comment]
@tgamblin What, if anything, should I do about the codecov issues?

**Comment by adamjstewart** [comment]
You could try adding a unit test to `lib/spack/spack/test/cmd/diy.py` (based on some of the other tests in that directory) but I'm not sure how easy it is to test an interactive command like `spack diy`.

**Comment by adamjstewart** [comment]
Great minds think alike I suppose. I don't normally like to merge non-package changes myself, but if you've been using it all this time without problems I think it should be safe. I'll merge the PR that came first and close this one.

**Comment by adamjstewart** [comment]
Closed as duplicate of #5963.

**Pull request closed without merging**
