### PR TITLE
openfoam: set run environment by sourcing bashrc

### LINKED ISSUE #15946: Installation issue: openfoam-org v7
Note: `spack debug report` fails:

> usage: spack debug [-h] SUBCOMMAND ...
> spack debug: error: argument SUBCOMMAND: invalid choice: 'report' choose from:
>     create-db-tarball

```console
$ uname -a
Linux login1.wally.unil.ch 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ spack -V
0.13.3-1359-09dfbf9
```

### Steps to reproduce the issue
```console
$ spack install openfoam-org@7 %gcc@8.3.0
$ spack load openfoam-org@7 %gcc@8.3.0
$ decomposePar 
decomposePar: error while loading shared libraries: libmetisDecomp.so: cannot open shared object file: No such file or directory
```
Note: the library can be found in the lib/dummy directory but likely should be considered when not asking for the variant "metis" (which works fine btw)

### Information on your system
[spack-db.master.09dfbf9.2020-04-08-130820.tar.gz](https://github.com/spack/spack/files/4450089/spack-db.master.09dfbf9.2020-04-08-130820.tar.gz)
[spack-build-env.txt](https://github.com/spack/spack/files/4450098/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4450099/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by alalazo**
fixes #15946

### CODE REVIEW

**Comment by alalazo** [comment]
@olesenm @orliac

**Comment by olesenm** [comment]
HI @alalazo - I've had some _funny_ issues in the past with sourcing files. Of course I can't remember when exactly this occurs :(

This is why I've gone with the `setup_minimal_environment()` as a fallback for a try/catch in the `setup_run_environment()`.

Is this something worth replicating here? Or have i made the other one too complicated?

**Comment by alalazo** [comment]
@olesenm I think #15791 might have improved the situation when sourcing files and I was able to use `openfoam-org` successfully with the change in this PR on a couple of platforms. Do you have any known "worst case" to try and see if this PR is robust enough to handle it?

**Comment by olesenm** [comment]
Is or was there anything triggering on shell errors (ie, like `set -e`). There are some bits in the OpenFOAM env sourcing that use a `return 1` from a shell function to signal that a section should be skipped. This caused some issues in RPM builds.

**Comment by alalazo** [comment]
I confirm there are bits triggering on shell errors. Should we assume that a `set -e` shell is used in a context where `setup_run_environment` is called? I'm not opposed to modify the current method, but I'd like to keep it as simple as possible.

**Comment by alalazo** [comment]
@olesenm If you're fine with that I would proceed by just printing a warning in case sourcing fails, and not silently switch to a minimal environment. In this way I hope we'll get more issues reported if failures occur frequently under certain conditions.

**Comment by olesenm** [comment]
Hi @alalazo - sure, go for it. Can always revive the minimal env later. I think it is better not to apply to the `openfoam/package.py` though.

**Pull request merged**
