### PR TITLE
dealii: disable tpetra when +cuda; check for '' in cuda_arch

### PR DESCRIPTION
**Pull request by davydden**
try to fix https://github.com/spack/spack/issues/7957

@aprokop see if this helps. Although I still don't understand `cuda_arch`...
 According to [this line](https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/cuda.py#L41) in CudaPackage it should really be `None` by default.

### CODE REVIEW

**Comment by aprokop** [comment]
This won't work because a bunch of other packages depend on `tpetra` (zoltan2, ifpack2, etc) but the conflicts are not specified in the spec. This needs some cleanup.

**Comment by davydden** [comment]
> conflicts are not specified in the spec

i guess that's Trilinos package side as we currently allow building `+zoltan2~tpetra`, right?

**Comment by aprokop** [comment]
Yes. At the minimum, it needs `~tpetra~zoltan2~ifpack2`, maybe `~intrepid2`.

**Comment by davydden** [comment]
> I would say, let me see first if I can find the Kokkos header.

thanks! Maybe we can fix this on deal.II side instead of limiting Trilinos installation.

**Comment by jppelteret** [comment]
Perhaps lets wait to see what we decide in dealii/dealii#6423 before moving forward with this change.

**Comment by davydden** [comment]
@aprokop i added the patch for trilinos based on https://github.com/kokkos/kokkos/issues/1607 Hopefully it will fix the issue now...

**Comment by aprokop** [comment]
I went further, and cleaned up `trilinos` package a bit (introduced `kokkos` variant,  some conflicts, and reordered alphabetically). I came slightly further in the build, but there still seems to be a bug in Trilinos where Sacado calls `Kokkos` explicitly (not header) even when Trilinos is compiled without it. This is by default using 12.12 branch. It does compile with `master`, though. So the diff is the result that seems to compile for me. It compiles for both external cuda 9.1 and 8.0. However, it does not work for 9.1 for me with the following failure:
```
<snip>/dealii-develop-tp7rlkyaownglmee4yuklyf2lcwg76mw/include/deal.II/lac/sparsity_pattern.h:1450:45:
 error: expected primary-expression before ‘[’ token
   colnums = std_cxx14::make_unique<size_type[]>(max_vec_len);
```

```diff
diff --git a/var/spack/repos/builtin/packages/dealii/package.py b/var/spack/repos/builtin/packages/dealii/package.py
index 2e8db4f50..ecfe409cf 100644
--- a/var/spack/repos/builtin/packages/dealii/package.py
+++ b/var/spack/repos/builtin/packages/dealii/package.py
@@ -146,8 +146,11 @@ class Dealii(CMakePackage, CudaPackage):
     depends_on('slepc@:3.6.3',     when='@:8.4.1+slepc+petsc+mpi')
     depends_on('slepc~arpack',     when='+slepc+petsc+mpi+int64')
     depends_on('sundials~pthread', when='@9.0:+sundials')
-    depends_on('trilinos+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos',       when='+trilinos+mpi~int64')
-    depends_on('trilinos+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos~hypre', when='+trilinos+mpi+int64')
+    depends_on('trilinos+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos',       when='+trilinos+mpi~int64~cuda')
+    depends_on('trilinos+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos~hypre', when='+trilinos+mpi+int64~cuda')
+    # FIXME: temporary Kokkos based packages when using CUDA due to # namespace "Kokkos::Impl" has no member "cuda_abort"
+    depends_on('trilinos@master+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos~amesos2~ifpack2~intrepid2~kokkos~tpetra~zoltan2',       when='+trilinos+mpi~int64+cuda')
+    depends_on('trilinos@master+amesos+aztec+epetra+ifpack+ml+muelu+rol+sacado+teuchos~hypre~amesos2~ifpack2~intrepid2~kokkos~tpetra~zoltan2', when='+trilinos+mpi+int64+cuda')
 
     # check that the combination of variants makes sense
     conflicts('^openblas+ilp64', when='@:8.5.1')
@@ -252,7 +255,7 @@ class Dealii(CMakePackage, CudaPackage):
             if not spec.satisfies('^cuda@9:'):
                 options.append('-DDEAL_II_WITH_CXX14=OFF')
             cuda_arch = spec.variants['cuda_arch'].value
-            if cuda_arch is not None:
+            if cuda_arch is not None and cuda_arch[0] is not '':
                 if len(cuda_arch) > 1:
                     raise InstallError(
                         'deal.II only supports compilation for a single GPU!'
diff --git a/var/spack/repos/builtin/packages/trilinos/package.py b/var/spack/repos/builtin/packages/trilinos/package.py
index b199df50c..87ac4c0e3 100644
--- a/var/spack/repos/builtin/packages/trilinos/package.py
+++ b/var/spack/repos/builtin/packages/trilinos/package.py
@@ -72,100 +72,111 @@ class Trilinos(CMakePackage):
 
     # ###################### Variants ##########################
 
-    variant('alloptpkgs',   default=False,
-            description='Compile with all optional packages')
-    variant('xsdkflags',    default=False,
-            description='Compile using the default xSDK configuration')
-    variant('metis',        default=True,
-            description='Compile with METIS and ParMETIS')
-    variant('mumps',        default=True,
-            description='Compile with support for MUMPS solvers')
-    variant('superlu-dist', default=True,
-            description='Compile with SuperluDist solvers')
-    variant('superlu',      default=False,
-            description='Compile with SuperLU solvers')
-    variant('hypre',        default=True,
-            description='Compile with Hypre preconditioner')
-    variant('hdf5',         default=True,
-            description='Compile with HDF5')
-    variant('suite-sparse', default=True,
-            description='Compile with SuiteSparse solvers')
+    # Other
     # not everyone has py-numpy activated, keep it disabled by default to avoid
     # configure errors
     variant('python',       default=False,
             description='Build python wrappers')
+
+    # Build options
+    variant('fortran',      default=True,
+            description='Compile with Fortran support')
+    variant('instantiate',  default=True,
+            description='Compile with explicit instantiation')
+    variant('instantiate_cmplx', default=False,
+            description='Compile with explicit instantiation for complex')
+    variant('openmp',       default=False,
+            description='Enable OpenMP')
     variant('shared',       default=True,
             description='Enables the build of shared libraries')
+    variant('xsdkflags',    default=False,
+            description='Compile using the default xSDK configuration')
+
+    # TPLs (alphabet order)
     variant('boost',        default=True,
             description='Compile with Boost')
-    variant('tpetra',       default=True,
-            description='Compile with Tpetra')
-    variant('epetra',       default=True,
-            description='Compile with Epetra')
-    variant('epetraext',    default=True,
-            description='Compile with EpetraExt')
+    variant('cgns',         default=False,
+            description='Enable CGNS')
     variant('exodus',       default=True,
             description='Compile with Exodus from SEACAS')
+    variant('gtest',        default=True,
+            description='Compile with Gtest')
+    variant('hdf5',         default=True,
+            description='Compile with HDF5')
+    variant('hypre',        default=True,
+            description='Compile with Hypre preconditioner')
+    variant('metis',        default=True,
+            description='Compile with METIS and ParMETIS')
+    variant('mumps',        default=True,
+            description='Compile with support for MUMPS solvers')
     variant('pnetcdf',      default=False,
             description='Compile with parallel-netcdf')
+    variant('suite-sparse', default=True,
+            description='Compile with SuiteSparse solvers')
+    variant('superlu-dist', default=True,
+            description='Compile with SuperluDist solvers')
+    variant('superlu',      default=False,
+            description='Compile with SuperLU solvers')
+    variant('x11',          default=False,
+            description='Compile with X11')
     variant('zlib',         default=False,
             description='Compile with zlib')
-    variant('stk',          default=False,
-            description='Compile with STK')
-    variant('teuchos',      default=True,
-            description='Compile with Teuchos')
-    variant('belos',        default=True,
-            description='Compile with Belos')
-    variant('zoltan',       default=True,
-            description='Compile with Zoltan')
-    variant('zoltan2',      default=True,
-            description='Compile with Zoltan2')
+
+    # Package options (alphabet order)
+    variant('alloptpkgs',   default=False,
+            description='Compile with all optional packages')
     variant('amesos',       default=True,
             description='Compile with Amesos')
     variant('amesos2',      default=True,
             description='Compile with Amesos2')
     variant('anasazi',      default=True,
             description='Compile with Anasazi')
+    variant('aztec',        default=True,
+            description='Compile with Aztec')
+    variant('belos',        default=True,
+            description='Compile with Belos')
+    variant('epetra',       default=True,
+            description='Compile with Epetra')
+    variant('epetraext',    default=True,
+            description='Compile with EpetraExt')
     variant('ifpack',       default=True,
             description='Compile with Ifpack')
     variant('ifpack2',      default=True,
             description='Compile with Ifpack2')
-    variant('muelu',        default=True,
-            description='Compile with Muelu')
-    variant('fortran',      default=True,
-            description='Compile with Fortran support')
+    variant('intrepid',     default=False,
+            description='Enable Intrepid')
+    variant('intrepid2',    default=False,
+            description='Enable Intrepid2')
+    variant('kokkos',       default=True,
+            description='Compile with Kokkos')
     variant('ml',           default=True,
             description='Compile with ML')
-    variant('gtest',        default=True,
-            description='Compile with Gtest')
-    variant('aztec',        default=True,
-            description='Compile with Aztec')
+    variant('muelu',        default=True,
+            description='Compile with Muelu')
+    variant('nox',          default=False,
+            description='Enable NOX')
+    variant('rol',          default=False,
+            description='Enable ROL')
     variant('sacado',       default=True,
             description='Compile with Sacado')
-    variant('x11',          default=False,
-            description='Compile with X11')
-    variant('instantiate',  default=True,
-            description='Compile with explicit instantiation')
-    variant('instantiate_cmplx', default=False,
-            description='Compile with explicit instantiation for complex')
+    variant('stk',          default=False,
+            description='Compile with STK')
+    variant('shards',       default=False,
+            description='Enable Shards')
+    variant('teuchos',      default=True,
+            description='Compile with Teuchos')
+    variant('tpetra',       default=True,
+            description='Compile with Tpetra')
+    variant('zoltan',       default=True,
+            description='Compile with Zoltan')
+    variant('zoltan2',      default=True,
+            description='Compile with Zoltan2')
+
+    # External package options
     variant('dtk',          default=False,
             description='Enable DataTransferKit')
     variant('fortrilinos',  default=False,
             description='Enable ForTrilinos')
-    variant('openmp',       default=False,
-            description='Enable OpenMP')
-    variant('rol',          default=False,
-            description='Enable ROL')
-    variant('nox',          default=False,
-            description='Enable NOX')
-    variant('shards',       default=False,
-            description='Enable Shards')
-    variant('intrepid',     default=False,
-            description='Enable Intrepid')
-    variant('intrepid2',    default=False,
-            description='Enable Intrepid2')
-    variant('cgns',         default=False,
-            description='Enable CGNS')
 
     resource(name='dtk',
              git='https://github.com/ornl-cees/DataTransferKit',
@@ -178,6 +189,12 @@ class Trilinos(CMakePackage):
              placement='packages/ForTrilinos',
              when='+fortrilinos')
 
+    conflicts('+tpetra', when='~kokkos')
+    conflicts('+intrepid2', when='~kokkos')
+    conflicts('+amesos2', when='~tpetra')
+    conflicts('+ifpack2', when='~tpetra')
+    conflicts('+zoltan2', when='~tpetra')
+
     conflicts('+dtk', when='~tpetra')
     conflicts('+fortrilinos', when='~fortran')
     conflicts('+fortrilinos', when='@:99')
@@ -281,50 +298,52 @@ class Trilinos(CMakePackage):
         options.extend([
             '-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=%s' % (
                 'ON' if '+alloptpkgs' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Tpetra:BOOL=%s' % (
-                'ON' if '+tpetra' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Epetra:BOOL=%s' % (
-                'ON' if '+epetra' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_EpetraExt:BOOL=%s' % (
-                'ON' if '+epetraext' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_ML:BOOL=%s' % (
-                'ON' if '+ml' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_AztecOO:BOOL=%s' % (
-                'ON' if '+aztec' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Sacado:BOOL=%s' % (
-                'ON' if '+sacado' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Belos:BOOL=%s' % (
-                'ON' if '+belos' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Zoltan:BOOL=%s' % (
-                'ON' if '+zoltan' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Zoltan2:BOOL=%s' % (
-                'ON' if '+zoltan2' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Amesos:BOOL=%s' % (
                 'ON' if '+amesos' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Amesos2:BOOL=%s' % (
                 'ON' if '+amesos2' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_MueLu:BOOL=%s' % (
-                'ON' if '+muelu' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Anasazi:BOOL=%s' % (
+                'ON' if '+anasazi' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_AztecOO:BOOL=%s' % (
+                'ON' if '+aztec' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Belos:BOOL=%s' % (
+                'ON' if '+belos' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Epetra:BOOL=%s' % (
+                'ON' if '+epetra' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_EpetraExt:BOOL=%s' % (
+                'ON' if '+epetraext' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Ifpack:BOOL=%s' % (
                 'ON' if '+ifpack' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Ifpack2:BOOL=%s' % (
                 'ON' if '+ifpack2' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Gtest:BOOL=%s' % (
-                'ON' if '+gtest' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Teuchos:BOOL=%s' % (
-                'ON' if '+teuchos' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Anasazi:BOOL=%s' % (
-                'ON' if '+anasazi' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_ROL:BOOL=%s' % (
-                'ON' if '+rol' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_NOX:BOOL=%s' % (
-                'ON' if '+nox' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_Shards=%s' % (
-                'ON' if '+shards' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Intrepid=%s' % (
                 'ON' if '+intrepid' in spec else 'OFF'),
             '-DTrilinos_ENABLE_Intrepid2=%s' % (
                 'ON' if '+intrepid2' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Kokkos:BOOL=%s' % (
+                'ON' if '+kokkos' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_ML:BOOL=%s' % (
+                'ON' if '+ml' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_MueLu:BOOL=%s' % (
+                'ON' if '+muelu' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_NOX:BOOL=%s' % (
+                'ON' if '+nox' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_PyTrilinos:BOOL=%s' % (
+                'ON' if '+python' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_ROL:BOOL=%s' % (
+                'ON' if '+rol' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Shards=%s' % (
+                'ON' if '+shards' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Teuchos:BOOL=%s' % (
+                'ON' if '+teuchos' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Tpetra:BOOL=%s' % (
+                'ON' if '+tpetra' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Sacado:BOOL=%s' % (
+                'ON' if '+sacado' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Zoltan:BOOL=%s' % (
+                'ON' if '+zoltan' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Zoltan2:BOOL=%s' % (
+                'ON' if '+zoltan2' in spec else 'OFF'),
         ])
 
         if '+xsdkflags' in spec:
@@ -388,8 +407,8 @@ class Trilinos(CMakePackage):
             '-DNetCDF_ROOT:PATH=%s' % spec['netcdf'].prefix,
             '-DTPL_ENABLE_X11:BOOL=%s' % (
                 'ON' if '+x11' in spec else 'OFF'),
-            '-DTrilinos_ENABLE_PyTrilinos:BOOL=%s' % (
-                'ON' if '+python' in spec else 'OFF'),
+            '-DTrilinos_ENABLE_Gtest:BOOL=%s' % (
+                'ON' if '+gtest' in spec else 'OFF'),
         ])
 
         if '+hypre' in spec:
```

**Comment by davydden** [comment]
@aprokop :

> So the diff is the result that seems to compile for me. It compiles for both external cuda 9.1 and 8.0. 

did you mean cuda `9.0` as below you say it does not work with 9.1:

> However, it does not work for 9.1 for me with the following failure:

> <snip>/dealii-develop-tp7rlkyaownglmee4yuklyf2lcwg76mw/include/deal.II/lac/sparsity_pattern.h:1450:45:
 error: expected primary-expression before ‘[’ token
   colnums = std_cxx14::make_unique<size_type[]>(max_vec_len);

So this error is with updated `trilinos` and `deal.II` according to your diff above (which I pushed to this PR)?

We have a [CUDA 9.0 tester](https://cdash.kyomu.43-1.org/index.php?project=deal.II), here's the config @Rombur has

```
DEAL_II_WITH_CUDA set up with external dependencies
#            CUDA_VERSION = 9.0
#            CMAKE_CUDA_COMPILER = /usr/local/cuda/bin/nvcc
#            CUDA_COMPUTE_CAPABILITY = 3.5
#            DEAL_II_CUDA_FLAGS = -arch=sm_35 -std=c++11
#            DEAL_II_CUDA_FLAGS_RELEASE = 
#            DEAL_II_CUDA_FLAGS_DEBUG = -G
#            CUDA_INCLUDE_DIRS = /usr/local/cuda/include
#            CUDA_USER_INCLUDE_DIRS = /usr/local/cuda/include
#            CUDA_LIBRARIES = /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;rt;/usr/local/cuda/lib64/libcusparse.so;/usr/local/cuda/lib64/libcusolver.so;-fopenmp
```
and the same for 8.0:
```
#        DEAL_II_WITH_CUDA set up with external dependencies
#            CUDA_VERSION = 8.0
#            CMAKE_CUDA_COMPILER = /usr/local/cuda/bin/nvcc
#            CUDA_COMPUTE_CAPABILITY = 3.5
#            DEAL_II_CUDA_FLAGS = -arch=sm_35 -std=c++11
#            DEAL_II_CUDA_FLAGS_RELEASE = 
#            DEAL_II_CUDA_FLAGS_DEBUG = -G
#            CUDA_INCLUDE_DIRS = /usr/local/cuda/include
#            CUDA_USER_INCLUDE_DIRS = /usr/local/cuda/include
#            CUDA_LIBRARIES = /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;rt;/usr/local/cuda/lib64/libcusparse.so;/usr/local/cuda/lib64/libcusolver.so;-fopenmp
```

The only difference I see is that @Rombur adds `-std=c++11` to `CUDA_FLAGS`. I have updated this PR to do the same. Could you please give it a try?

**Comment by davydden** [comment]
p.s. i hope the code work as I don't have CUDA to test the changes...

**Comment by aprokop** [comment]
> did you mean cuda 9.0 as below you say it does not work with 9.1:

Sorry, no. dealII itself compiles fine, but when I compile another application against deali.ii it fails. @Rombur can probably explain the nuances of MFMG interacting with dealII.  

> So this error is with updated trilinos and deal.II according to your diff above (which I pushed to this PR)?

Again, this is the error from a different application that tries to use dealII.

**Comment by Rombur** [comment]
> The only difference I see is that @Rombur adds -std=c++11 to CUDA_FLAGS. 

I do not. This is done by deal

**Comment by davydden** [comment]
> I do not. This is done by deal

Thanks Bruno, I will undo my last commit then

**Comment by davydden** [comment]
@aprokop 

>  this is the error from a different application that tries to use dealII.

p.s. if you have not resolved the issue yet, such problems are best to be asked in the Google group https://groups.google.com/forum/?fromgroups#!forum/dealii 

please confirm that the current state is what makes `dealii+trilinos+cuda` build in your settings and then i think we can merge this PR.

**Comment by aprokop** [comment]
@davydden Yes, I'm using dealii installed with this patch.

**Comment by davydden** [comment]
> Yes, I'm using dealii installed with this patch.

ok, thanks!

@adamjstewart @alalazo could you please merge this PR? I think @jppelteret won't mind that we temporarily request `trilinos@master` if `+cuda` is enabled.

**Comment by jppelteret** [comment]
> I think @jppelteret won't mind that we temporarily request trilinos@master if +cuda is enabled.

@davydden's supposition is correct - this doesn't bother me at all :-)

**Comment by alalazo** [comment]
@davydden Can you fix the `flake8` issue?

**Comment by davydden** [comment]
@alalazo 

> Can you fix the flake8 issue?

sure, should be ok now, sorry, did not notice this.

**Comment by davydden** [comment]
there is again something with Travis, flake8 pass, though.

**Comment by davydden** [comment]
@alalazo maybe merge this one as well 😄

**Pull request merged**
