### PR TITLE
Add new version of MSTK

### PR DESCRIPTION
**Pull request by raovgarimella**

### CODE REVIEW

**Comment by raovgarimella** [comment]
Maybe my comment was misworded. I meant to say I added a new version of MSTK with only change being in the patch version not the major or minor version.

**Comment by alalazo** [comment]
Ok, then I'll wait for the test to finish and merge. Thanks for the confirmation.

**Comment by raovgarimella** [comment]
Actually, can you hold off for a bit. I have to update the sha256. I will let you know as soon as I do.

**Comment by raovgarimella** [comment]
OK. It's all set to be merged. Thanks

**Pull request merged**
