### PR TITLE
Cmake/add option for fujitsu compiler

### PR DESCRIPTION
**Pull request by t-karatsu**
When installing cmake with Fujitsu compiler, add the process of setting the environment variable to build based on the C++11 specification.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Why is this always being added instead of letting the package decide?

**Comment by t-karatsu** [comment]
Thanks for your reply!
Certainly, it may be necessary to determine the contents of options included in the installation command.
I will consider logic for parsing install command.

**Comment by t-karatsu** [comment]
I pushed fixes to add condition of whether to add cxx11 option.
So this fix should no longer add the same cxx11 option in duplicate.

**Comment by tgamblin** [comment]
@becker33: this one deals with flag assignment -- can you review it?

We don't have a convention yet for what @t-karatsu is trying to do here so we'll need to decide.

I *don't* think this should be handled by the CMake build system package, though.  This stuff should really be up to the package as @chuckatkins suggests.

**Comment by t-karatsu** [comment]
I'm sorry if I misled you.
`cmake` needs to be built with C++ compiler based on C++11 specification, but Fujitsu C++ compiler  is based on the C++14 specification by default. So, I defined `CXXFLAGS` to  build based on C++11 specification  only when building `cmake`.

I confirmed that `CXXFLAGS` was not defined in the dependent package, so I do not think that dependent packages have any effect. Is my understanding correct?

Could you tell me if there is a better fix?

**Comment by chuckatkins** [comment]
I've got a clearer picture of what's going on now.  Essentially this is a workaround for CMake not having builtin support for the Fujitsu toolchains and just knowing what flags need to be set (coincidentally I'm working on that in upstream CMake for the 3.16 release in a few months, but that doesn't solve your problem now).  Given that, the general idea here is fine, i.e. to add additional c++ standard flags to build cmake (not things that are built *with* cmake like I initially thought), but something doesn't quite seem right in that the default c++14 mode since that should work to build CMake.  Could you provide the failing output from how it's broken?

**Comment by t-karatsu** [comment]
@chuckatkins
Thanks for comment and considering it! I'll provide output logs that I got errors building cmake with Fujitsu compiler. Please let me know if there is a lack of information.

[cmake_bootstrap.log](https://github.com/spack/spack/files/3399712/cmake_bootstrap.log)
[cmake_error.txt](https://github.com/spack/spack/files/3399713/cmake_error.txt)

**Comment by chuckatkins** [comment]
> `cmake` needs to be built with C++ compiler based on C++11

It needs to be build with *at least* c++11, so c++14 would work just fine.


> Fujitsu C++ compiler is based on the C++14 specification by default

Given the output, I'm skeptical of this and have my doubts that this is actually the case.


> I defined `CXXFLAGS` to build based on C++11 specification only when building `cmake`.

All things considered, if that makes it build with the fujitsu compilers and is limited to only building cmake itself them I'm fine with it.

**Comment by becker33** [comment]
@chuckatkins @t-karatsu For future reference, this would be better done using a `flag_handler` method. As it is, it could conflict with any flags someone later tries to add through a `flag_handler` in the cmake package. That's why I marked it `don't-merge-yet`, since it wasn't clear from the conversation what changes I should be asking for but I knew it wasn't ready.

**Comment by t-karatsu** [comment]
Thanks for merge @chuckatkins .

@becker33
`As it is, it could conflict with any flags someone later tries to add through a flag_handler in the cmake package. `
OK... Is it necessary to check for duplicate flags when using the `flag_handler` method? I considered the following modifications using `flag_handler`.

```     phases = ['bootstrap', 'build', 'install']

-    def setup_environment(self, spack_env, run_env):
-        if self.compiler.name == 'fj' \
-                and self.compiler.cxx11_flag \
-                not in self.spec.compiler_flags['cxxflags']:
-            spack_env.append_flags('CXXFLAGS', self.compiler.cxx11_flag)
+    def flag_handler(self, name, flags):
+        flags = list(flags)
+        if self.compiler.name == 'fj':
+            if name == 'cxxflags':
+                flags.append(self.compiler.cxx11_flag)
+            return (None, flags, None)
+        else:
+            return (flags, None, None)

     def bootstrap_args(self):
         spec = self.spec```

**Comment by becker33** [comment]
I think this PR could've been handled with

```
def flag_handler(self, name, flags):
    if name == 'cxxflags' and self.compiler.name == 'fc':
        flags.append(self.compiler.cxx11_flag)
    return (flags, None, None)
```

**Comment by chuckatkins** [comment]
My apologies.  I assumed it was marked as such because of the ongoing discussion on using the flag in the first place, not the package mechanism with which it was being added.

**Comment by t-karatsu** [comment]
@becker33
Thank you for correct my changes. I confirmed to be able to install cmake with your fixes. I commented to new pullreq.

**Pull request merged**
