### PR TITLE
Proposed restructuring of python spackages to new spack repo

### PR DESCRIPTION
**Pull request by rspavel**
Proposing migration of spackages with a common theme (in this case python) to a different builtin spack repo as a way to simplify development.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you describe how this simplifies development?

**Comment by rspavel** [comment]
Sorry for the delay. The benefits are twofold: 

On platforms where file system issues are a regular concern, having a large number of folders and files in a directory can slow things down when git operations (or just ls) are called. While development can occur in much healthier, local, environments it is often beneficial to test the builds in the eventual environment we will deploy the packages to.

But mostly it is a case of letting developers quickly type ls (or look at the sidebar in their IDE of choice) and skim the list for a spackage they know has a similar build system to what they are working on. Over time developers learn the gold standards or know they have a spackage for a code by the same team they can reference, but there is still a lot to be said about being able to quickly glance at the folders in a directory and know they have a common theme or even be able to spot a good reference.

**Comment by tgamblin** [comment]
What if, instead of separating the repositories, we modified `Repo` so that there could be directory structure under `packages`?  Then we could separate things into categories like many package managers currently do.

The question would be whether you want that hierarchy to affect the package namespaces.  i.e., would you rather have something like macports, where packages are categorized but there is really only one namespace (you can't have both `python/foo` and `tools/foo`), or do you want the hierarchy to have an effect on the namespace?

Currently each repo gets its own top-level namespace, which can be separated by `.`.  If we let this affect namespacing, then you could have `builtin.python`, `builtin.tools`, or even `builtin.foo.bar` if you wanted.   I think we should cap the max depth to bound the depth we'd need to spider to find all the package files, but a couple levels seems reasonable.

The other question would be how this affects overlay semantics bt/w repos.  i.e., if I have `builtin` and `llnl` repos, and they both define `python.numpy`, I think one should be able to take precedence over the other.  So only the top-level namespace would be overlaid.  But then if there is also `builtin.numpy`, it's confusing which is the real numpy.  I would need to think about this aspect a bit more.

Thoughts?

**Comment by rspavel** [comment]
I'll fully admit to having no idea how priorities with respect to multiple repositories work.

I personally have no preference as to how restructuring goes and this was primarily a way to encourage discussion (that I promptly forgot about due to other constraints...). I think different spack repos were suggested as that would (theoretically) need no actual changes to spack to support and might even add some testing for the multiple spack repos model. And "languages" seemed like a good arbitrary divide.

The hierarchies may simplify some categorization (over just "language") but would still have the issue with cases where a spackage might be a tool, a c library, and bindings for a python library (and even an r library) all in one. But we would be no worse off than we currently are in that case.

**Comment by adamjstewart** [comment]
Another option is sub-directories based on the first letter of the package name. You would have `a/abinit` and `p/py-numpy`. This is how PyPI works, for example.

**Comment by tgamblin** [comment]
I like @adamjstewart's idea, as it doesn't require rethinking namespaces.  It solves the technical issue that there are too many files in `<repo>/packages`.

Seems like @rspavel was hoping for a logical grouping as well, though.  One thing we have for that, which may make more sense than a hierarchy, is tags.  Packages can have a `tags` attribute like this:

```python
tags = ['foo', 'bar', 'baz']`
```

You can currently search for tagged packages with `spack list -t <tags>` but there isn't a way to list existing tags and tagged packages.  If we added that and took @adamjstewart's suggestion (maybe with another level of hierarchy) would that solve the issues, or are we still missing something?

**Comment by adamjstewart** [comment]
Would it help to be able to list packages by build system? Like `spack list --build-system python`?

**Comment by rspavel** [comment]
I think having a list --build-system would provide the utility aspect, and grouping by letter simplifies the "at a glance" aspects and still is beneficial for cases where a group's apps tend to have similar naming conventions (or languages, as with python/r/perl).

**Comment by tgamblin** [comment]
> Would it help to be able to list packages by build system? Like spack list --build-system python?

What if the build system classes just defined `tags = ['python']`?

**Comment by healther** [comment]
> Another option is sub-directories based on the first letter of the package name. You would have a/abinit and p/py-numpy. This is how PyPI works, for example.

but then we should have more sensible conventions than pypi has... They distinguish (or at least they did distinguish) between lower case and capital letters, which made the url finding quite interesting.

In this method would we then have to do `spack install p/py-numpy` or would `spack install py-numpy` still work? I think we should limit the changes in the user interface, but are free to change the implementation and storage as we want.

> You can currently search for tagged packages with `spack list -t <tags>` but there isn't a way to list existing tags and tagged packages.

could we have `spack list` default to report both the tag-matches and string-matches? As of now I wasn't even aware of the concept of tags... But this will make something like `spack list python` be quite verbose

**Comment by alalazo** [comment]
Closing for the huge number of conflicts. Feel free to open a new PR pointing to this if you feel this is still necessary (or open an issue if you want to discuss the idea first).

**Pull request closed without merging**
