### PR TITLE
openfoam & openfoam-org: Fixing GCC 9 compilation errors.

### PR DESCRIPTION
**Pull request by simo-tuomisto**
openfoam & openfoam-org do not build correctly with gcc@9: because
it raises an error for -Wdeprecated-copy. This commit fixes that.

Also fixes an issue with building openfoam-org as flex is needed
after the build has finished.

Fix is done by modifying `cWARN`- and `c++WARN`-flags in `c`-and `c++`-files in `wmake/rules/*Gcc*`-folders. From version 1906 onwards openfoam uses the folder `wmake/rules/Generic/Gcc` instead. The logic in the patch looks for both places for files to adapt.

Unfortunately this does not fix the issue for versions older than openfoam@1812 or openfoam-org@6. For those versions there are plenty of other compilation issues due to gcc's stricter standards.

More info on -Wdeprecated-copy can be found in [gcc's bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58407). This issue is was previously mentioned in #13995 .

### CODE REVIEW

**Comment by adamjstewart** [comment]
@olesenm

**Comment by olesenm** [comment]
Not really crazy about this.
I think that what @scheibelp mentioned makes sense. Add a spack conflict definition for existing OpenFOAM installations and newer gcc (could later also be clang?). Fix compilation issues [upstream](https://develop.openfoam.com/Development/openfoam/issues/1547) for a bugfix patch, or the next version.

If we _really_ want to be patching the rules, then probably better to make it a patch file with a conditional application. The openfoam package.py file is already far too big.

**Comment by adamjstewart** [comment]
@simo-tuomisto @olesenm can this PR be closed or is there more work to be done?

**Comment by simo-tuomisto** [comment]
This can be closed. The solution for fixing the openfoam compilation errors should probably be done upstream.

**Comment by olesenm** [comment]
fixed upstream for new versions.

**Pull request closed without merging**
