### PR TITLE
Use GCC6 by Default

### PR DESCRIPTION
**Pull request by citibeth**
Spack users have encountered known problems with GCC7 not building certain things.  Setting GCC6 as the default will make life easier for everybody here.  See #7803

### CODE REVIEW

**Comment by citibeth** [comment]
@JohnWGrove Would this change make your life easier?

**Comment by citibeth** [comment]
Looks like this PR is not considered the way to go.  Closing now.

**Comment by JohnWGrove** [comment]
Thanks for your help Elizabeth. As a general comment, the AVX and AVX2 optimization options do not work for GNU GCC. While they work for Apple clang, I suggest that for portability, these options be disabled by default for all packages supported by spack when used on Macs.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by citibeth** [comment]
Can you submit a darwin-specific `packages.yaml` that would do this?

**Comment by JohnWGrove** [comment]
I am not sure how one would do this. The AVX, AVX2 options seem to be specified on a package by package basis. They are turned on for openblas and this only way I found to turn them off was to use cpu_target=GENERIC, which translates into a package specific Makefile option. For FFTW these are controlled via the simd= variation. By default for FFTW simd=sse2,avx,avx2 and the build fails, specifying simd=sse2 works around this option. I noticed for this package in particular (FFTW) the linux version does not seem to use AVX, but the Apple versions will try it. I would need to examine the other package python scripts to see which use these options and how. If I figure out a way to universally turn off AVX/AVX2 I will let you know.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Pull request closed without merging**
