### PR TITLE
intel: optionally take gcc executable from cflags

### PR DESCRIPTION
**Pull request by davydden**
fixes https://github.com/spack/spack/issues/11135

### CODE REVIEW

**Comment by davydden** [comment]
> The Intel compilers also have a -gxx-name flag to point to the desired g++. It would seem prudent to add that as well if you think that fits in this PR.

I would leave it for other folks to add, I never used `-gxx-name`.

**Comment by davydden** [comment]
ah, nevermind, I will update...

**Comment by davydden** [comment]
@lee218llnl 

> The Intel compilers also have a -gxx-name flag to point to the desired g++

I updated the PR. But to be fair, I have not tested, since I am away from Linux box with Intel compilers.

**Comment by lee218llnl** [comment]
@davydden, I don't typically build things with the Intel Spack packages since we support them at my site using other methods. Do you have a simple way for me to test this PR?

**Comment by davydden** [comment]
> I don't typically build things with the Intel Spack packages since we support them at my site using other methods.

You can test this by adding those flags in compilers.yaml and trying to build something with tbb provided by intel-parallel-studio.

P.s. I **did** test the first commit, I just have not tested yet the second one which looks at cxxflags aswell. But I will do so in a few hours.

**Comment by davydden** [comment]
@lee218llnl tested the latest commit, still works:
```
==> [2019-04-10-08:21:00.409349] _tbb_abi._gcc_executable:	/usr/bin/g++-4.8
```
with
```
    flags:
      cflags: -gcc-name=/usr/bin/gcc-4.8
      cxxflags: -gxx-name=/usr/bin/g++-4.8
      fflags: -gcc-name=/usr/bin/gcc-4.8
```
since we break inner loop, we pick up the last occurrence of the flag, but that is ok.

**Comment by davydden** [comment]
@lee218llnl I extended the regex in the third commit, looks reasonable:
```
==> [2019-04-10-11:49:44.679370] _tbb_abi._gcc_executable:	/usr/bin/g++-4.8
==> [2019-04-10-11:49:44.679550] '/usr/bin/g++-4.8' '--version'
==> [2019-04-10-11:49:44.683839] component_lib_dir._tbb_abi:	gcc4.7
==> [2019-04-10-11:49:44.684427] tbb_libs.component_lib_dir:	/home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7
==> [2019-04-10-11:49:44.685022] tbb_libs._gcc_executable:	/usr/bin/g++-4.8
==> [2019-04-10-11:49:44.685111] '/usr/bin/g++-4.8' '--print-file-name' 'libstdc++.so'
==> [2019-04-10-11:49:44.688106] libs.tbb_libs:	/home/davydden/spack/opt/spack/linux-ubuntu18.04-x86_64/intel-19.0.3.gcc.4.8/intel-parallel-studio-cluster.2019.3-fydxjqhcqkmygxfmgb34rp22isvrencb/compilers_and_libraries_2019.3.199/linux/tbb/lib/intel64/gcc4.7/libtbb.so /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so
```

**Comment by lee218llnl** [comment]
Looking at this further, I think this will hard for me to actually test since we don't have any gcc version less than 4.7. The code looks OK to me, so I can merge this PR if you think it is ready.

**Comment by lee218llnl** [comment]
@davydden Perhaps this is a separate issue, but the flags in my compilers.yaml don't seem to be taken into effect. Instead it looks like it still uses the default gcc in my PATH which is version 4.9.3:

bash-4.2$ which gcc
/usr/tce/packages/gcc/gcc-4.9.3/bin/gcc

Here you can see my compiler configuration

bash-4.2$ ./bin/spack compiler info intel@19.0.3
intel@19.0.3.199:
        paths:
                cc = /usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/icc
                cxx = /usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/icpc
                f77 = /usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/ifort
                fc = /usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/ifort
        flags:
                cxxflags = ['-gxx-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/g++']
                fflags = ['-gcc-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/gcc']
                cflags = ['-gcc-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/gcc']
        modules  = []
        operating system  = rhel7

And notice in the icc-v output that the .o files and the lib directories are coming from the default 4.9.3 gcc installation:

bash-4.2$ ./bin/spack build-env zlib%intel@19.0.3 /usr/WS2/lee218/spack.pr11136/lib/spack/env/intel/icc -v
icc version 19.0.3.199 (gcc version 4.9.3 compatibility)
ld    /lib/../lib64/crt1.o /lib/../lib64/crti.o /usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin -L/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/ -L/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64 -L/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath=/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64 -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/crtend.o /lib/../lib64/crtn.o
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'

However, if I explicitly add -gcc-name, you can see that it finds the appropriate gcc-7.1.0 .o files and lib directories:

bash-4.2$ ./bin/spack build-env zlib%intel@19.0.3 /usr/WS2/lee218/spack.pr11136/lib/spack/env/intel/icc -gcc-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/gcc -v
icc version 19.0.3.199 (gcc version 7.1.0 compatibility)
ld    /lib/../lib64/crt1.o /lib/../lib64/crti.o /usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/crtbegin.o --eh-frame-hdr --build-id -dynamic-linker /lib64/ld-linux-x86-64.so.2 -m elf_x86_64 -o a.out -L/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin -L/usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/ -L/usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../lib64 -L/usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/../../../../lib64/ -L/lib/../lib64 -L/lib/../lib64/ -L/usr/lib/../lib64 -L/usr/lib/../lib64/ -L/usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/../../../ -L/lib64 -L/lib/ -L/usr/lib64 -L/usr/lib -rpath=/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64 -Bdynamic -Bstatic -limf -lsvml -lirng -Bdynamic -lm -Bstatic -lipgo -ldecimal --as-needed -Bdynamic -lcilkrts -lstdc++ --no-as-needed -lgcc -lgcc_s -Bstatic -lirc -lsvml -Bdynamic -lc -lgcc -lgcc_s -Bstatic -lirc_s -Bdynamic -ldl -lc /usr/tce/packages/gcc/gcc-7.1.0/lib64/gcc/x86_64-pc-linux-gnu/7.1.0/crtend.o /lib/../lib64/crtn.o
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'

I can also see if I actually build zlib, that it does not pick up the gcc-7.1.0 .so's even though the build environment looks correct:

[lee218@rzwiz2:spack.pr11136]$ grep gcc-7.1.0 /usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/intel-19.0.3/zlib-1.2.11-hip2dpjyumeiunixdrsur6ptbz5zdvtr/.spack/build.env 
export SPACK_CC="/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/icc"
export SPACK_CFLAGS="-gcc-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/gcc"
export SPACK_CXX="/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/icpc"
export SPACK_CXXFLAGS="-gxx-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/g++"
export SPACK_F77="/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/ifort"
export SPACK_FC="/usr/WS2/lee218/spack.pr11136/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/intel-parallel-studio-professional.2019.3-vk3e2ynjjin3uxutw63qy76fs5bgu7lu/bin/ifort"
export SPACK_FFLAGS="-gcc-name=/usr/tce/packages/gcc/gcc-7.1.0/bin/gcc"

bash-4.2$ ldd opt/spack/linux-rhel7-x86_64/intel-19.0.3/zlib-1.2.11-hip2dpjyumeiunixdrsur6ptbz5zdvtr/lib/libz.so | grep libgcc
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaad872000)

Please let me know if my testing mechanism is flawed in some way.

**Comment by davydden** [comment]
@lee218llnl 

> Perhaps this is a separate issue, but the flags in my compilers.yaml don't seem to be taken into effect.

I think it is indeed a separate issue. The way to test this PR is to install something which uses `tbb` provided by `intel-parallel-studio`, that's the only case when `_gcc_executable` will be used. That is, in `tbb_libs()` and `_tbb_abi()`. Then you can check in spack logs 
```
_tbb_abi._gcc_executable
```

**Comment by davydden** [comment]
@lee218llnl 

> Please let me know if my testing mechanism is flawed in some way.

I don't think so, looks like flags are somehow ignored:

```
$ spack build-env zlib%intel bash
$ which icc
/home/davydden/spack/lib/spack/env/intel/icc
$ icc -v
icc version 19.0.3.199 (gcc version 7.3.0 compatibility)
```

**Comment by davydden** [comment]
p.s. 

> The code looks OK to me, so I can merge this PR if you think it is ready.

I think it is, I dropped `cxx` support for now to keep changes to the minimum. That's also closer the Intel package as refactored by @mgsternberg

**Pull request merged**
