### PR TITLE
Mark GCC7 and newer as conflicting with rhel6 without binutils

### LINKED ISSUE #12235: "Installation issue: openblas: default blas/lapack 'openblas' can't build on RHEL6 with gcc@7.2.0 built by Spack
**snl-atdm-issue**

### Steps to reproduce the issue

```console
$ ./atdm-spack/spack/bin/spack install openblas %gcc@7.2.0
```

with build errors starting with:

```
==> Installing openblas
==> Searching for binary cache of openblas
==> Finding buildcaches in /ascldap/users/rabartl/Spack.base3/atdm-spack/atdm-spack-tarball-mirror/build_cache
==> No binary for openblas found: installing from source
==> Using cached archive: /home/rabartl/Spack.base3/atdm-spack/spack/var/spack/cache/openblas/openblas-0.3.5.tar.gz
==> Staging archive: /home/rabartl/Spack.base3/atdm-spack/spack/var/spack/stage/openblas-0.3.5-ase7rloe2w5cvr7egf4fglyx5kw2egrl/v0.3.5.tar.gz
==> Created stage in /home/rabartl/Spack.base3/atdm-spack/spack/var/spack/stage/openblas-0.3.5-ase7rloe2w5cvr7egf4fglyx5kw2egrl
==> No patches needed for openblas
==> Building openblas [MakefilePackage]
==> Executing phase: 'edit'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32' 'CC=/home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc' 'FC=/home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gfortran' 'MAKE_NB_JOBS=0' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'

577 errors found in build log:
     1348    /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 
             -DVERSION=\"0.3.5\" -mavx2 -DASMNAME=dtrmm_kernel_LN -DASMFNAME=dtrmm_kernel_LN_ -DNAME=dtrmm_kernel_LN_ -DCNAME=dtrmm_kernel_LN -DCHAR_NAME=\"dtrmm_kernel_LN_\" -DCHAR_CNAME=\"dtrmm_kernel_LN\" -D
             NO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86_64/dtrmm_kernel_4x8_haswell.c -o dtrmm_kernel_LN.o
     1349    /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 
             -DVERSION=\"0.3.5\" -mavx2 -DASMNAME=dtrmm_kernel_LT -DASMFNAME=dtrmm_kernel_LT_ -DNAME=dtrmm_kernel_LT_ -DCNAME=dtrmm_kernel_LT -DCHAR_NAME=\"dtrmm_kernel_LT_\" -DCHAR_CNAME=\"dtrmm_kernel_LT\" -D
             NO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -DTRANSA ../kernel/x86_64/dtrmm_kernel_4x8_haswell.c -o dtrmm_kernel_LT.o
     1350    /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 
             -DVERSION=\"0.3.5\" -mavx2 -DASMNAME=dtrmm_kernel_RN -DASMFNAME=dtrmm_kernel_RN_ -DNAME=dtrmm_kernel_RN_ -DCNAME=dtrmm_kernel_RN -DCHAR_NAME=\"dtrmm_kernel_RN_\" -DCHAR_CNAME=\"dtrmm_kernel_RN\" -D
             NO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -UTRANSA ../kernel/x86_64/dtrmm_kernel_4x8_haswell.c -o dtrmm_kernel_RN.o
     1351    /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 
             -DVERSION=\"0.3.5\" -mavx2 -DASMNAME=dtrmm_kernel_RT -DASMFNAME=dtrmm_kernel_RT_ -DNAME=dtrmm_kernel_RT_ -DCNAME=dtrmm_kernel_RT -DCHAR_NAME=\"dtrmm_kernel_RT_\" -DCHAR_CNAME=\"dtrmm_kernel_RT\" -D
             NO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -DTRANSA ../kernel/x86_64/dtrmm_kernel_4x8_haswell.c -o dtrmm_kernel_RT.o
     1352    /home/rabartl/Spack.base3/atdm-spack/spack/lib/spack/env/gcc/gcc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_AVX512 -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER
             =1 -DVERSION=\"0.3.5\" -mavx2 -DASMNAME=dtrsm_kernel_LN -DASMFNAME=dtrsm_kernel_LN_ -DNAME=dtrsm_kernel_LN_ -DCNAME=dtrsm_kernel_LN -DCHAR_NAME=\"dtrsm_kernel_LN_\" -DCHAR_CNAME=\"dtrsm_kernel_LN\"
              -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -DTRSMKERNEL -UCOMPLEX -DDOUBLE -DUPPER -DLN -UCONJ ../kernel/x86_64/../generic/trsm_kernel_LN.c -o dtrsm_kernel_LN.o
     1353    ../kernel/x86_64/dgemm_kernel_4x8_haswell.S: Assembler messages:
  >> 1354    ../kernel/x86_64/dgemm_kernel_4x8_haswell.S:1759: Error: no such instruction: `vpermpd $ 0xb1,%ymm0,%ymm0'
  >> 1355    ../kernel/x86_64/dgemm_kernel_4x8_haswell.S:1759: Error: no such instruction: `vpermpd $ 0x1b,%ymm0,%ymm0'
```

The STDOUT from spack is given in:

* [spack.install.openblas.gcc-7.2.0.rhel6..out.txt](https://github.com/spack/spack/files/3458812/spack.install.openblas.gcc-7.2.0.rhel6.out.txt)

The the build log file:

```
atdm-spack/spack/var/spack/stage/openblas-0.3.5-ase7rloe2w5cvr7egf4fglyx5kw2egrl/OpenBLAS-0.3.5/spack-build.out
```

is:

* [OpenBLAS-0.3.5-spack-build.out.txt](https://github.com/spack/spack/files/3458814/OpenBLAS-0.3.5-spack-build.out.txt)

### Platform and user environment

Please report your OS here:
```commandline
 $ uname -a
Linux crf450.srn.sandia.gov 2.6.32-696.30.1.el6.x86_64 #1 SMP Fri May 18 11:50:44 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:    Red Hat Enterprise Linux Workstation release 6.9 (Santiago)
``` 

Here are the compilers (where gcc@7.2.0 was built by spack itself with gcc@4.4.7 on the system).

* [compilers.yaml.txt](https://github.com/spack/spack/files/3458813/compilers.yaml.txt)

### Additional information

Sometimes the issue benefits from additional details. In these cases there are
a few things we can suggest doing. First of all, you can post the full output of:

```console
./atdm-spack/spack/bin/spack spec --install-status openblas %gcc@7.2.0
Input spec
--------------------------------
 -   openblas%gcc@7.2.0

Concretized
--------------------------------
==> Error: String contains no specs: 
```

to show people whether Spack installed a faulty software or if it was not able to
build it at all.

### PR DESCRIPTION
**Pull request by sethrj**
When building gcc7 and gcc8 on RHEL6 with Spack, then installing it as a
spack-available compiler, OpenBLAS will fail to compile because GCC
generates newer instructions than rhel6's `as` assembler knows about:
```
make[1]: *** [dtrsm_kernel_RN_HASWELL.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c: Assembler messages:
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c:33: Error: no such
instruction: `vpermpd $0x1b,%ymm0,%ymm0'
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c: Assembler messages:
../kernel/x86_64/dtrmm_kernel_4x8_haswell.c:33: Error: no such
instruction: `vpermpd $0x1b,%ymm0,%ymm0'
```

Building gcc8 (I didn't test with gcc7) with binutils succeeds, and it
generates a GCC that can then successfully build OpenBLAS.

This should fix #12235 by preventing an invalid compiler from being built by spack, *and* satisfy @adamjstewart 's [official stance on binutils](https://github.com/spack/spack/pull/14380#discussion_r363900239).

### CODE REVIEW

**Comment by alalazo** [comment]
@lee218llnl @becker33 Would this change be fine with you?

**Comment by lee218llnl** [comment]
Sounds reasonable to me, although we don't have anything with RHEL6 that I can verify this with, so I'll trust that this is universally true with RHEL6.

**Comment by sethrj** [comment]
Maybe @bartlettroscoe could verify that this allows spack-compiled GCC to build openblas on the legacy systems that somehow we get stuck maintaining...

**Comment by sethrj** [comment]
Interestingly, the `+binutils` flag fails on RHEL7 due to the `-static-libstdc++` that spack adds when said option is enabled.

[From spack-src/spack-bld/gcc/config.log:]
```
configure:6108: /projects/spack/lib/spack/env/gcc/g++ -std=gnu++98 -o conftest -g   -Wl,-rpath,/projects/ spack/opt/spack/gcc-4.8.5/gcc/q7k3652/lib -Wl,-rpath,/projects/spack/opt/spack/gcc-4.8.5/gcc/q7k3652/     lib64 -Wl,-rpath,/projects/spack/opt/spack/gcc-4.8.5/binutils/4qf3hz7/lib -Wl,-rpath,/projects/spack/opt/ spack/gcc-4.8.5/gmp/raqmdao/lib -Wl,-rpath,/projects/spack/opt/spack/gcc-4.8.5/isl/zwfd4x6/lib -Wl,-      rpath,/projects/spack/opt/spack/gcc-4.8.5/mpc/gevrvuj/lib -Wl,-rpath,/projects/spack/opt/spack/gcc-4.8.5/ mpfr/52czcru/lib -Wl,-rpath,/projects/spack/opt/spack/gcc-4.8.5/zlib/zolwez4/lib -static-libstdc++ -      static-libgcc  conftest.cpp  >&5
/projects/spack/opt/spack/gcc-4.8.5/binutils/4qf3hz7/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
```

**Comment by sethrj** [comment]
See https://github.com/spack/spack/issues/6080 and https://github.com/spack/spack/pull/4973 for discussion about `+binutils` being required for rhel6 and `~binutils` being required for rhel7.

**Comment by bartlettroscoe** [comment]
@sethrj, what exactly is needed to test this?  Just build `gcc@7.y.z+binutils` and then use that to build `openblas`?  What version of Spack?  Can I cherry-pick this on top of the latest Spack release?

**Comment by sethrj** [comment]
@bartlettroscoe You shouldn't even need to cherry-pick this commit. Otherwise, exactly right:
- build `gcc@7 +binutils` on a system that currently can't build openblas;
- add the resulting compiler with `spack compiler find`
- install `openblas %gcc@thatversion`

**Comment by bartlettroscoe** [comment]
Does this need to be tested off Spack 'develop' or can just the commits in this branch be cherry-picked?  I nervous taking 'develop'.

**Comment by sethrj** [comment]
Along the same lines, when using llvm@9 compiled against (spack-installed) gcc@8.3 on rhel6, the linker dies with this message:
```
/usr/bin/ld: BFD version 2.20.51.0.2-5.36.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```
even though the default spack clang uses `+gold` which compiles its own binutils.

A bit of googling shows that using the `-B` flag allows you to specify the binutils location, fixing the error:
```
/projects/spack/lib/spack/env/clang/clang -B $(spack location -i binutils %gcc@8.3.0)/bin ...
```

I can't find where or if Clang bakes the binutils path into its linker logic. Judging by the [gold plugin page](https://llvm.org/docs/GoldPlugin.html) it looks like it expects you to literally replace your system's `ld`... so I guess I need to add some spack compiler flags.

**Comment by scheibelp** [comment]
> Does this need to be tested off Spack 'develop' or can just the commits in this branch be cherry-picked? 

You can probably cherry pick this change without much issue. Depending on how old your Spack instance is, if some intervening changes have been applied to the `gcc` package, then you may encounter a merge conflict (e.g. there was a change to the `gcc` package as recently as January 4 2020 but that one is unlikely to conflict).

Another option that might be easier is to pull the entire develop repo into a separate directory, take only the `gcc` package.py file, and then temporarily overwrite that in whatever Spack instance you want to test with. That way, you will get all the intervening changes for `gcc` between your version and develop (without any changes to other packages or to the core of Spack).

**Pull request merged**
