### PR TITLE
enh: `buildcache list` should behave similar to `find`

### PR DESCRIPTION
**Pull request by matz-e**
The current output of buildcache list is very verbose and I feel like
some details are getting lost. By making the output similar to find, I
think users will be able to get a better overview of what is stored in
the cache.

### CODE REVIEW

**Comment by tgamblin** [comment]
@gartung: question: should this be called `buildcache find`?

* `spack find`: queries installed software packages
* `spack list`: lists available package recipes
* `spack buildcache list`: queries available binary caches, which are concrete and look like installed packages

Thoughts?

**Comment by tgamblin** [comment]
I can't decide whether it's more important that `list` always means "look at available stuff" or that `find` always implies nice queries on concrete specs.

**Comment by gartung** [comment]
Maybe make find an alias for list?

**Comment by gartung** [comment]
Probably most people do not even know buildache list is available. They spack install and sometimes that installs the buildache if the hashes happen to match.

**Comment by gartung** [comment]
And they happen to have the signing key installed and trusted,

**Comment by tgamblin** [comment]
Yeah let's just keep it `buildcache find` for now.  I think it's the best option.

We have had people argue that we should replace `list` with `avail` in a lot of places.  I'm not sure whether there is really a good set of subcommands that are unambiguous across all the use cases in Spack.

**Comment by tgamblin** [comment]
and of course I typed "keep it `buildcache find`" when I meant "keep it `buildcache list`" above.  Sorry!  🤯

**Pull request merged**
