### PR TITLE
Reformat Bash tab completion script

### PR DESCRIPTION
**Pull request by adamjstewart**
The only purpose of this PR is to minimize the diff in #14393 by factoring out formatting differences.

- [x] Replace `function foo` with `foo ()` declaration
- [x] Don't wrap long lines anymore

This PR should involve no functionality change.

### CODE REVIEW

**Comment by jcftang** [comment]
LGTM, have we considered in using an auto formatter like shfmt to ensure consistency in the long run for somethings?

**Comment by adamjstewart** [comment]
shfmt looks interesting. We’ve talked about using black for Python files, so that would be related. I think with the changes in #14393, this particular file won’t be a problem, but we could consider it for other shell scripts.

**Comment by jcftang** [comment]
FYI we use black in work for auto formatting, it works reasonably well until you want to do auto sorting of imports as some ide's sort the imports differently than others and it just causes chaos.

**Comment by adamjstewart** [comment]
That's surprising, PEP-8 is pretty explicit about how [imports should be sorted](https://www.python.org/dev/peps/pep-0008/#imports):

> Imports should be grouped in the following order:
>
> 1. Standard library imports.
> 2. Related third party imports.
> 3. Local application/library specific imports.
>
> You should put a blank line between each group of imports.

The only thing it doesn't specify is if imports should be sorted alphabetically within each group.

**Pull request merged**
