### PR TITLE
Add package anaconda3

### PR DESCRIPTION
**Pull request by ajkotobi**
Anaconda3 Base installation

### CODE REVIEW

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/anaconda3/package.py:9: [E302] expected 2 blank lines, found 1
var/spack/repos/builtin/packages/anaconda3/package.py:10: [E501] line too long (82 > 79 characters)
var/spack/repos/builtin/packages/anaconda3/package.py:10: [W291] trailing whitespace
var/spack/repos/builtin/packages/anaconda3/package.py:11: [E501] line too long (87 > 79 characters)
var/spack/repos/builtin/packages/anaconda3/package.py:11: [W291] trailing whitespace
var/spack/repos/builtin/packages/anaconda3/package.py:12: [E501] line too long (87 > 79 characters)
var/spack/repos/builtin/packages/anaconda3/package.py:13: [W291] trailing whitespace
var/spack/repos/builtin/packages/anaconda3/package.py:49: [W291] trailing whitespace
```

**Comment by ajkotobi** [comment]
@adamjstewart, Yeah sure, I'll take miniconda.

**Comment by ajkotobi** [comment]
I do see all checks are passed except `codecov/patch`, how to tackle it down?

**Comment by ajkotobi** [comment]
Those changes now been taken out. All checks passed.

**Comment by adamjstewart** [comment]
I still see 4 changed files...

**Comment by ajkotobi** [comment]
Sorry for that, I reverted back all unwanted changed files.

**Pull request merged**
