### PR TITLE
Add `spack pkg changed` command

### PR DESCRIPTION
**Pull request by tgamblin**
This provides some updates to the `spack pkg` command.  This command has been around for a while, though it is [only documented here](https://spack.readthedocs.io/en/latest/command_index.html#spack-pkg).  It'll tell you what packages were present in particular revisions of Spack, e.g.:

```console
$ spack pkg list v0.10.0 | wc -l
1114
$ spack pkg list v0.11.0 | wc -l
2177
$ spack pkg list v0.12.1 | wc -l
2907
```

It can diff two revisions, e.g.:

```console
$ spack pkg diff HEAD~150 
HEAD~150:
    openfoam-com

HEAD:
    dimemas       llvm-openmp  powerapi                   py-mlxtend       py-pyke      r-grbase     r-spatialreg
    jube          nim          py-antlr4-python3-runtime  py-mo-pack       py-pyugrid   r-gwmodel    r-spdata
    libmo-unpack  openfoam     py-cf-units                py-nc-time-axis  py-stratify  r-spacetime  umap
```

This PR adds the `spack pkg changed` command, which will tell you which packages have *changed* from one commit to another, e.g.:

```console
$ spack pkg changed  HEAD~40
bmi           cmake      hpcviewer  kim-api  libjpeg-turbo  llvm-openmp-ompt  openkim-models  prrte     py-scikit-learn
charliecloud  font-util  ibm-java   leveldb  libxpm         ompt-openmp       pmix            py-numpy
```
You can also ask for added, removed, and changed packages all at once:

```console
$ spack pkg changed --type ARC HEAD~40
bmi           font-util  kim-api        libxpm            ompt-openmp     prrte       py-scikit-learn
charliecloud  hpcviewer  leveldb        llvm-openmp       openkim-models  py-mlxtend
cmake         ibm-java   libjpeg-turbo  llvm-openmp-ompt  pmix            py-numpy
```

The motivation here is really to support a GitHub action that adds any `maintainers` specified on the package as reviewers for changed packages in the PR.  You can get that with, e.g.:

```console
$ spack pkg changed develop...
```

- [x] Added `spack pkg changed` command
- [x] Added tests for all `spack pkg` subcommands

### CODE REVIEW

**Comment by adamjstewart** [comment]
I've never used this command before, but more unit tests is always an improvement. Automatically pinging maintainers would be great. I wish there was a way to do it on issues as well.

**Comment by tgamblin** [comment]
@adamjstewart: issues are harder as I don't know how we'd detect the package names.  I guess we could look in the issue text for `spack install <name>` or other common command names and package specs.  That could probably work pretty well.

**Comment by adamjstewart** [comment]
We could also try searching the issue title for any package names when the `build-error` label has been applied.

**Comment by tgamblin** [comment]
Yeah, that, and we could ask in the issue template if particular packages were affected.  I think it would be pretty easy to come up with reasonably effective heuristics.

**Comment by tgamblin** [comment]
Anyway, this PR is just about the `spack pkg` command.

**Pull request merged**
