### PR TITLE
binutils: added '-Wno-narrowing' to CXXFLAGS when using fj compiler via flag_handler

### PR DESCRIPTION
**Pull request by Hironori-Yamaji**
I fixed the download URL because the previous URL are no longer available.

In addition, installing binutils with Fujitsu compiler will cause the following errors:
`x86_64.cc:1592:10: error: case value evaluates to 3221225474, which cannot be narrowed to type 'int' [-Wc++11-narrowing]`

The above cause is narrowing conversions are not allowed by {} initialization, since C++11. 

http://www.stroustrup.com/C++11FAQ.html#narrowing

Therefore, I used `-Wno-narrowing` to ignore the above errors and continue with the previous semantics of silently converting values.

https://gcc.gnu.org/wiki/FAQ#Wnarrowing

### CODE REVIEW

**Comment by mwkrentel** [comment]
@Hironori-Yamaji Could you try `spack fetch` with the ftpmirror URL
again?  How does it fail for you?

I'm guessing this is a transitory problem, which sometimes happens
with spack.

Anyway, there are more than 50 packages in spack whose URLs are from
ftpmirror.gnu.org.  And I run a cron job that fetches 7 of them from
scratch every day, and I haven't seen a problem.

So, I rather doubt that ftpmirror.gnu.org has gone away or anything.
A lot of people would be screaming if it did.

**Comment by Hironori-Yamaji** [comment]
@mwkrentel 
Thank you for your help.

> I'm guessing this is a transitory problem, which sometimes happens
> with spack

I tried `spack install` with the ftpmirror URL again.
As a result, I could fetch the tarball of binutils.

Therefore, I restored to the original URL.

**Comment by citibeth** [comment]
I'm a little uncomfortable with this.  It looks like a basic bug in the upstream package.  Therefore:

  1. Have you submitted it as a bug at the `binutils` site and seen what they have to say?  I

  2. It might be fixed sometime upstream.  In that case, we want our patch to be limited by version number, not universal.

  3. Since it's a language non-compliance issue, it might come up for more than the Fujitsu compiler.  (Also... please add comment explaining what `fj` is, many are not familiar).

@adamjstewart Any ideas of what to do with this, or others in Spack land we might engage?

**Comment by mwkrentel** [comment]
@Hironori-Yamaji 
See my comments in #11932.  The comments related to optimization level
also apply here, just substitue / -fPIC / -Wno-narrowing /.

I suggest changing the flag handling to:

```
def flag_handler(self, name, flags):
    if name == 'cxxflags' and self.compiler.name == 'fj':
        flags.append('-Wno-narrowing')
    return (flags, None, None)
```

The problem with `configure_args.append()` is that you'll erase any
optimization flag that autoconf adds.  For GNU, that would mean
building with `-O0`, I don't know what the default for Fujitsu is.

But be sure to test this, and run it with the following and you should
see the difference.

```
spack -d install -v binutils
```

----------

@citibeth
This is just CXXFLAGS, not a source code patch, right?

I tracked down the offending code.  `include/elf/common.h` has:

```
#define GNU_PROPERTY_X86_ISA_1_USED             0xc0000000
#define GNU_PROPERTY_X86_ISA_1_NEEDED           0xc0000001
#define GNU_PROPERTY_X86_FEATURE_1_AND          0xc0000002
```

These are used in `gold/x86_64.cc` as:

```
  int pr_type;
  ...
  switch (pr_type)
    {
    case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
    case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
    case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
```

So, C++ is fussy about 0xc0000002 and int vs unsigned int.  Sure, it's
technically inaccurate or sloppy, but I've seen worse.

I suggest add `-Wno-narrowing`, declare victory and move on.  The flag
is pretty innocuous.

I'm guessing that Fujitsu is unusual in that it fails the build for
this.  Maybe other compilers spit out a warning, but compile the code.
But that's just a guess.

**Comment by Hironori-Yamaji** [comment]
@citibeth
Thank you for your reply!

>1. Have you submitted it as a bug at the binutils site and seen what they have to say? I

I will submit this errors and let you know the details later.

>2. It might be fixed sometime upstream. In that case, we want our patch to be limited by version number, not universal.

I changed the patch to be applied for version less than or equal to 2.31.1.

>3. Since it's a language non-compliance issue, it might come up for more than the Fujitsu compiler. (Also... please add comment explaining what fj is, many are not familiar).

I tried to install binutils by gcc and fj, the errors occurred only in fj.
(And I added comment explaining what fj is.)

---
@mwkrentel
Thank you for your help!

I changed the flag handling and saw the difference between `configure_args.append()` and `flags.append()`.


When the flag handling is `configure_args.append()`, the optimization flag that autoconf adds was erased:
```
-frandom-seed=archive.o  -pthread -Wno-narrowing -c -o archive.o archive.cc
```
When the flag handling is `flags.append()`, the optimization flag that autoconf adds was not erased:
```
-frandom-seed=archive.o  -pthread -g -O2 -c -o archive.o archive.cc
```

To erase the the optimization flag is undesirable, so I changed `configure_args.append()` to `flags.append()`.

**Comment by citibeth** [comment]
I'm happy to merge.  The macOS test is blowing up for some unknown reason (and likely unrelated to this PR).

**Comment by mwkrentel** [comment]
I checked binutils 2.32 (released Feb 2019) and in 2.32, `pr_type` is
now `unsigned int`.  I can't guarantee that every such instance has
been fixed, but probably so.

So, it's probably safe to restrict `-Wno-narrowing` to <= 2.31.1
and I'm ok with the PR.

**Pull request merged**
