### PR TITLE
Add latest version of py-pybind11

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully builds on Cray CNL5 with GCC 5.3.0.

@ax3l

### CODE REVIEW

**Comment by adamjstewart** [comment]
@ax3l question for you. It looks like this package can be installed as either a `PythonPackage` or a `CMakePackage`? What are the advantages of using `CMakePackage`? I ask because I'm thinking about switching `py-torch` to `CMakePackage` as well.

**Comment by ax3l** [comment]
pybind11 is itself a C++ header-only library. In both builds (CMakePackage/PythonPackage) it will build via CMake, but the `setup.py` install just calls this via a wrapper of setuptools which is useful if one creates wheels or pip source tarballs. I just checked and in both ways it adds further swag in the sense that downstream python users can query a python module to get C-includes and it has a python egg.
    https://github.com/conda-forge/pybind11-feedstock/blob/master/recipe/build.sh

In CF we therefore test for this after install:
  https://github.com/conda-forge/pybind11-feedstock/blob/master/recipe/meta.yaml#L33-L34

Turns out this feature was broken for years in CF and nobody complained, probably because downstream is usually using CMake as well and queries the cmake config files instead ;) Either way, I just checked and the CMakePackage install seams to have everything in place already...

**Comment by adamjstewart** [comment]
> But we should add the same test

If you look at `PythonPackage` I already have the machinery for an import test. Feel free to steal this for `py-pybind11` if you want.

**Comment by ax3l** [comment]
Sounds great! I was tryting something like
```python
            module = "pybind11"
            self.python('-c', 'import {0}'.format(module))
            inc = self.python('-c', 'import {0} as py; print(py.get_include())'.format(module))
            print(inc)
            assert inc == self.prefix
```
but cannot capture the output to verify and could not find examples. Do you have hints for me about this?

**Comment by adamjstewart** [comment]
`self.python` is an object of type `spack.util.executable.Executable`. See the docstring for the `__call__` method for what can be passed in. I think `output=str` is what you want to capture the output.

**Comment by ax3l** [comment]
I just realized this is indeed also here pointing to the wrong location... Will document as an issue.

**Pull request merged**
