### PR TITLE
Report clean results to CDash

### PR DESCRIPTION
**Pull request by zackgalbreath**
Update the CDash reporter to generate results when nothing goes wrong.  Previously it would only generate and upload a report when errors occured during `spack install`.

### CODE REVIEW

**Comment by tgamblin** [comment]
@JavierCVilla: does this work for you?

**Comment by JavierCVilla** [comment]
@tgamblin haven’t tried it yet, I’ll test it tomorrow

**Comment by JavierCVilla** [comment]
@tgamblin @zackgalbreath 

After trying this PR, I still see some weird behaviours when reporting results to CDash. I have done the following tests:

- Installing `python` with some failures at build time, `Build.xml` got uploaded to CDash, but not the configuration logs.
- `zlib` did not upload configuration logs either, although it runs a `configure`, I think it's due to the fact that `zlib` inherits from `Package`. Are `phases` defined for this kind of packages?

I'm uploading [here](http://cdash.cern.ch/index.php?project=Spack) these logs.

On top of that I would like to share some questions:

- Let's say that installing `python` one of the dependencies fails, so far I think this failure would not be visible on the report. Should we try to cover this case? For example, one solution might be to attach the output of those failed packages as part of the report uploaded to cdash. [Here](http://cdash.cern.ch/viewFiles.php?buildid=579824) there is an example.

- How complicated would be to include the build time reported by spack as part of the logs? I mean this time:

```
==> Successfully installed python
  Fetch: 0.07s.  Build: 2m 33.14s.  Total: 2m 33.21s.
```
That would allow to see the build time in the *Advanced view*  of CDash.

cdash

**Comment by zackgalbreath** [comment]
Are there any other changes I should make to this PR before we can merge it?

**Comment by JavierCVilla** [comment]
@zackgalbreath 

>  I'm having trouble reproducing this. Locally I've been using util-linux as an example of a package that fails to build, and it uploads both Configure & Build for me. What did you do to get the python build to fail? Maybe that would work for me too.

I just tried the python build again and [this](http://cdash.cern.ch/index.php?project=Spack&date=20181031) is the result. I do the following:

- Checkout to this branch
- Modify `python` to fail: in line 183 `cppflags = '-I' + ' -I'` gets replaced by `cppflags = '-I' + ' -'` (just removed the last `I`)

**Comment by JavierCVilla** [comment]
Regarding this point:

> This should work already. The CDash reporter examines build/test output for all packages installed, not just the root package. To manually test this, I edited the diffutils' package to cause an error during installation. This error gets reported to CDash when I attempt to install bzip2 because bzip2 depends on diffutils.

Maybe I'm missing something. I modify `diffutils` to return a `--wrong` parameter in `configure_args` which makes its installation fail:

```
$ spack install --cdash-upload-url=http://cdash.cern.ch/submit.php?project=Spack bzip2
==> Installing diffutils
==> Using cached archive: /tmp/jcervant/spack/var/spack/cache/diffutils/diffutils-3.6.tar.xz
==> Staging archive: /tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q/diffutils-3.6.tar.xz
==> Created stage in /tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q
==> No patches needed for diffutils
==> Building diffutils [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q/diffutils-3.6/configure' '--prefix=/tmp/jcervant/spack/opt/spack/linux-centos7-x86_64/gcc-6.2.0/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q' '--wrong'

1 error found in build log:
     3    ==> '/tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q/diffutils-3.6/configure' '--prefix=/tmp/jcervant/spack/opt
          /spack/linux-centos7-x86_64/gcc-6.2.0/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q' '--wrong'
  >> 4    configure: error: unrecognized option: `--wrong'
     5    Try `/tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q/diffutils-3.6/configure --help' for more information

See build log for details:
  /tmp/jcervant/spack/var/spack/stage/diffutils-3.6-nx6pywubosop7rbnuws3nsilssefh34q/diffutils-3.6/spack-build.out
==> Installing bzip2
==> Using cached archive: /tmp/jcervant/spack/var/spack/cache/bzip2/bzip2-1.0.6.tar.gz
==> Staging archive: /tmp/jcervant/spack/var/spack/stage/bzip2-1.0.6-3qxk4hx4z6nqcivvuajybjdju4ur376o/bzip2-1.0.6.tar.gz
==> Created stage in /tmp/jcervant/spack/var/spack/stage/bzip2-1.0.6-3qxk4hx4z6nqcivvuajybjdju4ur376o
==> Ran patch() for bzip2
==> Building bzip2 [Package]
==> Executing phase: 'install'
==> Successfully installed bzip2
  Fetch: 0.00s.  Build: 2.59s.  Total: 2.59s.
[+] /tmp/jcervant/spack/opt/spack/linux-centos7-x86_64/gcc-6.2.0/bzip2-1.0.6-3qxk4hx4z6nqcivvuajybjdju4ur376o
``` 

However, the [report uploaded](http://cdash.cern.ch/buildSummary.php?buildid=585735) to CDash only shows bzip2.

**Comment by zackgalbreath** [comment]
I see the common pattern now, you're not getting configure results **at all**.  The next step is to figure out if Spack is failing to generate/upload Configure.xml, or if your instance of CDash is failing to parse it.  Try searching for `Configure.xml` after calling `spack install --cdash-upload-url=...`.

Here's what this looks like for me:
```
$ find . -name 'Configure.xml'
./cdash_report/Configure.xml
./share/spack/templates/reports/cdash/Configure.xml
```

**Comment by JavierCVilla** [comment]
Mmm you are right, indeed I have both:

```
$ find . -name 'Configure.xml'
./share/spack/templates/reports/cdash/Configure.xml
./var/spack/junit-report/test-python-2.7.15-gpykmyhiwecrbvzstvz3tkihnmsyz4uu.xml/Configure.xml
./var/spack/junit-report/test-bzip2-1.0.6-3qxk4hx4z6nqcivvuajybjdju4ur376o.xml/Configure.xml
```

So I guess it should be my CDash instance, any ideas to check what's going wrong?

**Comment by zackgalbreath** [comment]
> So I guess it should be my CDash instance, any ideas to check what's going wrong?

I just pushed a commit to this branch to better support older versions of CDash.  Please give it a try when you get a free minute & let me know if it looks better to you.

**Comment by JavierCVilla** [comment]
@zackgalbreath I tried the last commit and it worked for [`bzip2`](http://cdash.cern.ch/buildSummary.php?buildid=585797) but... trying with `lz4` I think i have hit a [parsing error](http://cdash.cern.ch/buildSummary.php?buildid=585838):

```
Build command: lz4
Start Time: 2018-10-31T15:47:19 UTC
End Time: 2018-10-31T15:47:19 UTC

 39: m4_stack                                        ok
 40: m4_defn                                         ok
 41: m4_dumpdef                                      ok
 42: m4_warn                                         ok
 43: m4_divert_stack                                 ok
 44: m4_expansion_stack                              ok

45: m4_require: error message                       ok
``` 

I think the previous message is not an error but a check. Also (maybe as a consequence of the previous error), errors from the dependencies have not been reported.

**Comment by zackgalbreath** [comment]
> I think the previous message is not an error but a check

Yeah, looks like configure output maybe? I had trouble reproducing this locally.  Is this from `spack install --test`?  We have a TODO item on our list to split out testing output into its own separate phase.

**Comment by zackgalbreath** [comment]
> Will the splitting be part of this PR?

That will be a separate effort, it's a bigger change to Spack outside of the scope of the CDash reporter. I created an issue so we don't forget: #9701.

**Comment by JavierCVilla** [comment]
@zackgalbreath In that case, from my side this can be merged, we'll keep moving on in other PR's.

**Pull request merged**
