### PR TITLE
Using ninja as cmake generator for trilinos

### PR DESCRIPTION
**Pull request by jrood-nrel**
Depends on if https://github.com/spack/spack/pull/10470 would be merged. I haven't formally tested how much faster this is, but anybody using trilinos would benefit from reduced build time with this.

### CODE REVIEW

**Comment by jrood-nrel** [comment]
I have a 32 core machine with SSDs and regular makefiles take 11 minutes, in which I build and test trilinos nightly, and with ninja it takes 4 minutes.
```
Make
==> Building trilinos [CMakePackage]
==> Executing phase: 'cmake'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed trilinos
  Fetch: 0.00s.  Build: 10m 46.36s.  Total: 10m 46.36s.
```
```
Ninja
==> Building trilinos [CMakePackage]
==> Executing phase: 'cmake'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed trilinos
  Fetch: 26.67s.  Build: 4m 13.65s.  Total: 4m 40.31s.
```

**Comment by scheibelp** [comment]
Given that the `kitware` version of `ninja` is currently pegged to a branch rather than a release or commit, this could possibly make the `trilinos` build unstable. Perhaps this could be activated with a variant? Admittedly that's not a great suggestion since `trilinos` has plenty of variants as is, and arguably building with `ninja` doesn't change the bits that are produced (although it may).

**Comment by jrood-nrel** [comment]
That makes sense. I can tie it to a variant.

**Comment by jrood-nrel** [comment]
One thing that confuses me is how to query the variant outside of the functions? It looks like I can't set `generator` inside of `cmake_args`.

**Comment by scheibelp** [comment]
> One thing that confuses me is how to query the variant outside of the functions? It looks like I can't set generator inside of cmake_args.

I think you may have better luck creating a `generator` property (returning `"ninja"` when the variant is active). This should work because although `generator` appears to be created as a class property it is read as an instance property. I'm inclined to say it ought to be an instance property (but this is probably the first time it mattered).

Updating `generator` in `cmake_args` may be too late: there is a function which runs before `cmake_args` and makes use of the `generator` variable.

**Comment by jrood-nrel** [comment]
Thanks @scheibelp . Before I do this, might it make sense to trade the ninja variant here and require a specific commit of the ninja kitware branch, either here or in the ninja package as if it were a tag?

**Comment by jrood-nrel** [comment]
@scheibelp Yeah it seems as though the Ninja Kitware fork is experimental, so I think it's probably best to leave it as a branch in the Ninja package file. I've been using it without any issues though. So if you're fine with this being a variant, I think this is done. Otherwise if this is a bad use of a variant, I'm not adamant about getting it merged because it's a simple feature I can just use locally. I'm not sure of the best route for experimental stuff like this, but I think this can be a step forward in testing the Kitware branch of Ninja in hopes it gets upstreamed so that maybe Spack would be able to switch to Ninja as a generator for all CMake packages in the future.

**Comment by jrood-nrel** [comment]
I think I'm going to close this. Probably only best to do this if when Spack officially supports Ninja as a generator instead of making this a custom modification.

**Pull request closed without merging**
