### PR TITLE
trilinos: update hdf5 dependency to use 'hdf5+hl'

### PR DESCRIPTION
**Pull request by balay**
Without this change - I get the following error [triggered by 161dca6d5 c9810f808 changes]

$ ./bin/spack install trilinos+hdf5
==> Error: An unsatisfiable variant constraint has been detected for spec:

    hdf5@1.10.1%gcc@7~cxx~debug~fortran~hl+mpi+pic+shared~szip~threadsafe arch=linux-fedora27-x86_64

while trying to concretize the partial spec:

    netcdf+mpi
        ^m4
        ^mpich@3.3a2%gcc@7 device=ch3 +hydra netmod=tcp +pmi+romio~verbs arch=linux-fedora27-x86_64
        ^zlib@1.2.11%gcc@7+optimize+pic+shared arch=linux-fedora27-x86_64

netcdf requires hdf5 variant +hl, but spec asked for ~hl

### CODE REVIEW

**Comment by balay** [comment]
I have no idea what the issue issue is. I get that  error message [listed in the commit message]  - and this change works for me.

So I guess I'm partly seeking feedback/confirmation on what the issue is.

If it is indeed a ' concretizer bug' - then I can updated the commit with this incode comment you suggest

**Comment by balay** [comment]
Ok - pushed the 'FIXME:' in-code comment.

**Comment by davydden** [comment]
Looks like this: https://github.com/LLNL/spack/issues/5465#issuecomment-332027738

**Comment by davydden** [comment]
@scheibelp ping

**Comment by scheibelp** [comment]
This is currently failing flake checks.

> Looks like this: #5465 (comment)

Agreed. You can also deal with this by specifying:

`spack spec trilinos+hdf5 ^hdf5+hl`

I'll also say the `trilinos` package.py has some odd constraints, namely it has both: 

`depends_on('hdf5@1.8.9:+hl')`

and

`depends_on('hdf5@:1.8.999', when='@:4.4.0')`

the first is unconditional and conflicts with the second. I'm surprised this isn't causing a problem right now. That being said, even if that issue were to be handled (and perhaps that isn't a priority because for whatever reason it isn't causing a failure now) the failure mentioned in this PR would still occur.

**Comment by davydden** [comment]
> I'll also say the trilinos package.py has some odd constraints

you probably meant `netcdf`. Those were introduced in https://github.com/LLNL/spack/pull/5819 . The first one should probably read
```
depends_on('hdf5@1.8.9:+hl', when='@4.4.1:')
```
would you agree @skosukhin ?

**Comment by skosukhin** [comment]
@davydden, the first constraint says that we need high-level API of hdf5 1.8.9 or later: `depends_on('hdf5@1.8.9:+hl')`. The second constraint says that for netcdf 4.4.0 and prior we want HDF 1.8.* (not 1.10.*): `depends_on('hdf5@:1.8.999', when='@:4.4.0')`. Thus, for netcdf 4.4.0 and prior we accept any hdf5 between 1.8.9 and 1.8.999. And for netcdf 4.4.1 and later we accept any hdf5 starting version 1.8.9.

Maybe we should make `+hl` by default for `hdf5`. I just wonder why I didn't have the same concretization problem with `cdo`.

**Comment by jrood-nrel** [comment]
I was having this same problem and made this commit that fixed it for met: 50d932d9f129aa807dec510b37847a7f9672a1e7

**Comment by davydden** [comment]
> I was having this same problem and made this commit that fixed it for me: 50d932d

i don't understand what's going on in Spack as in this change
```
-    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@master")
-    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@12.10.2:")
+    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@master,12.12.1:")
```
`12.12.1:` should be already covered by `+pnetcdf@12.10.2:`

**Comment by jrood-nrel** [comment]
@davydden To be honest I fully expected the original code to work and add in the netcdf dependency, but it wasn't doing so either after the netcdf package update or the new trilinos version being added. I have an explanation in #5990 . My problem had to do with `trilinos+pnetcdf` not adding `netcdf` dependency into the spec and the default netcdf would be used and cause the unsatisfiable constraint. I think there may be two problems, one where two `depends_on` statements weren't working together, as seen before my commit, and the other the `hdf5+hl` issue.

**Comment by scheibelp** [comment]
@jrood-nrel to be clear: in https://github.com/LLNL/spack/pull/5990 were you getting an error about unsatisfiable dependencies or was the concretization completing but not adding the `netcdf` dependency?

Also to be clear the following changes:

```
-    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@master")
-    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@12.10.2:")
+    depends_on('netcdf+mpi+parallel-netcdf', when="+pnetcdf@master,12.12.1:")
```

would ideally not be required

**Comment by jrood-nrel** [comment]
Before my commit with `spack spec nalu`, during concretization, the normalized spec was:
```
^netcdf+mpi
```
After my commit, `spack spec nalu` showed:
```
^netcdf+mpi+parallel-netcdf
```
The first spec had the exact unsatisfiable `+hl` `~hl` conflict due to the "vanilla" netcdf in the spec for trilinos 12.12.1 which is the default. My commit fixed the unsatisfiable error in my case because somehow the `+parallel-netcdf` turns on `hdf5+hl` for netcdf I believe. I agree my commit shouldn't have been necessary, but it wasn't adding `netcdf+mpi+parallel-netcdf` as expected. Maybe I am missing something though.

**Comment by jrood-nrel** [comment]
If you try adding the old lines back in my commit and doing `spack spec nalu`, you can see the unsatisfiable error.

**Comment by scheibelp** [comment]
> Before my commit with spack spec nalu, during concretization, the normalized spec was:

To be clear, additional Spec properties are chosen after spec normalization, so the normalized spec doesn't necessarily represent all the details that will be set on the final spec (especially for complex packages). It sounds like the primary issue fixed was the "unsatisfiable" error

**Comment by balay** [comment]
Just checking if this can be merged to develop [or if an alternate fix exists]

**Pull request merged**
