### PR TITLE
openssl: Add perl dependency

### PR DESCRIPTION
**Pull request by michaelkuhn**
perl is required for the configure script.

### CODE REVIEW

**Comment by adamjstewart** [comment]
We literally just removed this dependency if you check the history. Is Perl needed for something other than `make test`?

**Comment by michaelkuhn** [comment]
Ah, sorry, I did not check the history. The package calls the `config` script, which in turn calls `Configure`, which is a Perl script. If you do not have (a full) Perl installation, you get something like this:
```
Can't locate File/Compare.pm in @INC (you may need to install the File::Compare module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./Configure line 10.
BEGIN failed--compilation aborted at ./Configure line 10.
This system (linux-x86_64) is not supported. See file INSTALL for details.
```

**Comment by adamjstewart** [comment]
@tgamblin Can you comment?

**Comment by healther** [comment]
what is the status on this? is perl needed?

**Comment by michaelkuhn** [comment]
@alalazo @junghans Could you take a look? This is still required as far as I can tell.

**Comment by alalazo** [comment]
According to [this](https://wiki.openssl.org/index.php/Compilation_and_Installation) we need:
```python
depends_on('perl@5.10.0:', when='@1.1.0:')
```
there are more details in the `NOTES.PERL` text file shipped with the tarball:

>  You MUST have at least Perl version 5.10.0 installed.  This minimum
 requirement is due to our use of regexp backslash sequence \R among
 other features that didn't exist in core Perl before that version.

In older version (`@1.0.X` series) it seems the requirement on Perl is a bit softer (see INSTALL file in the tarball):

> To install OpenSSL, you will need:
>
>  * make
>  * Perl 5
>  * an ANSI C compiler
>  * a development environment in form of development libraries and C
>    header files
>  * a supported Unix operating system

Also: why are we marking version `1.0.2k` to be the preferred one?

**Pull request merged**
