### PR TITLE
Fix JDK 8 download URLs

### LINKED ISSUE #14104: JDK fetchers fail
### Steps to reproduce the issue

```
spack install jdk@1.8.0_231-b11%gcc@9.2.0
```

### Platform and user environment

```
$ uname -a 
Linux xrmlite 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 8.0.1905 (Core)
``` 

### Error message : 

```
[sajid@xrmlite spack]$ spack install jdk@1.8.0_231-b11%gcc@9.2.0
==> Installing jdk
==> Searching for binary cache of jdk
==> No binary for jdk found: installing from source
==> Fetching https://download.oracle.com/otn/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
################################################################################################################################################################ 100.0%################################################################################################################################################################ 100.0%==> Warning: The contents of the archive look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
==> Error: ChecksumError: sha256 checksum failed for /tmp/sajid/spack-stage/spack-stage-jdk-1.8.0_231-b11-3ymu66b4agiqqvwqmvt6cc5sffzu6d2t/jdk-8u231-linux-x64.tar.gz
    Expected a011584a2c9378bf70c6903ef5fbf101b30b08937441dc2ec67932fb3620b2cf but got febd55e91cc277096f0c9670bba0085503b982c59df48bd5aa673be2bad545cc

/home/sajid/packages/spack/lib/spack/spack/package.py:1083, in do_fetch:
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082
  >>   1083        if checksum and self.version in self.versions:
       1084            self.stage.check()
       1085
       1086        self.stage.cache_local()
```

I've gotten around with using a hash I found somewhere on the internet and using the URL specified in [this post](https://stackoverflow.com/questions/56650812/how-to-install-oraclejdk8-through-docker-file-in-ubuntu) instead of what spack uses. 

PS : I'm on develop at the latest commit.

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #14104 

@s-sajid-ali

### CODE REVIEW

**Comment by s-sajid-ali** [comment]
I'm unable to fetch as per the new rules on my laptop with WSL2-ubuntu : 
```
sajid@DESKTOP-NDBN82B:~$ curl -j -b 'oraclelicense=accept-securebackup-cookie' https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
sajid@DESKTOP-NDBN82B:~$ ls
miniconda3  nu-quest-mpi  nvim.appimage  ssh-keys
sajid@DESKTOP-NDBN82B:~$
```

**Comment by adamjstewart** [comment]
@s-sajid-ali It works for me:
```console
$ spack fetch jdk@1.8.0_231-b11
==> Fetching https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
################################################################################################################################# 100.0%
```

**Comment by s-sajid-ali** [comment]
Works for me as well, looks like I made an error in translating the `curl_options` to manually fetch via curl. Thanks for fixing this!

**Comment by s-sajid-ali** [comment]
This is failing again on develop (develop on my fork but it's synced to spack/spack/develop), at the latest commit : 


```
[sajid@xrmlite spack]$ git checkout develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
[sajid@xrmlite spack]$ git log -n 1
commit 94bc6b06b1e5cc8746271d761d7ff007a394d592 (HEAD -> develop, upstream/develop, origin/develop, origin/HEAD)
Author: Brian Van Essen <vanessen1@llnl.gov>
Date:   Thu Jan 16 15:02:50 2020 -0800

    Added new hashes for the protobuf and py-protobuf packates. (#14546)

    * Added new hashes for the protobuf and py-protobuf packates.

    * Fixed flake8
[sajid@xrmlite spack]$ spack fetch jdk@1.8.0_231-b11
==> Fetching https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
################################################################################################################################################################ 100.0% -=O#-    #      #        #
curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz
    URL https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz was not found!
==> Fetching from https://download.oracle.com/otn-pub/java/jdk/8u231-b11/5b13a193868b4bf28bcb45c792fce896/jdk-8u231-linux-x64.tar.gz failed.
==> Error: All fetchers failed for spack-stage-jdk-1.8.0_231-b11-qxdc23mb6ei7jvkfzpxmweuzu6sut5hb
[sajid@xrmlite spack]$
```

**Pull request merged**
