### PR TITLE
ADIOS 1.13.0: LZ4 & blosc support

### PR DESCRIPTION
**Pull request by ax3l**
Add additional transform libraries to ADIOS, [LZ4 and blosc](https://arxiv.org/abs/1706.00522).

Also modifies existing transforms to the versions they were introduced (otherwise this was resulting in unknown configure flags).

### CODE REVIEW

**Comment by alalazo** [comment]
@ax3l Care to add yourself as a maintainer for this package?

**Comment by ax3l** [comment]
Sure, why not. Is there a list or something on it?

**Comment by alalazo** [comment]
Check `dealii`. I think it should be as easy as adding a:
```python
maintainers = ['ax3l']
```
at class scope.

**Comment by ax3l** [comment]
All right, I will add me in a follow-up PR to all the packages I care about ;)

**Comment by alalazo** [comment]
Thanks!

**Comment by ax3l** [comment]
will adding the maintainer attribute give me any kind of notification on issues/PRs automatically?

**Comment by alalazo** [comment]
No, but you'll show up on `spack info` and it's likely people will request your review more often for those packages.

**Pull request merged**
