### PR TITLE
Added Nox for Trilinos installation by xSDK

### PR DESCRIPTION
**Pull request by keitat**

### CODE REVIEW

**Comment by balay** [comment]
I think its best to update only @develop and not change @0.3.0

**Comment by keitat** [comment]
Need another check-in (fix) so that it only affects @develop.

**Comment by tgamblin** [comment]
Does it makes sense to add a 0.3.1 version?

**Comment by aprokop** [comment]
@keitat Looking back at this PR, I'm not sure why it changed dependency from `trilinos@develop` to `trilinos@12.12.1`. This is going to cause conflicts with DataTransferKit which needs newer trilinos.

**Pull request merged**
