### PR TITLE
netcdf-fortran: enforce autoreconf when building with NAG.

### PR DESCRIPTION
**Pull request by skosukhin**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Finally someone else who uses NAG! I added support for the NAG compiler when I first started using Spack but found that very few packages would actually build. NAG is very strict about rules compliance.

**Comment by skosukhin** [comment]
Yes, many packages fail to build with NAG but I manage to build most of what I need. And this PR is not really about NAG but about an outdated version of the Libtool script that comes with the release tarball.

**Comment by adamjstewart** [comment]
Can you try running autoreconf yourself and see how big the diff is? I prefer patching over `force_autoreconf` to avoid the additional dependencies. Also, you can apply the patch `when='@:4.4.4'` as it sounds like this will be fixed in the next release.

**Comment by skosukhin** [comment]
We need to patch an autogenerated file, which might be very different between two version of netcdf-fortran and is very different between different version of Autotools. Which is why running autoreconf is the right solution in general. Luckily, we have only two versions of netcdf-fortran in Spack and their configure scripts do not differ much, so we can have just one patch file for both of them. The minimum that we need in this case is just two lines in libtool.m4, which get duplicated several times in the resulting configure script. I am submitting the patch in several minutes.

**Pull request merged**
