### PR TITLE
blast-plus: build fails on the IBM POWER8 unless the packaged config.guess is updated

### PR DESCRIPTION
**Pull request by dnanto**
NCBI packaged versions >=2.9.0 with a config.guess from 2013-02-12. This caused spack install to fail. The message suggested running `wget -O config.guess 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'` to obtain the latest config.guess script. Including the diff and patching it from within package.py resolved the issue.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@alalazo don't we already patch `config.guess` in `AutotoolsPackage`?

**Comment by dnanto** [comment]
> @alalazo don't we already patch `config.guess` in `AutotoolsPackage`?

Not sure why it's not automatically patching in that case. I can help provide some more debug info tomorrow to try and get a better solution within this branch. In the meantime, the current solution got us out of a bind. NCBI changed all BLAST databases to version 5 so we needed to update from version 2.6, which is the latest one that conda offers.

**Comment by dnanto** [comment]
I pulled the latest spack and re-installed to generate all the error messages I got. The first two are resolvable using a spack flag and setting an environment variable. The last error is the one due to `config.guess`.

* Certificate verification failed when installing `perl`. However, using `spack -k` resolved the issue.

```bash
==> Installing perl
==> Searching for binary cache of perl
==> No binary for perl found: installing from source
==> Fetching http://www.cpan.org/src/5.0/perl-5.30.1.tar.gz
######################################################################## 100.0%
==> Fetching http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz
######################################################################## 100.0%
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
==> Failed to fetch file from URL: http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz
    Curl was unable to fetch due to invalid certificate. This is either an attack, or your cluster's SSL configuration is bad.  If you believe your SSL configuration is bad, you can try running spack -k, which will not check SSL certificates.Use this at your own risk.
==> Fetching from http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7042.tar.gz failed.
==> Error: FetchError: All fetchers failed for resource-cpanm-abvo7srcdo4nhmwqkskysjilezglmwap

/home/dnanto/spack/lib/spack/spack/package.py:1110, in do_fetch:
       1107                raise FetchError("Will not fetch %s" %
       1108                                 self.spec.format('{name}{@version}'), ck_msg)
       1109
  >>   1110        self.stage.create()
       1111        self.stage.fetch(mirror_only)
       1112        self._fetch_time = time.time() - start_time
       1113


$ 
```

* Installation of `gmp` also failed. Running `export CXX="$(which c++)"` resolved this issue.

```bash
==> Installing gmp
==> Searching for binary cache of gmp
==> No binary for gmp found: installing from source
==> Fetching https://ftpmirror.gnu.org/gmp/gmp-6.1.2.tar.bz2
######################################################################## 100.0%
==> Staging archive: /tmp/dnanto/spack-stage/spack-stage-gmp-6.1.2-lpalkqlnx5kwhflnc6jyesqn2i6c3f6t/gmp-6.1.2.tar.bz2
==> Created stage in /tmp/dnanto/spack-stage/spack-stage-gmp-6.1.2-lpalkqlnx5kwhflnc6jyesqn2i6c3f6t
==> No patches needed for gmp
==> Building gmp [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/dnanto/spack-stage/spack-stage-gmp-6.1.2-lpalkqlnx5kwhflnc6jyesqn2i6c3f6t/spack-src/configure' '--prefix=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/gmp-6.1.2-lpalkqlnx5kwhflnc6jyesqn2i6c3f6t' '--enable-cxx'

1 error found in build log:
     70    checking for build system compiler math library... -lm
     71    checking for g++... g++
     72    checking whether we are using the GNU C++ compiler... no
     73    checking whether g++ accepts -g... no
     74    checking C++ compiler g++  -m64  -O3... no
     75    checking C++ compiler g++  ... no
  >> 76    configure: error: C++ compiler not available, see config.log for details

See build log for details:
  /tmp/dnanto/spack-stage/spack-stage-gmp-6.1.2-lpalkqlnx5kwhflnc6jyesqn2i6c3f6t/spack-build-out.txt

$ 
```

* Installation of blast-plus fails due to `config.guess` error.

```bash
==> Installing blast-plus
==> Searching for binary cache of blast-plus
==> No binary for blast-plus found: installing from source
==> Fetching https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-src.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/dnanto/spack-stage/spack-stage-blast-plus-2.9.0-e4zyhu3mwjtevp5ypre34miszdw2npdm/ncbi-blast-2.9.0+-src.tar.gz
==> Created stage in /tmp/dnanto/spack-stage/spack-stage-blast-plus-2.9.0-e4zyhu3mwjtevp5ypre34miszdw2npdm
==> No patches needed for blast-plus
==> Building blast-plus [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/dnanto/spack-stage/spack-stage-blast-plus-2.9.0-e4zyhu3mwjtevp5ypre34miszdw2npdm/spack-src/c++/configure' '--prefix=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/blast-plus-2.9.0-e4zyhu3mwjtevp5ypre34miszdw2npdm' '--with-bin-release' '--without-debug' '--with-mt' '--without-boost' '--with-64' '--with-dll' '--without-static' '--without-static-exe' '--with-jpeg=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/libjpeg-turbo-2.0.3-atammcpync2smvhzaigevsoeckif3kws' '--with-png=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/libpng-1.6.37-lsfpqfo37sofjbsy25vr7yi7pdhvbzjt' '--with-freetype=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/freetype-2.10.1-46euo4ixys5pcwy7g7buhdpuz7fmjpwy' '--without-hdf5' '--with-z=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/zlib-1.2.11-3nfndvocjc7tf3cudffziwou3h3le6aj' '--with-bz2=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/bzip2-1.0.8-amsg4hkouezx7otez6xvj2s5ijcvcyyk' '--with-lzo=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/lzo-2.10-2esnxow3ieeqlg7dcqc6m7rusnmtzwdc' '--with-gnutls=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/gnutls-3.6.8-45qu4tkibnsg2ihrrlycqs2mgytxmvlg' '--with-openssl=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/openssl-1.1.1d-fcdmumqlleqm2b6zvdegi7ml4ncx2bhh' '--with-pcre=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/pcre-8.42-kqb2whrkmtvlvhkefpz5icdp4vk7txu7' '--with-python=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/python-3.7.6-b6xfcid6brj4dqb5u352762jo53uvhnq' '--with-perl=/home/dnanto/spack/opt/spack/linux-ubuntu16.04-power8le/gcc-8.3.0/perl-5.30.1-abvo7srcdo4nhmwqkskysjilezglmwap'

1 error found in build log:
     40    /usr/convex/getsysinfo =
     41    
     42    UNAME_MACHINE = ppc64le
     43    UNAME_RELEASE = 4.4.0-171-generic
     44    UNAME_SYSTEM  = Linux
     45    UNAME_VERSION = #200-Ubuntu SMP Tue Dec 3 11:04:58 UTC 2019
  >> 46    configure: error: cannot guess build type; you must specify one

See build log for details:
  /tmp/dnanto/spack-stage/spack-stage-blast-plus-2.9.0-e4zyhu3mwjtevp5ypre34miszdw2npdm/spack-build-out.txt

$ 
```

**Comment by dnanto** [comment]
I added some debug print statements to the `_do_patch_config_guess` method in the `AutotoolsPackage` class.

```python
        if my_config_guess is not None:
            try:
                check_call([my_config_guess], stdout=PIPE, stderr=PIPE)
                # The package's config.guess already runs OK, so just use it
                print(">" * 10, "debug-04")
                return
            except Exception as e:
                print(">" * 10, "debug-05")
                tty.debug(e)
        else:
            print(">" * 10, "debug-06")
            return
```

It returns at the "debug-06" `return` statement.

**Comment by alalazo** [comment]
Closing as solved by #18347 Feel free to reopen if any issue persist.

**Pull request closed without merging**
