### PR TITLE
cmake: Add a patch to revert a findmpi regression

### LINKED ISSUE #12120: CMake: Could NOT find MPI (missing: MPI_C_FOUND C)
I was trying to build the `legion` spackage, but `MPI` could not be found.

### Steps to reproduce the issue

```console
$  spack install legion
```

### Error Message

```console
-- Could NOT find MPI_C (missing: MPI_C_WORKS)
CMake Error at /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND C)
Call Stack (most recent call first):
  /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindMPI.cmake:1687 (find_package_handle_standard_args)
  cmake/FindGASNet.cmake:160 (find_package)
  cmake/FindGASNet.cmake:262 (_GASNet_create_component_target)
  CMakeLists.txt:218 (find_package)


-- Configuring incomplete, errors occurred!
```

### Information on your system

I test this on multiple plattform and with multiple openmpi versions.

If I dig into the the `CMakeError.log`, I see:
```
Building C object CMakeFiles/cmTC_6d446.dir/test_mpi.c.o
/home/junghans/spack/lib/spack/env/gcc/gcc  -isystem /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/include  -fexceptions -pthread -o CMakeFiles/cmTC_6d446.dir/test_mpi.c.o   -c /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindMPI/test_mpi.c
Linking C executable cmTC_6d446
/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6d446.dir/link.txt --verbose=1
/home/junghans/spack/lib/spack/env/gcc/gcc      -rdynamic CMakeFiles/cmTC_6d446.dir/test_mpi.c.o  -o cmTC_6d446 -Wl,-rpath,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -pthread /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib/libmpi.so
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib: file not recognized: Is a directory
```
So there is this `/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib` argument in the link line.

if you ran:
```console
$ /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/bin/mpicc --showme
/usr/bin/gcc -I/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/include -fexceptions -pthread -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -lmpi
```
it seems the wrapper inject this directory somehow.

### PR DESCRIPTION
**Pull request by chuckatkins**
See https://gitlab.kitware.com/cmake/cmake/issues/19516
Replaces #12121 
Fixes #12120

### CODE REVIEW

**Comment by chuckatkins** [comment]
@junghans Can you please verify this fixes your `legion` issue?
@tldahlgren Can you please verify this fixes your `amrex` issue?

**Comment by ax3l** [comment]
Okay, but not identical to the proposed upstream fix in https://gitlab.kitware.com/cmake/cmake/merge_requests/3605 ?

**Comment by chuckatkins** [comment]
> Okay, but not identical to the proposed upstream fix in https://gitlab.kitware.com/cmake/cmake/merge_requests/3605 ?
No, it's just a revert of the commit that introduced the bug.  This morning it wasn't clear if the "fix" was going to be today or sometime next week so the revert was the safest bet.  Either way it'll be isolated to 3.15.0 and resolved in the 3.15.1 patch release

**Comment by mathstuf** [comment]
Yes, this just restores it to the 3.14.x (and older) behavior for what the original patch was for. 3.15.1 will have the desired behavior for both use cases.

**Pull request merged**
