### PR TITLE
r-pkgmaker, r-rngtools: fix checksums

### PR DESCRIPTION
**Pull request by molecuul**
not sure how these became invalid but they do not match the sums on CRAN.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you contact the developers and investigate why the checksums changed? Just trying to prevent another https://github.com/Homebrew/homebrew-cask/issues/33536.

**Comment by baberlevi** [comment]
I'm emailing the developer. @molecuul  - for now, let's just add new versions instead and leave the old hashes as-is. Both of these packages have a newer version out anyway.

**Comment by molecuul** [comment]
closing this in favor of new PRs #10419, #10418

**Comment by baberlevi** [comment]
Got a reply from the developer last week:
`Yes, these packages were updated, notably I updated rngtools a couple of days ago to ensure the version on CRAN is available for all R versions >= 3.2.`

**Pull request closed without merging**
