### PR TITLE
environment modifications: use cleaner reference environment

### PR DESCRIPTION
**Pull request by matz-e**
Replace the currently used os.environ by a reference environment to
catch modifications done by users.

Background: we've observed that our module for the `intel` package
includes a `unsetenv PS1` when building the module with Jenkins. I could
locally reproduce that by executing `export PS1=foo` on the local shell
before regenerating the intel module. With this fix, the environments
compared are closer together.

### CODE REVIEW

**Comment by alalazo** [comment]
Related to the refactoring done in #10753.  Can you provide a case for a unit test?

**Comment by matz-e** [comment]
I can add a unit test. Maybe it would be best to rebase this on top of #10753.

**Comment by alalazo** [comment]
@matz-e Apologies for the long time it took to get back to this. #10753 has been merged a year ago and if you still want to work on this I think the PR is worth a rebase and a few quick iterations to merge it.

**Comment by matz-e** [comment]
Noted, will probably take at least 1-2 weeks.

**Comment by matz-e** [comment]
Sorry, it's taken me a lot longer to circle back to this. Seems like the current code makes this pretty redundant.

Closing the PR, may file another one to fix Intel's messy environment script — `EnvironmentModifications.from_sourcing_file` there should be called with `clean=True` in the Intel build system, as goodies like this:
```
fix_environment() {
  remove_duplicate_paths "PATH"
  remove_duplicate_paths "LD_LIBRARY_PATH"
}

if [ -e "${PROD_DIR}/tbb/bin/tbbvars.sh" ]; then
    . "${PROD_DIR}/tbb/bin/tbbvars.sh" ${INTEL_TARGET_ARCH} ${INTEL_TARGET_PLATFORM}
    fix_environment
fi
```
need `clean=True` if one's cluster setup somehow duplicates paths…

**Pull request closed without merging**
