### PR TITLE
LLVM code-signing on OSX: link to the offical documentation

### PR DESCRIPTION
**Pull request by healther**
Follow-up to #13047 @kljohann pointed out that my previous improvement was due to an old version being the head of someone's private fork and provided a link to the official documentation. Using that link here rather than the old one.

### CODE REVIEW

**Comment by healther** [comment]
Mh, why did Travis fail?

**Comment by alalazo** [comment]
@healther That's because when you update a package you also need to update usage of deprecated APIs. In this case you need to split `setup_environment` into `setup_build_environment` and `setup_run_environment`.

**Comment by healther** [comment]
Ah I see, it's due to #11115, correct? Do you mind adding some information to the error that the test throws? A "see https://github.com/spack/spack/pull/11115 for further information" (or the relevant position in the docs) would have saved me that extra question round.

**Comment by healther** [comment]
For example like #13435

**Pull request merged**
