### PR TITLE
libhio: specify use of external json

### PR DESCRIPTION
**Pull request by plamborn**
libhio has been building it's own json.  With this change, libhio will rely on the json installed by spack.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Not sure what's up with Travis, closing and reopening to restart the tests...

**Comment by alalazo** [comment]
```
var/spack/repos/builtin/packages/libhio/package.py:59: [W293] blank line contains whitespace
```

**Comment by plamborn** [comment]
I took out the blank line that appeared to be causing a Travis error with my "Update package.py" commit.  I don't understand why the Travis CI is still giving an error.  Can someone tell me what is going on?

**Comment by alalazo** [comment]
There were 2 formatting errors reported by `flake8`, you solved only one in e88c5fe

**Pull request merged**
