### PR TITLE
Gtkorvo updates

### PR DESCRIPTION
**Pull request by kshitij-v-mehta**
Version updates for the following packages in the gtkorvo tool suite:
gtkorvo-atl
gtkorvo-dill
gtkorvo-enet
libffs
libevpath

Related to #8654

### CODE REVIEW

**Comment by adamjstewart** [comment]
We generally prefer to keep old versions, as researchers often need to produce results using old versions of software.

> I’d have left the old form of cmake_args and the old versions, but wasn’t certain how to do the args conditionally on the version requested.

You can do something like:
```python
args = []

if self.spec.satisfies('@4.4:'):  # or whatever version the syntax changed in
    args.append('-DBUILD_SHARED_LIBS=OFF')
else:
    args.append('-DBUILD_SHARED_STATIC=STATIC')

return args
```

**Comment by eisenhauer** [comment]
Does that spec, self.spec.satisfies('@4.4:'), represent a version great or equal condition?  If so, then that seems simple enough to do properly.

**Comment by adamjstewart** [comment]
Correct, see http://spack.readthedocs.io/en/latest/packaging_guide.html#version-ranges for examples.

**Comment by kshitij-v-mehta** [comment]
In that case, I am closing this PR and opening a new one that contains the above technique to keep old versions.

**Comment by kshitij-v-mehta** [comment]
Is there a way to speficy a dependency (using `depends_on`) depending on the version?
For libevpath, versions under 1.5 have a dependency on flex and bison, whereas newer versions do not. How do I express this?

**Comment by adamjstewart** [comment]
```python 
depends_on('flex', type='build', when='@:1.4')
```
I would highly recommend reading the Packaging Guide if you haven't already.

**Comment by kshitij-v-mehta** [comment]
Thanks. Created PR #8663

**Comment by alfredo-gimenez** [comment]
@kshitij-v-mehta @eisenhauer thanks! will try this out, there shouldn't be a problem updating sosflow to the newer version (and glad to have flex/bison removed from deps as they've been problematic for me in spack more than once...)

**Pull request closed without merging**
