### PR TITLE
Use a bot to mark top issues

### PR DESCRIPTION
**Pull request by alalazo**
As a member of the community I want the top issues to be labeled so that I can quickly track which features or bug-fixes are the most requested.

**Rationale**
This can be an effective way for a contributor to select something to work on that can have the most impact on the community. 

**Alternatives**
Github already permits to sort issues by the number of the various reactions. Using a bot can be  nonetheless an improvement as:
- It labels issues, so that we can keep track of historical information e.g. if some issue has been in the top 10 at some point
- We will develop an habit, as a community, to vote for features or bug fixes we care the most

N.B. In case we want to merge the PR, this [bot](https://probot.github.io/apps/topissues/) needs to be activated first by an owner of the repository.

### CODE REVIEW

**Comment by scheibelp** [comment]
Question (from discussing with @tgamblin and @becker33): what is the advantage of this over going to the list of all PRs/issues and using the built-in github sort-by functionality which allows by sorting by the number of 👍 ?

**Comment by adamjstewart** [comment]
I think the advantage is that people are more likely to add their own 👍 if they know it actually has an effect and that someone is looking at it. I didn't know you could sort by 👍, but even now that I do, I probably won't regularly do that. I'm much more used to searching by label.

**Comment by adamjstewart** [comment]
Also, does the sort-by (or the bot) look at 👍 on the first comment, or over all comments?

**Comment by alalazo** [comment]
@adamjstewart The bot looks at :+1: in the description. From its doc page:

> . Top issues are issues with the most "+1" emoji reactions on the issue description. "+1" emoji reactions on issues comments are not considered.

My impression is that sort-by does the same, but I couldn't find any reference in Github's help pages.

**Pull request closed without merging**
