### PR TITLE
Set CC and similar variables for intel compilers

### PR DESCRIPTION
**Pull request by anderbubble**

### CODE REVIEW

**Comment by anderbubble** [comment]
@becker33, Jack and I mentioned this to you on Slack and we're finally getting around to it.

I was a bit confused by your original advice:

>>> Yeah it looks like those were never added to the setup_run_environment method for the intel compiler package. It would need to be added as part of _setup_environment_callback in the IntelPackage class in lib/spack/spack/build_systems/intel.py.

I never did find `_setup_environment_callback` anywhere in Spack, so I just followed an example from the gcc package.

 Let me know what you think.

**Comment by adamjstewart** [comment]
I think there was a typo in @becker33's advice, it should be `_setup_dependent_env_callback`. You should move the logic there so you can avoid code duplication. I'm not sure what the check should be, I guess whether `self.spec.name == 'intel' or self.spec.name == 'intel-parallel-studio`?

Why don't we just source the same startup scripts that we do during `setup_run_environment` in `setup_dependent_build_environment`? This relates to #13926.

**Comment by anderbubble** [comment]
> Can you explain why this change is necessary?

Our experience is that if you load the intel module, you don't get `CC` "and friends" at all. If this is meant to be happening automatically, but isn't for some reason, I'm happy to try to find out why; but since the gcc package sets them precisely like this, it seemed like they were missing from the `intel` package at least, and possibly `intel-parallel-studio` (though over there I could see not setting them like this, since it's undefined whether the compilers or the wrappers are the right executables).

**Comment by adamjstewart** [comment]
> Our experience is that if you load the intel module, you don't get CC "and friends" at all.

The function that controls which variables are added to the module file is `setup_run_environment`, not `setup_dependent_build_environment`. Right now, we only include what is set by sourcing the script provided by Intel. We could of course add `CC` and friends to that if it's not already being set.

> but since the gcc package sets them precisely like this

The GCC package overrides `setup_run_environment`, not `setup_dependent_build_environment`

**Comment by anderbubble** [comment]
> The GCC package overrides setup_run_environment, not setup_dependent_build_environment

As did I, so I don't understand this comment.

**Comment by adamjstewart** [comment]
Sorry, I’m referring to @becker33’s advice. This still needs to be moved into the base class

**Comment by anderbubble** [comment]
@adamjstewart should it go in the base class' `setup_run_environment`, or some other `_*_callback` method that I'm not aware of?

I copied that "caution: duplicate code" style from an existing implementation. Should I take this time to move that to the base class as well?

**Comment by adamjstewart** [comment]
Nope, it should go directly in `setup_run_environment` in `lib/spack/spack/build_systems/intel.py`. The only reason all that hacky logic for `setup_dependent_build_environment` exists is that some subclasses of IntelPackage actually override it. That isn't the case with `setup_run_environment`, at least not yet. You'll probably need to guard it with `self.spec.name == 'intel' or self.spec.name == 'intel-parallel-studio'` since this method is run by all subclasses, not just the compilers.

**Comment by anderbubble** [comment]
@adamjstewart what if, in stead of having guard conditions in a shared `setup_run_environment` I set a shared `_setup_run_environment_compiler_variables` and then call that in `setup_run_environment` from each build script? That feels more correct to me; but if it feels worse to you I'll defer to the maintainer.

**Comment by adamjstewart** [comment]
@mgsternberg was the one who came up with the current design of the `IntelPackage` base class. Maybe he can comment on this.

**Comment by anderbubble** [comment]
@mgsternberg I'd be interested in your thoughts on this. I should be able to submit a new implementation this weekend if I can know whether it'd be supported.

**Comment by mgsternberg** [comment]
@anderbubble 
### Recap ###

The Intel packages serve the dual purpose of being used internal to Spack and external to it for direct use by an end user, so Spack needed the distinction between `setup_dependent_build_environment()` and `setup_run_environment()`, respectively, or their future incarnation per #13926. The `CC` & friends env. vars. are not exposed externally because, I think, the assumption is that (a) that the user who'd  explicitly run `module load intel` would "know" what to do with the compilers, and (b) for Spack to be conservative and not impose more assumptions and practices than strictly needed. Further, for internal use, the vars point to Spack wrappers, IIRC, which wouldn't be appropriate or even usable standalone.

### Approach ###

I agree with @adamjstewart that it's desirable to avoid the code duplication for `setup_run_environment()`. The DUP in `setup_dependent_build_environment()` are there because the base class did not have access to `spack_cc` etc. (IIRC), but the extent of the duplication is a single function call to the base class, rather than variable manipulations and logic. Can you try that approach, as you in fact suggested in  https://github.com/spack/spack/pull/15794#issuecomment-609942879 ?

### Implementation Notes ###

The use of `env.set(lang.upper(), realpath)` looks a bit hack-ish. It's fine for the GCC family where "we know" what's implemented and how, but for the Intel items I think a `dict` like in the `def setup_dependent_build_environment()` above would be more straightforward and longer-term stable, and also provide all 3 of the Fortran-flavored vars: `F77`, `F90` and `FC`.

I'd also _not_ assume that the end tool _must not_ be a symlink, i.e., it could be a plain file or symlink, and that all tools need to be in the same directory. I'd have to look at the historic versions where those could differ, and Intel is prone to move things around. An explicit implementation should be more transparent and adaptable.

M.
Sorry for the delay – was out with a bout of RSI 🤒.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you want to continue work on this. Also note that in the meanwhile Intel packages have been heavily reworked.

**Pull request closed without merging**
