### PR TITLE
correct with-xxx-lib= options

### PR DESCRIPTION
**Pull request by JaroslavHron**
use list of library files for `--with-zlib-lib=` and `--with-suitesparse-lib=` to get their rpath included correctly

(see https://github.com/spack/spack/issues/10585#issuecomment-510429843)

### CODE REVIEW

**Comment by scheibelp** [comment]
Closing and reopening to restart tests

**Comment by adamjstewart** [comment]
@JaroslavHron Can you merge this into `develop` instead of `master`?

**Comment by scheibelp** [comment]
@JaroslavHron When you add a PR here, is it based off of a package-specific branch? A typical workflow that does not seem to bother github is:

```
git checkout develop # the develop branch of Spack in your repo, which ideally matches Spack's develop branch
git checkout -b features/new-package-x develop # create a new separate branch
# edit, commit, etc.
git push origin features/new-package-x # push to your fork, when you visit your fork in github there should be a UI option to make a PR
```

Currently somehow github is getting confused and displaying a bunch of unrelated changes, so following a strategy like the above (opening a new PR) could prevent this.

**Comment by JaroslavHron** [comment]
Thanks - sorry for the mess - i did this trough the web interface....
I will close this one and open a new PR for this.

**Pull request closed without merging**
