### PR TITLE
Improve concretization performance

### LINKED ISSUE #12779: Spack is very slow with a large number of packages
I've built python and and R with many packages for each of them and spack becomes very slow to install packages (or also spack spec -I). When I strace spack while it is running, it looks like it repeatedly gets locks and reads the index.json for each package. It seems like maybe the locking and DB read should just be done once.

Here's a couple of seconds of strace on `spack spec -I r-caret`:
```
08:29:18 stat("/shared/spack/opt/spack", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
08:29:18 mkdir("/shared/spack/opt/spack/.spack-db", 0777) = -1 EEXIST (File exists)
08:29:18 stat("/shared/spack/opt/spack/.spack-db", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
08:29:18 stat("/shared/spack/opt/spack/.spack-db/lock", {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:18 access("/shared/spack/opt/spack/.spack-db/lock", W_OK) = 0
08:29:18 open("/shared/spack/opt/spack/.spack-db/lock", O_RDWR|O_CREAT, 0777) = 3
08:29:18 fcntl(3, F_GETFL)              = 0x8002 (flags O_RDWR|O_LARGEFILE)
08:29:18 fstat(3, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:18 mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f93dc278000
08:29:18 lseek(3, 0, SEEK_CUR)          = 0
08:29:18 fstat(3, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:18 fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
08:29:18 stat("/shared/spack/opt/spack/.spack-db/index.json", {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:18 open("/shared/spack/opt/spack/.spack-db/index.json", O_RDONLY) = 4
08:29:18 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:18 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:18 lseek(4, 0, SEEK_CUR)          = 0
08:29:18 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:18 mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f93dba78000
08:29:18 lseek(4, 0, SEEK_CUR)          = 0
08:29:18 read(4, "{\n \"database\": {\n  \"installs\": {"..., 8388608) = 743955
08:29:18 read(4, "", 8388608)           = 0
08:29:19 close(4)                       = 0
08:29:19 munmap(0x7f93dba78000, 8388608) = 0
08:29:19 fcntl(3, F_SETLKW, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
08:29:19 close(3)                       = 0
08:29:19 munmap(0x7f93dc278000, 8388608) = 0
08:29:19 stat("/shared/spack/opt/spack", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
08:29:19 mkdir("/shared/spack/opt/spack/.spack-db", 0777) = -1 EEXIST (File exists)
08:29:19 stat("/shared/spack/opt/spack/.spack-db", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
08:29:19 stat("/shared/spack/opt/spack/.spack-db/lock", {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:19 access("/shared/spack/opt/spack/.spack-db/lock", W_OK) = 0
08:29:19 open("/shared/spack/opt/spack/.spack-db/lock", O_RDWR|O_CREAT, 0777) = 3
08:29:19 fcntl(3, F_GETFL)              = 0x8002 (flags O_RDWR|O_LARGEFILE)
08:29:19 fstat(3, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:19 mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f93dc278000
08:29:19 lseek(3, 0, SEEK_CUR)          = 0
08:29:19 fstat(3, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
08:29:19 fcntl(3, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
08:29:19 stat("/shared/spack/opt/spack/.spack-db/index.json", {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:19 open("/shared/spack/opt/spack/.spack-db/index.json", O_RDONLY) = 4
08:29:19 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:19 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:19 lseek(4, 0, SEEK_CUR)          = 0
08:29:19 fstat(4, {st_mode=S_IFREG|0644, st_size=743955, ...}) = 0
08:29:19 mmap(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f93dba78000
08:29:19 lseek(4, 0, SEEK_CUR)          = 0
08:29:19 read(4, "{\n \"database\": {\n  \"installs\": {"..., 8388608) = 743955
08:29:19 read(4, "", 8388608)           = 0
08:29:20 close(4)                       = 0
```

With profiling turned on for `spack spec -I r-caret`:
```
         581360413 function calls (514772064 primitive calls) in 313.928 CPU seconds

   Ordered by: internal time
   List reduced from 1439 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
32668189/5878144   67.459    0.000  125.206    0.000 /shared/spack/lib/spack/spack/spec.py:1143(traverse_edges)
2017614/369   27.344    0.000  134.369    0.364 /usr/lib64/python2.6/json/decoder.py:162(JSONObject)
19260894/738   20.656    0.000  134.373    0.182 /usr/lib64/python2.6/json/scanner.py:38(iterscan)
18690042/2017980   18.318    0.000   33.818    0.000 /shared/spack/lib/spack/spack/util/spack_json.py:40(_strify)
 10570044   14.352    0.000   21.527    0.000 /shared/spack/lib/spack/spack/dependency.py:20(canonical_deptype)
67861316/67861315   11.328    0.000   11.615    0.000 {isinstance}
 11881485    8.450    0.000    8.450    0.000 {_json.scanstring}
1838949/1838639    8.174    0.000   24.866    0.000 /usr/lib64/python2.6/json/decoder.py:206(JSONArray)
16638831/16638432    7.953    0.000    8.089    0.000 {sorted}
  5487136    6.824    0.000   11.091    0.000 /usr/lib64/python2.6/_abcoll.py:362(items)
 18549071    5.592    0.000    5.592    0.000 {built-in method scanner}
  5874765    5.221    0.000  131.176    0.000 /shared/spack/lib/spack/spack/spec.py:1128(traverse)
 11901204    5.073    0.000    5.073    0.000 {method 'encode' of 'unicode' objects}
  4839501    5.044    0.000   10.021    0.000 /usr/lib64/python2.6/json/decoder.py:152(JSONString)
 66980134    5.001    0.000    5.003    0.000 {method 'get' of 'dict' objects}
  9059595    4.707    0.000   24.955    0.000 /shared/spack/lib/spack/spack/util/spack_json.py:53(<genexpr>)
 31707642    4.414    0.000    4.414    0.000 /shared/spack/lib/spack/spack/spec.py:1198(validate)
 43138508    4.118    0.000    4.118    0.000 {built-in method end}
 10087620    3.348    0.000    3.348    0.000 {built-in method match}
 20272794    3.314    0.000    3.314    0.000 /shared/spack/lib/spack/spack/spec.py:1245(<genexpr>)
```

### PR DESCRIPTION
**Pull request by tgamblin**
Fixes #12779.

This addresses two problems:

1. Checks for deprecated specs (introduced in #12933) were repeatedly taking out read locks on the database, which can be very slow.
2. `get_platform()` is pretty expensive and can be called many times in a spack invocation.

- [x] put a read transaction around the deprecation check to avoid repeated locking/reading
- [x] memoize `get_platform()`

@ajw1980 @matz-e: does this improve things for you?

### CODE REVIEW

**Comment by matz-e** [comment]
@tgamblin thank you, very instructive! I see a > 3x speedup.

(I also built on top of that to speed-up our own custom commands)

**Comment by tgamblin** [comment]
@matz-e: can you run `pyinstrument —show-all $(which spack) <slow command>` and paste the output?  There may still be more we could improve if you only got 3x.

**Comment by adamjstewart** [comment]
### Before

```console
$ time spack spec r-condop
...
real	1m11.689s
user	1m1.083s
sys	0m4.075s
```

### After
```console
$ time spack spec r-condop
...
real	0m12.434s
user	0m10.675s
sys	0m0.547s
```

Great job!

**Comment by tgamblin** [comment]
@adamjstewart @ajw1980: try now.

**Comment by tgamblin** [comment]
@ajw1980: let's move the conversation from #12779 here.

**Comment by adamjstewart** [comment]
@tgamblin now things are slightly slower than the previous commit (ran it twice just to make sure):
```console
$ time spack spec r-condop
...
real	0m17.480s
user	0m14.182s
sys	0m0.921s
```

**Comment by ajw1980** [comment]
Yes, now I think we're looking good.
pyinstrument output:
[spack-pyinstrument2.txt](https://github.com/spack/spack/files/3975528/spack-pyinstrument2.txt)

Profile:
```
         32521324 function calls (28879768 primitive calls) in 14.944 seconds

   Ordered by: cumulative time
   List reduced from 1620 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   14.944   14.944 /shared/spack/lib/spack/spack/main.py:450(_invoke_command)
        1    0.000    0.000   14.944   14.944 /shared/spack/lib/spack/spack/cmd/spec.py:48(spec)
        1    0.004    0.004   11.112   11.112 /shared/spack/lib/spack/spack/spec.py:2119(concretize)
        8    0.000    0.000    5.015    0.627 /shared/spack/lib/spack/spack/spec.py:2570(normalize)
   2834/8    0.018    0.000    4.567    0.571 /shared/spack/lib/spack/spack/spec.py:2527(_normalize_helper)
 2826/118    0.112    0.000    4.525    0.038 /shared/spack/lib/spack/spack/spec.py:2427(_merge_dependency)
        2    0.000    0.000    3.831    1.915 /shared/spack/lib/spack/spack/spec.py:3807(tree)
   1434/4    0.007    0.000    3.301    0.825 /shared/spack/lib/spack/spack/spec.py:1956(_concretize_helper)
        2    0.001    0.001    2.840    1.420 /shared/spack/lib/spack/spack/spec.py:3814(_tree)
        4    0.002    0.000    2.720    0.680 /shared/spack/lib/spack/spack/spec.py:2017(_expand_virtual_packages)
      147    0.001    0.000    2.694    0.018 /shared/spack/lib/spack/spack/spec.py:3787(install_status)
      146    0.000    0.000    2.693    0.018 /shared/spack/lib/spack/spack/database.py:84(converter)
      146    0.000    0.000    2.693    0.018 /shared/spack/lib/spack/spack/database.py:948(get_record)
      146    0.001    0.000    2.692    0.018 /shared/spack/lib/spack/spack/database.py:937(_get_matching_spec_key)
      146    0.001    0.000    2.688    0.018 /shared/spack/lib/spack/spack/spec.py:3783(__str__)
      146    0.000    0.000    2.645    0.018 /shared/spack/lib/spack/spack/spec.py:3780(dep_string)
   113981    0.129    0.000    2.604    0.000 /shared/spack/lib/spack/spack/spec.py:1197(traverse)
628232/118177    1.163    0.000    2.534    0.000 /shared/spack/lib/spack/spack/spec.py:1212(traverse_edges)
   310686    0.126    0.000    2.200    0.000 /shared/spack/lib/spack/spack/spec.py:1167(virtual)
   310686    0.381    0.000    2.074    0.000 /shared/spack/lib/spack/spack/spec.py:1178(is_virtual)
```

**Comment by tgamblin** [comment]
@adamjstewart: does the previous commit still run in 12s for you?

**Comment by ajw1980** [comment]
"spack find" is still a little slow for the python3 environment I have. It takes around 34 seconds. Here is the pyinstrument for that.
[spack-find-pyinstrument.txt](https://github.com/spack/spack/files/3975583/spack-find-pyinstrument.txt)

Running outside of the environment is fast -- about 1.5 seconds real time.

**Comment by adamjstewart** [comment]
> @adamjstewart: does the previous commit still run in 12s for you?

Previous commit is consistently 12 seconds, current commit is 13-20 seconds.

**Comment by adamjstewart** [comment]
I think there's still a lot of room for improvement within Spack Environments. Concretization seems pretty fast now. After concretization, I see thousands of comments like:
```
==> [2019-12-17-18:39:33.057440] Installing /Users/Adam/spack/var/spack/repos/builtin/packages/bash/package.py to /Users/Adam/.spack/darwin/.spack-env/repos/builtin/packages/bash
```
These debug messages show that we're installing the same files dozens of times. After this finishes, I see messages like:
```
==> [2019-12-17-18:50:04.540219] READ LOCK: /Users/Adam/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-17-18:50:04.541389] READ LOCK: /Users/Adam/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-17-18:50:04.873852] READ LOCK: /Users/Adam/spack/opt/spack/.spack-db/lock[0:0] [Released]
```
thousands of times. This step lasts around 15 minutes for a partially installed environment. If you don't run `spack install` with `--debug`, this means you see Spack doing nothing for 15 minutes, which is not good. It also means SSH connections usually timeout due to inactivity.

**Comment by tgamblin** [comment]
@adamjstewart: see if the latest commits have the same issue.  Turns out the transaction really belongs in `spack spec`, and only when `-I` is used.  `Spec.tree()` doesn't need to know anything about the DB like it did in my previous version.

**Comment by tgamblin** [comment]
@ajw1980: I pushed another commit that should speed up `spack find`.  See if you see an improvement.

**Comment by adamjstewart** [comment]
@tgamblin latest commit has a bug:
```
$ spack -d spec zlib
==> [2019-12-18-16:42:29.249939] Reading config file /Users/Adam/spack/etc/spack/defaults/modules.yaml
==> [2019-12-18-16:42:29.264306] Reading config file /Users/Adam/spack/etc/spack/defaults/darwin/modules.yaml
==> [2019-12-18-16:42:29.272395] Reading config file /Users/Adam/.spack/darwin/modules.yaml
==> [2019-12-18-16:42:29.274251] Reading config file /Users/Adam/spack/etc/spack/defaults/config.yaml
==> [2019-12-18-16:42:29.299837] Imported spec from built-in commands
==> [2019-12-18-16:42:29.300868] Imported spec from built-in commands
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/spec.py", line 92, in spec
    with tree_context:
AttributeError: __enter__
```

**Comment by tgamblin** [comment]
@adamjstewart: oops try now

**Comment by adamjstewart** [comment]
On the latest commit, `spack spec` in my home directory is the fastest time yet:
```console
$ time spack spec r-condop
...
real	0m11.816s
user	0m10.789s
sys	0m0.512s
```
However, if I run `spack install` on an **already installed environment**, it's still prohibitively slow:
```console
$ time spack install
...
real	29m57.196s
user	27m50.154s
sys	1m20.027s
```
The environment in question is pretty big:
```yaml
spack:
  specs:
  - bash
  - graphviz
  - watch
  - wget
  - automake
  - autoconf
  - libtool
  - m4
  - cmake
  - ninja
  - patchelf
  - mercurial
  - subversion
  - gnupg
  - python
  - py-codecov
  - py-flake8
  - py-matplotlib
  - py-numpy
  - py-pandas
  - py-pytest
  - py-pytest-cov
  - py-pytest-mock
  - py-pytest-runner
  - py-setuptools
  - py-scikit-learn
  - py-scipy
  - py-sphinx
  - py-sphinx-rtd-theme
  - py-sphinxcontrib-programoutput
  - py-tables
  - py-torch
  - py-torchvision
  - py-twine
  - gdal

  concretization: together
```
If you run `spack -d install`, you'll see that we are still acquiring and releasing locks on the database tens of thousands of times. Do you want to try to resolve this in this PR, or do you want me to open a separate issue?

**Comment by tgamblin** [comment]
@adamjstewart: go ahead and open another issue for that one as I can't reproduce it right now.  I do want to stamp that out, though.

**Comment by matz-e** [comment]
> @matz-e: can you run `pyinstrument —show-all $(which spack) <slow command>` and paste the output? There may still be more we could improve if you only got 3x.

I able to revisit this only just now. After locking the database a bit more, I observe a 10x speed-up, seems in-line with the other results. I think that's fine. I've attached some results [pyinstrument_filter.txt](https://github.com/spack/spack/files /3982399/pyinstrument_filter.txt) for our [custom command](https://github.com/BlueBrain/spack/blob/merge/2019/10/lib/spack/spack/cmd/filter.py) (based on Scitas)

Thank you for the speed-up!

**Pull request merged**
