### PR TITLE
CONFIG: openfoam package renaming

### LINKED ISSUE #11875: openfoam package renaming
As I discussed off-line with @tgamblin - the original packaging with `openfoam` as a virtual and with `openfoam-com` being a provider, as well as the `openfoam-org` and `openfoam-extend` forks, adds an obfuscation layer without any benefit. Since the forks are not coordinated with the [official upstream](https://www.openfoam.com/history/), there is no way to benefit from an interface layer.  The proposed change would be to rename the `openfoam-com` package to simply `openfoam` and drop the superfluous virtual layer.  This change does trigger the regression #11870 at the moment.

As a temporary workaround to remove _old_ packages, Todd suggested the following which works quite adequately:
1. Find the installed locations
    ```
    spack find -p openfoam-com
    ```
2. Remove the particular package/version
    ```
    rm -rf  the-installed-package-version
    ```
3. Fixup the internal indexing
    ```
    spack reindex 
    ```

You may also need to remove the correspond module file(s):
1. List the possible modules to find the package that  you removed in the first step
    ```
   module avail 2>&1 | grep openfoam-com
    ```
2. Locate the spack module path
    ```
   echo $MODULEPATH
    ```
3. Remove the module for the particular package/version 
    ```
    rm -rf  module-path-installed-package-version
    ```

### PR DESCRIPTION
**Pull request by olesenm**
Closes #11875.

- as detailed in the issue - the original packaging with openfoam as a
  virtual and with openfoam-com being a provider, as well as the
  openfoam-org and openfoam-extend forks, adds an obfuscation layer
  without any benefit.

  Removing old 'openfoam-com' packages may be temporarily impeded
  by #11870, but the issue #11875 also documents a workaround.

### CODE REVIEW

**Comment by olesenm** [comment]
@adamjstewart - willing to pick this up?

**Comment by adamjstewart** [comment]
I'll let someone else take this one.

**Comment by olesenm** [comment]
@alalazo , @scheibelp, @tgamblin ?

**Comment by tgamblin** [comment]
@olesenm: one more thing -- can you please remove the `openfoam` line from `etc/spack/defaults/packages.yaml` now that the virtual is gone?

**Comment by olesenm** [comment]
> @olesenm: one more thing -- can you please remove the `openfoam` line from `etc/spack/defaults/packages.yaml` now that the virtual is gone?

Done

**Comment by olesenm** [comment]
Failing, but doesn't look it is related to this pull request

**Comment by olesenm** [comment]
Thanks!

**Pull request merged**
