### PR TITLE
Add note to Environments docs, how to install packages from yaml/lock files

### PR DESCRIPTION
**Pull request by odoublewen**
I offer this small addition to the Environment docs.

Prompted by my confusion described in #14554

### CODE REVIEW

**Comment by odoublewen** [comment]
Yes, the docs are good, and arguably I should have known that after `spack env create myenv spack.yaml` I would need to activate and install.  (In fact, I did try that, but was just confused by the unrelated error.)

However... I suggest this small additional note in the docs, because:
1. One might reasonably think that the 4 step dance you outlined is somehow rolled into one when the spec is provided in step 1.  This is [how conda works](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file).  I am definitely not suggesting in anyway that conda is worth emulating, but just that users might assume this behavior in this scenario.
2. The phrasing in the docs perhaps makes it sound like Something More is happening:  *To create an Environment from a spack.yaml manifest...*.   Would it not be more precise to say:  *To create an Environment and copy the initialization file into it...* because that's really all that is happening, right?

> I'm on the fence about whether we want to add shortcuts to this procedure.

Just to be clear, I'm not suggesting any kind of shortcut, just adding an N.B. to the docs to remind the user that there is no shortcut.

Totally respect your editorial decision!  😀

**Comment by adamjstewart** [comment]
I'll let others chime in.

**Comment by tgamblin** [comment]
RE: @odoublewen 
> This is how conda works

Conda [doesn't actually do lockfiles](https://github.com/conda/conda/issues/7248) so I'm not sure it's a perfect analog.  But people *are* used to it.

RE: @adamjstewart 
> which are the 4 steps required

Technically you can do this in 3 steps (install implies concretize) or, if the environment is not named (and is in some directory you can cd to) you can just install (activation is implicit).  The intent was always to make the process of reusing someone else's configuration easy.

My thought on this is that what we *really* want is an option, `-i`/`--install` on `spack env create`.  what about:

```console
$ spack env create --install /path/to/spack.lock
```

That would give you a one-step command to get a fully installed version of someone else's env.  Then you can activate it if you want.

It would make the docs clearer, too.  Instead of @odoublewen's note, you could just say in the same place that creating an environment from a manifest `spack.yaml` or `spack.lock` file does *not* automatically install it, and if you want that, you can supply the `--install` argument.  Then just put "see [installing specs] below".  Thoughts?  I think this argument would be pretty simple to add.

**Comment by cjw296** [comment]
If it's helpful, I put together a separate package for lock files for conda envs:
https://picky-conda.readthedocs.io/en/latest/

**Pull request closed without merging**
