### PR TITLE
Ipython > 6 is python 3 only. Update pacakges and dependencies.

### PR DESCRIPTION
**Pull request by s-sajid-ali**
```
	modified:   var/spack/repos/builtin/packages/py-ipython-genutils/package.py
	modified:   var/spack/repos/builtin/packages/py-ipython/package.py
	new file:   var/spack/repos/builtin/packages/py-testpath/package.py
	modified:   var/spack/repos/builtin/packages/py-traitlets/package.py
```
I don't understand why ipython doesn't work when py-setuptools is specified as a dependency. Leaving it as is until someone understands how to fix it. 

One package requires master and has to be installed with -n.

### CODE REVIEW

**Comment by s-sajid-ali** [comment]
Also, does spack have a plan for dealing with the ```flit``` buildsystem for python packages ?
refer to [1](https://github.com/takluyver/backcall/issues/4)

**Comment by adamjstewart** [comment]
Oh, very interesting. For some reason they use the `setup` function from `distutils` instead of from `setuptools`, which explains why those install flags aren't working. You could override the default `install` phase to not add those flags even though setuptools is a dependency.

**Comment by s-sajid-ali** [comment]
So it looks like there's a choice for ```ipython```. The ```setup.py``` has this comment : 
```
# For some commands, use setuptools.  Note that we do NOT list install here!
# If you want a setuptools-enhanced install, just run 'setupegg.py install'
```
Should this be left here or should a variant for ```setuptools``` also be included ?

**Comment by citibeth** [comment]
This cannot be merged because it breaks Python2.  See #7926 for how to create packages that work for Python2 and Python3.  HOWEVER... the core problem is that the concretizer cannot properly handle things like:
```
depends_on('py-backport', when='^python@:2')
```
@scheibelp we have had discussion about that, and the plan is to fix the concretizer.  In the meantime, #7926 provides a "hack" of a `+python3` variant you have to set manually, and then the concretizer is able to use that in `depends_on()` statements.  So the above turns into:
```
depend_on('py-backport', when='~python3')
```
It has been decided that this stuff will not be merged into `develop`; but instead (for now), Python3 users will merge #7926.  See #8018.  If you wish this decision to be revisited, you need to petition core Spack maintainers such as @scheibelp.  In any case... the good thing about #7926 is it doesn't break Python2; so in theory it COULD be merged.

Moving forward... I see this PR as basically as new versions of a bunch of things.  Please do the following:

1. If the new package or version requires Python3, submit a new PR based on the branch `efischer/Python3Fixes` and notify me (@citibeth) when opening the PR.  Please do one package per PR.  I will merge it into that branch, where it becomes part of #7926.

2. If the new package can also work with Python2, please separate it into its own PR and re-submit to the general `develop` branch.

**Comment by citibeth** [comment]
> All that needs to be done is to add an if statement to force it to pick versions lower than 6.0.0 if the python version is 2.7.x.

@s-sajid-ali That is done with `depends_on('xyz', when='^python@...')` --- which is unfortunately what doesn't work with the concretizer at this point.  Please do submit a PR on top of the `efischer/Python3Fixes` branch.

**Comment by s-sajid-ali** [comment]
It looks like all the commits to develop are also included. I'll see if i can submit a PR for only this set of commits.

**Comment by citibeth** [comment]
I'll merge develop into `efischer/Python3Fixes`.  If we both merge
`develop` into the respective branches, then things should work well.

**Comment by s-sajid-ali** [comment]
@adamjstewart  : would it be possible to add the py-backcall package to develop so that it's easier for people who do use it ?

**Comment by adamjstewart** [comment]
You can add any package you want to develop, just submit a PR.

**Pull request closed without merging**
