### PR TITLE
cp2k: add dependency on smm and libxc & new version 5.1

### PR DESCRIPTION
**Pull request by baip**
I don't know how best to do these as separate PRs as they build on one another. I try to keep separate tasks into logically complete commits. I'd appreciate some feedback especially on "cp2k: add smm variant to select from libxsmm or libsmm". Thanks!

### CODE REVIEW

**Comment by tgamblin** [comment]
@baip: are `libsmm` and `libxsmm` api-compatible?

**Comment by baip** [comment]
They need different pre-processor flags.

**Comment by tgamblin** [comment]
Just curious if they should be variants or they should be a new virtual dependency type.

**Comment by baip** [comment]
Ah, I don't think so. `libsmm` is only for small matrix multiplications while libxsmm has small convolutions too.

**Pull request merged**
