### PR TITLE
FFTW: expose optimization handles via variants (SIMD + FMA)

### PR DESCRIPTION
**Pull request by alalazo**
refers #6999 @boegel

### CODE REVIEW

**Comment by lee218llnl** [comment]
Did we ever decide on what a reasonable default level of vectorization should be set at? I see this sets FFTW's at AVX2, however, I know that we still have systems here that do not support that.

**Comment by alalazo** [comment]
@lee218llnl No problem changing defaults, if they don't meet the expectations of other sites. What do you suggest? `simd=sse2,avx` ?

**Comment by lee218llnl** [comment]
I think the default level is an open question. I for one am OK with your "sse2,avx" suggestion.

**Comment by alalazo** [comment]
@lee218llnl @tgamblin As I submitted this PR, and see how it may be controversial, I'll wait for somebody else to merge it.

**Comment by tgamblin** [comment]
@lee218llnl @alalazo for this package, I think the default levels are fine.  FFTW's `--enable-avx` options are smart enough to detect the architecture and only use the option *if* the architecture supports it.  So it's safe in that sense, and it's definitely useful; we get a speed boost out of this.

The one problem I see with this is that it can put `simd=avx` in the spec for an architecture that doesn't actually have AVX.  I think that is ok, as it only really affects this package.

I don't necessarily think this is the right way to do this for all packages.  I think that really needs more support from Spack.  @becker33 has a feature in the queue to do fine-grained architecture detection.  That would allow packagers to query what's available, which i think is the right thing to do.  What I would really like is if, eventually, you could have a user preference for what target architecture to build and tune for (e.g. you could target "must run on nehalem"), and have Spack be either aggressive or generic depending on the preference.  Obviously the choices made should then show up in the spec.  I think there is a little ways to go until we're at that point.

There is also one tricky thing we'd need to address.  The defaults for variants are set in directives, which are evaluated at class definition time, before some choices about architectures are made.  We would need to think about how best to factor that to enable the right choice to be made in cross-compiled builds.

**Comment by tgamblin** [comment]
@alalazo: is the avx2 option in FFTW not also smart enough to not actually use `avx2` if it's not supported?  Why not keep that one for now?

**Comment by alalazo** [comment]
@tgamblin Looking right now at [docs](http://www.fftw.org/fftw3_doc/Installation-on-Unix.html). It seems they support some sort of auto-detection at run-time:
>Enable various SIMD instruction sets. You need compiler that supports the given SIMD extensions, but FFTW will try to detect at runtime whether the CPU supports these extensions. That is, you can compile with--enable-avx and the code will still run on a CPU without AVX support.

I'll revert the last commit, and bring `avx2` back into the defaults.

**Comment by lee218llnl** [comment]
One thing we still need to be careful about is the fact that we may build on a machine that has a different architecture than we run on. I don't know how common this is at other sites, but it is quite common here at LLNL since we have global/networked file systems that serve multiple machines. I've run into trouble here before by building things on our AVX2-supporting system and then having it fail on some of our older systems with illegal instructions. My policy has thus been to build on the oldest architecture that we have available. It would be nice, though, if I could build on any architecture and target a specific (or potentially even a list) of architectures that I want to run on.

**Comment by alalazo** [comment]
> I've run into trouble here before by building things on our AVX2-supporting system and then having it fail on some of our older systems with illegal instructions. My policy has thus been to build on the oldest architecture that we have available. It would be nice, though, if I could build on any architecture and target a specific (or potentially even a list) of architectures that I want to run on.

I sympathize with that as we had the same problem at my site.  In this case though it seems sufficient to have the instruction set of the oldest architecture enabled to be able to run on that architecture (I say *it seems* because I didn't actually try a run, just read documentation).

p.s. with a small change to `develop` (https://github.com/epfl-scitas/spack/pull/127) you can manage the target name manually. That's what we currently do to build software for different architectures on the same parallel filesystem (each node defines the environment variable `SPACK_TARGET_TYPE` appropriately). Just saying in case it could be useful to you as a workaround.

**Pull request merged**
