### PR TITLE
Added dependencies

### PR DESCRIPTION
**Pull request by JSquar**
Fixes two issues:
1. OpenGL2 dependency needs libxt, since CMake searches for X11_Xt_LIB
2. Same issue like #7145, same solution like #7404

### CODE REVIEW

**Comment by adamjstewart** [comment]
@chuckatkins @danlipsa

**Comment by chuckatkins** [comment]
The `libxt` dependency isn't tied to the "opengl2" feature but instead the use of GLX.  So given that, I believe the condition should be `when='~osmesa platform=linux'`.  @adamjstewart can you add the platform in the when spec like that?

**Comment by adamjstewart** [comment]
> @adamjstewart can you add the platform in the when spec like that?

Yep!

**Comment by JSquar** [comment]
Since there is already an os check for linux for `glx`, I added the libxt dependency there.

**Pull request merged**
