### PR TITLE
cmake: prefer 3.14

### PR DESCRIPTION
**Pull request by junghans**
Workaround for #12120

### CODE REVIEW

**Comment by tldahlgren** [comment]
FWIW.  This fix allowed me to install ``amrex``, which is required for my testing of changes to ``xsdk``.

**Comment by tgamblin** [comment]
Is 3.15 broken?  Do we need some option like “discourage” for particular versions?

Otherwise I think amrex needs to state *its* requirements explicitly, rather than changing cmake prefs for everyone.

**Comment by tldahlgren** [comment]
> Is 3.15 broken? Do we need some option like “discourage” for particular versions?
> 
> Otherwise I think amrex needs to state _its_ requirements explicitly, rather than changing cmake prefs for everyone.

According to #12120, it may be an issue with ``openmpi``.

**Comment by chuckatkins** [comment]
I believe we've identified the source of the regression and should have a patch in the next day or two.  To that end I'd prefer not to merge this change and instead apply the forthcoming patch to 3.15.0 in the spack package.

**Comment by tgamblin** [comment]
@chuckatkins: as long as you can get this in quickly I think this sounds good!

**Comment by chuckatkins** [comment]
I should have a pr ready tomorrow with the patch that will go into upstream cmake

**Comment by junghans** [comment]
Patch is small we could just apply it in Spack as well.

**Comment by tgamblin** [comment]
I think that’s what Chuck’s suggesting

**Comment by junghans** [comment]
Duplicate of #12129

**Pull request closed without merging**
