### PR TITLE
change recurse into recursive in a few places

### PR DESCRIPTION
**Pull request by davydden**
i introduced those in https://github.com/spack/spack/pull/6552 and I don't understand how it worked as `find_libraries` seem to have `recursive` for at least 7 months https://github.com/spack/spack/blame/develop/lib/spack/llnl/util/filesystem.py#L1069

### CODE REVIEW

**Comment by davydden** [comment]
@tgamblin I would cherry-pick this PR to the release branch once/if it is merged.

**Comment by davydden** [comment]
@tgamblin @alalazo ping.

**Comment by alalazo** [comment]
@davydden I think the cause is not you adding the wrong thing, but #4470 that has been merged 15 days ago (with commits that date back quite a lot in time).

**Comment by alalazo** [comment]
I'll merge as soon as Travis go green

**Comment by davydden** [comment]
>  but #4470 that has been merged 15 days ago (with commits that date back quite a lot in time).

ah, you are right, i see those changes there from `recurse` to `recursive`

**Pull request merged**
