### PR TITLE
Implementation to jail Spack inside a user chroot using Linux namespaces

### PR DESCRIPTION
**Pull request by TheTimmy**
This feature support to jail Spack inside a chroot (see #5193 approach 3 for details),
but without the requirements of the pull request #5489.
This allows to find potentially missing depends_on calls.

It introduces the commands:

./spack isolate --build-environment path/to/jail/dir --tarball path/to/tarball
To create a jail for Spack and mount bind /dev, /sys and /proc to be available inside the jail.

./spack isolate --remove-environment
To unmount the mounted /dev, /sys and /proc directories.

./spack isolate --cli
To start a shell inside the jail.

To create a bootstrap environment it is possible to use an already generated tarball from OpenStack or by using mkosi. A restriction is, that the root directory of the tarball must be a directory which contains the distribution.

To generate the mount bind and chroot calls in uses namespaces.
Unfortunately it does not support the separation of the PID namespace, due to the fact, that Python cannot read C defines and structs.

### CODE REVIEW

**Comment by davydden** [comment]
After the interface is agreed upon, please document the usage somewhere in `/lib/spack/docs` http://spack.readthedocs.io/en/latest/

**Comment by alalazo** [comment]
> This allows to find potentially missing depends_on calls.

@tgamblin @ax3l The use case above is better served in my opinion using Spack from within a container. I'll leave this open to see if somebody disagrees, will revisit in some time.

**Comment by ax3l** [comment]
I think this is an interesting approach.
Probably cuts even more cases than the conda-build approach, which uses elftools to grep out-of-sysroot dependencies in generated binaries.

**Comment by michaelkuhn** [comment]
I guess now that we have `spack containerize` we do not really need this anymore. If anyone else is interested, feel free to pick it up, though.

**Comment by alalazo** [comment]
Closing the PR following the comment of @michaelkuhn If anybody wants to continue the work and discussion, feel free to reopen.

**Pull request closed without merging**
