### PR TITLE
Automatically add autotools deps to master/develop

### PR DESCRIPTION
**Pull request by adamjstewart**
See conversation in #11684.

@citibeth

### CODE REVIEW

**Comment by adamjstewart** [comment]
There are quite a few packages that could have their dependencies removed now:
```console
$ grep depends_on.*automake */package.py
abyss/package.py:    depends_on('automake', type='build')
adios/package.py:    depends_on('automake', type='build')
adlbx/package.py:    depends_on('automake', type='build', when='@master')
adol-c/package.py:    depends_on('automake', type='build', when='@develop')
aml/package.py:    depends_on('automake', type='build')
andi/package.py:    depends_on('automake', type='build')
argobots/package.py:    depends_on("automake", type=("build"), when="@develop")
arpack-ng/package.py:    depends_on('automake', when='@3.3.0', type='build')
axel/package.py:    depends_on('automake', type='build')
bash-completion/package.py:    depends_on('automake', type='build')
breseq/package.py:    depends_on('automake', type='build')
charmpp/package.py:    depends_on("automake", when="@develop")
cln/package.py:    depends_on('automake', type='build')
codes/package.py:    depends_on('automake', type='build')
czmq/package.py:    depends_on('automake', type='build')
dash/package.py:    depends_on('automake', type='build')
dataspaces/package.py:    depends_on('automake', type='build')
ds/package.py:    depends_on('automake', type='build')
editline/package.py:    depends_on('automake', type='build')
eqr/package.py:    depends_on('automake', type='build')
erfa/package.py:    depends_on('automake', type='build')
exmcutils/package.py:    depends_on('automake', when='@master')
expect/package.py:    depends_on('automake', type='build')
fastme/package.py:    depends_on('automake', type='build')
fftw/package.py:    depends_on('automake', type='build', when='+pfft_patches')
findutils/package.py:    depends_on('automake', type='build', when='@4.6.0')
flex/package.py:    depends_on('automake', type='build', when='@:2.6.0,2.6.4')
flux-core/package.py:    depends_on("automake", type='build', when='@master')
flux-sched/package.py:    depends_on("automake", type='build', when='@master')
folly/package.py:    depends_on('automake', type='build')
ftgl/package.py:    depends_on('automake', type='build')
fyba/package.py:    depends_on('automake', type='build')
geopm/package.py:    depends_on('automake', type='build')
git/package.py:    depends_on('automake', type='build')
gmp/package.py:    depends_on('automake', type='build')
gource/package.py:    depends_on('automake',   type='build')
graphviz/package.py:    depends_on('automake', type='build')
hdf5/package.py:    depends_on('automake', type='build', when='@develop')
hpx5/package.py:    depends_on("automake", type='build')
hstr/package.py:    depends_on('automake', type='build')
htslib/package.py:    depends_on('automake', when="@1.2")
hunspell/package.py:    depends_on('automake', type='build')
i3/package.py:    depends_on('automake',  type='build')
idba/package.py:    depends_on('automake', type='build')
ior/package.py:    depends_on('automake', type='build')
json-cwx/package.py:    depends_on('automake', type='build')
launchmon/package.py:    depends_on('automake', type='build')
libbeagle/package.py:    depends_on('automake', type='build')
libbson/package.py:    depends_on('automake', type='build', when='@1.6.1')
libconfig/package.py:    depends_on('automake', type=('build'))
libev/package.py:    depends_on('automake', type='build', when='@develop')
libfabric/package.py:    depends_on('automake', when='@develop', type='build')
libgd/package.py:    depends_on('automake', type='build')
libharu/package.py:    depends_on('automake', type=('build'))
libint/package.py:    depends_on('automake', type='build')
libjpeg-turbo/package.py:    depends_on('automake', type='build', when="@1.3.1:1.5.3")
libmongoc/package.py:    depends_on('automake', type='build', when='@1.8.1')
libnova/package.py:    depends_on('automake')
libnsl/package.py:    depends_on('automake', type='build')
libplist/package.py:    depends_on('automake',   type='build', when='@master')
libquo/package.py:    depends_on('automake', when='@develop', type='build')
libseccomp/package.py:    depends_on('automake', type='build')
libtool/package.py:    depends_on('automake', type='build', when='@develop')
libunwind/package.py:    depends_on('automake', type='build', when='@2018:')
libusb/package.py:    depends_on('automake', type='build', when='@master')
libusbmuxd/package.py:    depends_on('automake',   type='build', when='@master')
libuv/package.py:    depends_on('automake', type='build')
libyaml/package.py:    depends_on('automake')
man-db/package.py:    depends_on('automake')
margo/package.py:    depends_on('automake',  type='build')
masa/package.py:    depends_on('automake', type='build')
memkind/package.py:    depends_on('automake', type='build')
mesa/package.py:    depends_on('automake', type='build')
metaphysicl/package.py:    depends_on('automake', type='build')
migrate/package.py:    depends_on('automake')
moab/package.py:    depends_on('automake', type='build', when='@master,5.0.1:')
mount-point-attributes/package.py:    depends_on('automake', type='build')
mrbayes/package.py:    depends_on('automake', type='build')
nauty/package.py:    depends_on('automake',  type='build', when='@2.6r7')
netcdf-cxx4/package.py:    depends_on('automake', type='build')
netcdf/package.py:    depends_on('automake', type='build', when='@4.7.0')
neuron/package.py:    depends_on('automake',   type='build')
neuron/package.py:    depends_on('automake',   type='build')
nix/package.py:    depends_on('automake', type='build')
numactl/package.py:    depends_on('automake', type='build')
openmpi/package.py:    depends_on('automake', type='build', when='@develop')
osmctools/package.py:    depends_on('automake', type='build')
p4est/package.py:    depends_on('automake', type='build')
pandaseq/package.py:    depends_on('automake',    type='build')
plumed/package.py:    depends_on('automake', type='build')
portcullis/package.py:    depends_on('automake@1.11:', type='build')
prng/package.py:    depends_on('automake', type='build')
pruners-ninja/package.py:    depends_on("automake", type='build')
rempi/package.py:    depends_on("automake", type='build')
rose/package.py:    depends_on("automake@1.14:", type="build")
saga-gis/package.py:    depends_on('automake', type='build')
sga/package.py:    depends_on('automake', type='build')
singularity-legacy/package.py:    depends_on('automake', type='build', when='@2.6-release')
squashfs/package.py:    depends_on('automake', type='build')
sst-core/package.py:    depends_on('automake@1.11.1:', type='build', when='@develop')
sst-dumpi/package.py:    depends_on('automake@1.11.1:', type='build')
sst-macro/package.py:    depends_on('automake@1.11.1:', type='build', when='@develop')
stat/package.py:    depends_on('automake', type='build')
stc/package.py:    depends_on('automake', type='build')
swiftsim/package.py:    depends_on('automake', type='build')
thrift/package.py:    depends_on('automake', type='build')
tophat/package.py:    depends_on('automake',                        type='build')
tophat/package.py:    depends_on('automake@1.15.1', when='@:2.1.1', type='build')
trinity/package.py:    depends_on("automake", type="build")
turbine/package.py:    depends_on('automake', type='build', when='@master')
unifycr/package.py:    depends_on('automake',  type='build')
valgrind/package.py:    depends_on("automake", type='build', when='@develop')
verrou/package.py:    depends_on('automake', type='build')
vsearch/package.py:    depends_on('automake', type='build')
workrave/package.py:    depends_on('automake', type='build')
xcb-util-xrm/package.py:    depends_on('automake', type='build')
xclip/package.py:    depends_on('automake', type='build')
xmlf90/package.py:    depends_on('automake@1.14:', type='build')
yara/package.py:    depends_on('automake', type='build')
yasm/package.py:    depends_on('automake', when='@develop')
zeromq/package.py:    depends_on('automake', type='build', when='@develop')
```

**Comment by adamjstewart** [comment]
It looks like this won't work, as `automake` and friends are already `AutotoolsPackage`s, and they can't depend on themselves.

**Comment by citibeth** [comment]
What if we create a class hierarchy:
1. Rename `AutotoolsPackage` to `BaseAutotoolsPackage`
2. Create `AutotoolsPackage` that subclasses `BaseAutotoolsPackage`
3. Use `BaseAutotoolsPackage` for `automake` and friends, and anyone else where this automagic doesn't work.

**Comment by adamjstewart** [comment]
We could do that. Let's let others vote and see what they think. I'm on the fence as to whether that is a good idea or not.

**Comment by citibeth** [comment]
What are your thoughts, pro vs con?

**Comment by adamjstewart** [comment]
Pros:

- Removes code duplication
- Makes it easier to add master/develop versions of packages

Cons:

- Having 2 base classes for Autotools could be confusing to some people

**Comment by adamjstewart** [comment]
I implemented @citibeth's suggestion. Still needs a lot of comments/docs, but it does work in theory. 

Another alternative is to modify `spack create` to automatically add:
```python
depends_on('automake', type='build', when='@develop,master')                
depends_on('autoconf', type='build', when='@develop,master')                
depends_on('libtool',  type='build', when='@develop,master')                
depends_on('m4',       type='build', when='@develop,master')
```

**Comment by alalazo** [comment]
> It looks like this won't work, as automake and friends are already AutotoolsPackages, and they can't depend on themselves.

I would just wait for when build deps will be concretized separately. Having this hierarchy seems kind of confusing, in particular for people that add a `develop` version to an already existing package.

**Comment by citibeth** [comment]
@alalazo I don't think this hierarchy is confusing because `BaseAutotoolsPackage` will only be used by Autotools-related packages; of which I believe there are 4, and they're already in Spack.  Package authors can just use `AutotoolsPackage` class as they always have.

Would it be possible to add an option to `AutotoolsPackage` to do the same thing as `BaseAuttoolsPackage` instead of creating a new class?  @adamjstewart I think the pros outweight the cons here.

BUT... I think this PR should be put on hold until we can affect behavior based on the *download type*, not the name of the version requested.  Basically, tarballs should assume a `configure` script, and "all" other download types should assume a need to add autotools dependencies.  `@master` and `@develop` --- hacks themselves --- are not the only versions that require autotools.  Some packages download all their versions from a source repo, for example.

@adamjstewart mentioned that adding download type info to the spec is necessary to make this happen.  I suspect it wouldn't be too hard; @alalazo do you have any estimates on this question?

*ASIDE*: The original intent of autotools --- to make it easy to manually install a package on commercial Unix systems without requiring any extra stuff --- is about 20 years out of date now.  Commercial Unix is dead, Linux systems now routinely come with Autotools provided in vast distro repositories; and not having to install a builder (eg CMake) is less of a benefit because so many packages today require a zillion dependencies anyway.  Autobuilders like Spack make the decisions surrounding the `configure` script even more vestigal.  Meanwhile, the idea that tarballs are different from git repos (which didn't exist 20 years ago) causes unending low-level pain as people download stuff from git repos and wonder why their `configure` script is missing.  I'd be happy to just throw in the towel and always require autotools for any autotools-based package; they way things work in CMake land.  I think we (the global software community) are getting very little out of the pre-build `configure` scripts these days.

**Comment by citibeth** [comment]
@scheibelp
Speak of the devil...  See #11808 for an example of why we should maybe
just run autotools on everything.  That would certainly simplify Spack's
life.  Consider this as a simplified approach:

1. Include Autotools dependencies in `AutotoolsPackage`.
2. Run Autotools by default in `AutotoolsPackage.install()`.
3. Add an option to turn off autotools-running for the 0.1% of Autototools
packages where this would create a problem.

In case of (3), the package will still depend on Autotools, of course;
which could in theory cause a little more downloading / building than is
necessary.  But in any large-enough environment, there will probably be at
least one package that needs it; so it was going to have to be downloaded
and installed anyway.  And in the remaining environments that don't need
it; well, downloading and installing Autotools dependencies is really quick.

**Comment by adamjstewart** [comment]
Closing due to lack of interest

**Pull request closed without merging**
