### PR TITLE
Make CDash reporting easier to use

### PR DESCRIPTION
**Pull request by zackgalbreath**
* Better default arguments
* Improve documentation to include a usage example

### CODE REVIEW

**Comment by zackgalbreath** [comment]
@scottwittenburg @opadron PTAL.  Does this seem like a reasonable spot to put an example of how to use the CDash reporter?

**Comment by scottwittenburg** [comment]
This looks ok to me at a brief glance, but I must admit I haven't yet taken the time to figure out how these reporting modules fit into the larger picture/workflow.  I should be able to spend more time early next week though.  Thanks @zackgalbreath.

**Comment by zackgalbreath** [comment]
@tgamblin FYI

**Comment by tgamblin** [comment]
@JavierCVilla: can you take a look at this one?  I think this addresses some issues you brought up in the HSF packaging meeting.

**Pull request merged**
