### PR TITLE
Update the Nekbone package

### PR DESCRIPTION
**Pull request by thilinarmtb**
Minor changes. I installed the `makenek` file so that user can use this to
build any example she wants. Feel free to merge as it is if this looks okay.

### CODE REVIEW

**Comment by thilinarmtb** [comment]
The build has failed due to a home-brew error. My guess is it is not related to this PR.
If that is the case, can we restart the tests?

**Comment by adamjstewart** [comment]
See #6513

**Comment by thilinarmtb** [comment]
Thanks Adam for the link to the issue !!

This look good to me as it is. I am okay for merging.

**Comment by junghans** [comment]
Introduced #8845

**Pull request merged**
