### PR TITLE
Allow disabling font installation

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Why is this change necessary?

**Comment by iarspider** [comment]
To take fonts from the OS, for example.

**Comment by adamjstewart** [comment]
I'm not sure if we want the option to use system fonts. We're trying to do everything we can to separate Spack from the OS, so that you get a reproducible build no matter where you go.

**Comment by tkameyama** [comment]
This PR allows combination of none and fonts:
```
spack install font-util font=none,encodings
```
May be we change variant as follows:
```
   variant('fonts',
            description='Installs fonts',
            values=any_combination_of(*fonts).with_default(','.join(fonts)))
```

**Comment by iarspider** [comment]
@adamjstewart any chance for this to be merged?

**Comment by adamjstewart** [comment]
I’m still hesitant about allowing the package to take fonts from the OS. Is there a good reason for it?

**Comment by iarspider** [comment]
@adamjstewart LCG releases - we take as much as possible from the OS, and only build things that are either not available in OS, or if the version is wrong.

**Comment by iarspider** [comment]
@adamjstewart LCG releases - we take as much as possible from the OS, and only build things that are either not available in OS, or if the version is wrong.

**Comment by iarspider** [comment]
@adamjstewart LCG releases - we take as much as possible from the OS, and only build things that are either not available in OS, or if the version is wrong.

**Comment by iarspider** [comment]
@adamjstewart LCG releases - we take as much as possible from the OS, and only build things that are either not available in OS, or if the version is wrong.

**Comment by adamjstewart** [comment]
Maybe @tgamblin has opinions on this. @hartzell didn't you write a lot of the font-stuff in Spack?

**Comment by iarspider** [comment]
@adamjstewart @tgamblin @hartzell merge or abandon?

**Comment by adamjstewart** [comment]
I'm personally opposed to merging this. If you want to take libraries from the OS, you should add them as external packages so that Spack knows about them.

**Comment by tgamblin** [comment]
I agree with @adamjstewart on this one.

**Comment by iarspider** [comment]
@adamjstewart should I split font installation from `font-util`, something similar to `geant4` + `geant4-data`?

**Pull request closed without merging**
