### PR TITLE
Add and clean up some debug statements

### PR DESCRIPTION
**Pull request by krafczyk**
This commit adds a couple of debug messages reporting when modules are loaded or unloaded, as well as makes a debug message more clear that a command is being executed.

### CODE REVIEW

**Comment by krafczyk** [comment]
@tgamblin ping

**Comment by alalazo** [comment]
@krafczyk Can you rebase this one? I think the addition is small enough to say it's safe to be merged.

**Comment by krafczyk** [comment]
@alalazo I've rebased it.

**Comment by krafczyk** [comment]
@alalazo, I've fixed a unit test bug and rebased this branch again. I believe it is ready.

**Comment by krafczyk** [comment]
@tgamblin That's a good suggestion, I've done just that.

**Comment by alalazo** [comment]
ping

**Comment by alalazo** [comment]
Superseded by #9476

**Pull request closed without merging**
