### PR TITLE
GCC sets CC and CXX flags in it's environment module

### PR DESCRIPTION
**Pull request by sknigh**
Fix discussed in #3884

### CODE REVIEW

**Comment by adamjstewart** [comment]
I agree with this approach. Can you add this to the other compiler packages too? And set `F77`, `F90`, and `FC` too?

**Comment by adamjstewart** [comment]
Uh oh, bad merge.

**Comment by sknigh** [comment]
I was trying to rebase.

**Comment by davydden** [comment]
> I was trying to rebase.

bad rebase, then :smile:

**Comment by alalazo** [comment]
ping

**Comment by sknigh** [comment]
@adamjstewart How do the flags look?

**Comment by adamjstewart** [comment]
Thanks! We should do this for the other compilers as well.

**Comment by alalazo** [comment]
@tgamblin I'll go ahead and merge this, as your request seems to be fulfilled

**Pull request merged**
