### PR TITLE
BundlePackage

### PR DESCRIPTION
**Pull request by citibeth**
Continuation of #3133

### CODE REVIEW

**Comment by citibeth** [comment]
@tgamblin Can we get this merged?

**Comment by citibeth** [comment]
I could.  But my experience is I resolve conflicts repeatedly, but they
don't get merged.  Then another conflict pops up.

**Comment by junghans** [comment]
@adamjstewart I think this is clean enough, some doc stings clean up yes, but otherwise, I would merge this.

**Comment by citibeth** [comment]
Now I'm confused.  @junghans Are you volunteering to merge this, or are you making a suggestion.  What do I need to do to get this merged?  It looks like just:

- [ ] Clean up docstrings

Is there anything else?

**Comment by junghans** [comment]
I think this package class is trivial enough too not overthink this feature.

**Comment by citibeth** [comment]
Can you merge it?

**Comment by tgamblin** [comment]
@adamjstewart still has comments on this and I agree with him.

**Comment by citibeth** [comment]
Thank you for the clarity.

**Comment by citibeth** [comment]
OK, this now "works" in a sense.  But I agree with @adamjstewart, this feels far too much like a hack, and it is far too dependent on whatever refactoring state Spack internals find themselves in at the moment.

We need answers to fundamental questions, like:
1. Should installation of a `BundlePackage` result in a module?  [No, unless we have some kind of module auto-loading of dependencies]
2. Do `BundlePackage`s need versions?  [Yes; because you might want to make releases of DAGs that are known to work together.]

The current PR satisfies those properties.  However, it can get Spack into a strange state.  See below, in which `zlib@1.2.3` is simultaneously installed and not installed.  The command `spack uninstall test-bundle` also yields nothing.  So clearly something is broken, and I feel the specifics are beyond me.  This feels more like random hacking until things stop not-working.

Maybe @scheibelp has insight on internal specifics that this is messing with?

```
$ ~/spack/scratch/bin/spack install test-bundle ^zlib@1.2.3
$ ~/spack/scratch/bin/spack spec -Il test-bundle ^zlib@1.2.3
Input spec
--------------------------------
     test-bundle
         ^zlib@1.2.3

Concretized
--------------------------------
[+]  dypbyuh  test-bundle@1.0%clang@9.0.0-apple arch=darwin-sierra-x86_64 
[+]  pleo2g2      ^ncurses@6.0%clang@9.0.0-apple patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=darwin-sierra-x86_64 
[+]  uh4ub5t          ^pkgconf@1.4.0%clang@9.0.0-apple arch=darwin-sierra-x86_64 
[+]  rawy7ba      ^zlib@1.2.3%clang@9.0.0-apple+optimize+pic+shared arch=darwin-sierra-x86_64 

gs611-tyndall:spack rpfische$ spack find
==> 52 installed packages.
-- darwin-sierra-x86_64 / clang@9.0.0-apple ---------------------
autoconf@2.69               libxml2@2.9.4        py-requests@2.14.2
automake@1.16.1             m4@1.4.18            py-setuptools@39.0.1
bison@3.0.4                 ncurses@6.0          py-six@1.11.0
bzip2@1.0.6                 openssl@1.0.2n       py-snowballstemmer@1.2.1
environment-modules@3.2.10  pcre@8.41            py-sphinx@1.7.4
flex@2.6.4                  perl@5.24.1          py-sphinx-rtd-theme@0.2.5b1
font-util@1.3.1             pkg-config@0.29.2    py-sphinxcontrib-websupport@1.0.1
fontconfig@2.12.3           pkgconf@1.4.0        py-typing@3.6.1
freetype@2.7.1              py-alabaster@0.7.10  python@3.5.2
gdbm@1.14.1                 py-babel@2.4.0       readline@7.0
gettext@0.19.8.1            py-docutils@0.13.1   sqlite@3.22.0
gperf@3.0.4                 py-imagesize@0.7.1   tar@1.30
graphviz@2.40.1             py-jinja2@2.9.6      tcl@8.6.8
help2man@1.47.4             py-markupsafe@1.0    util-macros@1.19.1
libffi@3.2.1                py-packaging@17.1    xz@5.2.3
libpng@1.6.34               py-pygments@2.2.0    zlib@1.2.11
libsigsegv@2.11             py-pyparsing@2.2.0
libtool@2.4.6               py-pytz@2017.2
gs611-tyndall:spack rpfische$ spack find  | grep zlib
zlib@1.2.11
```

**Comment by citibeth** [comment]
I give up... maybe someone else wants to carry this PR forward.

**Comment by junghans** [comment]
@tgamblin @scheibelp can you please make this happen? xsdk, ecp-proxy and more really needs this!

**Comment by RemiLacroix-IDRIS** [comment]
Is this PR still considered for merging? This would indeed be interesting.

**Comment by junghans** [comment]
Ping @tgamblin

**Comment by flxmr** [comment]
So, after encountering the same problem of wanting to create a package which allowed me to use spack to install a self-consistent set of packages (e.g. not a dozen py2/py3-installs intermixed), I started with the advice of the documentation, that one [should be able to create dummy packages.](https://spack.readthedocs.io/en/latest/workflows.html#dummy-packages) Unfortunately I soon learned that this part of documentation was never relevant (though the naive bundle spec'ed just fine) and this led me here.

Looking at the proposed changes, I think that generating a lot of do-nothing-shims seems a little shoddy  – while the stage is used at different places, which might still matter in the case of "installing" a bundle package (for example for logging), a fetcher is something which is clearly not necessary.

And indeed it is, as it's basically only called once in the _make_stage-method of the PackageBase-class. So, overriding this method, and in process not calling the fetcher in the BundlePackage is very effective in making the proposed BundleFetchStrategy a bunch of dead code (hence probably the call for tests). Additionally, the BundleStage-class seems very similar in functionality to the existing DIY-Stage and one could wonder, if those could somehow be merged (be it with creating a base class doing the logging).

If you think this strategy seems worthwile, I'll have a look at the testing procedures of the project and will hopefully be back with a solution requiring less code and including tests after a while. For all people wanting a solution now, which is lean enough to be reasonably used in their package.py-s (and copy&paste-able) you could try this approach: [https://gist.github.com/flxmr/548556ea0b5a3aaa97f28e6d76a4fac4](https://gist.github.com/flxmr/548556ea0b5a3aaa97f28e6d76a4fac4)
I guess you could also let you write a module file with all dependency paths included in relevant env-variables this way?

**Comment by alalazo** [comment]
@flxmr Please have a look at #11158 . It should provide foundations to what you ask for: allow to use Spack to install a self-consistent set of packages.

**Comment by citibeth** [comment]
Another way is to put all your variant and version needs in a spack.yaml
file and only installing “naked” undecorated specs.

**Comment by tgamblin** [comment]
Closing in favor of #11797.  Sorry this sat around so long.

**Pull request closed without merging**
