### PR TITLE
FAODEL: Add FAODEL package to spack

### PR DESCRIPTION
**Pull request by fbudin69500**
FAODEL (Flexible, Asynchronous, Object Data-Exchange Libraries) is a collection
of software libraries that are used to implement different data management
services on high-performance computing (HPC) platforms. This project is part of
the Advanced Technology Development and Mitigation (ATDM) effort for NNSA's ASC
program at Sandia National Laboratories.

### CODE REVIEW

**Comment by fbudin69500** [comment]
This package is a dependency of [ecp-io-sdk](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ecp-io-sdk/package.py#L31-L33)

**Comment by fbudin69500** [comment]
FYI @chuckatkins

**Comment by chuckatkins** [comment]
@craigulmer I see you're the main commiter on the upstream FAODEL repo.  We're adding this as part of the Data & Viz SDK. Does this look good to you?

**Comment by craigulmer** [comment]
@fbudin69500 and @chuckatkins  Thanks for putting this in- we've been meaning to get something together for Spack. 

@tkordenbrock can you take a look at this (and the Faodel issues), verify it works on Kahuna and Mutrino, and see if there's anything else that should be put into the Spack config?

**Comment by fbudin69500** [comment]
This PR is superseeded by #11323

**Pull request closed without merging**
