### PR TITLE
galahad: Added new package.

### PR DESCRIPTION
**Pull request by citibeth**
GALAHAD is an optimization library.

### CODE REVIEW

**Comment by adamjstewart** [comment]
A few comments:

1. Licenses missing from packages
2. How are `xcopy_tree` and `xinstall_tree` different from `install_tree` in `lib/spack/llnl/util/filesystem.py`? Even if they are different, they should go in that file as to reduce code duplication.
3. Need to resolve a lot of flake8 warnings

**Comment by adamjstewart** [comment]
Ping @citibeth

**Comment by citibeth** [comment]
Getting this into Spack has been low priority for me.

**Comment by alalazo** [comment]
Same as #1544 Feel free to reopen if there are updates.

**Pull request closed without merging**
