### PR TITLE
hypre: add superlu-dist variant

### PR DESCRIPTION
**Pull request by balay**
- add a patch to fix build error with superlu-dist

cc: @ulrikeyang

### CODE REVIEW

**Comment by v-dobrev** [comment]
This PR probably broke all packages that use hypre -- now they all need to link explicitly with superlu-dist when linking with hypre. This is certainly the case for mfem.

I think the variant `+superlu-dist`, added in this PR, should not be enabled by default.

**Comment by balay** [comment]
Hm - mfem builds fine when I build xsdk [after this change] and all other xsdk packages - [atleast on the machines I checked.]

And this should be true for any shared libary build [default] of hypre.

I guess I could switch the default to off.

cc: @ulrikeyang

**Comment by v-dobrev** [comment]
Yes, not all builds are broken, however, the default build of mfem is.

In xsdk, I believe, mfem is built with `+superlu-dist` enabled and that is why there is no issue there.

**Comment by balay** [comment]
Well - I just tried this on my linux box - and mfem@develop builds  fine - along with the examples
```
diff --git a/var/spack/repos/builtin/packages/xsdk/package.py b/var/spack/repos/builtin/packages/xsdk/package.py
index 8b3418c8b..c61d0337f 100644
--- a/var/spack/repos/builtin/packages/xsdk/package.py
+++ b/var/spack/repos/builtin/packages/xsdk/package.py
@@ -35,7 +35,7 @@ class Xsdk(Package):
     depends_on('hypre@2.12.1~internal-superlu', when='@0.3.0')
     depends_on('hypre@xsdk-0.2.0~internal-superlu', when='@xsdk-0.2.0')
 
-    depends_on('mfem@develop+mpi+hypre+superlu-dist+petsc~sundials+examples+miniapps', when='@develop')
+    depends_on('mfem@develop+mpi+hypre+petsc~sundials+examples+miniapps', when='@develop')
     depends_on('mfem@3.4.0+mpi+hypre+superlu-dist+petsc+sundials+examples+miniapps', when='@0.4.0')
     depends_on('mfem@3.3.2+mpi+hypre+superlu-dist+petsc+sundials+examples+miniapps', when='@0.3.0')
```
Perhaps the issue you are encountering is some other bug [but somehow `hypre+superlu-dist` is the trigger?

```
/home/petsc/soft/mpich-3.3b1/bin/mpic++  -O3 -I.. -I/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hypre-develop-se6ik4jjugnvre36mjx3nrxtwmbtnazr/include -I/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/metis-5.1.0-avowfg4gmxs47cmzncffsofz4nw56c5p/include -I/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/petsc-develop-zeyvovd3qtucuyjkbydqlt5f4dnaqvaq/include -I/usr/include ex1.cpp -o ex1 -L.. -lmfem -Wl,-rpath,/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hypre-develop-se6ik4jjugnvre36mjx3nrxtwmbtnazr/lib -Wl,-rpath,/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/openblas-0.3.5-xokonl5jhgandxuwswkaabijra337l2d/lib -L/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hypre-develop-se6ik4jjugnvre36mjx3nrxtwmbtnazr/lib -L/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/openblas-0.3.5-xokonl5jhgandxuwswkaabijra337l2d/lib -lHYPRE -lopenblas -Wl,-rpath,/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/metis-5.1.0-avowfg4gmxs47cmzncffsofz4nw56c5p/lib -L/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/metis-5.1.0-avowfg4gmxs47cmzncffsofz4nw56c5p/lib -lmetis -Wl,-rpath,/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/petsc-develop-zeyvovd3qtucuyjkbydqlt5f4dnaqvaq/lib -L/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/petsc-develop-zeyvovd3qtucuyjkbydqlt5f4dnaqvaq/lib -lpetsc -lrt -Wl,-rpath,/usr/lib64 -L/usr/lib64 -lz
```
```
[balay@pj03 examples]$ pwd
/home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/mfem-develop-3u6otejapxf5zi2ixe37vgsdv3h523ej/examples
[balay@pj03 examples]$ ldd ex1
	linux-vdso.so.1 (0x00007fff9e3fc000)
	libHYPRE-2.15.1.so => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hypre-develop-se6ik4jjugnvre36mjx3nrxtwmbtnazr/lib/libHYPRE-2.15.1.so (0x00007f0161c96000)
	libopenblas.so.0 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/openblas-0.3.5-xokonl5jhgandxuwswkaabijra337l2d/lib/libopenblas.so.0 (0x00007f01610c6000)
	libmetis.so => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/metis-5.1.0-avowfg4gmxs47cmzncffsofz4nw56c5p/lib/libmetis.so (0x00007f0161058000)
	libpetsc.so.3.011 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/petsc-develop-zeyvovd3qtucuyjkbydqlt5f4dnaqvaq/lib/libpetsc.so.3.011 (0x00007f015fe87000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007f015fe7d000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f015fe63000)
	libmpicxx.so.0 => /home/petsc/soft/mpich-3.3b1/lib/libmpicxx.so.0 (0x00007f015fe3b000)
	libmpi.so.0 => /home/petsc/soft/mpich-3.3b1/lib/libmpi.so.0 (0x00007f015f9cb000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f015f833000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f015f6af000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f015f694000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f015f4ce000)
	libsuperlu_dist.so.6 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/superlu-dist-develop-vwfyinkl7rg6lrq5hcxstsdm2vjejdap/lib/libsuperlu_dist.so.6 (0x00007f015f40d000)
	libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007f015f184000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0161ff1000)
	libdtk_hybridtransport.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_hybridtransport.so.12 (0x00007f015f176000)
	libdtk_mapfactory.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_mapfactory.so.12 (0x00007f015f14f000)
	libdtk_meshfree.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_meshfree.so.12 (0x00007f015f0cf000)
	libdtk_discretization.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_discretization.so.12 (0x00007f015efe6000)
	libdtk_search.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_search.so.12 (0x00007f015efe0000)
	libdtk_interface.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_interface.so.12 (0x00007f015efc6000)
	libdtk_utils.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libdtk_utils.so.12 (0x00007f015efbc000)
	libmuelu-adapters.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libmuelu-adapters.so.12 (0x00007f015eb6f000)
	libmuelu-interface.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libmuelu-interface.so.12 (0x00007f015e486000)
	libmuelu.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libmuelu.so.12 (0x00007f015d364000)
	liblocaepetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/liblocaepetra.so.12 (0x00007f015d262000)
	liblocalapack.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/liblocalapack.so.12 (0x00007f015d20a000)
	libloca.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libloca.so.12 (0x00007f015cef9000)
	libnoxepetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libnoxepetra.so.12 (0x00007f015ce65000)
	libnoxlapack.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libnoxlapack.so.12 (0x00007f015ce4f000)
	libnox.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libnox.so.12 (0x00007f015cd5e000)
	libintrepid2.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libintrepid2.so.12 (0x00007f015cd56000)
	libifpack2.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libifpack2.so.12 (0x00007f015c7c2000)
	libanasazitpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libanasazitpetra.so.12 (0x00007f015c7ba000)
	libModeLaplace.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libModeLaplace.so.12 (0x00007f015c77f000)
	libanasaziepetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libanasaziepetra.so.12 (0x00007f015c758000)
	libanasazi.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libanasazi.so.12 (0x00007f015c750000)
	libamesos2.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libamesos2.so.12 (0x00007f015c614000)
	libbelosxpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libbelosxpetra.so.12 (0x00007f015c223000)
	libbelostpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libbelostpetra.so.12 (0x00007f015bc0b000)
	libbelosepetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libbelosepetra.so.12 (0x00007f015b892000)
	libbelos.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libbelos.so.12 (0x00007f015b6a9000)
	libml.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libml.so.12 (0x00007f015b3d9000)
	libifpack.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libifpack.so.12 (0x00007f015b1e0000)
	libzoltan2.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libzoltan2.so.12 (0x00007f015b176000)
	libamesos.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libamesos.so.12 (0x00007f015b124000)
	libgaleri-xpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libgaleri-xpetra.so.12 (0x00007f015b11c000)
	libgaleri-epetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libgaleri-epetra.so.12 (0x00007f015b0e1000)
	libaztecoo.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libaztecoo.so.12 (0x00007f015b064000)
	libxpetra-sup.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libxpetra-sup.so.12 (0x00007f015b03f000)
	libxpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libxpetra.so.12 (0x00007f015afc0000)
	libtrilinosss.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtrilinosss.so.12 (0x00007f015af8d000)
	libtpetraext.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetraext.so.12 (0x00007f015adf9000)
	libtpetrainout.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetrainout.so.12 (0x00007f015adc2000)
	libtpetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetra.so.12 (0x00007f015a1f8000)
	libkokkostsqr.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libkokkostsqr.so.12 (0x00007f015a199000)
	libtpetraclassiclinalg.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetraclassiclinalg.so.12 (0x00007f015a192000)
	libtpetraclassicnodeapi.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetraclassicnodeapi.so.12 (0x00007f015a18b000)
	libtpetraclassic.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtpetraclassic.so.12 (0x00007f015a186000)
	libepetraext.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libepetraext.so.12 (0x00007f0159ff4000)
	libtriutils.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libtriutils.so.12 (0x00007f0159fa8000)
	libshards.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libshards.so.12 (0x00007f0159f89000)
	libzoltan.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libzoltan.so.12 (0x00007f0159ea7000)
	libepetra.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libepetra.so.12 (0x00007f0159d43000)
	libsacado.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libsacado.so.12 (0x00007f0159d1f000)
	libkokkoskernels.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libkokkoskernels.so.12 (0x00007f01599eb000)
	libteuchoskokkoscomm.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchoskokkoscomm.so.12 (0x00007f01599e4000)
	libteuchoskokkoscompat.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchoskokkoscompat.so.12 (0x00007f01599de000)
	libteuchosremainder.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchosremainder.so.12 (0x00007f01599d5000)
	libteuchosnumerics.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchosnumerics.so.12 (0x00007f01599ba000)
	libteuchoscomm.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchoscomm.so.12 (0x00007f01598c0000)
	libteuchosparameterlist.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchosparameterlist.so.12 (0x00007f0159476000)
	libteuchosparser.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchosparser.so.12 (0x00007f0159403000)
	libteuchoscore.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libteuchoscore.so.12 (0x00007f01593a5000)
	libkokkosalgorithms.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libkokkosalgorithms.so.12 (0x00007f015939f000)
	libkokkoscontainers.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libkokkoscontainers.so.12 (0x00007f0159399000)
	libkokkoscore.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libkokkoscore.so.12 (0x00007f015933d000)
	libgtest.so.12 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/trilinos-develop-4a7w6c4aynncdaz36wtbuuq3grtxxo5g/lib/libgtest.so.12 (0x00007f01592ed000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f01592cb000)
	libhdf5hl_fortran.so.100 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hdf5-1.10.5-wzobpqpb26ljnkktatxlilzk5n7kwqkn/lib/libhdf5hl_fortran.so.100 (0x00007f01592ae000)
	libhdf5_fortran.so.102 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hdf5-1.10.5-wzobpqpb26ljnkktatxlilzk5n7kwqkn/lib/libhdf5_fortran.so.102 (0x00007f0159264000)
	libhdf5_hl.so.100 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hdf5-1.10.5-wzobpqpb26ljnkktatxlilzk5n7kwqkn/lib/libhdf5_hl.so.100 (0x00007f015923c000)
	libhdf5.so.103 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/hdf5-1.10.5-wzobpqpb26ljnkktatxlilzk5n7kwqkn/lib/libhdf5.so.103 (0x00007f0158e40000)
	libparmetis.so => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/parmetis-4.0.3-jj5xpkazypj54oi2hqqeji2qgviyc6hl/lib/libparmetis.so (0x00007f0158e08000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0158e02000)
	libmpifort.so.0 => /home/petsc/soft/mpich-3.3b1/lib/libmpifort.so.0 (0x00007f0158d88000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f0158d45000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f0158d11000)
	libboost_program_options.so.1.69.0 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/boost-1.69.0-6q6w5sd36b5id37wn65aspdtbftskq4h/lib/libboost_program_options.so.1.69.0 (0x00007f0158c8a000)
	libnetcdf.so.15 => /home/balay/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/netcdf-4.6.3-cj4qtfs3zu2ki3wpvq7gqs4tcn6yqnor/lib/libnetcdf.so.15 (0x00007f0158b9e000)
[balay@pj03 examples]$ 


```

**Comment by v-dobrev** [comment]
Even if you remove the `+superlu-dist` variant in mfem, mfem gets the superlu-dist dependency from petsc (I think) -- you can see the library in the line `libsuperlu_dist.so.6 => ...` in the ldd output.

Anyway, my point is that `spack install mfem` fails on the current develop branch because of this change. Also, other packages using hypre will probably fail too.

**Comment by balay** [comment]
`spack install mfem@develop+examples` also works fine for me.

I can change the hypre default - but that just
- hides the problem
- mfem would be enforcing defaults on hypre

presumably there is a correct way to handle this in spack. As its a tool meant to let such things work correctly.

perhaps spack developers will chime in here..

also I think one of the things with xsdk is to test and make sure such things work between xsdk packages

cc: @ulrikeyang @jwillenbring  @jedbrown @tgamblin

**Comment by v-dobrev** [comment]
I guess the reason it works for you is that you are testing on linux, where hypre is built as a shared library (is that the case?), and I'm testing this on mac, where hypre is built as a static library and so superlu-dist needs to be explicitly given when linking with hypre.

**Comment by balay** [comment]
yes - shared library build shouldn't have problems.

 Will have to check why hypre is not installed shard on mac.

I understand static build needs correct linking. And I'm not sure exactly how spack helps here.

**Comment by goxberry** [comment]
@balay `hypre` isn't installed shared by default on macOS because until recently (September 2018), it wasn't possible to install `hypre` as a shared library on macOS. I added macOS shared library builds to `hypre` a few months ago, and it should work as of `hypre` 2.15.0, with patches in `spack` to backport macOS shared library functionality to versions 2.13.0 and 2.14.0.

**Comment by balay** [comment]
@goxberry Thanks for the clarification. I was just checking the comments in hypre/package.py - and now have a successful shared build.

```
balay@jpro^~/spack(balay/xsdk-develop) $ ls /Users/balay/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/hypre-2.15.1-q533suh3lf3xp2gqcxmlrphv3vij3ld4/lib/
libHYPRE-2.15.1.dylib*	libHYPRE.dylib@
balay@jpro^~/spack(balay/xsdk-develop) $ 

```

Is there a way in spack to have different defaults for variants based on version? This way `shared=False` is set only for older versions of hypre?

**Pull request merged**
