### PR TITLE
Make neuron package more generic

### PR DESCRIPTION
**Pull request by rmsds**
* find the bin directory dynamically for use in run_env and spack_env
* replace filter_compilers with filter_compiler_wrappers
* update checksum for "current" 7.5 version

Signed-off-by: Ricardo Silva <ricardo.silva@epfl.ch>

### CODE REVIEW

**Comment by rmsds** [comment]
@pramodskumbhar Thanks for the review but please do **not** merge yet as I'm looking into a possible issue with the python integration.

**Comment by alalazo** [comment]
@rmsds Let me know when you're finished. I'll re-review the PR then.

**Comment by pramodskumbhar** [comment]
@rmsds : whats the issue with python integration? My [version of package](https://github.com/pramodskumbhar/spack-packages/blob/develop/packages/neuron/package.py) is bit older but I use it on all our systems.

**Comment by rmsds** [comment]
@pramodskumbhar I wasn't building the shared libraries which are required for the python module to work, so I made that relation explicit ('+python' requires '+shared'). The LD_LIBRARY_PATH also needs to be set to the architecture-specific directory for the same reason.

Otherwise I got the following when running `python -c 'import neuron'`:

`ImportError: libnrnpython.so.0: cannot open shared object file: No such file or directory`

**Pull request merged**
