### PR TITLE
Fix bug introduced by pull request 14467 being merged

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
I tried this out, and it solved the problem for me.

:+1:

**Comment by gartung** [comment]
Are your pipelines building in a VM? Will they always report the same arch?
I worry this might be too restrictive since arch might report microarch.

**Comment by scottwittenburg** [comment]
> Are your pipelines building in a VM? Will they always report the same arch?

Pipelines can run pretty much anywhere, but in the cloud gitlab we tend to use Docker containers to build the specs.  

> I worry this might be too restrictive since arch might report microarch.

Yeah.  In general if I'm on a `haswell` machine, for example, I might be fine installing a binary package for `x86_64`.

**Comment by scottwittenburg** [comment]
@gartung So this did work when I originally tested it, but something you pushed more recently broke things again.  Running on the latest `develop`, I'm getting this error when spack is trying to install packages from the mirror:

```
==> [2020-01-27-23:08:16.999960] Installing libiconv
==> [2020-01-27-23:08:16.999984] Searching for binary cache of libiconv
==> [2020-01-27-23:08:17.000325] Finding buildcaches at s3://spack-tutorial-container/mirror/build_cache
Traceback (most recent call last):
  File "/builds/scott/spack-tutorial-container/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/main.py", line 722, in main
    return _invoke_command(command, parser, args, unknown)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/main.py", line 456, in _invoke_command
    return_val = command(parser, args)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/cmd/install.py", line 368, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/cmd/install.py", line 226, in install_spec
    env.install(abstract_spec, spec, **kwargs)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/environment.py", line 1019, in install
    self._install(concrete, **install_args)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/environment.py", line 1022, in _install
    spec.package.do_install(**install_args)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/package.py", line 1652, in do_install
    dep.package.do_install(**dep_kwargs)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/package.py", line 1665, in do_install
    if self.try_install_from_binary_cache(explicit):
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/package.py", line 1510, in try_install_from_binary_cache
    specs = binary_distribution.get_specs(use_arch=True)
  File "/builds/scott/spack-tutorial-container/spack/lib/spack/spack/binary_distribution.py", line 709, in get_specs
    spack.architecture.os),
AttributeError: module 'spack.architecture' has no attribute 'os'
```

**Comment by scottwittenburg** [comment]
You can reproduce it the same way as for the other issue I brought up:

1. install `zlib` from source
2. create an unsigned buildcache for that `zlib`
3. uninstall that `zlib`
4. install `zlib` with the `--cache-only` option

**Comment by gartung** [comment]
Working on another fix.

**Comment by gartung** [comment]
Yet another fix here https://github.com/spack/spack/pull/14642

**Comment by gartung** [comment]
Ugh I should have realized that the hash won't match if the arch triplet is different.

**Pull request merged**
