### PR TITLE
Remove definition of dirent for the PGI compiler.

### PR DESCRIPTION
**Pull request by serbanmaerean**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Can you provide some sort of justification for the change? Has this patch been submitted upstream?

**Comment by serbanmaerean** [comment]
I discovered this problem when we tried to build boost with the PGI compiler.  The defintion of dirent to dirent64 break the build.  Considering that I only have access to ppc64le platform, I decided to add a patch.  I will contact the boost community with the proposed patch.

**Comment by serbanmaerean** [comment]
@adamjstewart is there anything else I need to do for you to merge this pull request?

**Comment by djfitzgerald** [comment]
@adamjstewart @alalazo @tgamblin -- would any of you be willing to merge this PR?

**Comment by scheibelp** [comment]
@serbanmaerean/@djfitzgerald can you use a more descriptive patch name like in https://github.com/spack/spack/pull/4426 (e.g. add the boost version since the patch is specific to the boost version, or call it something like `boost_pgi_dirent.patch`). In particular I think since there are multiple pgi-related patches already it would be good to have a more-distinctive name.

Not as important: add a comment next to the patch directive explaining the patch like https://github.com/spack/spack/pull/8313#issuecomment-393212000 (this isn't essential since `git blame` would lead one here, but it's still nice).

**Comment by scheibelp** [comment]
Thanks for adding https://github.com/spack/spack/pull/8313/commits/8a630fe23800f909cfb00824ac265631233d3ad8! I'll have a chance to merge it later today (after the CI tests run)

**Pull request merged**
