### PR TITLE
Fixed detection for cascadelake microarchitecture

### LINKED ISSUE #13803: cascadelake detected as skylake_avx512
Hi

Referenced at end of #12915 my cascadelake CPU seems to be detected by `spack arch` as skylake_avx512.

```
[root@phobos ~]# spack arch
linux-centos7-skylake_avx512
```

The CPU:

```
dod2014@phobos[~/prepos/spack]$ cat /proc/cpuinfo | head -n 20
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
stepping        : 7
microcode       : 0x5000024
cpu MHz         : 2400.000
cache size      : 36608 KB
physical id     : 0
siblings        : 48
core id         : 0
cpu cores       : 24
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```

Using latest code:

```
[root@phobos centos7]# git log | head
commit f25a4ab089fc84d88d4bbd2180f1ed0e43c6f096
Author: albestro <9337627+albestro@users.noreply.github.com>
Date:   Tue Nov 19 20:49:32 2019 +0100

    add MAX_CPU_COUNT variant to HPX package (#13769)
    
    * add MAX_CPU_COUNT variant to HPX package
    
    * compatibility with python2
    
```

Did not change anything in configuration except compilers:

```
[root@phobos centos7]# git status
# On branch develop
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       etc/spack/defaults/compilers.yaml
nothing added to commit but untracked files present (use "git add" to track)
```

As you can see this is cascadelake per avx512_vnni.

Thank you!

### PR DESCRIPTION
**Pull request by alalazo**
fixes #13803

### CODE REVIEW

**Comment by ifelsefi** [comment]
Nice

**Comment by ifelsefi** [comment]
Confirmed, this fixes the problem

```
[root@phobos centos7]# source /software/spack/centos7/share/spack/setup-env.sh
[root@phobos centos7]# spack arch
linux-centos7-cascadelake
```

**Comment by ifelsefi** [comment]
Can this be merged?

**Comment by alalazo** [comment]
@ifelsefi When I get a review and Travis finishes sure :slightly_smiling_face:

**Comment by tgamblin** [comment]
Moving this to `0.14`, as it'll change specs, and it's conflicted with #13780.

**Pull request merged**
