### PR TITLE
doxygen: add version 1.8.5 for RHEL 7

### PR DESCRIPTION
**Pull request by goxberry**
Adds version 1.8.5 so `packages.yaml` can use RHEL 7 installation of doxygen 1.8.5.

### CODE REVIEW

**Comment by adamjstewart** [comment]
> so `packages.yaml` can use RHEL 7 installation of doxygen 1.8.5.

Have you seen any indication that this is required? I've been using system installations with Spack for years and the versions have never been present in the `package.py`.

**Comment by goxberry** [comment]
@adamjstewart Yes, spack throws an error if the version isn’t present in the `package.py` file, at least on one of the LLNL clusters.

**Comment by adamjstewart** [comment]
I'm sorry, I'm still having trouble reproducing this. Can you give more specific instructions? With the following `packages.yaml`:
```yaml
packages:
  zlib:
    paths:
      zlib@1.2.7: /usr
    buildable: False
```
I'm not having any trouble building `zlib` or anything that depends on it:
```console
$ spack install zlib
==> zlib@1.2.7 : externally installed in /usr
==> zlib@1.2.7 : generating module file
==> zlib@1.2.7 : registering into DB
$ spack uninstall -y zlib
==> Successfully uninstalled zlib@1.2.7%gcc@7.1.0+optimize+pic+shared arch=linux-centos7-x86_64 /jzwkqjx
$ spack install openssl
==> zlib@1.2.7 : externally installed in /usr
==> zlib@1.2.7 : generating module file
==> zlib@1.2.7 : registering into DB
==> Installing openssl
==> Fetching http://www.openssl.org/source/openssl-1.0.2n.tar.gz
######################################################################## 100.0%
==> Staging archive: /blues/gpfs/home/ajstewart/spack/var/spack/stage/openssl-1.0.2n-vpydmxkmrzrx3htxly5bxbbjejozjkau/openssl-1.0.2n.tar.gz
==> Created stage in /blues/gpfs/home/ajstewart/spack/var/spack/stage/openssl-1.0.2n-vpydmxkmrzrx3htxly5bxbbjejozjkau
==> No patches needed for openssl
==> Building openssl [Package]
==> Executing phase: 'install'
==> Successfully installed openssl
  Fetch: 0.79s.  Build: 2m 54.72s.  Total: 2m 55.51s.
[+] /blues/gpfs/home/ajstewart/spack/opt/spack/linux-centos7-x86_64/gcc-7.1.0/openssl-1.0.2n-vpydmxkmrzrx3htxly5bxbbjejozjkau
```
@citibeth reported this as well, but I was never able to reproduce it.

**Comment by citibeth** [comment]
@goxberry Would it be possible for you to just bundle a bunch of 'new-version' PRs into a single PR?  I don't think these PRs need any debate, and having them in would would make it easier.

**Comment by adamjstewart** [comment]
> Would it be possible for you to just bundle a bunch of 'new-version' PRs into a single PR? I don't think these PRs need any debate, and having them in would would make it easier.

Please don't do that, separate PRs are preferred: http://spack.readthedocs.io/en/latest/contribution_guide.html

> If possible, try to follow the one-PR-one-package/feature rule.

**Comment by adamjstewart** [comment]
Based on the outcome of #7971, it sounds like this old version is not needed. If you can find a way to reproduce the problem you were seeing, please open an issue. Old versions of software should not need to be present in Spack packages in order to use them as external packages.

**Pull request closed without merging**
