### PR TITLE
Add latest version of jq

### PR DESCRIPTION
**Pull request by adamjstewart**
Also switches download to tarball containing `configure` script and adds post-installation tests.

Successfully installs and passes all tests on macOS 10.15.1 with Clang 11.0.0.

### CODE REVIEW

**Comment by hartzell** [comment]
Three cheers for the tests! 

Homebrew won't take new recipes without tests, and [has a bit of docs about what makes a good test](https://docs.brew.sh/Formula-Cookbook#add-a-test-to-the-formula).

Wonder if we could do something similar?  We have this bit [about post-build tests](https://spack.readthedocs.io/en/latest/packaging_guide.html#build-time-tests) but it's followed by a warning about the testing API changing drastically, which is offputting.  There's also this bit [in the custom packaging section](https://spack.readthedocs.io/en/latest/build_systems/custompackage.html#testing).  Both of those are "after build", while your code here is "after install".  Any material difference?

**Comment by adamjstewart** [comment]
@hartzell I would love to have custom unit tests for every package like Homebrew does. I would also love to have `maintainers` for every package like Conda-Forge does. I think both of these things are hard to enforce at the moment though, and I don't want to discourage new contributors. I add a lot of packages that are dependencies of packages I actually care about, so I wouldn't volunteer myself to be a maintainer. Also, we don't have the infrastructure in place to automatically ping `maintainers` or to run build/unit tests for PRs yet. Once we have that, I think it will be easier (should be coming in the next year). We could also use better docs or a simpler process for adding package testing. I wrote a little bit in https://spack.readthedocs.io/en/latest/build_systems/custompackage.html#testing but it's pretty well hidden.

**Comment by adamjstewart** [comment]
Oops, accidental close

**Comment by hartzell** [comment]
> I don't want to discourage new contributors.

a) I think that Homebrew's an existence proof for the idea that requiring a set of reasonable tests is won't kill contributions.

b) I've thought of maintainer-ship as opt-in; I'm not in a position to be a full time owner of every thing that I contribute but the fact that it works here and now seems to make it a useful contribution.

The FreeBSD ports tree has a long history of maintainer-ship backed up by "fostering" of unmaintained ports by the freebsd-ports community.

I think that requiring a) actually goes a long way toward making b) more useful, as it gives foster-ers/adopters a handle on what "working" means.

Your prose in the [custom packaging section](https://spack.readthedocs.io/en/latest/build_systems/custompackage.html#testing) uses both `@run_after('build')` and `@run_after('install')` tests and the [packaging guide section](https://spack.readthedocs.io/en/latest/build_systems/custompackage.html#testing) uses `@run_after('build')`.  You've used `@run_after('install')` here and I believe that `jq = self.spec['jq'].command` is actually using the installed version of the program.

If one were to adopt a personal best practice of including tests with new packages, would it be better to test what you've built before installing it, or testing the installed version to ensure that it works as it should?

**Comment by hartzell** [comment]
Speaking of including tests in what we contribute, any thoughts on how to include broken packages in the `builtins.mock` tree w/out causing test failures all over the place?

https://github.com/spack/spack/pull/14061#issuecomment-565213741

**Comment by hartzell** [comment]
Just to add a bit of useful info to my balance questions, both versions install with `--run-tests` for me on a Mac running OS X 10.13.6 running clang `Apple LLVM version 10.0.0`.

**Comment by adamjstewart** [comment]
> If one were to adopt a personal best practice of including tests with new packages, would it be better to test what you've built before installing it, or testing the installed version to ensure that it works as it should?

Most packages come with `make check` but not `make installcheck`, so they already have build-time tests, but not run-time tests. Also, we don't support this yet, but there's been a lot of talk about being able to re-run tests after a package is already installed.

**Comment by hartzell** [comment]
> but not run-time tests

Which, if I hear you correctly, suggests that packagers should include `@run_after('install')` tests.  Ring true?

**Comment by adamjstewart** [comment]
Trust me, I would love to see more post-installation tests, or tests in general. But right now, most packages don't even have maintainers. Adding unit tests isn't simple (this PR took me an hour to figure out how to pass input to `jq`). Until we make it easier or better documented, I wouldn't require it. Unless @hartzell writes the PR, in which case I might start requiring it 😝

**Comment by hartzell** [comment]
@hartzell would like to lead by setting an example (except for the bit about referring to himself in the third person, that's just annoying....), but isn't entirely sure what the best practice should be.  Perhaps if/when he's added a bit of practice/experience to his opinion, he'll submit a [another] PR....

I'll take your example here (post install testing) as an example of WWAD.

**Pull request merged**
