### PR TITLE
Add an explicit fpic variant for netcdf to support building on pgi

### LINKED ISSUE #10705: "shared" variant in netcdf incorrectly assumes fPIC
When installing netcdf with pgi, pgi exits with an error about fPIC. (See below.)

The package sets fPIC if the shared variant is *excluded*

```
    variant('shared', default=True, description='Enable shared library')
```

```
        if '~shared' in self.spec:
            # We don't have shared libraries but we still want it to be
            # possible to use this library in shared builds
            cflags.append(self.compiler.pic_flag)
```

But this assumes that fPIC is set by `--shared`, which it appears to not be. (See the error above.)

I propose an explicit fpic variant, like is seen in some other packages. I've prototyped this, and plan to submit a PR.

### Steps to reproduce the issue

```
Concretized
--------------------------------
netcdf@4.6.1%pgi@18.4~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-rhel7-x86_64 
    ^hdf5@1.10.4%pgi@18.4~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-rhel7-x86_64 
        ^openmpi@3.1.3%pgi@18.4~cuda+cxx_exceptions fabrics=libfabric,psm2,ucx,verbs ~java~legacylaunchers~memchecker+pmi schedulers=slurm ~sqlite3~thread_multiple+vt arch=linux-rhel7-x86_64 
            ^hwloc@1.11.9%gcc@8.2.0~cairo~cuda+libxml2+pci+shared arch=linux-rhel7-x86_64 
                ^libpciaccess@0.13.5%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^libxml2@2.9.8%gcc@8.2.0~python arch=linux-rhel7-x86_64 
                    ^xz@5.2.4%gcc@8.2.0 arch=linux-rhel7-x86_64 
                    ^zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-rhel7-x86_64 
                ^numactl@2.0.11%gcc@8.2.0 patches=592f30f7f5f757dfc239ad0ffd39a9a048487ad803c26b419e0f96b8cda08c1a arch=linux-rhel7-x86_64 
                    ^m4@1.4.18%gcc@8.2.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-rhel7-x86_64 
                        ^libsigsegv@2.11%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^libfabric@1.6.1%gcc@8.2.0 fabrics=sockets arch=linux-rhel7-x86_64 
            ^slurm@17-11-9-2%gcc@8.2.0~gtk~hdf5~hwloc~mariadb+readline arch=linux-rhel7-x86_64 
                ^curl@7.60.0%gcc@8.2.0~darwinssl~libssh~libssh2~nghttp2 arch=linux-rhel7-x86_64 
                    ^openssl@1.0.2o%gcc@8.2.0+systemcerts arch=linux-rhel7-x86_64 
                        ^perl@5.26.2%gcc@8.2.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-rhel7-x86_64 
                            ^gdbm@1.14.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                                ^readline@7.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
                                    ^ncurses@6.1%gcc@8.2.0~symlinks~termlib arch=linux-rhel7-x86_64 
                ^glib@2.56.2%gcc@8.2.0~libmount patches=c325997b72a205ad1638bb3e3ba0e5b73e3d32ce63b2d0d3282f3e3a2ff4663c tracing= arch=linux-rhel7-x86_64 
                    ^gettext@0.19.8.1%gcc@8.2.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-rhel7-x86_64 
                        ^bzip2@1.0.6%gcc@8.2.0+shared arch=linux-rhel7-x86_64 
                        ^tar@1.30%gcc@8.2.0 arch=linux-rhel7-x86_64 
                    ^libffi@3.2.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                    ^pcre@8.42%gcc@8.2.0~jit+utf arch=linux-rhel7-x86_64 
                    ^python@2.7.15%gcc@8.2.0+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-rhel7-x86_64 
                        ^sqlite@3.23.1%gcc@8.2.0~functions arch=linux-rhel7-x86_64 
                ^json-c@0.13.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^lz4@1.8.1.2%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^munge@0.5.11%gcc@8.2.0 arch=linux-rhel7-x86_64 
                    ^libgcrypt@1.8.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                        ^libgpg-error@1.27%gcc@8.2.0 arch=linux-rhel7-x86_64 
            ^ucx@1.3.1%gcc@8.2.0 arch=linux-rhel7-x86_64 
                ^rdma-core@20%gcc@8.2.0 build_type=RelWithDebInfo arch=linux-rhel7-x86_64 
                    ^libnl@3.3.0%gcc@8.2.0 arch=linux-rhel7-x86_64 
```

### Error Message

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j24'

4 errors found in build log:
     742    PGC-W-0136-Function nc_finalize has non-prototype declaration in scope (nc_initialize.c: 114)
     743    PGC/x86-64 Linux 18.4-0: compilation completed with warnings
     744    libtool: compile:  /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/openmpi-3.1.3-afu27drj7suoqzmsx4rkvpgchbei4ms4/bin/mpicc -DHAVE_CONFIG_H -I. -I/curc/sw/spack/var/spack/stage/netcdf-4.6.1-a4a3afpyqydceqa3w72ks
            trcahfybqgy/netcdf-4.6.1/liblib -I.. -I/curc/sw/spack/var/spack/stage/netcdf-4.6.1-a4a3afpyqydceqa3w72kstrcahfybqgy/netcdf-4.6.1/include -I/curc/sw/spack/var/spack/stage/netcdf-4.6.1-a4a3afpyqydceqa3w72kstrcahfybqgy/
            netcdf-4.6.1/libsrc4 -I/curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x73guf5mxno/include -c nc_initialize.c -MD -o libnetcdf_la-nc_initialize.o >/dev/null 2>&1
     745    /bin/sh ../libtool  --tag=CC   --mode=link /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/openmpi-3.1.3-afu27drj7suoqzmsx4rkvpgchbei4ms4/bin/mpicc   -version-info 14:1:1 -L/curc/sw/spack/opt/spack/linux-rhel7-x
            86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x73guf5mxno/lib -o libnetcdf.la -rpath /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/netcdf-4.6.1-a4a3afpyqydceqa3w72kstrcahfybqgy/lib libnetcdf_la-nc_initialize
            .lo ../libdispatch/libnetcdf2.la ../libdispatch/libdispatch.la ../libsrc/libnetcdf3.la     ../libsrc4/libnetcdf4.la -lhdf5_hl -lhdf5 -lm -lz
     746    libtool: link: /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/openmpi-3.1.3-afu27drj7suoqzmsx4rkvpgchbei4ms4/bin/mpicc -shared  -DPIC  .libs/libnetcdf_la-nc_initialize.o  --whole-archive ../libdispatch/.libs/li
            bnetcdf2.a ../libdispatch/.libs/libdispatch.a ../libsrc/.libs/libnetcdf3.a ../libsrc4/.libs/libnetcdf4.a --no-whole-archive  -rpath /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34yc
            w6x73guf5mxno/lib -rpath /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x73guf5mxno/lib -L/curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x
            73guf5mxno/lib -L/curc/sw/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zlib-1.2.11-hyog4nvfq25emh5taua53slpjeplgwm2/lib /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x73guf5mxn
            o/lib/libhdf5_hl.so /curc/sw/spack/opt/spack/linux-rhel7-x86_64/pgi-18.4/hdf5-1.10.4-bikmj2dtqggayel34ycw6x73guf5mxno/lib/libhdf5.so -ldl -lm -lz -lc    -soname libnetcdf.so.13 -o .libs/libnetcdf.so.13.1.1
     747    /usr/bin/ld: ../libdispatch/.libs/libnetcdf2.a(libnetcdf2_la-dv2i.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
  >> 748    ../libdispatch/.libs/libnetcdf2.a(libnetcdf2_la-dv2i.o): error adding symbols: Bad value
  >> 749    make[2]: *** [libnetcdf.la] Error 2
     750    make[2]: Leaving directory `/pl/active/rcops/spack-build/joan5896/spack-stage/spack-stage-lc8Nhz/netcdf-4.6.1/liblib'
  >> 751    make[1]: *** [all-recursive] Error 1
     752    make[1]: Leaving directory `/pl/active/rcops/spack-build/joan5896/spack-stage/spack-stage-lc8Nhz/netcdf-4.6.1'
  >> 753    make: *** [all] Error 2
```

### Information on your system

RHEL7 using spack 0.12.1.

### PR DESCRIPTION
**Pull request by anderbubble**
Fixes #10705

### CODE REVIEW

**Comment by adamjstewart** [comment]
I assume the other file changes are unintentional?

**Comment by chuckatkins** [comment]
It seems the pic variant was already added and this is redundant and can be closed, is that correct @anderbubble .  Although I believe it can actually be removed and wasn't necessary (I'll explain in a new pr shortly)

**Comment by anderbubble** [comment]
I'm returning to Spack and working from develop now, and it does look like the functionality we need is present now; but I'll let you know if I run into further trouble.

**Comment by alalazo** [comment]
Closing the PR as it seems it's not needed anymore. Feel free to rebase and reopen in case you think otherwise.

**Pull request closed without merging**
