### PR TITLE
Features/merged tcl modules

### PR DESCRIPTION
**Pull request by scheibelp**
@mamelara this can be used to create one module file per package (and more generally it is intended to be helpful for your use case at NERSC). I'm curious if you have feedback/questions. I'm also curious if the PE_PRODUCT_LIST variable at https://www.nersc.gov/assets/modulefile-example.txt is used to track modules for unloading when changing the compiler.

When multiple instances of a package are installed, this provides a ```merged_tcl``` command which creates a module file that can choose between those instances based on the value of an environment variable.

For a modules.yaml file with a TCL section like:

```
  tcl:
    merge:
        compiler:
            "%gcc@4.4.7": "gnu_447"
            "%gcc@4.8.5": "gnu_485"
```

If two instances of bzip are created with gcc 4.4.7 and 4.8.5, the command

```spack merged-tcl --output=testmodule bzip2```

will produce a module file like:

```
set compiler $env(compiler)

if { $compiler == "gnu_485" } {
	#do path modifications for spec which satisfies %gcc@4.8.5
}
elseif { $compiler == "gnu_447" } {
	#do path modifications for spec which satisfies %gcc@4.4.7
}
```

### CODE REVIEW

**Comment by mamelara** [comment]
Hi Peter.

Thanks for working on this. I'll check it out today and let you know about this. As for PE_PRODUCT_LIST, I'm not sure what we use that for. Seems we have a lot of cryptic variables in our module files :/

**Comment by mamelara** [comment]
@scheibelp Sorry it took me awhile to check this out. Got a chance to take a look at this and play around with it. Would it be difficult to have this automatically done after a compilation is finished? I think a lot of the consultants here would very much like it if they didn't have to run a command after an installation is finished. 

My guess is they will probably compile for gcc, intel and craype. So rather than have to run a command after compiling the same package with different compilers and PrgEnvs, it would be nice if Spack was able to look through the modules directory find the package name and then maybe create a new merged file while deleting the old one.

It looks good in generating the module file however, I found this bug while running ```module load testmodule``` after running your example above.

```testmodule(16):ERROR:102: Tcl command execution failed: set compiler $env(compiler)```

Am I suppose to use spack module for these? Again thanks so much for your help.

**Comment by scheibelp** [comment]
>after running your example above.
> ```testmodule(16):ERROR:102: Tcl command execution failed: set compiler $env(compiler)```
>Am I suppose to use spack module for these? Again thanks so much for your help.

I'm guessing this failed because there isn't an environment variable called "compiler" in your environment. I think you'd want the modules.yaml file to look like:

```
  tcl:
    merge:
        LCcompiler:
            "%gcc@4.4.7": "gnu_447"
            "%gcc@4.8.5": "gnu_485"
```

> Would it be difficult to have this automatically done after a compilation is finished?

That should be readily doable. I presume you'd also want to customize where these module files are placed (i.e. so they are placed in the correct location automatically). I think I'd have to add a bit for that but that should also be simple.

**Comment by alalazo** [comment]
@scheibelp I assigned this to myself just to have it pinned somewhere in my issues.

**Comment by alalazo** [comment]
@scheibelp @mamelara Is something like this still desirable? If so I can have a look how to implement it with the current template based system.

**Comment by mamelara** [comment]
I think so, we are still using our in-house modulefile generator for this.

**Comment by adamjstewart** [comment]
Is this PR still relevant or can it be closed?

**Comment by adamjstewart** [comment]
No response, so I'm assuming this PR is stale. Feel free to reopen if this feature is still desired.

**Pull request closed without merging**
