### PR TITLE
Don't prepend Tcl/Python to PATH if in system directory

### LINKED ISSUE #7676: Adding depends_on('tcl') with Tcl in packages.yaml causes /usr/bin to be at front (!) of PATH in install()
Adding `depends_on('tcl')` to a spec when Tcl is specified in `packages.yaml` as being in the system results in `/usr/bin` being put at the front of `PATH`, ahead of the compiler wrapper locations. 

### Steps to reproduce the issue

1. Apply the following patch to the `zlib` spec:
   ```patch
   diff --git a/var/spack/repos/builtin/packages/zlib/package.py b/var/spack/repos/builtin/packages/zlib/package.py
   index 7ff6a9a..a602018 100644
   --- a/var/spack/repos/builtin/packages/zlib/package.py
   +++ b/var/spack/repos/builtin/packages/zlib/package.py
   @@ -23,7 +23,7 @@
    # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
    ##############################################################################
    from spack import *
   -
   +import os
    
    # Although zlib comes with a configure script, it does not use Autotools
    # The AutotoolsPackage causes zlib to fail to build with PGI
   @@ -48,6 +48,9 @@ class Zlib(Package):
        variant('optimize', default=True,
                description='Enable -O2 for a more optimized lib')
 
   +    depends_on('tcl')
   +    print("PATH after depends_on() calls: {0}".format(os.environ['PATH']))
   +
        patch('w_patch.patch', when="@1.2.11%cce")
    
        @property
   @@ -64,6 +67,7 @@ class Zlib(Package):
                spack_env.append_flags('CFLAGS', '-O2')
    
        def install(self, spec, prefix):
   +        print("PATH on entry to install(): {0}".format(os.environ['PATH']))
            config_args = []
            if '~shared' in spec:
                config_args.append('--static')
   ```
1. Add the following clause to `etc/spack/packages.yaml`:     
   ```yaml
     tcl:
       paths:
         tcl@8.5.13 arch=linux-rhel7-x86_64: /usr
   ```
1. Attempt to build `zlib`
   ```
   spack install zlib
   ```
1. Look at the output and in `<install-dir>/.spack.build.out` for `PATH` diagnostic printouts.

### Root cause.

https://github.com/spack/spack/blob/a63450bc4537f8db04530d0dacdc98babbdd38f2/var/spack/repos/builtin/packages/tcl/package.py#L105

### Information on your system

SLF7, Spack from `develop@6a0f9ccf8`.

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #7676.

@chissg can you test this?

### CODE REVIEW

**Comment by chissg** [comment]
Appears to solve the problem, thank you.

**Comment by tgamblin** [comment]
Question: we use the `EnvironmentModifications` objects for this stuff, why not move the check there so that all the different parts of spack will filter system paths?  Seems like a better long-term fix, but it would require more thought about what it could potentially affect.

**Comment by adamjstewart** [comment]
I agree, that would be a good way to do it. I like @chissg's suggestion as well; `/`, `/usr`, and `/usr/local` may not be the only directories containing multiple installations, it would be good to be able to add to the list of filtered directories via `config.yaml` or `packages.yaml`. Ideally, we would prepend all non-system paths and add any system paths to the end of the PATH if they aren't already in the PATH.

**Comment by chissg** [comment]
If I had my druthers, (and a pony) I would add to the end of the spack-added part of `PATH` rather than the end proper: it's conceivable that some things may be in `packages.yaml` that are installed in a system area that is not in the user's `PATH` already: it would need to be ahead of the user's `PATH`, but behind anything else the user added. Note that this protection should be utilized in `depends_on()` as well as available to call from spec code. If we were being _really_ careful we'd make sure that any system areas we add to `PATH` preserve the ordering if they're already in `PATH`. As you are undoubtedly already aware, it's a tricky thing to divine what might be the "correct" thing to do.

**Pull request merged**
