### PR TITLE
Fastx-toolkit: Specified the scope of pragma pack

### PR DESCRIPTION
**Pull request by noguchi-k**
I specified the scope of pragma pack because the following error occurred.
`error: the current #pragma pack aligment value is modified in the included file [-Werror,-Wpragma-pack]`

### CODE REVIEW

**Comment by scheibelp** [comment]
Do you think this only happens on a specific compiler/architecture?

**Comment by noguchi-k** [comment]
An error occurred in the Fujitsu Compiler.
However, this error didn't occur in the gcc.
So I think it will be different for each compiler.

**Comment by scheibelp** [comment]
OK: in that case could you restrict the patch to only apply for the Fujitsu Compiler?

For example:

`patch('fix_pragma_pack.patch', when='%fj')`

**Comment by noguchi-k** [comment]
OK. I restricted the patch to only apply for the Fujitsu Compiler.

**Comment by scheibelp** [comment]
Thanks!

**Pull request merged**
