### PR TITLE
precice: add version 1.5.0

### PR DESCRIPTION
**Pull request by fsimonis**
Add new version of preCICE.

### CODE REVIEW

**Comment by citibeth** [comment]
@scheibelp @tgamblin This is "failing" coverage checks, even though it's just a single new version being added.  How do I merge it anyway?

**Comment by scheibelp** [comment]
> This is "failing" coverage checks, even though it's just a single new version being added. How do I merge it anyway?

From what the UI is telling me the unit tests are failing. I don't think that's on account of this PR though: occasionally they will time out. Can you see the test report in the UI? It should give you an option to restart the tests. I've already done that a couple times though and it's being stubborn so I'm going to restart the whole process by closing and reopening.

**Comment by citibeth** [comment]
This failed CI tests again.  Still can't merge! :(

**Comment by adamjstewart** [comment]
I restarted the failing tests.

**Pull request merged**
