### PR TITLE
Check minimum required Python version with an external tool

### PR DESCRIPTION
**Pull request by alalazo**
refers to #13485

This commit removes the `python_version.py` unit test module and the vendored dependencies `pyqver2.py` and `pyqver3.py`. It substitutes them with an equivalent check done using `vermin` that is run as a separate workflow via Github Actions. Rationale is to remove 2 vendored and unmaintained dependencies and use instead a maintained tool.

Vermin is currently run with Python 2 because of https://github.com/netromdk/vermin/issues/32

### CODE REVIEW

**Comment by adamjstewart** [comment]
Don't forget to update `lib/spack/external/__init__.py` if you're removing a vendored dep.

**Comment by alalazo** [comment]
@adamjstewart Done

**Comment by tgamblin** [comment]
Does it catch empty format strings?  We had to modify pyqver to do this:

```
“Foo {} baz”.format(“bar”)  # requires 2.7+
```

**Comment by alalazo** [comment]
@tgamblin It seems so:
```console
$ cat format_str.py
"Foo {} baz".format("bar") 

$ vermin -vvv format_str.py
Detecting python files..
Analyzing using 4 processes..
2.7, 3.0     /home/culpo/tmp/vermin/format_str.py
  L1: 'str.format' requires 2.6, 3.0
  L1: `"..{}..".format(..)` requires (2.7, 3.0)

Minimum required versions: 2.7, 3.0
```
More than that the project is maintained, so we can eventually submit issues or PRs and get responses from maintainer.

**Pull request merged**
