### PR TITLE
Language-specific PIC flags

### LINKED ISSUE #15445: NAG/GNU mixed toolchain problem
I have set up a NAG/GNU mixed compiler tool-chain according to the [documentation](https://spack.readthedocs.io/en/latest/getting_started.html#nag). When I try to build a simple package, I get an error. It turns out, that configure fails, since instead of `-fPIC` the `-PIC` flag is passed to the C-compiler.  Apparently the `-PIC` flag is defined in the `nag.py` compiler definition file, which is OK for the NAG Fortran compiler, but not for the GNU C-compiler.

### Spack version
```console
$ spack --version
0.14.0
```

### Steps to reproduce the issue

```console
spack install zlib %nag@7.0
```

The NAG compiler had been added by adding the following lines to the `compilers.yaml` configuration file:
```yaml
- compiler:
    spec: nag@7.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /opt/nag/7.0/bin/nagfor
      fc: /opt/nag/7.0/bin/nagfor
    flags:
        fflags: -dusty -dcfuns -mismatch_all
    operating_system: centos8
    target: x86_64
    modules: [nagfor/7.0]
    environment: {}
    extra_rpaths: []
```

### Error Message
The `configure.log` file of the zlib-build contains the following error message:
```
Checking for obsessive-compulsive compiler options...                          
=== ztest15505.c ===
int foo() { return 0; }
===
/home/packager/spack/spack-packages/lib/spack/env/cc -c -PIC -O2 ztest15505.c  
gcc: error: unrecognized command line option '-PIC'; did you mean '-fPIC'?     
(exit code 1)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```

### PR DESCRIPTION
**Pull request by adamjstewart**
#2375 added compiler-specific PIC flags.

This PR adds language-specific PIC flags.

Fixes #15445

@aradi can you test this?

### CODE REVIEW

**Comment by aradi** [comment]
The patch solves the compiler dependent `pic` flag problem. However, compilation still fails since zlib is linked with the C-compiler (gcc), but gets flags passed (`-Wl,-Wl,,`) which are meant for the cases, where the NAG Fortran compiler is used for the linking. So, maybe we would need  a similar language dependent separation also for the linker flag?

**Comment by adamjstewart** [comment]
@aradi good point, let me open up a separate PR to address that.

**Comment by adamjstewart** [comment]
@alalazo it looks like you added the `linker_arg` logic in #9168. When does this arg get used? Maybe we don't even need a special `linker_arg` for NAG if it's only used by the linker, not the compiler.

**Comment by alalazo** [comment]
Not sure this is the right direction to go. Do I understand correctly that this works just because `nag` overrides only the Fortran compilers and uses the defaults for C and C++? What if I use a C compiler that doesn't support `-fPIC`, would that work?

**Comment by adamjstewart** [comment]
You are correct, that’s how we’ve handled all language-specific flags in the past. We do this for NAG and Clang (assume GCC is the other half of the compiler).

**Comment by adamjstewart** [comment]
From what I can tell, #15443 is a step in the right direction, but better mixed compiler support is still a long way off. Without this PR, NAG users can't build _anything_ right now, due to both the `self.compiler.pic_flag` and `self.compiler.linker_arg` usage.

**Comment by adamjstewart** [comment]
> @alalazo it looks like you added the `linker_arg` logic in #9168. When does this arg get used? Maybe we don't even need a special `linker_arg` for NAG if it's only used by the linker, not the compiler.

Ping @alalazo

**Comment by adamjstewart** [comment]
Ping ping @alalazo

**Comment by adamjstewart** [comment]
Ping x4 @alalazo @tgamblin

**Comment by alalazo** [comment]
@adamjstewart I put this in the 0.15.0 dashboard (and not 0.14.X) since I think it needs some discussions on the opportunity to merge a workaround that is fairly large and we know it needs to be undone in the mid-long term (because of the reworking of compilers).

If it was a 10 lines change I would merge it straight away, likewise if it was a more permanent fix without its own issues. In this case I think more discussion is needed as we are dealing with something sizeable and that comes with known limitations.

**Comment by adamjstewart** [comment]
I agree that more discussion is welcome (thanks for pinging more reviewers). The long and short of it is that it is currently impossible to use the NAG compiler with Spack because:

1. Any package that uses `self.compiler.pic_flag` for C/C++ code is broken, and
2. Any package that uses `self.compiler.linker_arg` (which I think is all packages??) is broken

I would hate to see the NAG compiler go unsupported for months while we wait for 0.15.0, although I'm fine with reaching a consensus on this PR and merging it into develop in the meantime. Also see #15445 and #15776 for more discussion.

Adding @ThemosTsikas to the discussion as our official NAG representative.

**Comment by tgamblin** [comment]
@alalazo: if you're ok with the above, then I am fine with this.  Do you have other objections?

**Comment by adamjstewart** [comment]
I think the only thing left we need to decide (either in this PR or a separate PR) is what to do about the `linker_arg` issue:

> @alalazo it looks like you added the linker_arg logic in #9168. When does this arg get used? Maybe we don't even need a special linker_arg for NAG if it's only used by the linker, not the compiler.

**Comment by alalazo** [comment]
@adamjstewart I'll have a look at `linker_arg` tomorrow and post here.

**Comment by adamjstewart** [comment]
Since this affects a lot of packages, and users may submit PRs that use the removed `self.compiler.pic_flag` in the meantime, I'm going to merge this. @alalazo let me know if you figure out what to do about `self.compiler.linker_arg` and one of us can address that in a follow-up PR. Then we'll have full NAG support again.

**Pull request merged**
