### PR TITLE
kealib: fix incorrect md5sum for v1.4.11

### PR DESCRIPTION
**Pull request by Sinan81**
fix incorrect md5sum for version 1.4.11

### CODE REVIEW

**Comment by adamjstewart** [comment]
@gillins do you have any idea why the checksum for this release has changed? Was it re-released with a bug fix?

Also, @gillins would you be interested in becoming a "maintainer" of this package? There's not a lot of responsibility involved. Basically, if someone reports a problem using Spack to install `kealib`, or someone makes a drastic change to the package, we would ping you for feedback.

**Comment by gillins** [comment]
Is spack downloading the tar.gz from https://bitbucket.org/chchrsc/kealib/downloads/? If so, the md5 hasn't changed (still `90f581c794bb7c7e6d76b0ad29f0ca40`) - I just downloaded it again, plus checked the original on my PC. I didn't re-release it (well as far as I can remember, nothing obvious in the commits).

Yep happy to be a maintainer (but don't know much about spack). 

ping @neilflood

**Comment by neilflood** [comment]
Sorry, I noticed this problem recently, and have been meaning to fix it. The original kealib package.py used the bitbucket /get/ URL, which generates the tar.gz from the repo, instead of using the tar.gz files already uploaded in the /downloads/ area. 

I think that I had added that last checksum, which I calculated on the tar.gz I had downloaded and used for testing, so it worked fine for me. However, it later arose that the checksum was not matching the URL method used to fetch it. 

I am not sure of Spack's conventions, but my preference would be for the URL to be changed to the /download/ one, and all the existing checksums changed. It seems to me that such checksums are more likely to be stable over time. 

Very happy to have Sam on board for kealib, thank you. :-)

**Comment by adamjstewart** [comment]
I'm fine with switching to the more stable download URL.

You can add the following to the package too:
```python
maintainers = ['gillins']
```
@neilflood let me know if you also want to be a maintainers. I've been trying to push for more maintainers lately.

**Comment by neilflood** [comment]
giggle... I know a little more about Spack, but less about kealib. Between us, we might add up to one whole maintainer. 

Should we make all those changes as a separate PR and ask that @Sinan81 abandon this one?

**Comment by adamjstewart** [comment]
If @Sinan81 responds, all of these changes can be made in this PR. If not, we can make a separate PR. No rush.

**Comment by neilflood** [comment]
OK, sounds good. 

@Sinan81 if you are happy to run with this, the correct URL should be
    https://bitbucket.org/chchrsc/kealib/downloads/kealib-1.4.11.tar.gz

and then change the md5 sums for all the previous versions.

**Comment by adamjstewart** [comment]
Might as well switch to `sha256` while you're at it. You can run `spack checksum` with the new URL in place to automate all of this.

**Comment by Sinan81** [comment]
will do by end of today, Thanks

**Comment by Sinan81** [comment]
actually, just did the modifications.

**Pull request merged**
