### PR TITLE
Added python-editor package, a dependency of py-alembic

### PR DESCRIPTION
**Pull request by wspear**

### CODE REVIEW

**Comment by alalazo** [comment]
Ouch! I already merged the fix on `py-alembic`. For the next PRs could you either:
1. State in a PR that it depends on another
2. Make a unique PR that is self-consistent

?

**Comment by wspear** [comment]
> Ouch! I already merged the fix on `py-alembic`. For the next PRs could you either:
> 
> 1. State in a PR that it depends on another
> 2. Make a unique PR that is self-consistent
> 
> ?

Will do. Also: The error output looks like timeouts to me and I didn't have any trouble installing this earlier. I'm not seeing anything to fix in the package. Can we have it rerun the check?

**Comment by alalazo** [comment]
I already tried re-running Travis, and it always hangs on Python 2.X Re-started again and :crossed_fingers: but if it hangs again in the same workers we should probably have a closer look at what happens and if this is a spurious failure.

**Comment by wspear** [comment]
There's not much to this package. Any thoughts on how to debug? I'm not sure what Travis is doing under the hood. I see that it's trying and timing out with tests for python@2.6 when the package won't even begin to install unless it has python@2.7: because of the py-setuptools dependency. I tried installing with the exact version of python (2.7.15) that has it timing out but that worked for me.

**Comment by wspear** [comment]
The string '$EDITOR' in the package description prevented the module from loading. ... But fixing that doesn't seem to have fixed the CI check. Not sure what else to test now...

**Comment by wspear** [comment]
Is it safe/reasonable to push a merge from develop into this branch? In case there was some temporary breakage when I branched this that has since been fixed?

**Comment by wspear** [comment]
Fixed! In addition to the $STRING the ’ character was also fatal.

**Pull request merged**
