### PR TITLE
Add --term/termprint option to spack graph.

### PR DESCRIPTION
**Pull request by kisaacs**
These options use an alternate layout for ASCII node-link diagrams. The --term
option provides interactive selection through curses. The --termprint option
directs a static depiction to stdout.

interactive-ascii-graph-python
ascii-graph-ferret

### CODE REVIEW

**Comment by healther** [comment]
spack could get the dependencies via `spack bootstrap`

**Comment by adamjstewart** [comment]
@alalazo @tgamblin is this a feature we still want, or is it too much effort to add a new vendored dependency to be worth it?

**Comment by adamjstewart** [comment]
@kisaacs what if we remove the vendored dependency and only enable this feature when `graphterm` is installed?

**Comment by alalazo** [comment]
Closing, but we can find this PR by the `revisit` tag in case we want to resurrect it.

**Pull request closed without merging**
