### PR TITLE
Add option to build either w/ RPATH or RUNPATH

### PR DESCRIPTION
**Pull request by hegner**
As discussed in #639 this PR adds an option whether to use RPATH or RUNPATH.
Please note that this PR sits on top of PR #908, so that would need to be accepted first.

### CODE REVIEW

**Comment by alalazo** [comment]
@hegner This is almost one year and a half old, and it has a number of conflicts I have never seen in any other PR :smile: Are you still maintaining this? 

@tgamblin @scheibelp @davydden @adamjstewart Is this even a feature we want?

**Comment by adamjstewart** [comment]
I think this would be a good feature to have. I've talked to people who loved the idea of Spack, but the use of RPATH was a dealbreaker for them.

**Comment by tgamblin** [comment]
@alalazo @adamjstewart: I've been remiss in not getting this merged.  It's an easy enough feature to add -- I want to get this in before SC.

**Comment by alalazo** [comment]
@tgamblin ping

**Comment by becker33** [comment]
This is superseded by #9168. Closing this as out-of-date, I think it will be easier to work from #9168.

**Pull request closed without merging**
