### PR TITLE
RHEL8 bugfix for module_cmd

### PR DESCRIPTION
**Pull request by s-sajid-ali**
Similar to https://github.com/spack/spack/pull/14252

### CODE REVIEW

**Comment by s-sajid-ali** [comment]
Would it be a good idea to have a PR that modifies either the `github-actions` or `travis-CI` pipelines to run the entire test suite on `centOS8/rhel8` docker image before the `0.14` release ?

I'm not too familiar with spack util so I don't know if there exit many instances where an assumption about the existence of `/bin/bash/python` is made.

**Comment by adamjstewart** [comment]
@s-sajid-ali that's not a bad idea. I think Travis CI only offers Ubuntu, and I'm not sure about GitHub Actions. You could run `spack test` yourself and report back on which tests fail on your machine.

**Comment by s-sajid-ali** [comment]
I ran the tests on a `centOS-8` workstation and [here are the results](https://pastebin.com/i60n9e2Q). I don't see any more errors due to `/bin/bash/python` assumptions (after this merge) so there is no need to run this test on either of the CI pipelines.

PS : `github-actions` only supports `ubuntu` as per [the documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by adamjstewart** [comment]
I would open a separate issue for that `test_nosource_pkg_install` failure.

**Comment by tldahlgren** [comment]
@s-sajid-ali Does this test still fail for you using the new merged develop?

**Comment by s-sajid-ali** [comment]
@tldahlgren : I added my results for the specific subtests on the issue. If either of you can tell me which commit was supposed to fix this, I can run the tests before and after the commit.

**Pull request merged**
