### PR TITLE
Document suite-sparse GCC version requirement

### LINKED ISSUE #7610: Installation of package suite-sparse fail.
Installation of package suite-sparse fail.

It seems that package suite-sparse do not mention a dependance to gcc version 4.9 or greater.
See : [suite-sparse/package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/suite-sparse/package.py#L47)
### Expected Result

```
spack install suite-sparse
```
Correct install.

### Actual Result
Suite-sparse installation fail with this message : 
```
1 error found in build log:
[...]
  >> 38    CMake Error at CMakeLists.txt:65 (message):
     39      gcc version must be at least 4.9
```

Complet log here :  
[spack-suite-sparse.log](https://github.com/spack/spack/files/1852009/spack-suite-sparse.log)

### Steps to reproduce the issue

```console
cd spack
git pull
spack install suite-sparse
```

### Information on your system

```
benjamin@nebulja:~/Codes/Spack $ uname -a
Linux nebulja 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
benjamin@nebulja:~/Codes/Spack $ spack arch
linux-ubuntu14.04-x86_64
benjamin@nebulja:~/Codes/Spack $ spack compilers 
==> Available compilers
-- gcc ubuntu14.04-x86_64 ---------------------------------------
gcc@4.8
```

[packages.yaml](https://github.com/spack/spack/files/1852030/packages.yaml.txt)
[compilers.yaml](https://github.com/spack/spack/files/1852032/compilers.yaml.txt)
(renamed because github won't me upload something else than .txt)

Also, I use an other personal spack repo, but I don't think this is correlated.
Because this repo only build something on top of suite-sparse.

Feel free to ask for anything I omitted.

Regards,
Benjamin

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #7610. @Oximore

### CODE REVIEW

**Comment by adamjstewart** [comment]
P.S. No idea if this version constraint affects older versions of GCC or not. I suspect someone will try to build `suite-sparse` tomorrow with their system GCC and be very disappointed. If someone can point me to more specific GCC requirements per version, that would be helpful.

**Comment by Oximore** [comment]
@adamjstewart The initial error come from :  

[GraphBLAS/CMakeList.txt : l.58-80](https://github.com/sergiud/SuiteSparse/blob/master/GraphBLAS/CMakeLists.txt#L58)
```
# check which compiler is being used.  If you need to make
# compiler-specific modifications, here is the place to do it.
if ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
    # cmake 2.8 workaround: gcc needs to be told to do ANSI C11.
    # cmake 3.0 doesn't have this problem.
    set (CMAKE_C_FLAGS  "-std=c11 -lm -fopenmp")
    if (CMAKE_C_COMPILER_VERSION VERSION_LESS 4.9)
        message (FATAL_ERROR "gcc version must be at least 4.9")
    endif ( )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "Intel")
    # options for icc: also needs -std=c11
    set (CMAKE_C_FLAGS  "-std=c11 -fopenmp")
    if (CMAKE_C_COMPILER_VERSION VERSION_LESS 18.0)
        message (FATAL_ERROR "icc version must be at least 18.0")
    endif ( )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang")
    # options for clang
    if (CMAKE_C_COMPILER_VERSION VERSION_LESS 3.3)
        message (FATAL_ERROR "clang version must be at least 3.3")
    endif ( )
elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
    # options for MicroSoft Visual Studio
endif ( )
```

Hope it help you.

**Comment by adamjstewart** [comment]
@davydden SuiteSparse 5.1.0 has the same constraint in `GraphBLAS/CMakeLists.txt`. It also says "icc version must be at least 18.0" which seems pretty strict. Is GraphBLAS an optional component that only some of you are building?

**Comment by davydden** [comment]
> Is GraphBLAS an optional component that only some of you are building?

maybe it was turned `off` by default in `5.1.0` and it is `on` since `5.2.0`?

**Comment by davydden** [comment]
p.s. `suite-sparse` in spack does not have any special options and since `5.1.0` builds with older compilers (for whatever reason) we should keep it this way. On a personal note, our HPC cluster is very concervative in compiler versions, I don't even have a choice of externally provided `openmpi` built with more recent `gcc` ;-(

**Comment by davydden** [comment]
> can you try building 5.2.0 and see if it works for you?

our sysadmin at the chair had this issue today, on `ubuntu14.04` with `gcc@4.8`. I advised him to choose `suite-sparse@5.1.0` and it worked as expected.

**Comment by davydden** [comment]
@Oximore can you confirm that `5.1.0` works for you also?

**Comment by Oximore** [comment]
@adamjstewart 
@davydden 
Yes, suite-sparse@5.1.0 works fine for me.
And use it is my solution to this problem.

On my local computer I always can try to install a new compiler.
But as our code run on HPC platforms we can't afford to have a gcc 4.9 dependency.
As a work around I fixed a dependency to suite-sparse@5.1.0 

I am now a little sceptical about this patch, because it forbids construction of suite-sparse with gcc 4.9 even if suite-sparse version is 5.1.0

**Comment by davydden** [comment]
> I am now a little sceptical about this patch, because it forbids construction of suite-sparse with gcc 4.9 even if suite-sparse version is 5.1.0

Exactly my point, this would break my packages on HPC

**Comment by adamjstewart** [comment]
I agree, this shouldn't be merged until we figure out why 5.2.0 is enforcing these constraints but older versions are not. There may be some way to avoid building GraphBLAS in 5.2.0.

**Pull request closed without merging**
