### PR TITLE
Buildache install fix: replace placeholder and origin install paths in rpath when relocating binaries 

### PR DESCRIPTION
**Pull request by gartung**
This fixes a problem where the placeholder path was not in the first rpath entry. This was seen in c++ libraries and binaries because the compiler was outside the spack install base path and always appears first in the rpath. 

Instead of checking the first rpath entry, all rpaths have the placeholder path and the old install path (if it exists)  replaced with the new install path.  

The second commit changes the check for old install path strings by using the install prefix instead of the install root.

### CODE REVIEW

**Comment by gartung** [comment]
@tgamblin

**Comment by gartung** [comment]
Pending merge of 
https://github.com/spack/spack/pull/10073

**Comment by gartung** [comment]
@tgamblin

**Comment by gartung** [comment]
@tgamblin the code coverage report link times out. How can I reproduce this on my machine?

**Comment by tgamblin** [comment]
@gartung: codecov seems to be having issues.  I pushed a commit to see whether it'll work if we generate fewer reports (they seem to crash on merging lots of reports for PRs).

If you do want to run this locally, you can do this (from the spack root).  You'll need the Python `coverage` tool installed.

```python
coverage run spack test
coverage combine
coverage html
```

Might need some options on the above, but that is the gist of it.  You should get a directory with a local HTML coverage view if you're successful.  Also, if you want to zoom in on one part, you can run, e.g.: `coverage run spack test packaging` to focus on the biuldcache stuff.

**Comment by gartung** [comment]
I would like to cherry-pick the changes from #9199 #9440 #9600 #10274 that involve the buildcache command and put them in this PR. I will try to resolve merge conflicts.

**Comment by gartung** [comment]
Close for now so every commit os not tested.

**Comment by gartung** [comment]
Re-open for comments.

**Comment by gartung** [comment]
This error was produced when trying to create a buildcache for gcc@7.3.0 that was linked against system zlib which has an entry for a version 1.2.7 that does not exists in the zlib package.py. The real cause of the error is in spec.full_hash().

```
  zlib:
    paths:
      zlib@1.2.7+optimize+pic+shared arch=linux-rhel7-x86_64: /usr
```

```
==> [2019-02-27-20:52:54.622705] Warning: Missing a source id for zlib@1.2.7
Traceback (most recent call last):
  File "/build/work/spack-tools/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/build/work/spack-tools/spack/lib/spack/spack/main.py", line 675, in main
    return _invoke_command(command, parser, args, unknown)
  File "/build/work/spack-tools/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/build/work/spack-tools/spack/lib/spack/spack/cmd/buildcache.py", line 528, in buildcache
    args.func(args)
  File "/build/work/spack-tools/spack/lib/spack/spack/cmd/buildcache.py", line 326, in createtarball
    not args.no_rebuild_index)
  File "/build/work/spack-tools/spack/lib/spack/spack/binary_distribution.py", line 363, in build_tarball
    spec_dict['full_hash'] = spec.full_hash()
  File "/build/work/spack-tools/spack/lib/spack/spack/spec.py", line 1306, in full_hash
    package_hash = self.package.content_hash()
  File "/build/work/spack-tools/spack/lib/spack/spack/package.py", line 1092, in content_hash
    for p in self.spec.patches)
  File "/build/work/spack-tools/spack/lib/spack/llnl/util/lang.py", line 183, in __call__
    self.cache[args] = self.func(*args)
  File "/build/work/spack-tools/spack/lib/spack/spack/spec.py", line 2690, in patches
    for sha256 in self.variants['patches']._patches_in_order_of_appearance:
AttributeError: 'MultiValuedVariant' object has no attribute '_patches_in_order_of_appearance'
```

**Comment by gartung** [comment]
@tgamblin  The patch coverage is at 62%. Is this OK to merge?

**Comment by scheibelp** [comment]
Either myself or @tgamblin can look at this by tomorrow

**Comment by gartung** [comment]
Note that I merged in pr #9199

**Comment by gartung** [comment]
With #9199 I am able to drop the whole replace rpaths with placeholders and check for install prefix strings in favor of @alalazo 's file_is_relocatable.

**Comment by gartung** [comment]
I did 'git push origin :branch' instead of 'git push origin +branch'.
I will have to resubmit but first #9199 needs to be merged.

**Comment by scheibelp** [comment]
> I will have to resubmit but first #9199 needs to be merged.

OK I will look at that, and check this out later today.

**Pull request closed without merging**
