### PR TITLE
Generic x86_64 code compiled with GCC uses non deprecated mtune flags

### LINKED ISSUE #12928: Build error: cmake
cmake errors even with cxxflags set (spack compiled gcc@9.2.0)

`spack install cmake cxxflags="-std=c++11"`

---

### Steps to reproduce the issue

```console
spack install cmake cxxflags="-std=c++11"

2 errors found in build log:
     454    -- Checking if compiler supports needed C++17 constructs
     455    -- Checking if compiler supports needed C++17 constructs - yes
     456    -- Checking if compiler supports C++ make_unique
     457    -- Checking if compiler supports C++ make_unique - no
     458    -- Checking if compiler supports C++ unique_ptr

  >> 474    CMake Error at CMakeLists.txt:92 (message):
     475      The C++ compiler does not support C++11 (e.g.  std::unique_ptr).
```

### Platform and user environment

```commandline
$ uname -a 
Linux edi 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

centOS 7.7
``` 

### Additional information

Possibly related https://github.com/spack/spack/issues/11223

### PR DESCRIPTION
**Pull request by alalazo**
fixes #12928

### CODE REVIEW

**Comment by alalazo** [comment]
@matz-e @pat-s

**Comment by alalazo** [comment]
This lets me build `cmake` with `target=x86_64`. If anybody else confirms I'll merge the PR.

**Comment by matz-e** [comment]
> This lets me build `cmake` with `target=x86_64`. If anybody else confirms I'll merge the PR.

Same here. Thank you!

**Comment by alalazo** [comment]
@tgamblin @becker33 Pinging you as I'm about to merge this PR of mine to solve #12928 quickly

**Pull request merged**
