### PR TITLE
Add new version of libunwind

### PR DESCRIPTION
**Pull request by iarspider**

### CODE REVIEW

**Comment by iarspider** [comment]
Pinging @mwkrentel based on his [comments](https://github.com/spack/spack/pull/14570#discussion_r370306316) in #14570

**Comment by mwkrentel** [comment]
Could you do me a favor and add a version for `1.4-rc1` and also keep
`2018.10.12` for now.  That would make my transition smoother.
Keep `1.3.1` preferred.

The way libunwind make their branches, `1.4-rc1` is actually a much
better replacement for `2018.10.12` than is `1.3.1`.  1.3.1 is
actually a bit old because it was split from master in Nov 2017, and
thus is missing a full year's worth of patches and bug fixes compared
to 2018.

Also, abruptly deleting `2018.10.12` will break my other package
(hpctoolkit).  It's smoother if both exist for 1-2 weeks while I
switch over and then I'll delete 2018.

Thanks

**Comment by adamjstewart** [comment]
@mwkrentel if this package is so important to your workflow, would you be interested in adding yourself as a maintainer? Then we could contact you for issues/PRs related to this package.

**Comment by mwkrentel** [comment]
@adamjstewart  Sure.  My plan was to get this PR in now, at least with
2018.10.12 in and preferably also with 1.4-rc1.  Then I can update
hpctoolkit smoothly.

Then I'll delete 2018.10.12, switch to 1.4-rc1, and add myself as
maintainer.  (Also, develop/master needs a small amount of work too.)

**Comment by mwkrentel** [comment]
LGTM, Thanks!

**Pull request merged**
