### PR TITLE
Fix bug where patches specified by dependents were not applied

### PR DESCRIPTION
**Pull request by scheibelp**
Fixes https://github.com/spack/spack/issues/7885

https://github.com/spack/spack/pull/7193 added the `patches_to_apply` function to collect patches which are then applied in `Package.do_patch`. However this only collects patches that are associated with the `Package` object and does not include `Spec`-related patches (which are applied by dependents, added in https://github.com/spack/spack/pull/5476). ~This updates the `Package.patches_to_apply` function to add `Spec` patches.~

EDIT: turns out `Spec.patches` already collects patches from the package so the `Package.patches_to_apply` function isn't necessary. All uses of `Package.patches_to_apply` are replaced with `Package.spec.patches`.

### CODE REVIEW

**Comment by scheibelp** [comment]
Note: this was not detected because unit tests access dependency patches in the spec (which works) but do not check the collection of patches in `do_patch` (which does not work).

**Comment by scheibelp** [comment]
As a consequence of swapping to using `Spec.patches`, `Package.do_patch` now uses the same code path to retrieve patches as the patch tests. Arguably adding a test to check that patches have been applied would still be useful.

**Comment by adamjstewart** [comment]
Was just hit by this in #8207/#8263. GDAL requires a hacked version of JasPer, but the patch wasn't being applied.

**Comment by aprokop** [comment]
This works (checked with `flang`).

**Comment by junghans** [comment]
@scheibelp: why didn't the test catch that problem?

**Comment by adamjstewart** [comment]
> turns out `Spec.patches` already collects patches from the package so the `Package.patches_to_apply` function isn't necessary. All uses of `Package.patches_to_apply` are replaced with `Package.spec.patches`.

The only thing to be careful of is that `patches_to_apply` returns the patches in the correct order. You'll want to make sure that `spec.patches` does the same. See #7558 for details. This function was introduced in #7193 but I don't know the internals well enough to understand why it was necessary.

**Comment by junghans** [comment]
@scheibelp can we merge this some when soon?

**Comment by scheibelp** [comment]
> The only thing to be careful of is that patches_to_apply returns the patches in the correct order. You'll want to make sure that spec.patches does the same. See #7558 for details. This function was introduced in #7193 but I don't know the internals well enough to understand why it was necessary.

This doesn't actually change anything about the consistency of patch ordering: You are right that #7193 did enforce an order, but that part was reverted in https://github.com/spack/spack/pull/7558. Patch order is still arbitrary and it remains as unfinished business to enforce the patch declaration order as the consistent ordering - see: https://github.com/spack/spack/pull/7193#pullrequestreview-106123876

**Comment by adamjstewart** [comment]
I wouldn't say the order is arbitrary, my understanding is that the order is that of the patches in the `package.py`, which seems intuitive. I just want to make sure this behavior is preserved.

**Comment by scheibelp** [comment]
> my understanding is that the order is that of the patches in the package.py

I think that is agreed upon as what we want to guarantee, but we do not guarantee it right now: Patch ordering has not changed since https://github.com/spack/spack/pull/7193#discussion_r176448831 which mentions:

> Before this PR we were granted that patch3 would be applied after patch1, but we had no guarantee on the order of application for patch2 with respect to the other two. After this PR we are granted that we apply patches sorted by their path or urls. I think both strategies are wrong and we should apply patches in the order they are declared, if they match the constraint.

That being said, `Spec.patches` is constructed with `Package` class patches using the same logic as `Package.patches_to_apply`. This may seem like duplication of effort, which it is: #7193 was started before merging #5476. In the future, when enforcing the agreed-upon patch order, it will be a matter of modifying the logic which creates `Spec.patches`.

**Comment by aprokop** [comment]
Can this be merged? Or are there remaining issues to be addressed?

**Comment by aprokop** [comment]
Thanks!

**Pull request merged**
