### PR TITLE
Fix outdated bash tab completion

### PR DESCRIPTION
**Pull request by adamjstewart**
@tgamblin I'm not sure how much longer I can keep doing this. How much work would it be to make a bot that pops up on a PR and says "don't forget to update the tab completion script!" every time someone edits a file in `lib/spack/spack/cmd`?

@JBlaschke please use this version when you start working on your fish tab completion script.

### CODE REVIEW

**Comment by tgamblin** [comment]
@adamjstewart: is it worth auto-generating this?  I am not sure where you started with the bash completion but would looking at `spack commands --format rst` help?  It already auto-generates [this page](https://spack.readthedocs.io/en/latest/command_index.html), which I believe has everything you need.

**Comment by tgamblin** [comment]
@adamjstewart: note also that the hard part (mining the `argparse` data structures for all the options) is already done in `llnl.util.argparsewriter`, so you could just recycle that.  `cmd/commands.py` should show you how to use it.

**Comment by tgamblin** [comment]
Ok @adamjstewart @JBlaschke: I made you a skeleton completion generator in #14393.  See what you think -- I think it should help keep this stuff up to date.

**Comment by tgamblin** [comment]
Also this was simpler to write than a bot that comments on PRs 😄

**Comment by JBlaschke** [comment]
@adamjstewart thanks! I will spend some time on this, and @tgamblin 's generator script later this week.

**Comment by adamjstewart** [comment]
Merging this until I get a chance to work on #14393.

**Pull request merged**
