### PR TITLE
expect: fix darwin install name

### PR DESCRIPTION
**Pull request by adamjstewart**
### Before

```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib:
	libexpect5.45.dylib (compatibility version 5.45.0, current version 5.45.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect:
	libexpect5.45.dylib (compatibility version 5.45.0, current version 5.45.0)
	/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/tcl-8.6.8-zspmkfnhk7tfd2gqruab2qj5rvjqaii7/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

### After

```console
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/libexpect5.45.dylib:
	/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/expect5.45/libexpect5.45.dylib (compatibility version 5.45.0, current version 5.45.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
$ otool -L /Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect 
/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/bin/expect:
	/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/expect-5.45-w4kvty4l6eemafjlslp7t53am5o3ob4c/lib/expect5.45/libexpect5.45.dylib (compatibility version 5.45.0, current version 5.45.0)
	/Users/Adam/spack/opt/spack/darwin-mojave-ivybridge/clang-11.0.0-apple/tcl-8.6.8-zspmkfnhk7tfd2gqruab2qj5rvjqaii7/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

### CODE REVIEW

**Comment by gartung** [comment]
https://github.com/spack/spack/blob/141a1648e682bebff3c705f8b60678c00fa2ff11/lib/spack/llnl/util/filesystem.py#L914

**Comment by gartung** [comment]
@adamjstewart You can also make use of the macholib external that I added recently to find all mach-o binaries and fix paths with that. I recommend looking at this example
https://programtalk.com/python-examples/PyInstaller.lib.macholib.MachO.MachO/

**Comment by adamjstewart** [comment]
Thanks @gartung, I think I'll leave a more general solution to you and just hardcode a single call to `install_name_tool` in this package. I'm not sure how prevalent this problem is, but maybe we should always run `fix_darwin_install_name` recursively from the prefix for all macOS installations.

**Comment by adamjstewart** [comment]
Okay, I manually hacked the binary. This should be safe to merge until we come up with a more general solution.

**Comment by gartung** [comment]
python -mmacholib find $PREFIX
will find all mach-o binaries in prefix. 
I don't see how to call the main function here
https://bitbucket.org/ronaldoussoren/macholib/src/default/macholib/__main__.py

**Pull request merged**
