### PR TITLE
boost: Add versions 1.71.0 and 1.72.0, use Clang toolset on Darwin

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by hainest** [comment]
Both correctly build on Ubuntu-18.04 on x86_64.

**Comment by hainest** [comment]
@adamjstewart Well, I searched the *open* PRs, but I see that one was closed just a few days ago (I was only slightly late to the party!). I use Boost extensively, and I would like to be able to test these new versions with my packages. I'll ping the Boost dev mailing list, but I don't have a Mac platform to test this on.

**Comment by adamjstewart** [comment]
I can test it for you. See #13326 for the error message I was getting. Basically, darwin is no longer and accepted toolset and we don’t know why because it’s still documented.

**Comment by adamjstewart** [comment]
> I use Boost extensively, and I would like to be able to test these new versions with my packages. 

Another thing you can do is add:
```python
maintainers = ['hainest']
```
to the package below `list_depth`. This gives us someone to ping in case anyone encounters a build issue or wants to make changes to the package. You don't need to be a Spack expert to be a package maintainer, we just want someone who is willing to help look at issues and review PRs for `boost`.

**Comment by hainest** [comment]
The Darwin tool target was removed in https://github.com/boostorg/build/commit/eb8da52df3a43ca9616a7a6e11e0ad6fe896c031, but the commit message does not provide a rationale. I have contacted the author, and am awaiting a response.

>Another thing you can do is add: maintainers = ['hainest'] to the package below list_depth. This gives us someone to ping in case anyone encounters a build issue or wants to make changes to the package. You don't need to be a Spack expert to be a package maintainer, we just want someone who is willing to help look at issues and review PRs for boost.

I'm not a Boost expert, but I would be happy to act as a maintainer for the package.

**Comment by adamjstewart** [comment]
@svenevs unless we hear back from the author of https://github.com/boostorg/build/commit/eb8da52df3a43ca9616a7a6e11e0ad6fe896c031, I propose we remove the `darwin` toolset from our `boost` package, or remove it for versions 1.71.0+. Do you have any preference? Do version 1.70.0 and older work if you build them with the `clang` toolset? Also, do you want to be added to the `maintainers` list with @hainest?

**Comment by adamjstewart** [comment]
@hainest I successfully built boost 1.69.0 on macOS with Apple Clang using the `clang` toolset, so I think it's safe to drop the `darwin` toolset. Can you apply the following patch:
```patch
diff --git a/var/spack/repos/builtin/packages/boost/package.py b/var/spack/repos/builtin/packages/boost/package.py
index 8f5c33556..2dabede61 100644
--- a/var/spack/repos/builtin/packages/boost/package.py
+++ b/var/spack/repos/builtin/packages/boost/package.py
@@ -205,7 +205,7 @@ def libs(self):
 
     # Add option to C/C++ compile commands in clang-linux.jam
     patch('clang-linux_add_option.patch', when='@1.56.0:1.63.0')
-    patch('clang-linux_add_option2.patch', when='@:1.55.0')
+    patch('clang-linux_add_option2.patch', when='@1.47.0:1.55.0')
 
     def url_for_version(self, version):
         if version >= Version('1.63.0'):
@@ -216,9 +216,6 @@ def url_for_version(self, version):
         return url.format(version.dotted, version.underscored)
 
     def determine_toolset(self, spec):
-        if spec.satisfies("platform=darwin"):
-            return 'darwin'
-
         toolsets = {'g++': 'gcc',
                     'icpc': 'intel',
                     'clang++': 'clang',
```
(I noticed the patch doesn't work for older versions)

**Comment by hainest** [comment]
@adamjstewart Does that patch let you build 1.71.0 and 1.72.0 with `tool=clang`?

**Comment by adamjstewart** [comment]
@hainest yep!

**Comment by hainest** [comment]
From the author https://github.com/boostorg/build/issues/528#issuecomment-580541076:

>it was removed for building b2 as here is no difference between it and the clang toolset. Hence there was no point in maintaining duplicate code for both. You should be able to make things work equally well by using `--with-toolset=clang`.

I would be fine allowing the Darwin target to still work, but just get forwarded to `clang` as of 1.71.0.

**Comment by adamjstewart** [comment]
I'm fine with either using `darwin` on old versions of always using `clang`. Always using `clang` leaves the code simpler.

**Comment by hainest** [comment]
On second thought, simpler code is probably better for the long run. I was just thinking that allowing for both would stave off any issues in the future for mac+boost users, but I think that's a fairly small set. Once this passes CI, it's ready to go.

**Comment by hainest** [comment]
@chissg I could see how that could be misconstrued. Updated.

**Comment by hainest** [comment]
@adamjstewart Could you remove the 'don-merge-yet' label?

**Pull request merged**
