### PR TITLE
boost: Add "container" library

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**

### CODE REVIEW

**Comment by hainest** [comment]
@ChristianTackeGSI I'm a bit confused by this PR. The title is "Add container library", but it's been added to the list of Boost sub-libraries **not** installed by default because they have non-trivial dependencies. Yet, Boost.Container is header-only. Could you clarify what you are trying to achieve?

@adamjstewart It was introduced in 1.48, so we'll need to constrain its inclusion.

**Comment by ChristianTackeGSI** [comment]
Hi @hainest,

Thanks for your comments! I am quite new to boost. I just know, that some of our applications need boost container.

Version 1.55.0 gives me this, so it's really header only until then it seems:

    error: wrong library name 'container' in the --with-<library> option

It seems, that boost 1.56.0 added a `libs/container/src/` and accepts `--with-libraries=container`.

So I moved `container` to the normal libraries area and added a versioning line like for the other libraries also.

Does that now make more sense?

**Comment by hainest** [comment]
@ChristianTackeGSI Thanks for the updated description and code; it is much clearer to me now.

I just did a `spack install boost@1.55.0` without this PR, and Boost.Container was installed:

    $ cd /var/software/spack/opt/spack/linux-ubuntu19.04-skylake/gcc-8.3.0/boost-1.55.0-2m5n6lc3p43a6k3mfuiocwbs4ltq3jwo/include/boost
    $ ls container
    allocator_traits.hpp  flat_map.hpp  scoped_allocator_fwd.hpp  stable_vector.hpp    vector.hpp
    container_fwd.hpp     flat_set.hpp  scoped_allocator.hpp      static_vector.hpp
    deque.hpp             list.hpp      set.hpp                   string.hpp
    detail                map.hpp       slist.hpp                 throw_exception.hpp

When you were doing your build test above, were you using Spack or building from source?

**Comment by ChristianTackeGSI** [comment]
@hainest
As I said, I am quite new to boost. That said:

My test was with `'container'` being added to the `default_install_libs` list, but not doing the version constraints. What it showed to me: 

* 1.55 does have the header-only part, but no actual library. That's, what you showed too. So `@1.55.0+container` makes no sense.

* But for 1.56.0 it seems that there is an actual library. So `+container` seems to make sense.

Could you clarity, what I missed?

**Comment by hainest** [comment]
Ah, I found the source of my confusion. It's not that Boost.Container needs to be compiled, but that using Extended Allocators (EAs) requires a build+link [step](https://www.boost.org/doc/libs/1_56_0/doc/html/container.html#container.intro.introduction_building_container). If you aren't using EAs, then Boost.Container is header-only and *always* present (since 1.48.0), and no Spack variant is needed. If you want EAs, then we need to add 'container' to `--with-libraries`, but only for >=1.56.0. To this end, I propose adding a variant for EAs, rather than container. Something like

    spack install boost           # Boost.Container is header-only
    spack install boost+extalloc  # Build and link Extended Allocators, use them in Boost.Container

This is slightly different than the other variants which are named after a Boost library (i.e., boost+XXX includes Boost.XXX). I'm hesitant to make the variant 'container' since that implies that it won't be included in the build without the variant, but that's not true.

Does this work for you, @ChristianTackeGSI?
@adamjstewart do you have any thoughts on my proposal?

**Comment by adamjstewart** [comment]
> @adamjstewart do you have any thoughts on my proposal?

Nope, I don't use boost so I'll let you two decide. It is kind of nice to have variants named after libraries though, as it makes it easy for packages that depend on boost to know what variants they require. This is similar to how `python` works, where I named all of the variants after the Python modules they build.

**Comment by hainest** [comment]
> > @adamjstewart do you have any thoughts on my proposal?
> 
> Nope, I don't use boost so I'll let you two decide. It is kind of nice to have variants named after libraries though, as it makes it easy for packages that depend on boost to know what variants they require. This is similar to how `python` works, where I named all of the variants after the Python modules they build.

I agree. It breaks the normal flow, and doesn't feel quite right. However, `spack install boost` already installs the header-only version of Boost.Container. Having `spack install boost+container` makes it seem like it won't install Boost.Container without the variant- which isn't true. The *real* variant is whether or not Boost.Container is built with Extended Allocators.

**Comment by ChristianTackeGSI** [comment]
> Does this work for you, @ChristianTackeGSI?

Well, for specific details, I need to ask our local boost users. My current guess is, that they need the extalloc stuff.

That said, I find it not nice to invent a new name:

* Say software X says: "Build boost using `--with-libraries=container`"
* If someone packages X for spack, they need to know, that this translates to `boost+extalloc`
* While for all other `--with-libraries=Y` it translates to `boost+Y`.
* Not to mention, we'd need to special case `+extalloc` everywhere in the spack recipe.

So I'd prefer to stay with the `container` variant despite confusioin on the boost side of things.

**Comment by hainest** [comment]
My biggest concern was breaking people's existing builds by adding default dependency that now has a link requirement that wasn't present before. I've had a bit of a think about this over the weekend, and the original patch just needed a slight modification to make everything work. The proposed patch is below.

    diff --git a/var/spack/repos/builtin/packages/boost/package.py b/var/spack/repos/builtin/packages/boost/package.py
    index 452ae99b8..68f418a65 100644
    --- a/var/spack/repos/builtin/packages/boost/package.py
    +++ b/var/spack/repos/builtin/packages/boost/package.py
    @@ -96,8 +96,12 @@ class Boost(Package):
         # mpi/python are not installed by default because they pull in many
         # dependencies and/or because there is a great deal of customization
         # possible (and it would be difficult to choose sensible defaults)
    +    #
    +    # Boost.Container can be both header-only and compiled. '+container'
    +    # indicates the compiled version which requires Extended Allocator
    +    # support. The header-only library is installed when no variant is given.
         default_noinstall_libs\
    -        = set(['context', 'coroutine', 'fiber', 'mpi', 'python'])
    +        = set(['container', 'context', 'coroutine', 'fiber', 'mpi', 'python'])
     
         all_libs = default_install_libs | default_noinstall_libs
     
    @@ -173,6 +177,9 @@ def libs(self):
     
         conflicts('+taggedlayout', when='+versionedlayout')
         conflicts('+numpy', when='~python')
    +    
    +    # Container's Extended Allocators were not added until 1.56.0
    +    conflicts('+container', when='@:1.55.99')
     
         # Patch fix from https://svn.boost.org/trac/boost/ticket/11856
         patch('boost_11856.patch', when='@1.60.0%gcc@4.4.7')

**Comment by adamjstewart** [comment]
@ChristianTackeGSI can you add @hainest's patch above?

**Comment by ChristianTackeGSI** [comment]
Hi @adamjstewart 

I was busy around Europe.

Yes, @hainest's patch looks good. Adopted it!

See changed and rebased push.

**Comment by hainest** [comment]
Versions 1.55.0 to 1.72.0 build with and without '+container' (1.55.0 correctly fails).

@adamjstewart I'm ok with merging.

**Pull request merged**
