### PR TITLE
Create rpms and update rpms in a DB

### PR DESCRIPTION
**Pull request by scheibelp**
This builds on #631 (which adds support for installing to a directory that differs from the final intended destination of a package). Using that as a base for comparison may help distinguish the important functionality.

This adds the following functionality:
1. Using a command with similar syntax to "spack install", create RPM specs which invoke spack installations to generate RPMs 
2. Update RPM packages and use Spack's spec DAG logic to transitively update dependencies 
3. Allow in-place updates for RPM package dependencies - achieved by specifying (on a per-package basis) how Spack specs should be projected onto a namespace

At the moment it is expected that all packages are managed by Spack. Support for specifying non-Spack RPMs as dependencies is planned.

~~This is currently in the process (mostly finished) of transitioning from using a single one-size-fits-all RPM spec template to allowing users to create their own templates and defining a set of variable substitutions.~~

Update 8/30/16: template substitution is now available. A default template is supplied if the user does not want a customized spec template.

Examples:
Using [packages.yaml.txt](https://github.com/LLNL/spack/files/342631/packages.yaml.txt)

~~`>spack rpm-install --output-dir=rpms1/ --universal-ring=ringX --rpm-db=rpms1/rpmdb.pkl gcc@4.9.3  %gcc@4.8.5 ~gold`~~

~~`>spack rpm-install --specs-dir=rpms1/ --rpm-db-from-spec=gccnogold-4.9.3-binutils-2.25.spec --output-dir=rpms2/ --universal-ring=ringX gcc@4.9.3 %gcc@4.8.5 ~gold ^gmp@6.0.0a`~~

Update 8/30/16: new command syntax is simpler; RPM DB is replaced with property files that can be stored in a centralized repository (e.g. the git repo maintained by fedpkg)

`>spack rpm --output-dir rpms1 --universal-ring=ringX gcc@4.9.3 %gcc@4.8.5 ~gold`

`>spack rpm --specs-dir rpms1/ --output-dir rpms2 --universal-ring=ringX gcc@4.9.3 %gcc@4.8.5 ~gold ^gmp@6.0.0a`

### CODE REVIEW

**Comment by scheibelp** [comment]
@citibeth here is the PR

The following link would be useful for understanding the distinct parts of this PR WRT #631 : https://github.com/scheibelp/spack/compare/features/make-rpms-prep...scheibelp:features/make-rpms

**Comment by citibeth** [comment]
Peter,

Thank you for the RPM PR.

One note on the caching docs --- it's so small I didn't want to post
publicly.  I would try to avoid parenthetical remarks.  I write a lot of
parentheses in my pros, and I find it really annoying.  So I try to edit
them out, using commas instead.

Anyway, thank you for the great work!
-- Elizabeth

**Comment by scheibelp** [comment]
> I would try to avoid parenthetical remarks.

I'm overly fond of parentheses. I'll be more diligent about eliminating them in the future.

FYI: The PR description does not specifically address potential reusable functionality for generating conda packages which is IIRC the basis of your interest. I figured I could do a better job of answering clarifying questions after providing a general description.

Thanks!

**Comment by gartung** [comment]
@scheibelp thanks for making this available. There is at least one case where HEP packages would be installed to a fixed path instead of the usual case where the install path is not known ahead of time. Using rpms would be the easiest way to do this.

**Comment by gartung** [comment]
@scheibelp  Could you also use a variable for the install location in packages.yaml?

**Comment by scheibelp** [comment]
@gartung I imagine that this preference could be implemented in a separate PR (which when combined with this would generate RPMs as you require): e.g. an option not to set RPATHs plus a post-install hook to get all library paths for a package and generate the site-specific config script.

Does that seem reasonable?

**Comment by gartung** [comment]
In #1013 ( #445 ) Benedikt saved the original install path in a text file  in the package .spack directory. The binary install command then makes use of that to change the old rpath to the new rpath. 

The first step to converting the CMS build system is to convert all of the "spec-lets" to spack packages. I saw "spec-lets" because our build script adds common scriptlets to the create the real spec passed to rpmbuild.

If you are interested see

https://github.com/gartung/cmsdist/tree/osx1011work

https://github.com/gartung/pkgtools/blob/V00-30-OSX/cmsBuild

**Comment by scheibelp** [comment]
Closing and reopening to restart tests

**Comment by becker33** [comment]
Closing as outdated. We have decided to pursue system installations via spack stacks rather than RPM generation. Maintenance for package mapping for RPM was too high to be a long-term solution.

**Pull request closed without merging**
