### PR TITLE
fix build for qt5 and the Intel compiler

### LINKED ISSUE #14400: Recent versions of QT5 do not build with the intel compiler
While working with the qt variant on a package I discovered that QT5 does not compile with the Intel compiler. It seems to be a problem with defining overflow builtins, which may be related to the underlying GCC used with the Intel compiler. Note that PR #14387 sets a `conflicts` directive to help prevent wasted build time.

---

### Steps to reproduce the issue

```console
$ spack install qt %intel ^freetype@2.7.1 ^harfbuzz@2.1.3 ^icu4c@58.2
...
3 errors found in build log:
     76    c++ -c -o qlist.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack-stage-q
           t-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-s
           zivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szi
           vpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-sz
           ivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/unix -I/dev/shm/gpjohnsn/spack-stage-qt-5.1
           3.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/win32 -I/dev/shm/gpjohnsn/spack-stage
           -qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/mac -I/dev/shm/gpjohnsn/spack-
           stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include -I/dev/shm/gpjohnsn/spack-stage-qt
           -5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore -I/dev/shm/gpjohnsn/spack-stage-qt-
           5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1 -I/dev/shm/gpjohnsn/spack-sta
           ge-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1/QtCore -I../src/corelib
           /global -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/mkspecs/
           linux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=1 -DQT_B
           UILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szi
           vpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qlist.cpp
     77    c++ -c -o qlocale.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack-stage
           -qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1
           -szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-s
           zivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-
           szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/unix -I/dev/shm/gpjohnsn/spack-stage-qt-5
           .13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/win32 -I/dev/shm/gpjohnsn/spack-sta
           ge-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/mac -I/dev/shm/gpjohnsn/spac
           k-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include -I/dev/shm/gpjohnsn/spack-stage-
           qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore -I/dev/shm/gpjohnsn/spack-stage-q
           t-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1 -I/dev/shm/gpjohnsn/spack-s
           tage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1/QtCore -I../src/corel
           ib/global -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/mkspec
           s/linux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=1 -DQT
           _BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-s
           zivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qlocale.cpp
     78    c++ -c -o qlocale_tools.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack
           -stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-
           5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.
           13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators -I/dev/shm/gpjohnsn/spack-stage-qt-5
           .13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/unix -I/dev/shm/gpjohnsn/spack-stag
           e-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/win32 -I/dev/shm/gpjohnsn/spa
           ck-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/mac -I/dev/shm/gpjohns
           n/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include -I/dev/shm/gpjohnsn/spack-
           stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore -I/dev/shm/gpjohnsn/spack-s
           tage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1 -I/dev/shm/gpjohnsn/s
           pack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1/QtCore -I../src
           /corelib/global -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/
           mkspecs/linux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=
           1 -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.
           13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qlocale_tools.cpp
     79    c++ -c -o qmap.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack-stage-qt
           -5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-sz
           ivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-sziv
           polegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szi
           vpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/unix -I/dev/shm/gpjohnsn/spack-stage-qt-5.13
           .1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/win32 -I/dev/shm/gpjohnsn/spack-stage-
           qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/mac -I/dev/shm/gpjohnsn/spack-s
           tage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include -I/dev/shm/gpjohnsn/spack-stage-qt-
           5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore -I/dev/shm/gpjohnsn/spack-stage-qt-5
           .13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1 -I/dev/shm/gpjohnsn/spack-stag
           e-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1/QtCore -I../src/corelib/
           global -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/mkspecs/l
           inux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=1 -DQT_BU
           ILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-sziv
           polegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qmap.cpp
     80    c++ -c -o qregexp.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack-stage
           -qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1
           -szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-s
           s/linux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=1 -DQT
           _BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-s
           zivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qregexp.cpp
     81    c++ -c -o qringbuffer.o   -std=c++11 -ffunction-sections -fdata-sections -O2 -g  -I/dev/shm/gpjohnsn/spack-s
           tage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake -I/dev/shm/gpjohnsn/spack-stage-qt-5.
           13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/library -I/dev/shm/gpjohnsn/spack-stage-qt-5.13
           .1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators -I/dev/shm/gpjohnsn/spack-stage-qt-5.1
           3.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/unix -I/dev/shm/gpjohnsn/spack-stage-
           qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/win32 -I/dev/shm/gpjohnsn/spack
           -stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/qmake/generators/mac -I/dev/shm/gpjohnsn/
           spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include -I/dev/shm/gpjohnsn/spack-st
           age-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore -I/dev/shm/gpjohnsn/spack-sta
           ge-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1 -I/dev/shm/gpjohnsn/spa
           ck-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.13.1/QtCore -I../src/c
           orelib/global -I/dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/mk
           specs/linux-g++ -DQT_VERSION_STR=\"5.13.1\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=13 -DQT_VERSION_PATCH=1 
           -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH /dev/shm/gpjohnsn/spack-stage-qt-5.13
           .1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/src/corelib/tools/qringbuffer.cpp
  >> 82    /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.1
           3.1/QtCore/private/../../../../../src/corelib/global/qnumeric_p.h(250): error: argument is incompatible with
            formal parameter
     83      { return __builtin_mul_overflow(v1, v2, r); }
     84               ^
     85    
  >> 86    /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/qtbase/include/QtCore/5.1
           3.1/QtCore/private/../../../../../src/corelib/global/qnumeric_p.h(240): error: argument is incompatible with
            formal parameter
     87      { return __builtin_add_overflow(v1, v2, r); }
     88               ^
     89    
     90    compilation aborted for /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/q
           tbase/src/corelib/tools/qbytearray.cpp (code 2)
  >> 91    gmake: *** [qbytearray.o] Error 2
     92    gmake: *** Waiting for unfinished jobs....
```
The problem is with the following code in qnumeric_p.h:
```
// Overflow math.                                                                                                       
// This provides efficient implementations for int, unsigned, qsizetype and                                             
// size_t. Implementations for 8- and 16-bit types will work but may not be as                                          
// efficient. Implementations for 64-bit may be missing on 32-bit platforms.                                            
                                                                                                                        
#if (defined(Q_CC_GNU) && (Q_CC_GNU >= 500) || (defined(Q_CC_INTEL) && !defined(Q_OS_WIN))) || QT_HAS_BUILTIN(__builtin_add_overflow)                                                                                                           
// GCC 5, ICC 18, and Clang 3.8 have builtins to detect overflows                                                       
                                                                                                                        
template <typename T> inline                                                                                            
typename std::enable_if<std::is_unsigned<T>::value || std::is_signed<T>::value, bool>::type                             
add_overflow(T v1, T v2, T *r)                                                                                          
{ return __builtin_add_overflow(v1, v2, r); }                                                                           
                                                                                                                        
template <typename T> inline                                                                                            
typename std::enable_if<std::is_unsigned<T>::value || std::is_signed<T>::value, bool>::type                             
sub_overflow(T v1, T v2, T *r)                                                                                          
{ return __builtin_sub_overflow(v1, v2, r); }                                                                           
                                                                                                                        
template <typename T> inline                                                                                            
typename std::enable_if<std::is_unsigned<T>::value || std::is_signed<T>::value, bool>::type                             
mul_overflow(T v1, T v2, T *r)                                                                                          
{ return __builtin_mul_overflow(v1, v2, r); }                                                                           
                                                                                                                        
#else                                                                                                                   
// Generic implementations  
...
```
That looks like the interfaces might be getting mixed up. There is more to it than that though as adding a module to specify a newer version of GCC, yields the following:

```console
...
Info: creating stash file /dev/shm/gpjohnsn/spack-stage-qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw/spack-src/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
==> Error: ProcessError: Command exited with status 3:
    './configure' '-no-eglfs' '-no-directfb' '-no-gtk' '-prefix' '/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/qt-5.13.1-szivpolegsx2j6hslwuyqkudeufbfhaw' '-v' '-opensource' '-no-opengl' '-release' '-confirm-license' '-openssl-linked' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/openssl-1.1.1d-vomzrhq3vyt2tkk5bx5nj6avhhei4qx6/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/openssl-1.1.1d-vomzrhq3vyt2tkk5bx5nj6avhhei4qx6/include' '-optimized-qmake' '-no-pch' '-system-freetype' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/freetype-2.7.1-glh2o2djvw4vcaffhizchjtjofqf4sfw/include/freetype2' '-fontconfig' '-openssl-linked' '-system-sqlite' '-shared' '-system-harfbuzz' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/harfbuzz-2.1.3-ggxas5icupgdslvf4kvfyt6rrlsdxmqk/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/harfbuzz-2.1.3-ggxas5icupgdslvf4kvfyt6rrlsdxmqk/include' '-system-pcre' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/pcre2-10.31-cbcfe5ynsf5ky7ccezwwc6ngmtnwbxot/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/pcre2-10.31-cbcfe5ynsf5ky7ccezwwc6ngmtnwbxot/include' '-system-doubleconversion' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/double-conversion-2.0.1-73vy7slnoduzb5m6rejai6degd5k27oi/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/double-conversion-2.0.1-73vy7slnoduzb5m6rejai6degd5k27oi/include' '-system-libpng' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/libpng-1.6.37-iu6mik7x7gbsb2sevn5bffomgkfwu643/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/libpng-1.6.37-iu6mik7x7gbsb2sevn5bffomgkfwu643/include' '-system-libjpeg' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/libjpeg-turbo-2.0.3-boohheheifgexzgwwideuon5buoqfxzc/lib64' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/libjpeg-turbo-2.0.3-boohheheifgexzgwwideuon5buoqfxzc/include' '-system-zlib' '-L/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/zlib-1.2.11-csbova4up62su6pxxlvzqf2tjef233ew/lib' '-I/opt/packages/gpjohnsn/apps/linux-centos7-broadwell/intel-19.0.5.281/zlib-1.2.11-csbova4up62su6pxxlvzqf2tjef233ew/include' '-nomake' 'examples' '-no-dbus' '-system-xcb' '-skip' 'webengine' '-skip' 'webglplugin' '-skip' 'wayland'
```
The qmake.stash file looks correct in this scenario.

```
QMAKE_CXX.QT_COMPILER_STDCXX = 201402L
QMAKE_CXX.QMAKE_ICC_VER = 1900
QMAKE_CXX.QMAKE_ICC_UPDATE_VER = 5
QMAKE_CXX.QMAKE_GCC_MAJOR_VERSION = 6
QMAKE_CXX.QMAKE_GCC_MINOR_VERSION = 1
QMAKE_CXX.QMAKE_GCC_PATCH_VERSION = 0
QMAKE_CXX.COMPILER_MACROS = \
    QT_COMPILER_STDCXX \
    QMAKE_ICC_VER \
    QMAKE_ICC_UPDATE_VER \
    QMAKE_GCC_MAJOR_VERSION \
    QMAKE_GCC_MINOR_VERSION \
    QMAKE_GCC_PATCH_VERSION
```
Interestingly, I see the same thing when I patch the source to remove the overflow builtins from qnumeric_p.h so that the generic interface is used. 

I see the same behavior with intel-17 and intel-18. So far I have only looked at qt-5.13.1.

### Platform and user environment

```commandline
$ uname -a 
Linux argon-build.hpc 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linuxx86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core) 
```

### PR DESCRIPTION
**Pull request by glennpj**
Fixes #14400

### CODE REVIEW

**Comment by glennpj** [comment]
> Did you report this to the Qt developers?

Not yet. I was focused on spack today.

**Comment by sethrj** [comment]
@glennpj This is alarming, as our group currently uses the ancient QT4 and is in the process of transitioning to QT5 (and we test on Intel as well).  Does Intel fail to build even with all the optional variants disabled? What error message(s) does it give? Which specific versions of the Intel compiler have you tried? It would be good to document this for future reference.

I do see that the [QT5  documentation](https://doc.qt.io/archives/qt-5.11/supported-platforms-and-configurations.html) specifies that only GCC is _supported_ on linux and only Clang is _supported_ on mac, but those are guarantees rather than limitations.

**Comment by glennpj** [comment]
Filed spack issue #14400. I am trying to ascertain whether this is something about the compiler wrapper and the Intel/GCC combo or a QT issue.

**Comment by sethrj** [comment]
Thanks! It might be just a matter of adding the correct `-platform` flag to the configure line, see #13684 (which I'm wrapping up now)

**Comment by glennpj** [comment]
Just to complete the picture, getting qt5 to build with Intel requires two things.
1. making the platform explicit per #13684 
1. checking the GCC version that the Intel compiler is using to set whether overflow builtins are used or not

There is also an issue with getting the database libraries set in the RPATH when the `sql` variant is set. Those require an extra parameter to tell the build system to RPATH them. I will set that for sqlite as that is already in the package explicitly. However, the `sql` variant needs to be converted from a Boolean to a multi value variant to accommodate the other DB types. That will have to be another PR.

The other thing that came up is that when qt5 is compiled with the intel compiler and the `sql` variant, the sqlite dependency needs the `column_metadata` variant set in order to pick up `sqlite3_column_database_name16()`. That is not needed for older GCC compilations and I am trying to find out about newer GCC versions.
@adamjstewart Should I set the sqlite dependency to `sqlite+column_metadata` for the entire package or just when `%intel`?

Note that I still need to determine if there are any differences when using intel-17 as opposed to intel-18 or intel-19.

**Comment by glennpj** [comment]
The Intel-17 compiler does not have the overflow builtins so it needs to be handled differently.

**Comment by glennpj** [comment]
I just pushed a new commit that gets the Intel compilers to build QT5. This PR will resolve #14400.

**Comment by sethrj** [comment]
Excellent! Thanks @glennpj .

**Comment by glennpj** [comment]
Here is the QT bug report that I filed:
[\[QTBUG\-81248\] Qt\-5 not compiling with Intel compiler \- Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-81248)

**Comment by sethrj** [comment]
Given the discussion on the QTBUG submission, this *might* only be needed with Intel versions built against an older GCC (4.8.5) as opposed to the highest compatible version (probably 6.5, see [intel compatibility matrix](https://github.com/UIUC-PPL/charm/issues/1560#issuecomment-581129714)).

Once improved "compilers as DAG nodes" support comes online (see discussion on [intel/gcc detection in numpy](https://github.com/spack/spack/issues/14729)) we should be able to improve the restrictions on this patch (e.g. `%(intel ^gcc@:5)` or whatever the syntax ends up as). See mention on an improved compiler dependency model on https://github.com/spack/spack/issues/8531.

@tgamblin, is there an issue documenting the plans for improved compiler dependencies?

**Pull request merged**
