### PR TITLE
Add JasPer 2.0.14

### PR DESCRIPTION
**Pull request by adamjstewart**
I ended up dropping the old version of JasPer because

1. They switched the build system from Autotools to CMake
2. They switched from `.zip` to `.tar.gz`

If someone really needs it, I can add support for it, but if not, I'd rather leave it out. It increases the complexity of the package too much.

P.S. Successfully installed on macOS 10.13.4 with Clang 9.0.0. Passed all of its own tests.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Actually, hold off on this, I might need to build with an old version of JasPer anyway:
https://trac.osgeo.org/gdal/wiki/JasPer

**Comment by healther** [comment]
Maybe we should take another look at supporting multiple build systems per package. I'm not completely sold on this, but the number of packages that I know of and that changed their build system is >2 now... 

This is one of the reasons why I'm yet to add [nest](https://github.com/electronicvisions/spack/blob/20180129/var/spack/repos/builtin/packages/nest/package.py) to upstream spack...

**Comment by adamjstewart** [comment]
> the number of packages that I know of and that changed their build system is >2 now...

There are exactly 6 out of 2693 packages in Spack that use multiple build systems:

- `arpack-ng`
- `dyninst`
- `glog`
- `metis`
- `opennurbs`
- `superlu`

I'm not sure how easy it would be to add builtin support for this. I'm sure it's doable, but would probably require some refactoring. I guess it depends on how much work it would be.

**Comment by adamjstewart** [comment]
@alalazo (@wscullin?) We recently added a mechanism by which a package can depend on another package with a specific patch applied, correct? Can you point me to an example?

GDAL depends on this hacked version of JasPer, but I don't want to apply this patch by default.

**Comment by alalazo** [comment]
@adamjstewart Look at `qmcpack`, which depends on a patched version of `espresso`

**Comment by adamjstewart** [comment]
@alalazo If I use a file instead of a URL, does the patch go with the dependent package or with the parent package?

**Comment by adamjstewart** [comment]
This is now ready to merge. Successfully installed both versions with Clang 9.0.0 on macOS 10.13.4. All unit tests passed.

**Pull request merged**
