### PR TITLE
Use the version reported by the IBM XL Fortran compiler.

### PR DESCRIPTION
**Pull request by serbanmaerean**
Use the version reported by the IBM XL Fortran compiler for compiler versions >= 16.0.
Starting with the April 2018 release, the IBM XL C and Fortran compilers report the same version, 16.0.  Consequently, there is no need to downgrade the Fortran compiler version to match that of the C compiler.

### CODE REVIEW

**Comment by serbanmaerean** [comment]
I don't understand they reason for the 2 failures reported.  Can someone pls help me understand what I need to do?  - Thx.

**Comment by adamjstewart** [comment]
> I don't understand they reason for the 2 failures reported. Can someone pls help me understand what I need to do? - Thx.

See the note at the bottom of: http://spack.readthedocs.io/en/latest/contribution_guide.html#coverage

**Comment by adamjstewart** [comment]
The failing codecov tests mean that you modified core Spack libraries but we don't have any unit tests to ensure that you didn't break anything.

**Comment by serbanmaerean** [comment]
What would a test case for this patch look like?  The changes are fairly minor and, to verify them, they require IBM XL compiler versions 16.1 and [15.1/13.1].

**Comment by adamjstewart** [comment]
We don't currently test compilers very well. It would be nice to see how other package managers handle this. An idea would be to write a bunch of bash scripts that when given the version flag, print the output for this version of this compiler. Then check to see if the version is the correct answer.

This would be really nice to add, but I don't think it should be a requirement in order to get this PR merged.

**Comment by serbanmaerean** [comment]
Besides the lack of test cases, what else do I need to do to get this pull request merged?

**Comment by adamjstewart** [comment]
You just need to convince someone who knows more about compilers and XL than me to review your PR. I don't like to merge non-package PRs myself.

**Comment by serbanmaerean** [comment]
@tgamblin can you pls review this PR?  It fixes an issue w/returning the correct version of the XL Fortran compiler.  Thanks.

**Pull request merged**
