### PR TITLE
Add the ability to separate architecture in path scheme

### PR DESCRIPTION
**Pull request by mamelara**
I think this is a nice change to have. You can create directories separated based off of operating system, target and platform. Helpful for HPC support teams and certainly helpful to NERSC.

### CODE REVIEW

**Comment by becker33** [comment]
Also your patch test coverage is low.

**Comment by alalazo** [comment]
@mamelara Are you still working on this?

**Comment by mamelara** [comment]
@alalazo yes. Been trying to play catch up now that SC is over

**Comment by scheibelp** [comment]
Hi @mamelara the edits and tests look good but it appears that `Spec.format` has changed in develop and generated a conflict. Let me know when you have resolved that and I'll look at this again.

**Comment by mamelara** [comment]
@scheibelp Hopefully fixed test patch coverage in spec. Let me know if the format section I added is too much spaghetti

**Pull request merged**
