### PR TITLE
WIP: Spack chain updates to #8014 for testing only

### PR DESCRIPTION
**Pull request by gartung**
These are changes needed to bring PR #8014 current with the head of develop.

### CODE REVIEW

**Comment by gartung** [comment]
@amundson @JavierCVilla I have the test working and I made a few improvements. I will submit a PR to Jim's branch once the tests complete.

**Comment by gartung** [comment]
@chissg @lgarren you might be interested in this PR.

**Comment by scheibelp** [comment]
You mentioned: 

> I see the problem. The system-like db is not being linked into the user-like db. When I try linking them I end up with infinite recursions that I am trying to debug.

> This PR is broken since commit f202198 was merged. Since then I am unable to find a way to add the parent database without infinite recursion.

I could look at why this might be occurring this afternoon if that is of interest, but more context would be useful: where is the infinite recursion occurring?

**Comment by gartung** [comment]
I think I have the infinite recursion problem fixed. Now I can build Jim's example with the expected linking of libraries from the system-like spack install.

**Comment by scheibelp** [comment]
Great! I'll be looking through this more later today and expect to have some suggestions/comments by tomorrow afternoon (6/28)

**Comment by gartung** [comment]
This is the example of infinite recursion I was talking about.

 spack -d find
==> In /build/spack/opt/spack:
==> READ LOCK: /build/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /build/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /build/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 6 installed packages.
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
cmake@3.11.0  garply@2.0.0  ncurses@6.0  openssl@1.0.2k  quux@2.0.0  zlib@1.2.11
Traceback (most recent call last):
  File "/home/gartung/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/home/gartung/spack/lib/spack/spack/main.py", line 607, in main
    return _main(command, parser, args, unknown)
  File "/home/gartung/spack/lib/spack/spack/main.py", line 505, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/home/gartung/spack/lib/spack/spack/main.py", line 417, in _invoke_spack_command
    return_val = command(parser, args)
  File "/home/gartung/spack/lib/spack/spack/cmd/find.py", line 147, in find
    tty.msg("In {0}:".format(db.root))
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 575, in __getattr__
    return getattr(self.ref_function(), name)
  File "/home/gartung/spack/lib/spack/spack/store.py", line 117, in <lambda>
    db = llnl.util.lang.LazyReference(lambda: store.db)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
...
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/home/gartung/spack/lib/spack/llnl/util/lang.py", line 552, in instance
    self._instance = self.factory()
  File "/home/gartung/spack/lib/spack/spack/store.py", line 109, in _store
    spack.config.get('config:install_hash_length'))
  File "/home/gartung/spack/lib/spack/spack/store.py", line 83, in __init__
    parent_db=spack.parents.parent_dbs[-1])
  File "/home/gartung/spack/lib/spack/spack/database.py", line 207, in __init__
    self.lock = Lock(self._lock_path)
  File "/home/gartung/spack/lib/spack/spack/util/lock.py", line 46, in __init__
    self._enable = spack.config.get('config:locks', True)
  File "/home/gartung/spack/lib/spack/spack/config.py", line 512, in get
    return config.get(path, default, scope)
  File "/home/gartung/spack/lib/spack/spack/config.py", line 409, in get
    value = self.get_config(section, scope=scope)
  File "/home/gartung/spack/lib/spack/spack/config.py", line 383, in get_config
    merged_section = _merge_yaml(merged_section, data)
  File "/home/gartung/spack/lib/spack/spack/config.py", line 671, in _merge_yaml
    dest[sk] = copy.copy(sv)
  File "/usr/lib64/python2.7/copy.py", line 88, in copy
    rv = reductor(2)
  File "/usr/lib64/python2.7/collections.py", line 181, in __reduce__
    for k in vars(OrderedDict()):
  File "/usr/lib64/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib64/python2.7/_abcoll.py", line 540, in update
    if isinstance(other, Mapping):
  File "/usr/lib64/python2.7/abc.py", line 141, in __instancecheck__
    subtype in cls._abc_negative_cache):
  File "/usr/lib64/python2.7/_weakrefset.py", line 73, in __contains__
    return wr in self.data
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by scheibelp** [comment]
I'm still looking at this but a couple of complications I see currently are:

* Dependents should set up RPATHs to point to the true install location of dependencies (I think that will not happen atm because `Spec.prefix` refers to the local spack)
* There are remaining functions which query one of the db's when they would want to query upstream db's as well, e.g. `Spec._install_status` (for reporting install status when printing out the Spec DAG)

Other notes:

* It may not be necessary to track separate `DirectoryLayout`s in addition to databases since the install records of databases store the install path
* I'd prefer to avoid a recursive implementation and instead add logic to query the set of DB's together. Potentially analogous to `RepoPath` and `Repo` but an aggregation object may not be required (I'm still thinking that through)

As a side note: this appears to contain unrelated changes to `setup-env.sh`

**Comment by gartung** [comment]
The rpaths were being set correctly because the spec returned from the query comes from the chained spack install db and includes the correct installed path

 

The DirectoryLayout and the section in setup-env.sh were done so that module files could be found in chained spack install.

**Comment by gartung** [comment]
There is one quirk: If a package is installed in multiple prefixes, spack find -p shows the same path in all prefixes.

**Comment by paul-chelarescu** [comment]
@gartung what changes would be needed to prevent this from happening? I would like to help you out with this feature in order to make it ready and would benefit greatly from some starting points.

**Comment by gartung** [comment]
This is where the paths get printed
https://github.com/gartung/spack/blob/dd646d409c1cb5949e8883b5934e6290300e34ef/lib/spack/spack/cmd/__init__.py#L303

**Comment by scheibelp** [comment]
Regarding https://github.com/spack/spack/pull/8545/#issuecomment-406304298

Hi @paul-chelarescu, I am also working on this. My plan is to get a PR out by the end of tomorrow which (a) will help me (and hopefully you) understand the ramifications of edits made here and (b) will serve as a reference point for how this could be improved. Overall I'm looking for an approach which interacts a bit less with Spack internals and I think that PR will either help guide this there or build on this to achieve that.

**Comment by gartung** [comment]
See https://github.com/spack/spack/pull/8772

**Pull request closed without merging**
