### PR TITLE
[WIP] mfem: if using clang, link to llvm libunwind

### PR DESCRIPTION
**Pull request by goxberry**
This patch is intended to build MFEM with LLVM's libunwind if the spec contains `+libunwind%clang`; however, I can't find a succinct way of doing that here. Lines 204-206 are supposed to enumerate all compilers other than clang, but I'm sure I'm missing XL, and possibly other compilers; this partial fix is temporary, mainly to PR a patch that almost does what it's supposed to. I'm also pretty sure I need to add a `-g` flag to the compiler commands for `mfem+libunwind%clang`; for now, I've built locally with `mfem+debug+libunwind%clang` because I need the debug info anyway, and I think bigger issues with this PR need to be addressed first, before adding flags.

A related PR is #7263; also see the comment at https://github.com/spack/spack/pull/7263#issuecomment-367258043. I don't think forcing users to add an external `libunwind` using system paths will be any easier, because:

- LLVM's libunwind is definitely different than the https://savannah.nongnu.org/projects/libunwind/ version of libunwind currently built by spack's libunwind package. Although they have a common ABI and some functions that form a common API (see http://lists.llvm.org/pipermail/cfe-dev/2016-September/050649.html), the libraries provide different symbols and the non-GNU version has more features

- The path of the LLVM libunwind header looks like `${LLVM_PREFIX}/lib/clang/${VERSION}/include/unwind.h` (e.g., `/usr/local/opt/llvm/lib/clang/6.0.0/include/unwind.h`), so listing a prefix isn't necessarily helpful for non-Apple LLVM installs. Apple installs have a simpler path (`/usr/include/unwind.h`), and libraries for Apple and non-Apple LLVM installs are in the usual directory (i.e., `$PREFIX/lib`)

- If a user installs LLVM via spack, they might want to use the accompanying libunwind, but it's not clear to me how to encode that information in a `packages.yaml` programmatically; maybe it's worth putting a `provides('llvm-libunwind')` directive in the LLVM spack package

Suggestions to make adding this feature more workable are welcome; I will do what I can to address them.

### CODE REVIEW

**Comment by v-dobrev** [comment]
@goxberry, this seems like an issue that should be resolved on system/spack level and not in a specific package. What if you specify in your `packages.yaml` file that `libunwind%clang@6.0.0` is an external package and set its location:
```yaml
packages:
  libunwind:
    paths:
      libunwind%clang@6.0.0: /path/to/llvl-libunwind
```
The idea is that if you are building `mfem%clang@6.0.0+libunwind` (or simply `mfem+libunwind` and `clang@6.0.0` is your default compiler) then spack will concretize the `libunwind` dependency to something containing `^libunwind%clang@6.0.0` which then will be resolved as the external package specified in `packages.yaml`.

I'm not sure if this actually works (I've had various issues with similar configurations not working as expected) but this seems to be a better solution.

@tgamblin, is my expectation for the Spack behavior in the above case correct? Or did I misunderstand how configurations in `packages.yaml` work?

**Comment by goxberry** [comment]
@v-dobrev: I’ve already discussed that possibility above in the PR description. The drawbacks are:

- LLVM `libunwind` is different from the packaged `libunwind`, and it’s inaccurate to represent the former as the latter (see the link above for why)
- the `depends_on` statements in the PR are kludgey — I need a better way to express “depend on the current spack `libunwind` unless `platform == Darwin` and `compiler == clang`
- manually registering spack-installed LLVM as `libunwind` is a bug waiting to happen

I’m fine with treating `libunwind` as a virtual package, and renaming the current `libunwind` package to `non-gnu-libunwind` (sort of like how `mesa` provides `gl`. Then I’d have LLVM `provide('libunwind')`, if that’s what the maintainers want. I think the API versioning scheme should probably be analogous to how spack treats the `elf` dependency. One could even have a fake `llvm-libunwind` package (as is done with OpenGL, to direct users to register an external implementation), and/or download libunwind from the LLVM GitHub repo and have spack build it.

Finally, the Apple-provided system “LLVM libunwind” may or may not be materially different (i.e., provides other symbols that actually matter) from the libunwind distributed by the open-source LLVM project. I suspect there’s not much of a real difference, but I don’t know that for sure. I do know that Apple doesn’t distribute some LLVM libunwind C headers (you can install them via Homebrew), which is why I hesitate to declare them equivalent.

I am asking for guidance from the maintainers on what to do next.

**Comment by goxberry** [comment]
Should probably make use of #8824 and #8825, if both PRs are merged.

**Comment by goxberry** [comment]
Closed in favor of #8825.

**Pull request closed without merging**
