### PR TITLE
Effective Use of Spack Environments

### PR DESCRIPTION
**Pull request by citibeth**
I've been relying on the current iteration of Spack Environments now for a year or more, and they are in the end working for me.  However, they also have shortcomings:

1. I don't feel they were designed for my use case.  They were intentionally designed to follow the model of Python environments, in which *install* actions taken by the user are recorded, to be later replayed by the environment.  This doesn't work for me because it is bottom-up thinking, which I argue is obsolete in a Spack-based universe (see the PR text).  My use case is more like compiling a C program.  First I write it, then I compile it, then I use it.  I want to write the environment spec, not have Spack automagically write it (and re-write it) for me as I do stuff.  And I don't want a "current" environment.

1. They have a number of small "gotchas" / bugs that I have to work around.

1. Some features are incomplete; for example, Environment views.  Meaning... if you create a view with your environment, you are left at the end with no automated way to set env vars to *use* that view.  You just have to manually set a bunch of env vars manually.  In contrast, using environment modules to load your environment addresses that problem.  Unfortunately, views have also been made the default; unfortunate because the feature is incomplete.

1. They are not as easy to debug as I would like, when things go wrong with the build.

1. They are (mostly) documented in the reference docs, but the documentation is poorly documented in the rest of the Spack manual.  Users, especially new users, continue to ask for / try to do things that make sense in a world of manual software building, but not so much in a Spack world with environments.  For example: (a) asking for Spack to re-use packages you've already installed makes sense if you're still in manual mode, but not really so much in a more Spack-centric universe where you want to support reproducible environments for specific user projects.  (b) The `spack load` command is fundamentally non-deterministic, and now completely obsolete with Spack Environments.  But people continue to ask questions about it, presumably because that's what we've documented.  We need to remove that stuff from the manual and replace it with high-quality documentation showing how to use Spack Environments effectively.

To that end I present this PR.  It both argues why we should let Spack change our thinking; and shows the steps I go through now to support multiple per-project Spack environments in my work.  I am looking for feedback on this draft, such as:

1. What do you think of the positions taken in this PR?  How do we integrate them coherently into the Spack documentation, recognizing that different people use Spack in different ways?

1. Does the technical part of the PR make sense?  Has anyone else been building and using environments in this way?  If not, how have other people been using Spack Environment functionality?

### CODE REVIEW

**Comment by citibeth** [comment]
OK, I have removed the obviously obsolete documentation from *workflows.rst*, most of which I wote before we had Spack Environments.  More work needs to be done, of course.  I would suggest:

1. We should more clearly separate out the following use cases:

   1. *Combinatorial Sets of Installs*

   1. *Using Spack to Replace Conda*: Place it next to the text I produced in this PR, and see if we can harmonize the two.  They are different styles of using environments.  I would like to understand better how `spack env activate` knows how to set env vars.  (In the past I believe I was told it is not as complete as loading the associated env modules).

   1. *Filesystem Views*: I would wonder whether this is now obsolete, and should be folded into *Using Spackto Replace Conda*, which provides a view-based use case of Spack Environments.  I don't think that "bare" filesystem views without environments are so useful anymore.  But this section has a LOT of useful info that needs to be folded in elsewhere.

  1. *Developing Software with Spack*: This will need to be its own section.  But it doesn't *really* make sense until we get *Spack Setup* in place (my bad, I know...)

   1. *Using Spack to Create Docker Images*: The problem with this approach is that building significant stacks from source takes a *long* time --- and Docker images must be rebuilt many times to debug them.  I've used a hybrid approach in which Spack is used to generate tarballs, which are then loaded into the Docker container.  Unfortunately, it was all in a proprietary setting, and would have to be redone if we want it in Spack.  But I'm convinced that it is the right way to go --- and it ties into the Spack Binary packages stuff.  So ultimately, this section will have to be rewritten.

   1. *Singularity*: If they are similar to Docker, we should have a whole section to Spack in containers.

1. I would like to see if we can bring Spack Environments to the next level by fixing / rethinking some of the "gotchas."  I have a list of improvements I would love to see, in the PR text.  This would be stuff to discuss at Spack telcons.

**Comment by tgamblin** [comment]
I haven't read this yet but am confused by a couple points in the PR:

> I want to write the environment spec, not have Spack automagically write it (and re-write it) for me as I do stuff.

Spack currently is a bit invasive in that the YAML parser adds default values for empty fields -- I would like to fix that.  But what else is Spack doing that is interfering with your workflow here?

> And I don't want a "current" environment.

You do not *have* to activate the environment -- isn't that sufficient?

> Environment views. Meaning... if you create a view with your environment, you are left at the end with no automated way to set env vars to use that view. You just have to manually set a bunch of env vars manually.

Why is `spack env activate <name>` not sufficient?  It sets env vars that let you use that environment.

**Comment by citibeth** [comment]
@tgamblin I think the problem here for me isn't one specific feature/behavior or another; but the sum total of how Spack Environments work isn't working for my use case.  Multiple "anti-features" seem to be conspiring to make my life difficult.  Each of those was put into Spack for a reason, I'm sure.  But they are just not working for me.

> I haven't read this yet but am confused by a couple points in the PR:
> 
> > I want to write the environment spec, not have Spack automagically write it (and re-write it) for me as I do stuff.
> 
> Spack currently is a bit invasive in that the YAML parser adds default values for empty fields -- I would like to fix that. But what else is Spack doing that is interfering with your workflow here?

I want to use Spack like a compiler.  I write source code (`spack.yaml`), and then use Spack to compile it into a working environment that I users can load in their shell with a `source` command (whether assembled using view or just long settings of env vars is secondary).  Compilers don't edit your source code when you compile it; but Spack does.  Git works best if files are either handmade (source files) or machine generated.  In this case `spack.yaml` is neither and both, causing constant git annoyances.  I constantly have to remove things that Spack added to `spack.yaml` that I didn't want (for example, if I do `spack install` but Spack automagically "activated" my environment when doing so).  I constantly have to deal with pointless / source formatting changes Spack made to my `spack.yaml` file, that end up getting caught up in git.

The fix I want here isn't to find a more clever way for Spack to rewrite `spack.yaml`; but rather for Spack to stop doing it.  At least stop doing it unless you've *explicilty* activated an environment (see below).

> > And I don't want a "current" environment.
> 
> You do not _have_ to activate the environment -- isn't that sufficient?

Not true, see #15850, where my environment is "activated" whether I like it or not.  This is causing me problems in 2 ways that I consider to be anti-features: (a) overwriting my source file, and (b) silently activating my env without any action on my part.

Now I get around this by prefixing every Spack command with `spack --no-env` if I don't want an environment, or `spack -e` if I do.  This all feels like a step backwards in usability, not forwards.
> > Environment views. Meaning... if you create a view with your environment, you are left at the end with no automated way to set env vars to use that view. You just have to manually set a bunch of env vars manually.
> 
> Why is `spack env activate <name>` not sufficient? It sets env vars that let you use that environment.

The correct setting of env vars would be what you would get if you did a search-and-replace in all the modules of `<package install root>` --> `<view root>` and then loaded all the modules.  I might be wrong, but I don't believe this is what `spack env activate` currently does.  Thus, it is not getting package-specific env vars; see *PISM_BIN*, for example at: https://github.com/citibeth/spack/blob/efischer/giss2/var/spack/repos/builtin/packages/pism/package.py

**Comment by citibeth** [comment]
> @citibeth Spack does respect all variables from `setup_run_environment` and `setup_dependent_run_environment`, although that behavior was not implemented with the first cut of Spack environments with views.

Thanks for the info.  So that would remove my main objection to views as a way to use environments.

In my use of Spack with containers, Spack doesn't even end up in the final container.  So requiring Spack just to set the environment variables is not ideal.  It would be better if Spack can just generate a script or module to set the environment as needed to use a particular environment.  This functionality should be available whether or not views are used.

**Comment by alalazo** [comment]
> In my use of Spack with containers, Spack doesn't even end up in the final container. So requiring Spack just to set the environment variables is not ideal. It would be better if Spack can just generate a script or module to set the environment as needed to use a particular environment. This functionality should be available whether or not views are used

@citibeth Did you have a look already at [spack containerize](https://spack.readthedocs.io/en/latest/containers.html) and at #15028 that improves the current command? What you ask above is exactly how we generate the images: multi-stage builds (Spack is not in the final image) and separate files to setup the environment.

**Comment by citibeth** [comment]
@alalazo @tgamblin Thanks for pointing out `spack containerize`.  The quick answer is, no, that is now how I do it, nor how I would want to do it, because it is very slow.  I am a part-time consultant in the work environment where I use Spack in this way.  Due to the part-time nature of my presence there, it is just not practical for me to debug processes that take hours to complete.  See #15888 for how I actually do it.

**Comment by alalazo** [comment]
> Due to the part-time nature of my presence there, it is just not practical for me to debug processes that take hours to complete.

In general this is a concern that we have in mind and understand. The way we'd like to deal with it is to leverage the binary packaging capability that Spack already has. The general idea is to arrive at a model where:
1. People can configure Spack to generate (possibly signed) binary packages while a DAG is installing and push them to a mirror with a post-install hook or similar mechanism
2. The mirror can be anywhere you want: you local disk (served through e.g. http during a docker build) or AWS etc.
3. If you happen to have a binary package available during the installation, Spack will prefer that and won't build from sources

This is currently a work in progress but once ready it should enable workflows where, if an error occurs at a certain point of the installation of an entire environment, it should be fast to reach that point on the next try because binary packages have been created and are available for all the specs that built succesfully.

**Comment by citibeth** [comment]
It sounds like a sophisticated system, and I suppose it would work, as long as the binary repo can reside in AWS.  And I suppose it supports more use cases than what I hacked together.

* Do you know if deleting files from a container actually removes them from the HDD image?  If not, then adding a Docker command to delete Spack wouldn't really have much point.  To save space on images, one would have to have a way to construct images without ever putting Spack in there to begin with.

* I'd like to think about environments in terms of "rendering" or "compiling" them.  Right now we have two main ways to render environments: (a) as a module load script that users source, or (b) as a view + a requirement that users run a Spack command to set env vars as appropriate.  Now it looks like we're talking about ways to render into a container, and I think it could eventually be quite slick.  If we think of all of these in a similar way, I think that could be helpful.  Because they all do a similar thing: take a spack.yaml and produce a way to use the installed software as a single environment.

* I think it's best to assume that things will be done manually the first time any spack.yaml file is changed.  So we should think through ways to make debugging workflows easy.  In the "classic" (non-containerized) environments case, I feel the tools available for debugging when an environment build fails are already not quite what they should be.  And when the process is put into a containerized environment (especially in a  CI/CD system), debugging becomes that much more remote.  We should assume that anyone who wants to put Spack into a CI/CD Dockerfile will also need a way to build that environment interactively first, and work out the bugs.

* And finally... I believe there are multiple containerization systems?  I've used Docker in a commercial environment, but our HPC system is mulling trying to move people toward Singularity.  As with different module systems, my guess is we'll need to support multiple containerization systems.

**Comment by citibeth** [comment]
OK, so here's how I end up using Spack Environments now.

1. I write a `spack.yaml2` file.

2. I run the following script to concretize.  This prevents Spack from running roughshod over my source code:
   ```
   cp spack.yaml2 spack.yaml; spack -e mien concretize -f
   ```

3. I use `Spack -e mien install`  to build the environment.

4. I run this script to generate a `loads` file that can be `source`d to load the environment.  (Note that this environment is being rendered with a view, not modules.  The env vars got too long for the system when using modules):

   ```
   #!/bin/sh
   # 
   # Generates the *loads* file

   # Set up Spack and Modules
   # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-which-directory-it-is-stored-in

   # macOS doesn't have readlink -f (but it can be obtained from GNU coreutils)
   # https://stackoverflow.com/questions/5756524/how-to-get-absolute-path-name-of-shell-script-on-macos
   pushd . >/dev/null
   export SPACK_ENVX=$(cd "$SCRIPT_DIR" >/dev/null; pwd -P )
   popd >/dev/null

   export SPACK_ROOT=$(dirname $(dirname $(dirname $(dirname $SPACK_ENVX))))


   # Hack around evil stateful Spack Environment stuff

   # spack env activate --sh doesn't work.
   #source $SPACK_ROOT/share/spack/setup-env.sh
   #$SPACK_ROOT/bin/spack env deactivate   # just in case
   $SPACK_ROOT/bin/spack env activate --sh myenv--with-view >$SPACK_ENVX/loads
   unset SPACK_ENVX   # Ignore previous activations
   ```

Note all the "features" that I don't use:

1. I don't ever (intentionally) activate an environment.
1. I don't incrementally add to an environment.  If I change the environment, I do so by editing the `spack.yaml` file and re-concretizing.  (I am using `concretize: together`).
1. I don't ever use the Spack shell integration or `spack load`.
1. Onc the envrionment is generated, Spack is not required to use it.  Users simply `source` a Spack-generate `loads` file (which was generated in a very roundabout way that should be a lot more straightforward)

**Comment by alalazo** [comment]
Closing as stale. Feel free to reopen if you want to continue discussion on this.

**Pull request closed without merging**
