### PR TITLE
make provision to install version 6.4.0beta.2

### PR DESCRIPTION
**Pull request by DarylGrunau**
This PR just adds support to build/install 6.4.0beta2.

### CODE REVIEW

**Comment by adamjstewart** [comment]
P.S. If anyone wants to submit a PR to clean up these version numbers I would support it. `6.4.0beta.2` is much more reasonable than `6.4.0beta.2_69196eadbc77506561eef711f19d2f03b4ab0ffa`.

**Comment by DarylGrunau** [comment]
@adamjstewart, I agree with you.  @junghans, do you have any concerns about shortening the version names to something sane?  I have no gauge of how wide the impact would be but making the mod at the beginning of 6.4.0beta.2 would be better than later on, IMHO.

**Comment by adamjstewart** [comment]
> I have no gauge of how wide the impact

There are no packages in Spack that depend on `eospac`, so as far as Spack is concerned, there would be no impacts (at least, nothing would break). At the worst, Spack might try to reinstall the package because it thinks there is a new version available.

**Comment by DarylGrunau** [comment]
I know for certain that other code teams here at LANL use version 6.3.1 of this package; my code team uses 6.4.0beta1 in production and wants to move to 6.4.0beta2.  The users that @junghans represents may have been using either of these versions.  Would you be willing to support a PR that modifies just the beta2 version to something reasonable and we can deprecate the long syntax as we roll forward?

**Comment by adamjstewart** [comment]
I would prefer a sweeping change that affects all versions. If someone already has version `6.3.1_r20161202150449` installed, then changing the version numbers in the package won't affect them. If they try to install `6.3.1_r20161202150449`, Spack will say that it is already installed. But if they try to install `eospac`, instead of saying that `6.3.1_r20161202150449` is already installed, it will try to install `6.3.1`, resulting in duplicate installations. I think this is a minor inconvenience.

**Comment by DarylGrunau** [comment]
Ok, I am in favor of this but I'd like to hear from @junghans as well.  This will mean dumping the url_for_version function and specifying a unique URL for each version since none can be inferred (unless you know of a better way of doing this).

**Comment by junghans** [comment]
Yeah, making the version more readable is fine with me!

**Comment by DarylGrunau** [comment]
See https://github.com/spack/spack/pull/8368

**Pull request merged**
