### PR TITLE
Add a node.js spackage

### PR DESCRIPTION
**Pull request by AndrewGaspar**
I added checksums for each latest major version going back to v4.

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
Sorry, hold off on reviewing this for now. This built fine on macOS, but I'm running into trouble building it under Linux on our cluster.

**Comment by AndrewGaspar** [comment]
Turns out it was a compiler configuration issue. This package works as expected.

**Comment by healther** [comment]
Duplicate of package `node-js`

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/node-js/package.py

**Comment by AndrewGaspar** [comment]
Wow, don't know how I missed that. Sorry about that!

**Pull request closed without merging**
