### PR TITLE
DESTDIR support

### PR DESCRIPTION
**Pull request by scheibelp**
IMO this could be merged before rpm support is ready (although is still a WIP). Right now it does the following:
1. (conditionally) Redirect makefile, python distutils, and boost installation methods
2. (conditionally) Redirect Spack commands that create files/directories 
3. Creates a separate .pth file for each python extension
4. (optionally) automatically activates python extensions as part of the install process (so an rpm for a python extension would include symlinks within site-packages of the base python installation)

In short: a combination of DESTDIR support and splitting the unified python extension installation state (i.e. the single .pth file) into per-package state.

Notes on [2]:
- These alternative redirected commands are implicit within Package.install and otherwise must be called explicitly (e.g. call “mkdirp_redirect” for other functions in Package)
- The redirected commands make assumptions about the desired source and/or destination
  - e.g. “install” assumes that one is always intending to take a file outside the package installation directory and install it within the package installation directory
  - build_environment adds a redirected working_dir which assumes by default that the user is not intending to work in package.prefix, but will attempt to redirect if the destination directory does not exist.
  - I haven’t redirected “move” yet but I assume it should make the same assumptions as working_dir (i.e. users may want to move files around within the staging dir, within package.prefix, or between the two)

Regarding [3] it may be the case that using the distutils DESTDIR equivalent eliminates .pth files (i.e. it does the installation so that .pth files are not required) so this may not be necessary.

Regarding [4]: the activating linkage is also redirected.

There are still a few TODOs, including:
- [x] redirection of all commands provided by build_environment to Package.install
- [x] Python extensions creating _markerlib and pkg_resources directories. That likely needs to be omitted from linking.
- [x] CustomDirectoryLayout in the install command does not do anything essential for this PR and should be removed

### CODE REVIEW

**Comment by scheibelp** [comment]
Recap from meeting today: 

My original assumption was that file commands (mkdir, install, etc.) called from Package.install/patch always have the package install directory as a prefix. It turns out they can also modify  the stage directory (e.g. boost adds symlink to libtool for darwin installs) so the redirection logic gets more complex. I haven't updated the redirection commands to fully account for this.

**Comment by scheibelp** [comment]
I should have a commit in later today to make things clearer

**Comment by tgamblin** [comment]
@scheibelp: I had this down as going into `0.10`, but I think I would like to hold off and merge it *after* `0.10`, since we're not actually going to put RPM support in `0.10`.  This would reduce the number of things changing.  We can put this in along with the RPM support in the following version -- we'll get it merged soon after the `0.10` release.

**Comment by scheibelp** [comment]
>We can put this in along with the RPM support in the following version -- we'll get it merged soon after the 0.10 release.

Sounds good!

**Comment by scheibelp** [comment]
Code coverage appears to be missing at least a couple spots (likely because they are only executed in a separate process): build_environment.set_module_variables_for_package, the definition of RedirectedCommand, and the function open_redirect.

There are at least a couple commands which are not covered in testing, namely symlink_redirect, working_dir_redirect, and strip_destdir. Next commit will cover those but I think either way it won't get picked up by codecov and will likely be considered insufficient.

**Comment by scheibelp** [comment]
Closing and reopening to resolve spurious test failure

**Comment by becker33** [comment]
Closing as outdated. We have decided to pursue system installations via spack stacks rather than RPM generation. Maintenance for package mapping for RPM was too high to be a long-term solution.

**Pull request closed without merging**
