### PR TITLE
chgcentre: a new package.

### PR DESCRIPTION
**Pull request by weijianwen**

### CODE REVIEW

**Comment by adamjstewart** [comment]
Flake8:
```
var/spack/repos/builtin/packages/chgcentre/package.py:11: [W291] trailing whitespace
var/spack/repos/builtin/packages/chgcentre/package.py:21: [W391] blank line at end of file
```

**Comment by weijianwen** [comment]
flake8 issues fixed.

**Comment by adamjstewart** [comment]
@weijianwen did you forget to push?

**Comment by weijianwen** [comment]
@adamjstewart oh, my fault. It's done now.

**Pull request merged**
