### PR TITLE
Add kealib 1.4.7

### PR DESCRIPTION
**Pull request by adamjstewart**
Successfully installs and passes all tests on macOS 10.13.4 with Clang 9.0.0.

Took me forever to figure out how to install this package. No matter what I tried, I kept getting the following error:
```
/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-55/test_keep_exceptions0/tmp/spack-stage/spack-stage-pbhblev6/chchrsc-kealib-c8646188a638/trunk/src/libkea/KEAImageIO.cpp:3607:10: fatal error: 'libkea/kea-config.h' file not found
#include "libkea/kea-config.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/kea.dir/libkea/KEAImageIO.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/kea.dir/all] Error 2
make: *** [all] Error 2
```
I eventually discovered that this package doesn't support out-of-source builds. I've never seen a CMake package like this. In fact, most CMake packages won't let you build in-source even if you want to.

@gillins Rumor has it that you're the author of `kealib`. For the life of me, I couldn't figure out how to file a bug report on your Bitbucket repo.

### CODE REVIEW

**Comment by gillins** [comment]
> For the life of me, I couldn't figure out how to file a bug report on your Bitbucket repo.

Turns out our issue tracker was private. I think I've fixed it so anyone can create issues now.

Regarding out of tree builds, (I hope) this was fixed here: https://bitbucket.org/chchrsc/kealib/commits/a4e63dbb642c83516104ea82cec0e45c4caffd54 but we haven't done a new release since - maybe we should do it soon.

@petebunting is the original author of `kealib` BTW. cc: @neilflood

**Comment by adamjstewart** [comment]
@gillins Thanks for the info. I tried the patch from that commit, however I'm still running into the same error when I do an out-of-source build. I also tried the latest develop commit and that failed as well.

**Comment by gillins** [comment]
@adamjstewart you are totally correct - thanks for letting me know. More work was needed. I've just pushed a new commit which (for me at least) allows in and out of tree builds. Let me know if this fixes it or not for you and I'll look into doing a new release.

**Comment by adamjstewart** [comment]
@gillins Thanks, that latest commit does the trick. The patch doesn't apply to 1.4.5, so I may just drop support for it. Any idea for the time frame on a new release? If it's soon, I might just wait and add that version instead.

**Comment by gillins** [comment]
> Any idea for the time frame on a new release?

Probably 2-3 weeks away. We have a bit more work to do. Will let you know.

**Comment by adamjstewart** [comment]
In that case I think I'll just merge this for now.

**Comment by gillins** [comment]
@adamjstewart kealib 1.4.8 has been released...

**Pull request merged**
